ns3-mmwave: ns3::mmwave::MmWaveControlMessage Class Reference
ns3::mmwave::MmWaveControlMessage Class Reference
#include "mmwave-control-messages.h"
Public Types
enum messageType {
DCI, DCI_TDMA, DL_CQI, MIB,
SIB1, RACH_PREAMBLE, RAR, BSR,
DL_HARQ
}
Public Member Functions
MmWaveControlMessage (void)
virtual ~MmWaveControlMessage (void)
messageType GetMessageType (void)
void SetMessageType (messageType type)
Private Attributes
messageType m_messageType
Detailed Description
Definition at line 44 of file mmwave-control-messages.h.
Member Enumeration Documentation
messageType
enum ns3::mmwave::MmWaveControlMessage::messageType
Enumerator
DCI
DCI_TDMA
DL_CQI
MIB
SIB1
RACH_PREAMBLE
RAR
BSR
DL_HARQ
Definition at line 47 of file mmwave-control-messages.h.
Constructor & Destructor Documentation
MmWaveControlMessage()
ns3::mmwave::MmWaveControlMessage::MmWaveControlMessage (void)
Definition at line 39 of file mmwave-control-messages.cc.
~MmWaveControlMessage()
ns3::mmwave::MmWaveControlMessage::~MmWaveControlMessage (void) virtual
Definition at line 44 of file mmwave-control-messages.cc.
Member Function Documentation
GetMessageType()
MmWaveControlMessage::messageType ns3::mmwave::MmWaveControlMessage::GetMessageType (void)
Definition at line 56 of file mmwave-control-messages.cc.
References m_messageType.
SetMessageType()
void ns3::mmwave::MmWaveControlMessage::SetMessageType (messageType type)
Definition at line 50 of file mmwave-control-messages.cc.
References m_messageType.
Referenced by ns3::mmwave::MmWaveBsrMessage::MmWaveBsrMessage(), ns3::mmwave::MmWaveDlCqiMessage::MmWaveDlCqiMessage(), ns3::mmwave::MmWaveDlHarqFeedbackMessage::MmWaveDlHarqFeedbackMessage(), ns3::mmwave::MmWaveMibMessage::MmWaveMibMessage(), ns3::mmwave::MmWaveRachPreambleMessage::MmWaveRachPreambleMessage(), ns3::mmwave::MmWaveRarMessage::MmWaveRarMessage(), ns3::mmwave::MmWaveSib1Message::MmWaveSib1Message(), and ns3::mmwave::MmWaveTdmaDciMessage::MmWaveTdmaDciMessage().
Member Data Documentation
m_messageType
messageType ns3::mmwave::MmWaveControlMessage::m_messageType private
Definition at line 68 of file mmwave-control-messages.h.
Referenced by GetMessageType(), and SetMessageType().
The documentation for this class was generated from the following files:
src/mmwave/model/mmwave-control-messages.h
src/mmwave/model/mmwave-control-messages.cc