ns3-mmwave: ns3::mmwave::MmWaveBeamformingModel Class Reference
ns3::mmwave::MmWaveBeamformingModel Class Reference abstract
This class handles the beamforming operations.
#include "mmwave-beamforming-model.h"
Public Member Functions
MmWaveBeamformingModel ()
Constructor.
virtual ~MmWaveBeamformingModel () override
Destructor.
Ptr< ThreeGppAntennaArrayModel > GetAntenna (void) const
Get the antenna on which beamforming is applied.
Ptr< NetDevice > GetDevice (void) const
Returns the NetDevice.
void SetAntenna (Ptr< ThreeGppAntennaArrayModel > antenna)
Set the antenna on which beamforming is applied.
virtual void SetBeamformingVectorForDevice (Ptr< NetDevice > otherDevice, Ptr< ThreeGppAntennaArrayModel > otherAntenna)=0
Computes the beamforming vector to communicate with the target device and antenna and configures the antenna.
void SetDevice (Ptr< NetDevice > device)
Set the NetDevice.
Static Public Member Functions
static TypeId GetTypeId (void)
Returns the object type id.
Protected Member Functions
virtual void DoDispose (void) override
Protected Attributes
Ptr< ThreeGppAntennaArrayModel > m_antenna
The antenna of the device on which the beamforming is applied.
Ptr< NetDevice > m_device
pointer to the NetDevice
Detailed Description
This class handles the beamforming operations.
Extend this class to implement a specific beamforming algorithm.
Definition at line 40 of file mmwave-beamforming-model.h.
Constructor & Destructor Documentation
MmWaveBeamformingModel()
ns3::mmwave::MmWaveBeamformingModel::MmWaveBeamformingModel ()
Constructor.
Definition at line 65 of file mmwave-beamforming-model.cc.
~MmWaveBeamformingModel()
ns3::mmwave::MmWaveBeamformingModel::~MmWaveBeamformingModel () override virtual
Destructor.
Definition at line 70 of file mmwave-beamforming-model.cc.
Member Function Documentation
DoDispose()
void ns3::mmwave::MmWaveBeamformingModel::DoDispose (void) override protected virtual
Reimplemented in ns3::mmwave::MmWaveSvdBeamforming.
Definition at line 75 of file mmwave-beamforming-model.cc.
References m_antenna, and m_device.
Referenced by ns3::mmwave::MmWaveSvdBeamforming::DoDispose().
GetAntenna()
Ptr< ThreeGppAntennaArrayModel > ns3::mmwave::MmWaveBeamformingModel::GetAntenna (void) const
Get the antenna on which beamforming is applied.
Returns
the antenna
Definition at line 97 of file mmwave-beamforming-model.cc.
References m_antenna.
Referenced by GetTypeId().
GetDevice()
Ptr< NetDevice > ns3::mmwave::MmWaveBeamformingModel::GetDevice (void) const
Returns the NetDevice.
Returns
the net device
Definition at line 83 of file mmwave-beamforming-model.cc.
References m_device.
Referenced by GetTypeId().
GetTypeId()
TypeId ns3::mmwave::MmWaveBeamformingModel::GetTypeId (void) static
Returns the object type id.
Returns
the type id
Definition at line 43 of file mmwave-beamforming-model.cc.
References GetAntenna(), GetDevice(), SetAntenna(), and SetDevice().
SetAntenna()
void ns3::mmwave::MmWaveBeamformingModel::SetAntenna (Ptr< ThreeGppAntennaArrayModel > antenna)
Set the antenna on which beamforming is applied.
Parameters
antenna
Definition at line 104 of file mmwave-beamforming-model.cc.
References m_antenna.
Referenced by GetTypeId(), and ns3::mmwave::MmWaveHelper::InstallSingleMcUeDevice().
SetBeamformingVectorForDevice()
virtual void ns3::mmwave::MmWaveBeamformingModel::SetBeamformingVectorForDevice (Ptr< NetDevice > otherDevice, Ptr< ThreeGppAntennaArrayModel > otherAntenna) pure virtual
Computes the beamforming vector to communicate with the target device and antenna and configures the antenna.
Parameters
otherDevice the target device
otherAntenna the target antenna of otherDevice
Implemented in ns3::mmwave::MmWaveSvdBeamforming, and ns3::mmwave::MmWaveDftBeamforming.
SetDevice()
void ns3::mmwave::MmWaveBeamformingModel::SetDevice (Ptr< NetDevice > device)
Set the NetDevice.
Parameters
device the net device
Definition at line 90 of file mmwave-beamforming-model.cc.
References m_device.
Referenced by GetTypeId().
Member Data Documentation
m_antenna
Ptr<ThreeGppAntennaArrayModel> ns3::mmwave::MmWaveBeamformingModel::m_antenna protected
The antenna of the device on which the beamforming is applied.
Definition at line 95 of file mmwave-beamforming-model.h.
Referenced by DoDispose(), GetAntenna(), SetAntenna(), ns3::mmwave::MmWaveDftBeamforming::SetBeamformingVectorForDevice(), and ns3::mmwave::MmWaveSvdBeamforming::SetBeamformingVectorForDevice().
m_device
Ptr<NetDevice> ns3::mmwave::MmWaveBeamformingModel::m_device protected
pointer to the NetDevice
Definition at line 94 of file mmwave-beamforming-model.h.
Referenced by DoDispose(), GetDevice(), ns3::mmwave::MmWaveDftBeamforming::SetBeamformingVectorForDevice(), ns3::mmwave::MmWaveSvdBeamforming::SetBeamformingVectorForDevice(), and SetDevice().
The documentation for this class was generated from the following files:
src/mmwave/model/mmwave-beamforming-model.h
src/mmwave/model/mmwave-beamforming-model.cc