ns3-mmwave: ns3::mmwave::MmWaveMacMemberMacCschedSapUser Class Reference
ns3::mmwave::MmWaveMacMemberMacCschedSapUser Class Reference
Public Member Functions
MmWaveMacMemberMacCschedSapUser (MmWaveEnbMac *mac)
virtual void CschedCellConfigCnf (const struct MmWaveMacCschedSapUser::CschedCellConfigCnfParameters &params)
virtual void CschedCellConfigUpdateInd (const struct MmWaveMacCschedSapUser::CschedCellConfigUpdateIndParameters &params)
virtual void CschedLcConfigCnf (const struct MmWaveMacCschedSapUser::CschedLcConfigCnfParameters &params)
virtual void CschedLcReleaseCnf (const struct MmWaveMacCschedSapUser::CschedLcReleaseCnfParameters &params)
virtual void CschedUeConfigCnf (const struct MmWaveMacCschedSapUser::CschedUeConfigCnfParameters &params)
virtual void CschedUeConfigUpdateInd (const struct MmWaveMacCschedSapUser::CschedUeConfigUpdateIndParameters &params)
virtual void CschedUeReleaseCnf (const struct MmWaveMacCschedSapUser::CschedUeReleaseCnfParameters &params)
Public Member Functions inherited from ns3::mmwave::MmWaveMacCschedSapUser
virtual ~MmWaveMacCschedSapUser ()
Private Attributes
MmWaveEnbMac * m_mac
Detailed Description
Definition at line 233 of file mmwave-enb-mac.cc.
Constructor & Destructor Documentation
MmWaveMacMemberMacCschedSapUser()
ns3::mmwave::MmWaveMacMemberMacCschedSapUser::MmWaveMacMemberMacCschedSapUser (MmWaveEnbMac * mac)
Definition at line 251 of file mmwave-enb-mac.cc.
Member Function Documentation
CschedCellConfigCnf()
void ns3::mmwave::MmWaveMacMemberMacCschedSapUser::CschedCellConfigCnf (const struct MmWaveMacCschedSapUser::CschedCellConfigCnfParameters & params) virtual
Implements ns3::mmwave::MmWaveMacCschedSapUser.
Definition at line 257 of file mmwave-enb-mac.cc.
References ns3::mmwave::MmWaveEnbMac::DoCschedCellConfigCnf(), and m_mac.
CschedCellConfigUpdateInd()
void ns3::mmwave::MmWaveMacMemberMacCschedSapUser::CschedCellConfigUpdateInd (const struct MmWaveMacCschedSapUser::CschedCellConfigUpdateIndParameters & params) virtual
Implements ns3::mmwave::MmWaveMacCschedSapUser.
Definition at line 293 of file mmwave-enb-mac.cc.
References ns3::mmwave::MmWaveEnbMac::DoCschedCellConfigUpdateInd(), and m_mac.
CschedLcConfigCnf()
void ns3::mmwave::MmWaveMacMemberMacCschedSapUser::CschedLcConfigCnf (const struct MmWaveMacCschedSapUser::CschedLcConfigCnfParameters & params) virtual
Implements ns3::mmwave::MmWaveMacCschedSapUser.
Definition at line 269 of file mmwave-enb-mac.cc.
References ns3::mmwave::MmWaveEnbMac::DoCschedLcConfigCnf(), and m_mac.
CschedLcReleaseCnf()
void ns3::mmwave::MmWaveMacMemberMacCschedSapUser::CschedLcReleaseCnf (const struct MmWaveMacCschedSapUser::CschedLcReleaseCnfParameters & params) virtual
Implements ns3::mmwave::MmWaveMacCschedSapUser.
Definition at line 275 of file mmwave-enb-mac.cc.
References ns3::mmwave::MmWaveEnbMac::DoCschedLcReleaseCnf(), and m_mac.
CschedUeConfigCnf()
void ns3::mmwave::MmWaveMacMemberMacCschedSapUser::CschedUeConfigCnf (const struct MmWaveMacCschedSapUser::CschedUeConfigCnfParameters & params) virtual
Implements ns3::mmwave::MmWaveMacCschedSapUser.
Definition at line 263 of file mmwave-enb-mac.cc.
References ns3::mmwave::MmWaveEnbMac::DoCschedUeConfigCnf(), and m_mac.
CschedUeConfigUpdateInd()
void ns3::mmwave::MmWaveMacMemberMacCschedSapUser::CschedUeConfigUpdateInd (const struct MmWaveMacCschedSapUser::CschedUeConfigUpdateIndParameters & params) virtual
Implements ns3::mmwave::MmWaveMacCschedSapUser.
Definition at line 287 of file mmwave-enb-mac.cc.
References ns3::mmwave::MmWaveEnbMac::DoCschedUeConfigUpdateInd(), and m_mac.
CschedUeReleaseCnf()
void ns3::mmwave::MmWaveMacMemberMacCschedSapUser::CschedUeReleaseCnf (const struct MmWaveMacCschedSapUser::CschedUeReleaseCnfParameters & params) virtual
Implements ns3::mmwave::MmWaveMacCschedSapUser.
Definition at line 281 of file mmwave-enb-mac.cc.
References ns3::mmwave::MmWaveEnbMac::DoCschedUeReleaseCnf(), and m_mac.
Member Data Documentation
m_mac
MmWaveEnbMac* ns3::mmwave::MmWaveMacMemberMacCschedSapUser::m_mac private
Definition at line 247 of file mmwave-enb-mac.cc.
Referenced by CschedCellConfigCnf(), CschedCellConfigUpdateInd(), CschedLcConfigCnf(), CschedLcReleaseCnf(), CschedUeConfigCnf(), CschedUeConfigUpdateInd(), and CschedUeReleaseCnf().
The documentation for this class was generated from the following file:
src/mmwave/model/mmwave-enb-mac.cc