ns3-mmwave: ns3::mmwave::CoreNetworkStatsCalculator Class Reference
ns3::mmwave::CoreNetworkStatsCalculator Class Reference
#include "core-network-stats-calculator.h"
Public Member Functions
CoreNetworkStatsCalculator ()
~CoreNetworkStatsCalculator ()
void DoDispose ()
std::string GetMmeOutputFilename (void)
std::string GetX2OutputFilename (void)
void LogMmePacket (std::string path, uint16_t sourceCellId, uint16_t targetCellId, uint32_t size, uint64_t delay)
void LogX2Packet (std::string path, uint16_t sourceCellId, uint16_t targetCellId, uint32_t size, uint64_t delay, bool data)
void SetMmeOutputFilename (std::string outputFilename)
void SetX2OutputFilename (std::string outputFilename)
Static Public Member Functions
static TypeId GetTypeId (void)
Private Attributes
std::ofstream m_mmeOutFile
std::string m_mmeOutFileName
std::ofstream m_x2OutFile
std::string m_x2OutFileName
Detailed Description
Definition at line 38 of file core-network-stats-calculator.h.
Constructor & Destructor Documentation
CoreNetworkStatsCalculator()
ns3::mmwave::CoreNetworkStatsCalculator::CoreNetworkStatsCalculator ()
Definition at line 37 of file core-network-stats-calculator.cc.
~CoreNetworkStatsCalculator()
ns3::mmwave::CoreNetworkStatsCalculator::~CoreNetworkStatsCalculator ()
Definition at line 42 of file core-network-stats-calculator.cc.
Member Function Documentation
DoDispose()
void ns3::mmwave::CoreNetworkStatsCalculator::DoDispose ()
Definition at line 69 of file core-network-stats-calculator.cc.
GetMmeOutputFilename()
std::string ns3::mmwave::CoreNetworkStatsCalculator::GetMmeOutputFilename (void)
Definition at line 107 of file core-network-stats-calculator.cc.
References m_mmeOutFileName.
Referenced by LogMmePacket().
GetTypeId()
TypeId ns3::mmwave::CoreNetworkStatsCalculator::GetTypeId (void) static
Definition at line 48 of file core-network-stats-calculator.cc.
References SetMmeOutputFilename(), and SetX2OutputFilename().
GetX2OutputFilename()
std::string ns3::mmwave::CoreNetworkStatsCalculator::GetX2OutputFilename (void)
Definition at line 101 of file core-network-stats-calculator.cc.
References m_x2OutFileName.
Referenced by LogX2Packet().
LogMmePacket()
void ns3::mmwave::CoreNetworkStatsCalculator::LogMmePacket (std::string path, uint16_t sourceCellId, uint16_t targetCellId, uint32_t size, uint64_t delay)
Definition at line 88 of file core-network-stats-calculator.cc.
References GetMmeOutputFilename(), and m_mmeOutFile.
LogX2Packet()
void ns3::mmwave::CoreNetworkStatsCalculator::LogX2Packet (std::string path, uint16_t sourceCellId, uint16_t targetCellId, uint32_t size, uint64_t delay, bool data)
Definition at line 75 of file core-network-stats-calculator.cc.
References GetX2OutputFilename(), and m_x2OutFile.
Referenced by ns3::mmwave::MmWaveHelper::AddX2Interface().
SetMmeOutputFilename()
void ns3::mmwave::CoreNetworkStatsCalculator::SetMmeOutputFilename (std::string outputFilename)
Definition at line 119 of file core-network-stats-calculator.cc.
References m_mmeOutFileName.
Referenced by GetTypeId().
SetX2OutputFilename()
void ns3::mmwave::CoreNetworkStatsCalculator::SetX2OutputFilename (std::string outputFilename)
Definition at line 113 of file core-network-stats-calculator.cc.
References m_x2OutFileName.
Referenced by GetTypeId().
Member Data Documentation
m_mmeOutFile
std::ofstream ns3::mmwave::CoreNetworkStatsCalculator::m_mmeOutFile private
Definition at line 61 of file core-network-stats-calculator.h.
Referenced by LogMmePacket().
m_mmeOutFileName
std::string ns3::mmwave::CoreNetworkStatsCalculator::m_mmeOutFileName private
Definition at line 57 of file core-network-stats-calculator.h.
Referenced by GetMmeOutputFilename(), and SetMmeOutputFilename().
m_x2OutFile
std::ofstream ns3::mmwave::CoreNetworkStatsCalculator::m_x2OutFile private
Definition at line 60 of file core-network-stats-calculator.h.
Referenced by LogX2Packet().
m_x2OutFileName
std::string ns3::mmwave::CoreNetworkStatsCalculator::m_x2OutFileName private
Definition at line 58 of file core-network-stats-calculator.h.
Referenced by GetX2OutputFilename(), and SetX2OutputFilename().
The documentation for this class was generated from the following files:
src/mmwave/helper/core-network-stats-calculator.h
src/mmwave/helper/core-network-stats-calculator.cc