ns3-mmwave: ns3::mmwave::MmWaveFlexTtiPfMacCschedSapProvider Class Reference
ns3::mmwave::MmWaveFlexTtiPfMacCschedSapProvider Class Reference
Public Member Functions
MmWaveFlexTtiPfMacCschedSapProvider (MmWaveFlexTtiPfMacScheduler *scheduler)
virtual void CschedCellConfigReq (const struct MmWaveMacCschedSapProvider::CschedCellConfigReqParameters &params)
CSCHED_CELL_CONFIG_REQ.
virtual void CschedLcConfigReq (const struct MmWaveMacCschedSapProvider::CschedLcConfigReqParameters &params)
virtual void CschedLcReleaseReq (const struct MmWaveMacCschedSapProvider::CschedLcReleaseReqParameters &params)
virtual void CschedUeConfigReq (const struct MmWaveMacCschedSapProvider::CschedUeConfigReqParameters &params)
virtual void CschedUeReleaseReq (const struct MmWaveMacCschedSapProvider::CschedUeReleaseReqParameters &params)
Public Member Functions inherited from ns3::mmwave::MmWaveMacCschedSapProvider
virtual ~MmWaveMacCschedSapProvider ()
Private Member Functions
MmWaveFlexTtiPfMacCschedSapProvider ()
Private Attributes
MmWaveFlexTtiPfMacScheduler * m_scheduler
Detailed Description
Definition at line 29 of file mmwave-flex-tti-pf-mac-scheduler.cc.
Constructor & Destructor Documentation
MmWaveFlexTtiPfMacCschedSapProvider() [1/2]
ns3::mmwave::MmWaveFlexTtiPfMacCschedSapProvider::MmWaveFlexTtiPfMacCschedSapProvider (MmWaveFlexTtiPfMacScheduler * scheduler)
Definition at line 50 of file mmwave-flex-tti-pf-mac-scheduler.cc.
MmWaveFlexTtiPfMacCschedSapProvider() [2/2]
ns3::mmwave::MmWaveFlexTtiPfMacCschedSapProvider::MmWaveFlexTtiPfMacCschedSapProvider () private
Definition at line 46 of file mmwave-flex-tti-pf-mac-scheduler.cc.
Member Function Documentation
CschedCellConfigReq()
void ns3::mmwave::MmWaveFlexTtiPfMacCschedSapProvider::CschedCellConfigReq (const struct MmWaveMacCschedSapProvider::CschedCellConfigReqParameters & params) virtual
CSCHED_CELL_CONFIG_REQ.
Implements ns3::mmwave::MmWaveMacCschedSapProvider.
Definition at line 56 of file mmwave-flex-tti-pf-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiPfMacScheduler::DoCschedCellConfigReq(), and m_scheduler.
CschedLcConfigReq()
void ns3::mmwave::MmWaveFlexTtiPfMacCschedSapProvider::CschedLcConfigReq (const struct MmWaveMacCschedSapProvider::CschedLcConfigReqParameters & params) virtual
Implements ns3::mmwave::MmWaveMacCschedSapProvider.
Definition at line 69 of file mmwave-flex-tti-pf-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiPfMacScheduler::DoCschedLcConfigReq(), and m_scheduler.
CschedLcReleaseReq()
void ns3::mmwave::MmWaveFlexTtiPfMacCschedSapProvider::CschedLcReleaseReq (const struct MmWaveMacCschedSapProvider::CschedLcReleaseReqParameters & params) virtual
Implements ns3::mmwave::MmWaveMacCschedSapProvider.
Definition at line 75 of file mmwave-flex-tti-pf-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiPfMacScheduler::DoCschedLcReleaseReq(), and m_scheduler.
CschedUeConfigReq()
void ns3::mmwave::MmWaveFlexTtiPfMacCschedSapProvider::CschedUeConfigReq (const struct MmWaveMacCschedSapProvider::CschedUeConfigReqParameters & params) virtual
Implements ns3::mmwave::MmWaveMacCschedSapProvider.
Definition at line 62 of file mmwave-flex-tti-pf-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiPfMacScheduler::DoCschedUeConfigReq(), and m_scheduler.
CschedUeReleaseReq()
void ns3::mmwave::MmWaveFlexTtiPfMacCschedSapProvider::CschedUeReleaseReq (const struct MmWaveMacCschedSapProvider::CschedUeReleaseReqParameters & params) virtual
Implements ns3::mmwave::MmWaveMacCschedSapProvider.
Definition at line 81 of file mmwave-flex-tti-pf-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiPfMacScheduler::DoCschedUeReleaseReq(), and m_scheduler.
Member Data Documentation
m_scheduler
MmWaveFlexTtiPfMacScheduler* ns3::mmwave::MmWaveFlexTtiPfMacCschedSapProvider::m_scheduler private
Definition at line 43 of file mmwave-flex-tti-pf-mac-scheduler.cc.
Referenced by CschedCellConfigReq(), CschedLcConfigReq(), CschedLcReleaseReq(), CschedUeConfigReq(), and CschedUeReleaseReq().
The documentation for this class was generated from the following file:
src/mmwave/model/mmwave-flex-tti-pf-mac-scheduler.cc