ns3-mmwave: ns3::mmwave::MmWaveMacTrace Class Reference
ns3::mmwave::MmWaveMacTrace Class Reference
This class contains the MmWave, MAC-related tracing entities.
#include "mmwave-mac-trace.h"
Public Member Functions
MmWaveMacTrace ()
virtual ~MmWaveMacTrace ()
void SetOutputFilename (std::string fileName)
Sets the filename for the MAC-related traces.
Static Public Member Functions
static TypeId GetTypeId (void)
static void ReportEnbSchedulingInfo (Ptr< MmWaveMacTrace > enbStats, MmWaveEnbMac::MmWaveSchedTraceInfo schedParams)
Callback used to trace the reception of a scheduling decision by the eNB and from the scheduler itself.
Static Private Attributes
static std::ofstream m_schedAllocTraceFile {}
Output stream for the scheduling allocations trace.
static std::string m_schedAllocTraceFilename {}
Output filename for the scheduling allocations trace.
Detailed Description
This class contains the MmWave, MAC-related tracing entities.
The purpose of this class is to implement the MmWave, MAC-related callbacks and to organize their setup (such as the traces' filename and their output streams)
Definition at line 40 of file mmwave-mac-trace.h.
Constructor & Destructor Documentation
MmWaveMacTrace()
ns3::mmwave::MmWaveMacTrace::MmWaveMacTrace ()
Definition at line 35 of file mmwave-mac-trace.cc.
~MmWaveMacTrace()
ns3::mmwave::MmWaveMacTrace::~MmWaveMacTrace () virtual
Definition at line 39 of file mmwave-mac-trace.cc.
References m_schedAllocTraceFile.
Member Function Documentation
GetTypeId()
TypeId ns3::mmwave::MmWaveMacTrace::GetTypeId (void) static
Definition at line 48 of file mmwave-mac-trace.cc.
References SetOutputFilename().
ReportEnbSchedulingInfo()
void ns3::mmwave::MmWaveMacTrace::ReportEnbSchedulingInfo (Ptr< MmWaveMacTrace > enbStats, MmWaveEnbMac::MmWaveSchedTraceInfo schedParams) static
Callback used to trace the reception of a scheduling decision by the eNB and from the scheduler itself.
Parameters
schedParams the actual scheduling info
enbStats the pointer to an object of this class
Definition at line 63 of file mmwave-mac-trace.cc.
References ns3::mmwave::MmWaveEnbMac::MmWaveSchedTraceInfo::m_ccId, ns3::mmwave::SfnSf::m_frameNum, ns3::mmwave::MmWaveEnbMac::MmWaveSchedTraceInfo::m_indParam, m_schedAllocTraceFile, m_schedAllocTraceFilename, ns3::mmwave::MmWaveMacSchedSapUser::SchedConfigIndParameters::m_sfnSf, ns3::mmwave::SfnSf::m_sfNum, ns3::mmwave::MmWaveMacSchedSapUser::SchedConfigIndParameters::m_slotAllocInfo, ns3::mmwave::SfnSf::m_slotNum, and ns3::mmwave::SlotAllocInfo::m_ttiAllocInfo.
Referenced by ns3::mmwave::MmWaveHelper::EnableEnbSchedTrace().
SetOutputFilename()
void ns3::mmwave::MmWaveMacTrace::SetOutputFilename (std::string fileName)
Sets the filename for the MAC-related traces.
Parameters
fileName the intended filename
Definition at line 92 of file mmwave-mac-trace.cc.
References m_schedAllocTraceFilename.
Referenced by GetTypeId().
Member Data Documentation
m_schedAllocTraceFile
std::ofstream ns3::mmwave::MmWaveMacTrace::m_schedAllocTraceFile {} static private
Output stream for the scheduling allocations trace.
Definition at line 63 of file mmwave-mac-trace.h.
Referenced by ReportEnbSchedulingInfo(), and ~MmWaveMacTrace().
m_schedAllocTraceFilename
std::string ns3::mmwave::MmWaveMacTrace::m_schedAllocTraceFilename {} static private
Output filename for the scheduling allocations trace.
Definition at line 64 of file mmwave-mac-trace.h.
Referenced by ReportEnbSchedulingInfo(), and SetOutputFilename().
The documentation for this class was generated from the following files:
src/mmwave/helper/mmwave-mac-trace.h
src/mmwave/helper/mmwave-mac-trace.cc