ns3-mmwave: ns3::mmwave::MmWaveBearerStatsCalculator Class Reference
ns3::mmwave::MmWaveBearerStatsCalculator Class Reference
This class is an ns-3 trace sink that performs the calculation of PDU statistics for uplink and downlink.
#include "mmwave-bearer-stats-calculator.h"
Public Member Functions
MmWaveBearerStatsCalculator ()
Class constructor.
MmWaveBearerStatsCalculator (std::string protocolType)
Class constructor.
virtual ~MmWaveBearerStatsCalculator ()
Class destructor.
void DlRxPdu (uint16_t cellId, uint64_t imsi, uint16_t rnti, uint8_t lcid, uint32_t packetSize, uint64_t delay)
Notifies the stats calculator that an downlink reception has occurred.
void DlTxPdu (uint16_t cellId, uint64_t imsi, uint16_t rnti, uint8_t lcid, uint32_t packetSize)
Notifies the stats calculator that an downlink transmission has occurred.
void DoDispose ()
uint32_t GetDlCellId (uint64_t imsi, uint8_t lcid)
Gets the attached Enb cellId.
double GetDlDelay (uint64_t imsi, uint8_t lcid)
Gets the downlink RLC to RLC delay.
std::vector< double > GetDlDelayStats (uint64_t imsi, uint8_t lcid)
Gets the downlink RLC to RLC statistics: average, min, max and standard deviation.
std::string GetDlOutputFilename (void)
Get the name of the file where the downlink statistics will be stored.
std::string GetDlPdcpOutputFilename (void)
Get the name of the file where the downlink PDCP statistics will be stored.
std::vector< double > GetDlPduSizeStats (uint64_t imsi, uint8_t lcid)
Gets the downlink PDU size statistics: average, min, max and standard deviation.
uint64_t GetDlRxData (uint64_t imsi, uint8_t lcid)
Gets the number of received downlink data bytes.
uint32_t GetDlRxPackets (uint64_t imsi, uint8_t lcid)
Gets the number of received downlink data bytes.
uint64_t GetDlTxData (uint64_t imsi, uint8_t lcid)
Gets the number of transmitted downlink data bytes.
uint32_t GetDlTxPackets (uint64_t imsi, uint8_t lcid)
Gets the number of transmitted downlink data bytes.
Time GetEpoch () const
Time GetStartTime () const
uint32_t GetUlCellId (uint64_t imsi, uint8_t lcid)
Gets the attached Enb cellId.
double GetUlDelay (uint64_t imsi, uint8_t lcid)
Gets the uplink RLC to RLC delay.
std::vector< double > GetUlDelayStats (uint64_t imsi, uint8_t lcid)
Gets the uplink RLC to RLC statistics: average, min, max and standard deviation.
std::string GetUlOutputFilename (void)
Get the name of the file where the uplink statistics will be stored.
std::string GetUlPdcpOutputFilename (void)
Get the name of the file where the uplink PDCP statistics will be stored.
std::vector< double > GetUlPduSizeStats (uint64_t imsi, uint8_t lcid)
Gets the uplink PDU size statistics: average, min, max and standard deviation.
uint64_t GetUlRxData (uint64_t imsi, uint8_t lcid)
Gets the number of received uplink data bytes.
uint32_t GetUlRxPackets (uint64_t imsi, uint8_t lcid)
Gets the number of received uplink packets.
uint64_t GetUlTxData (uint64_t imsi, uint8_t lcid)
Gets the number of transmitted uplink data bytes.
uint32_t GetUlTxPackets (uint64_t imsi, uint8_t lcid)
Gets the number of transmitted uplink packets.
void SetDlPdcpOutputFilename (std::string outputFilename)
Set the name of the file where the downlink PDCP statistics will be stored.
void SetEpoch (Time e)
void SetStartTime (Time t)
void SetUlPdcpOutputFilename (std::string outputFilename)
Set the name of the file where the uplink PDCP statistics will be stored.
void UlRxPdu (uint16_t cellId, uint64_t imsi, uint16_t rnti, uint8_t lcid, uint32_t packetSize, uint64_t delay)
Notifies the stats calculator that an uplink reception has occurred.
void UlTxPdu (uint16_t cellId, uint64_t imsi, uint16_t rnti, uint8_t lcid, uint32_t packetSize)
Notifies the stats calculator that an uplink transmission has occurred.
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Private Member Functions
void EndEpoch (void)
Function called in every endEpochEvent.
void RescheduleEndEpoch ()
Reschedules EndEpoch event.
void ResetResults (void)
Erases collected statistics.
void ShowResults (void)
Called after each epoch to write collected statistics to output files.
void WriteDlResults (std::ofstream &outFile)
Writes collected statistics to DL output file and closes DL output file.
void WriteUlResults (std::ofstream &outFile)
Writes collected statistics to UL output file and closes UL output file.
Private Attributes
Uint32Map m_dlCellId
List of DL CellIds by (IMSI, LCID) pair.
Uint64StatsMap m_dlDelay
DL delay by (IMSI, LCID) pair.
std::ofstream m_dlOutFile
std::string m_dlPdcpOutputFilename
Name of the file where the downlink PDCP statistics will be saved.
Uint32StatsMap m_dlPduSize
DL PDU Size by (IMSI, LCID) pair.
Uint64Map m_dlRxData
Amount of DL RX Data by (IMSI, LCID) pair.
Uint32Map m_dlRxPackets
Number of DL RX Packets by (IMSI, LCID) pair.
Uint64Map m_dlTxData
Amount of DL TX Data by (IMSI, LCID) pair.
Uint32Map m_dlTxPackets
Number of DL TX Packets by (IMSI, LCID) pair.
EventId m_endEpochEvent
Event id for next end epoch event.
Time m_epochDuration
Epoch duration.
bool m_firstWrite
true if output files have not been opened yet
FlowIdMap m_flowId
List of FlowIds, ie.
bool m_pendingOutput
true if any output is pending
std::string m_protocolType
Protocol type, by default RLC.
Time m_startTime
Start time of the on going epoch.
Uint32Map m_ulCellId
List of UL CellIds by (IMSI, LCID) pair.
Uint64StatsMap m_ulDelay
UL delay by (IMSI, LCID) pair.
std::ofstream m_ulOutFile
std::string m_ulPdcpOutputFilename
Name of the file where the uplink PDCP statistics will be saved.
Uint32StatsMap m_ulPduSize
UL PDU Size by (IMSI, LCID) pair.
Uint64Map m_ulRxData
Amount of UL RX Data by (IMSI, LCID) pair.
Uint32Map m_ulRxPackets
Number of UL RX Packets by (IMSI, LCID) pair.
Uint64Map m_ulTxData
Amount of UL TX Data by (IMSI, LCID) pair.
Uint32Map m_ulTxPackets
Number of UL TX Packets by (IMSI, LCID) pair.
Detailed Description
This class is an ns-3 trace sink that performs the calculation of PDU statistics for uplink and downlink.
Statistics are generated on a per radio bearer basis. This class can be used for RLC PDU stats or PDCP PDU stats by connecting to the appropriate trace sources at the RLC or PDCP layer.
The statistics are calculated at consecutive time windows and periodically written to a file. The calculated statistics are:
Number of transmitted PDUs
Number of received PDUs
Number of transmitted bytes
Number of received bytes
Average, min, max and standard deviation of PDU delay (delay is calculated from the generation of the PDU to its reception)
Average, min, max and standard deviation of PDU size
Definition at line 79 of file mmwave-bearer-stats-calculator.h.
Constructor & Destructor Documentation
MmWaveBearerStatsCalculator() [1/2]
ns3::mmwave::MmWaveBearerStatsCalculator::MmWaveBearerStatsCalculator ()
Class constructor.
Definition at line 48 of file mmwave-bearer-stats-calculator.cc.
MmWaveBearerStatsCalculator() [2/2]
ns3::mmwave::MmWaveBearerStatsCalculator::MmWaveBearerStatsCalculator (std::string protocolType)
Class constructor.
Definition at line 56 of file mmwave-bearer-stats-calculator.cc.
References m_protocolType.
~MmWaveBearerStatsCalculator()
ns3::mmwave::MmWaveBearerStatsCalculator::~MmWaveBearerStatsCalculator () virtual
Class destructor.
Definition at line 64 of file mmwave-bearer-stats-calculator.cc.
Member Function Documentation
DlRxPdu()
void ns3::mmwave::MmWaveBearerStatsCalculator::DlRxPdu (uint16_t cellId, uint64_t imsi, uint16_t rnti, uint8_t lcid, uint32_t packetSize, uint64_t delay)
Notifies the stats calculator that an downlink reception has occurred.
Parameters
cellId CellId of the attached Enb
imsi IMSI of the UE who received the PDU
rnti C-RNTI of the UE who received the PDU
lcid LCID through which the PDU has been transmitted
packetSize size of the PDU in bytes
delay RLC to RLC delay in nanoseconds
Definition at line 257 of file mmwave-bearer-stats-calculator.cc.
References GetDlOutputFilename(), and m_dlOutFile.
DlTxPdu()
void ns3::mmwave::MmWaveBearerStatsCalculator::DlTxPdu (uint16_t cellId, uint64_t imsi, uint16_t rnti, uint8_t lcid, uint32_t packetSize)
Notifies the stats calculator that an downlink transmission has occurred.
Parameters
cellId CellId of the attached Enb
imsi IMSI of the UE who is receiving the PDU
rnti C-RNTI of the UE who is receiving the PDU
lcid LCID through which the PDU has been transmitted
packetSize size of the PDU in bytes
Definition at line 180 of file mmwave-bearer-stats-calculator.cc.
References GetDlOutputFilename(), and m_dlOutFile.
DoDispose()
void ns3::mmwave::MmWaveBearerStatsCalculator::DoDispose ()
Definition at line 111 of file mmwave-bearer-stats-calculator.cc.
References m_pendingOutput, and ShowResults().
EndEpoch()
void ns3::mmwave::MmWaveBearerStatsCalculator::EndEpoch (void) private
Function called in every endEpochEvent.
It calls ShowResults() to write statistics to output files and ResetResults() to clear collected statistics.
Definition at line 477 of file mmwave-bearer-stats-calculator.cc.
References m_endEpochEvent, m_epochDuration, m_startTime, ResetResults(), and ShowResults().
Referenced by RescheduleEndEpoch().
GetDlCellId()
uint32_t ns3::mmwave::MmWaveBearerStatsCalculator::GetDlCellId (uint64_t imsi, uint8_t lcid)
Gets the attached Enb cellId.
Parameters
imsi IMSI of the UE
lcid LCID
Returns
Enb cellId
Definition at line 620 of file mmwave-bearer-stats-calculator.cc.
References m_dlCellId.
Referenced by WriteDlResults().
GetDlDelay()
double ns3::mmwave::MmWaveBearerStatsCalculator::GetDlDelay (uint64_t imsi, uint8_t lcid)
Gets the downlink RLC to RLC delay.
Parameters
imsi IMSI of the UE
lcid LCID
Returns
RLC to RLC delay in seconds
Definition at line 628 of file mmwave-bearer-stats-calculator.cc.
References m_dlDelay.
GetDlDelayStats()
std::vector< double > ns3::mmwave::MmWaveBearerStatsCalculator::GetDlDelayStats (uint64_t imsi, uint8_t lcid)
Gets the downlink RLC to RLC statistics: average, min, max and standard deviation.
Parameters
imsi IMSI of the UE
lcid LCID
Returns
RLC to RLC delay statistics average, min, max and standard deviation in seconds
Definition at line 642 of file mmwave-bearer-stats-calculator.cc.
References m_dlDelay.
Referenced by WriteDlResults().
GetDlOutputFilename()
std::string ns3::mmwave::MmWaveBearerStatsCalculator::GetDlOutputFilename (void)
Get the name of the file where the downlink statistics will be stored.
Returns
the name of the file where the downlink statistics will be stored
Definition at line 701 of file mmwave-bearer-stats-calculator.cc.
References GetDlPdcpOutputFilename(), and m_protocolType.
Referenced by DlRxPdu(), DlTxPdu(), and ShowResults().
GetDlPdcpOutputFilename()
std::string ns3::mmwave::MmWaveBearerStatsCalculator::GetDlPdcpOutputFilename (void)
Get the name of the file where the downlink PDCP statistics will be stored.
Returns
the name of the file where the downlink PDCP statistics will be stored
Definition at line 731 of file mmwave-bearer-stats-calculator.cc.
References m_dlPdcpOutputFilename.
Referenced by GetDlOutputFilename().
GetDlPduSizeStats()
std::vector< double > ns3::mmwave::MmWaveBearerStatsCalculator::GetDlPduSizeStats (uint64_t imsi, uint8_t lcid)
Gets the downlink PDU size statistics: average, min, max and standard deviation.
Parameters
imsi IMSI of the UE
lcid LCID
Returns
PDU size statistics average, min, max and standard deviation in seconds
Definition at line 665 of file mmwave-bearer-stats-calculator.cc.
References m_dlPduSize.
Referenced by WriteDlResults().
GetDlRxData()
uint64_t ns3::mmwave::MmWaveBearerStatsCalculator::GetDlRxData (uint64_t imsi, uint8_t lcid)
Gets the number of received downlink data bytes.
Parameters
imsi IMSI of the UE
lcid LCID
Returns
number of received data bytes
Definition at line 604 of file mmwave-bearer-stats-calculator.cc.
References m_dlRxData.
Referenced by WriteDlResults().
GetDlRxPackets()
uint32_t ns3::mmwave::MmWaveBearerStatsCalculator::GetDlRxPackets (uint64_t imsi, uint8_t lcid)
Gets the number of received downlink data bytes.
Parameters
imsi IMSI of the UE
lcid LCID
Returns
number of received data bytes
Definition at line 588 of file mmwave-bearer-stats-calculator.cc.
References m_dlRxPackets.
Referenced by WriteDlResults().
GetDlTxData()
uint64_t ns3::mmwave::MmWaveBearerStatsCalculator::GetDlTxData (uint64_t imsi, uint8_t lcid)
Gets the number of transmitted downlink data bytes.
Parameters
imsi IMSI of the UE
lcid LCID
Returns
number of transmitted data bytes
Definition at line 596 of file mmwave-bearer-stats-calculator.cc.
References m_dlTxData.
Referenced by WriteDlResults().
GetDlTxPackets()
uint32_t ns3::mmwave::MmWaveBearerStatsCalculator::GetDlTxPackets (uint64_t imsi, uint8_t lcid)
Gets the number of transmitted downlink data bytes.
Parameters
imsi IMSI of the UE
lcid LCID
Returns
number of transmitted data bytes
Definition at line 580 of file mmwave-bearer-stats-calculator.cc.
References m_dlTxPackets.
Referenced by WriteDlResults().
GetEpoch()
Time ns3::mmwave::MmWaveBearerStatsCalculator::GetEpoch () const
Returns
the epoch duration
Definition at line 141 of file mmwave-bearer-stats-calculator.cc.
References m_epochDuration.
Referenced by GetTypeId().
GetStartTime()
Time ns3::mmwave::MmWaveBearerStatsCalculator::GetStartTime () const
Returns
the value of the StartTime attribute
Definition at line 128 of file mmwave-bearer-stats-calculator.cc.
References m_startTime.
Referenced by GetTypeId().
GetTypeId()
TypeId ns3::mmwave::MmWaveBearerStatsCalculator::GetTypeId (void) static
Register this type.
Returns
The object TypeId.
Definition at line 70 of file mmwave-bearer-stats-calculator.cc.
References GetEpoch(), GetStartTime(), SetDlPdcpOutputFilename(), SetEpoch(), SetStartTime(), and SetUlPdcpOutputFilename().
GetUlCellId()
uint32_t ns3::mmwave::MmWaveBearerStatsCalculator::GetUlCellId (uint64_t imsi, uint8_t lcid)
Gets the attached Enb cellId.
Parameters
imsi IMSI of the UE
lcid LCID
Returns
Enb cellId
Definition at line 612 of file mmwave-bearer-stats-calculator.cc.
References m_ulCellId.
Referenced by WriteUlResults().
GetUlDelay()
double ns3::mmwave::MmWaveBearerStatsCalculator::GetUlDelay (uint64_t imsi, uint8_t lcid)
Gets the uplink RLC to RLC delay.
Parameters
imsi IMSI of the UE
lcid LCID
Returns
RLC to RLC delay in seconds
Definition at line 519 of file mmwave-bearer-stats-calculator.cc.
References m_ulDelay.
GetUlDelayStats()
std::vector< double > ns3::mmwave::MmWaveBearerStatsCalculator::GetUlDelayStats (uint64_t imsi, uint8_t lcid)
Gets the uplink RLC to RLC statistics: average, min, max and standard deviation.
Parameters
imsi IMSI of the UE
lcid LCID
Returns
RLC to RLC delay statistics average, min, max and standard deviation in seconds
Definition at line 534 of file mmwave-bearer-stats-calculator.cc.
References m_ulDelay.
Referenced by WriteUlResults().
GetUlOutputFilename()
std::string ns3::mmwave::MmWaveBearerStatsCalculator::GetUlOutputFilename (void)
Get the name of the file where the uplink statistics will be stored.
Returns
the name of the file where the uplink statistics will be stored
Definition at line 688 of file mmwave-bearer-stats-calculator.cc.
References GetUlPdcpOutputFilename(), and m_protocolType.
Referenced by ShowResults(), UlRxPdu(), and UlTxPdu().
GetUlPdcpOutputFilename()
std::string ns3::mmwave::MmWaveBearerStatsCalculator::GetUlPdcpOutputFilename (void)
Get the name of the file where the uplink PDCP statistics will be stored.
Returns
the name of the file where the uplink PDCP statistics will be stored
Definition at line 720 of file mmwave-bearer-stats-calculator.cc.
References m_ulPdcpOutputFilename.
Referenced by GetUlOutputFilename().
GetUlPduSizeStats()
std::vector< double > ns3::mmwave::MmWaveBearerStatsCalculator::GetUlPduSizeStats (uint64_t imsi, uint8_t lcid)
Gets the uplink PDU size statistics: average, min, max and standard deviation.
Parameters
imsi IMSI of the UE
lcid LCID
Returns
PDU size statistics average, min, max and standard deviation in seconds
Definition at line 557 of file mmwave-bearer-stats-calculator.cc.
References m_ulPduSize.
Referenced by WriteUlResults().
GetUlRxData()
uint64_t ns3::mmwave::MmWaveBearerStatsCalculator::GetUlRxData (uint64_t imsi, uint8_t lcid)
Gets the number of received uplink data bytes.
Parameters
imsi IMSI of the UE
lcid LCID
Returns
number of received data bytes
Definition at line 511 of file mmwave-bearer-stats-calculator.cc.
References m_ulRxData.
Referenced by WriteUlResults().
GetUlRxPackets()
uint32_t ns3::mmwave::MmWaveBearerStatsCalculator::GetUlRxPackets (uint64_t imsi, uint8_t lcid)
Gets the number of received uplink packets.
Parameters
imsi IMSI of the UE
lcid LCID
Returns
number of received uplink packets
Definition at line 495 of file mmwave-bearer-stats-calculator.cc.
References m_ulRxPackets.
Referenced by WriteUlResults().
GetUlTxData()
uint64_t ns3::mmwave::MmWaveBearerStatsCalculator::GetUlTxData (uint64_t imsi, uint8_t lcid)
Gets the number of transmitted uplink data bytes.
Parameters
imsi IMSI of the UE
lcid LCID
Returns
number of transmitted data bytes
Definition at line 503 of file mmwave-bearer-stats-calculator.cc.
References m_ulTxData.
Referenced by WriteUlResults().
GetUlTxPackets()
uint32_t ns3::mmwave::MmWaveBearerStatsCalculator::GetUlTxPackets (uint64_t imsi, uint8_t lcid)
Gets the number of transmitted uplink packets.
Parameters
imsi IMSI of the UE
lcid LCID
Returns
number of transmitted uplink packets
Definition at line 487 of file mmwave-bearer-stats-calculator.cc.
References m_ulTxPackets.
Referenced by WriteUlResults().
RescheduleEndEpoch()
void ns3::mmwave::MmWaveBearerStatsCalculator::RescheduleEndEpoch (void) private
Reschedules EndEpoch event.
Usually used after execution of SetStartTime() or SetEpoch()
Definition at line 468 of file mmwave-bearer-stats-calculator.cc.
References EndEpoch(), m_endEpochEvent, m_epochDuration, and m_startTime.
ResetResults()
void ns3::mmwave::MmWaveBearerStatsCalculator::ResetResults (void) private
Erases collected statistics.
Definition at line 448 of file mmwave-bearer-stats-calculator.cc.
References m_dlDelay, m_dlPduSize, m_dlRxData, m_dlRxPackets, m_dlTxData, m_dlTxPackets, m_ulDelay, m_ulPduSize, m_ulRxData, m_ulRxPackets, m_ulTxData, and m_ulTxPackets.
Referenced by EndEpoch().
SetDlPdcpOutputFilename()
void ns3::mmwave::MmWaveBearerStatsCalculator::SetDlPdcpOutputFilename (std::string outputFilename)
Set the name of the file where the downlink PDCP statistics will be stored.
Parameters
outputFilename string with the name of the file
Definition at line 725 of file mmwave-bearer-stats-calculator.cc.
References m_dlPdcpOutputFilename.
Referenced by GetTypeId().
SetEpoch()
void ns3::mmwave::MmWaveBearerStatsCalculator::SetEpoch (Time e)
Parameters
e the epoch duration
Definition at line 134 of file mmwave-bearer-stats-calculator.cc.
References m_epochDuration.
Referenced by GetTypeId().
SetStartTime()
void ns3::mmwave::MmWaveBearerStatsCalculator::SetStartTime (Time t)
Parameters
t the value of the StartTime attribute
Definition at line 121 of file mmwave-bearer-stats-calculator.cc.
References m_startTime.
Referenced by GetTypeId().
SetUlPdcpOutputFilename()
void ns3::mmwave::MmWaveBearerStatsCalculator::SetUlPdcpOutputFilename (std::string outputFilename)
Set the name of the file where the uplink PDCP statistics will be stored.
Parameters
outputFilename string with the name of the file
Definition at line 714 of file mmwave-bearer-stats-calculator.cc.
References m_ulPdcpOutputFilename.
Referenced by GetTypeId().
ShowResults()
void ns3::mmwave::MmWaveBearerStatsCalculator::ShowResults (void) private
Called after each epoch to write collected statistics to output files.
During first call it opens output files and write columns descriptions. During next calls it opens output files in append mode.
Definition at line 299 of file mmwave-bearer-stats-calculator.cc.
References GetDlOutputFilename(), GetUlOutputFilename(), m_firstWrite, m_pendingOutput, WriteDlResults(), and WriteUlResults().
Referenced by DoDispose(), and EndEpoch().
UlRxPdu()
void ns3::mmwave::MmWaveBearerStatsCalculator::UlRxPdu (uint16_t cellId, uint64_t imsi, uint16_t rnti, uint8_t lcid, uint32_t packetSize, uint64_t delay)
Notifies the stats calculator that an uplink reception has occurred.
Parameters
cellId CellId of the attached Enb
imsi IMSI of the UE who received the PDU
rnti C-RNTI of the UE who received the PDU
lcid LCID through which the PDU has been received
packetSize size of the PDU in bytes
delay RLC to RLC delay in nanoseconds
Definition at line 214 of file mmwave-bearer-stats-calculator.cc.
References GetUlOutputFilename(), and m_ulOutFile.
UlTxPdu()
void ns3::mmwave::MmWaveBearerStatsCalculator::UlTxPdu (uint16_t cellId, uint64_t imsi, uint16_t rnti, uint8_t lcid, uint32_t packetSize)
Notifies the stats calculator that an uplink transmission has occurred.
Parameters
cellId CellId of the attached Enb
imsi IMSI of the UE who transmitted the PDU
rnti C-RNTI of the UE who transmitted the PDU
lcid LCID through which the PDU has been transmitted
packetSize size of the PDU in bytes
Definition at line 147 of file mmwave-bearer-stats-calculator.cc.
References GetUlOutputFilename(), and m_ulOutFile.
WriteDlResults()
void ns3::mmwave::MmWaveBearerStatsCalculator::WriteDlResults (std::ofstream & outFile) private
Writes collected statistics to DL output file and closes DL output file.
Parameters
outFile ofstream for DL statistics
Definition at line 403 of file mmwave-bearer-stats-calculator.cc.
References GetDlCellId(), GetDlDelayStats(), GetDlPduSizeStats(), GetDlRxData(), GetDlRxPackets(), GetDlTxData(), GetDlTxPackets(), m_dlTxPackets, m_epochDuration, m_flowId, and m_startTime.
Referenced by ShowResults().
WriteUlResults()
void ns3::mmwave::MmWaveBearerStatsCalculator::WriteUlResults (std::ofstream & outFile) private
Writes collected statistics to UL output file and closes UL output file.
Parameters
outFile ofstream for UL statistics
Definition at line 357 of file mmwave-bearer-stats-calculator.cc.
References GetUlCellId(), GetUlDelayStats(), GetUlPduSizeStats(), GetUlRxData(), GetUlRxPackets(), GetUlTxData(), GetUlTxPackets(), m_epochDuration, m_flowId, m_startTime, and m_ulTxPackets.
Referenced by ShowResults().
Member Data Documentation
m_dlCellId
Uint32Map ns3::mmwave::MmWaveBearerStatsCalculator::m_dlCellId private
List of DL CellIds by (IMSI, LCID) pair.
Definition at line 408 of file mmwave-bearer-stats-calculator.h.
Referenced by GetDlCellId().
m_dlDelay
Uint64StatsMap ns3::mmwave::MmWaveBearerStatsCalculator::m_dlDelay private
DL delay by (IMSI, LCID) pair.
Definition at line 413 of file mmwave-bearer-stats-calculator.h.
Referenced by GetDlDelay(), GetDlDelayStats(), and ResetResults().
m_dlOutFile
std::ofstream ns3::mmwave::MmWaveBearerStatsCalculator::m_dlOutFile private
Definition at line 459 of file mmwave-bearer-stats-calculator.h.
Referenced by DlRxPdu(), and DlTxPdu().
m_dlPdcpOutputFilename
std::string ns3::mmwave::MmWaveBearerStatsCalculator::m_dlPdcpOutputFilename private
Name of the file where the downlink PDCP statistics will be saved.
Definition at line 452 of file mmwave-bearer-stats-calculator.h.
Referenced by GetDlPdcpOutputFilename(), and SetDlPdcpOutputFilename().
m_dlPduSize
Uint32StatsMap ns3::mmwave::MmWaveBearerStatsCalculator::m_dlPduSize private
DL PDU Size by (IMSI, LCID) pair.
Definition at line 414 of file mmwave-bearer-stats-calculator.h.
Referenced by GetDlPduSizeStats(), and ResetResults().
m_dlRxData
Uint64Map ns3::mmwave::MmWaveBearerStatsCalculator::m_dlRxData private
Amount of DL RX Data by (IMSI, LCID) pair.
Definition at line 412 of file mmwave-bearer-stats-calculator.h.
Referenced by GetDlRxData(), and ResetResults().
m_dlRxPackets
Uint32Map ns3::mmwave::MmWaveBearerStatsCalculator::m_dlRxPackets private
Number of DL RX Packets by (IMSI, LCID) pair.
Definition at line 410 of file mmwave-bearer-stats-calculator.h.
Referenced by GetDlRxPackets(), and ResetResults().
m_dlTxData
Uint64Map ns3::mmwave::MmWaveBearerStatsCalculator::m_dlTxData private
Amount of DL TX Data by (IMSI, LCID) pair.
Definition at line 411 of file mmwave-bearer-stats-calculator.h.
Referenced by GetDlTxData(), and ResetResults().
m_dlTxPackets
Uint32Map ns3::mmwave::MmWaveBearerStatsCalculator::m_dlTxPackets private
Number of DL TX Packets by (IMSI, LCID) pair.
Definition at line 409 of file mmwave-bearer-stats-calculator.h.
Referenced by GetDlTxPackets(), ResetResults(), and WriteDlResults().
m_endEpochEvent
EventId ns3::mmwave::MmWaveBearerStatsCalculator::m_endEpochEvent private
Event id for next end epoch event.
Definition at line 404 of file mmwave-bearer-stats-calculator.h.
Referenced by EndEpoch(), and RescheduleEndEpoch().
m_epochDuration
Time ns3::mmwave::MmWaveBearerStatsCalculator::m_epochDuration private
Epoch duration.
Definition at line 432 of file mmwave-bearer-stats-calculator.h.
Referenced by EndEpoch(), GetEpoch(), RescheduleEndEpoch(), SetEpoch(), WriteDlResults(), and WriteUlResults().
m_firstWrite
bool ns3::mmwave::MmWaveBearerStatsCalculator::m_firstWrite private
true if output files have not been opened yet
Definition at line 437 of file mmwave-bearer-stats-calculator.h.
Referenced by ShowResults().
m_flowId
FlowIdMap ns3::mmwave::MmWaveBearerStatsCalculator::m_flowId private
List of FlowIds, ie.
(RNTI, LCID) by (IMSI, LCID) pair
Definition at line 406 of file mmwave-bearer-stats-calculator.h.
Referenced by WriteDlResults(), and WriteUlResults().
m_pendingOutput
bool ns3::mmwave::MmWaveBearerStatsCalculator::m_pendingOutput private
true if any output is pending
Definition at line 442 of file mmwave-bearer-stats-calculator.h.
Referenced by DoDispose(), and ShowResults().
m_protocolType
std::string ns3::mmwave::MmWaveBearerStatsCalculator::m_protocolType private
Protocol type, by default RLC.
Definition at line 447 of file mmwave-bearer-stats-calculator.h.
Referenced by GetDlOutputFilename(), GetUlOutputFilename(), and MmWaveBearerStatsCalculator().
m_startTime
Time ns3::mmwave::MmWaveBearerStatsCalculator::m_startTime private
Start time of the on going epoch.
Definition at line 427 of file mmwave-bearer-stats-calculator.h.
Referenced by EndEpoch(), GetStartTime(), RescheduleEndEpoch(), SetStartTime(), WriteDlResults(), and WriteUlResults().
m_ulCellId
Uint32Map ns3::mmwave::MmWaveBearerStatsCalculator::m_ulCellId private
List of UL CellIds by (IMSI, LCID) pair.
Definition at line 416 of file mmwave-bearer-stats-calculator.h.
Referenced by GetUlCellId().
m_ulDelay
Uint64StatsMap ns3::mmwave::MmWaveBearerStatsCalculator::m_ulDelay private
UL delay by (IMSI, LCID) pair.
Definition at line 421 of file mmwave-bearer-stats-calculator.h.
Referenced by GetUlDelay(), GetUlDelayStats(), and ResetResults().
m_ulOutFile
std::ofstream ns3::mmwave::MmWaveBearerStatsCalculator::m_ulOutFile private
Definition at line 460 of file mmwave-bearer-stats-calculator.h.
Referenced by UlRxPdu(), and UlTxPdu().
m_ulPdcpOutputFilename
std::string ns3::mmwave::MmWaveBearerStatsCalculator::m_ulPdcpOutputFilename private
Name of the file where the uplink PDCP statistics will be saved.
Definition at line 457 of file mmwave-bearer-stats-calculator.h.
Referenced by GetUlPdcpOutputFilename(), and SetUlPdcpOutputFilename().
m_ulPduSize
Uint32StatsMap ns3::mmwave::MmWaveBearerStatsCalculator::m_ulPduSize private
UL PDU Size by (IMSI, LCID) pair.
Definition at line 422 of file mmwave-bearer-stats-calculator.h.
Referenced by GetUlPduSizeStats(), and ResetResults().
m_ulRxData
Uint64Map ns3::mmwave::MmWaveBearerStatsCalculator::m_ulRxData private
Amount of UL RX Data by (IMSI, LCID) pair.
Definition at line 420 of file mmwave-bearer-stats-calculator.h.
Referenced by GetUlRxData(), and ResetResults().
m_ulRxPackets
Uint32Map ns3::mmwave::MmWaveBearerStatsCalculator::m_ulRxPackets private
Number of UL RX Packets by (IMSI, LCID) pair.
Definition at line 418 of file mmwave-bearer-stats-calculator.h.
Referenced by GetUlRxPackets(), and ResetResults().
m_ulTxData
Uint64Map ns3::mmwave::MmWaveBearerStatsCalculator::m_ulTxData private
Amount of UL TX Data by (IMSI, LCID) pair.
Definition at line 419 of file mmwave-bearer-stats-calculator.h.
Referenced by GetUlTxData(), and ResetResults().
m_ulTxPackets
Uint32Map ns3::mmwave::MmWaveBearerStatsCalculator::m_ulTxPackets private
Number of UL TX Packets by (IMSI, LCID) pair.
Definition at line 417 of file mmwave-bearer-stats-calculator.h.
Referenced by GetUlTxPackets(), ResetResults(), and WriteUlResults().
The documentation for this class was generated from the following files:
src/mmwave/helper/mmwave-bearer-stats-calculator.h
src/mmwave/helper/mmwave-bearer-stats-calculator.cc