ns3-mmwave: ns3::mmwave::MmWaveEnbPhy Class Reference
ns3::mmwave::MmWaveEnbPhy Class Reference
#include "mmwave-enb-phy.h"
Public Member Functions
MmWaveEnbPhy ()
MmWaveEnbPhy (Ptr< MmWaveSpectrumPhy >, Ptr< MmWaveSpectrumPhy >)
virtual ~MmWaveEnbPhy ()
double AddGaussianNoise (double sample)
bool AddUePhy (uint64_t imsi, Ptr< NetDevice > ueDevice)
virtual void SendIdealControlMessage(Ptr<IdealControlMessage> msg); virtual void ReceiveIdealControlMessage(Ptr<IdealControlMessage> msg)
std::pair< uint64_t, uint64_t > ApplyFilter (std::vector< double >)
void CalcChannelQualityForUe (std::vector< double > sinr, Ptr< MmWaveSpectrumPhy > ue)
virtual Ptr< SpectrumValue > CreateTxPowerSpectralDensity () override
Compute the TX Power Spectral Density.
virtual void DoDispose (void) override
int8_t DoGetReferenceSignalPower () const
virtual void DoInitialize (void) override
void DoSetSubChannels ()
void EndSlot (void)
Marks the end of the current NR slot.
void EndTti (void)
Marks the end of the current Transmission Time Interval (TTI).
void GenerateDataCqiReport (const SpectrumValue &sinr)
uint32_t GetAbsoluteSubframeNo ()
Ptr< MmWaveSpectrumPhy > GetDlSpectrumPhy () const
LteEnbCphySapProvider * GetMmWaveEnbCphySapProvider ()
double GetNoiseFigure () const
double GetTxPower () const
Ptr< MmWaveSpectrumPhy > GetUlSpectrumPhy () const
double MakeAvg (std::vector< double >)
std::vector< double > MakeFilter (std::vector< double >, std::vector< double >, std::pair< uint64_t, uint64_t >)
double MakeVar (std::vector< double >, double)
void PhyCtrlMessagesReceived (std::list< Ptr< MmWaveControlMessage > > msgList)
void PhyDataPacketReceived (Ptr< Packet > p)
void ReceiveUlHarqFeedback (UlHarqInfo mes)
void SendCtrlChannels (std::list< Ptr< MmWaveControlMessage > > ctrlMsg, Time slotPrd)
void SendDataChannels (Ptr< PacketBurst > pb, Time slotPrd, TtiAllocInfo &slotInfo)
void SetHarqPhyModule (Ptr< MmWaveHarqPhy > harq)
void SetMmWaveEnbCphySapUser (LteEnbCphySapUser *s)
void SetNoiseFigure (double pf)
void SetPhySapUser (MmWaveEnbPhySapUser *ptr)
void SetSubChannels (std::vector< int > mask)
void SetTxPower (double pow)
void StartSlot (void)
Marks the beginning of a new NR slot.
void StartTti (void)
Marks the beginning of a new Transmission Time Interval (TTI).
void UpdateUeSinrEstimate ()
Public Member Functions inherited from ns3::mmwave::MmWavePhy
MmWavePhy ()
MmWavePhy (Ptr< MmWaveSpectrumPhy > dlChannelPhy, Ptr< MmWaveSpectrumPhy > ulChannelPhy)
virtual ~MmWavePhy ()
void AddPropagationLossModel (Ptr< PropagationLossModel > model)
void AddSpectrumPropagationLossModel (Ptr< SpectrumPropagationLossModel > model)
void DoSetCellId (uint16_t cellId)
void DoSetSlotAllocInfo (SlotAllocInfo sfAllocInfo)
uint8_t GetComponentCarrierId ()
Get the component carrier ID.
Ptr< MmWavePhyMacCommon > GetConfigurationParameters (void) const
std::list< Ptr< MmWaveControlMessage > > GetControlMessages (void)
Ptr< NetDevice > GetDevice ()
Time GetNextSlotDelay ()
The purpose of this function is to sync the slot duration to the correct value.
double GetNoiseFigure (void) const
virtual Ptr< PacketBurst > GetPacketBurst (SfnSf)
MmWavePhySapProvider * GetPhySapProvider ()
SlotAllocInfo GetSfAllocInfo (uint8_t subframeNum)
virtual void SendRachPreamble (uint32_t PreambleId, uint32_t Rnti)
void SetChannel (Ptr< SpectrumChannel > c)
void SetComponentCarrierId (uint8_t index)
Set the component carrier ID.
void SetConfigurationParameters (Ptr< MmWavePhyMacCommon > ptrConfig)
void SetControlMessage (Ptr< MmWaveControlMessage > m)
void SetDevice (Ptr< NetDevice > d)
virtual void SetMacPdu (Ptr< Packet > pb)
void SetNoiseFigure (double nf)
void SetSlotCtrlStructure (uint8_t slotIndex)
Sets the control data allocation within a NR slot.
void UpdateCurrentAllocationAndSchedule (uint32_t frame, uint32_t sf)
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::mmwave::MmWavePhy
static TypeId GetTypeId (void)
Public Attributes
SlotAllocInfo m_currSlotAllocInfo
Holds the allocation info for the current NR slot.
Private Member Functions
bool AddUePhy (uint16_t rnti)
void DoAddUe (uint16_t rnti)
void DoRemoveUe (uint16_t rnti)
void DoSetBandwidth (uint8_t ulBandwidth, uint8_t dlBandwidth)
void DoSetBandwidth (uint8_t Bandwidth)
void DoSetEarfcn (uint16_t dlEarfcn, uint16_t ulEarfcn)
void DoSetEarfcn (uint16_t Earfcn)
void DoSetMasterInformationBlock (LteRrcSap::MasterInformationBlock mib)
void DoSetPa (uint16_t rnti, double pa)
void DoSetSrsConfigurationIndex (uint16_t rnti, uint16_t srcCi)
void DoSetSystemInformationBlockType1 (LteRrcSap::SystemInformationBlockType1 sib1)
void DoSetTransmissionMode (uint16_t rnti, uint8_t txMode)
void TraceDlPhyTransmission (DciInfoElementTdma dciInfo, uint8_t tddType)
Triggers the callback for the ReportDlPhyTransmission Trace Source.
Private Attributes
std::vector< int > m_channelChunks
uint8_t m_currSlotNumTti
The amount of TTIs scheduled in the current slot.
uint8_t m_currSymStart
Beginning of the current TTI, expressed as OFDM symbol # within the NR slot.
std::vector< Ptr< NetDevice > > m_deviceMap
TracedCallback< PhyTransmissionTraceParams > m_dlPhyTrace
Traces the current TTI allocation info, from the eNB side.
LteEnbCphySapProvider * m_enbCphySapProvider
LteEnbCphySapUser * m_enbCphySapUser
std::map< pairDevices_t, std::vector< double > > m_finalSinrVector
Ptr< MmWaveHarqPhy > m_harqPhyModule
std::vector< int > m_listOfSubchannels
bool m_noiseAndFilter
MmWaveEnbPhySapUser * m_phySapUser
uint8_t m_prevSlot
1->UL 0->DL 2->Unspecified
TtiAllocInfo::TddMode m_prevTtiDir
Previous TTI TDD mode; 0->Unspecified, 1->DL, 2->UL.
uint16_t m_roundFromLastUeSinrUpdate
std::map< uint64_t, Ptr< SpectrumValue > > m_rxPsdMap
std::map< pairDevices_t, std::pair< uint64_t, uint64_t > > m_samplesFilter
LteRrcSap::SystemInformationBlockType1 m_sib1
std::map< uint64_t, double > m_sinrMap
std::map< pairDevices_t, std::vector< double > > m_sinrVector
std::map< pairDevices_t, std::vector< double > > m_sinrVectorNoisy
std::map< pairDevices_t, std::vector< double > > m_sinrVectorToFilter
double m_transient
std::set< uint64_t > m_ueAttached
std::map< uint64_t, Ptr< NetDevice > > m_ueAttachedImsiMap
std::set< uint16_t > m_ueAttachedRnti
double m_ueUpdateSinrPeriod
TracedCallback< uint64_t, SpectrumValue &, SpectrumValue &> m_ulSinrTrace
double m_updateSinrCollect
int m_updateSinrPeriod
Friends
class MemberLteEnbCphySapProvider< MmWaveEnbPhy >
Additional Inherited Members
Protected Attributes inherited from ns3::mmwave::MmWavePhy
uint16_t m_cellId
uint8_t m_componentCarrierId
component carrier Id used to address sap
std::vector< std::list< Ptr< MmWaveControlMessage > > > m_controlMessageQueue
Time m_ctrlPeriod
Time m_dataPeriod
Ptr< MmWaveSpectrumPhy > m_downlinkSpectrumPhy
uint16_t m_frameNum
Time m_lastSlotStart
Time at which the current slot started.
Ptr< NetDevice > m_netDevice
double m_noiseFigure
std::map< uint64_t, Ptr< PacketBurst > > m_packetBurstMap
Ptr< MmWavePhyMacCommon > m_phyMacConfig
MmWavePhySapProvider * m_phySapProvider
Ptr< PropagationLossModel > m_propagationLoss
uint32_t m_raPreambleId
bool m_sfAllocInfoUpdated
uint8_t m_sfNum
std::vector< SlotAllocInfo > m_slotAllocInfo
Maps slot number to its allocation info.
std::map< uint32_t, SlotAllocInfo > m_slotAllocInfoMap
uint8_t m_slotNum
Time m_slotPeriod
Slot period time duration.
Ptr< MmWaveSpectrumPhy > m_spectrumPhy
Ptr< SpectrumPropagationLossModel > m_spectrumPropagationLossModel
uint8_t m_ttiIndex
Keeps track of the TTIs within the single NR slot.
double m_txPower
Ptr< MmWaveSpectrumPhy > m_uplinkSpectrumPhy
Detailed Description
Definition at line 59 of file mmwave-enb-phy.h.
Constructor & Destructor Documentation
MmWaveEnbPhy() [1/2]
ns3::mmwave::MmWaveEnbPhy::MmWaveEnbPhy ()
Definition at line 74 of file mmwave-enb-phy.cc.
MmWaveEnbPhy() [2/2]
ns3::mmwave::MmWaveEnbPhy::MmWaveEnbPhy (Ptr< MmWaveSpectrumPhy > dlPhy, Ptr< MmWaveSpectrumPhy > ulPhy)
Definition at line 80 of file mmwave-enb-phy.cc.
References m_enbCphySapProvider, m_roundFromLastUeSinrUpdate, MemberLteEnbCphySapProvider< MmWaveEnbPhy >, and StartSlot().
~MmWaveEnbPhy()
ns3::mmwave::MmWaveEnbPhy::~MmWaveEnbPhy () virtual
Definition at line 91 of file mmwave-enb-phy.cc.
Member Function Documentation
AddGaussianNoise()
double ns3::mmwave::MmWaveEnbPhy::AddGaussianNoise (double sample)
Definition at line 247 of file mmwave-enb-phy.cc.
Referenced by UpdateUeSinrEstimate().
AddUePhy() [1/2]
bool ns3::mmwave::MmWaveEnbPhy::AddUePhy (uint64_t imsi, Ptr< NetDevice > ueDevice)
virtual void SendIdealControlMessage(Ptr<IdealControlMessage> msg); virtual void ReceiveIdealControlMessage(Ptr<IdealControlMessage> msg)
Definition at line 1216 of file mmwave-enb-phy.cc.
References m_deviceMap, m_ueAttached, and m_ueAttachedImsiMap.
Referenced by DoAddUe().
AddUePhy() [2/2]
bool ns3::mmwave::MmWaveEnbPhy::AddUePhy (uint16_t rnti) private
Definition at line 1369 of file mmwave-enb-phy.cc.
References m_ueAttachedRnti.
ApplyFilter()
std::pair< uint64_t, uint64_t > ns3::mmwave::MmWaveEnbPhy::ApplyFilter (std::vector< double > noisySinr)
Definition at line 269 of file mmwave-enb-phy.cc.
References MakeAvg(), and MakeVar().
Referenced by UpdateUeSinrEstimate().
CalcChannelQualityForUe()
void ns3::mmwave::MmWaveEnbPhy::CalcChannelQualityForUe (std::vector< double > sinr, Ptr< MmWaveSpectrumPhy > ue)
Definition at line 540 of file mmwave-enb-phy.cc.
CreateTxPowerSpectralDensity()
Ptr< SpectrumValue > ns3::mmwave::MmWaveEnbPhy::CreateTxPowerSpectralDensity () override virtual
Compute the TX Power Spectral Density.
Returns
a pointer to a newly allocated SpectrumValue representing the TX Power Spectral Density in W/Hz for each Resource Block
Implements ns3::mmwave::MmWavePhy.
Definition at line 546 of file mmwave-enb-phy.cc.
References ns3::mmwave::MmWaveSpectrumValueHelper::CreateTxPowerSpectralDensity(), m_listOfSubchannels, ns3::mmwave::MmWavePhy::m_phyMacConfig, and ns3::mmwave::MmWavePhy::m_txPower.
Referenced by SetSubChannels().
DoAddUe()
void ns3::mmwave::MmWaveEnbPhy::DoAddUe (uint16_t rnti) private
Definition at line 1360 of file mmwave-enb-phy.cc.
References AddUePhy().
DoDispose()
void ns3::mmwave::MmWaveEnbPhy::DoDispose (void) override virtual
Reimplemented from ns3::mmwave::MmWavePhy.
Definition at line 203 of file mmwave-enb-phy.cc.
DoGetReferenceSignalPower()
int8_t ns3::mmwave::MmWaveEnbPhy::DoGetReferenceSignalPower () const
Definition at line 1437 of file mmwave-enb-phy.cc.
References ns3::mmwave::MmWavePhy::m_txPower.
DoInitialize()
void ns3::mmwave::MmWaveEnbPhy::DoInitialize (void) override virtual
Reimplemented from ns3::mmwave::MmWavePhy.
Definition at line 167 of file mmwave-enb-phy.cc.
References ns3::mmwave::MmWaveSpectrumValueHelper::CreateNoisePowerSpectralDensity(), ns3::mmwave::MmWavePhy::DoInitialize(), m_channelChunks, ns3::mmwave::MmWavePhy::m_controlMessageQueue, ns3::mmwave::MmWavePhy::m_downlinkSpectrumPhy, ns3::mmwave::MmWavePhy::m_frameNum, m_noiseAndFilter, ns3::mmwave::MmWavePhy::m_noiseFigure, ns3::mmwave::MmWavePhy::m_phyMacConfig, ns3::mmwave::MmWavePhy::m_sfNum, ns3::mmwave::MmWavePhy::m_slotAllocInfo, ns3::mmwave::MmWavePhy::m_slotPeriod, m_transient, m_updateSinrPeriod, ns3::mmwave::MmWavePhy::SetSlotCtrlStructure(), SetSubChannels(), and UpdateUeSinrEstimate().
DoRemoveUe()
void ns3::mmwave::MmWaveEnbPhy::DoRemoveUe (uint16_t rnti) private
Definition at line 1387 of file mmwave-enb-phy.cc.
References m_ueAttachedRnti.
DoSetBandwidth() [1/2]
void ns3::mmwave::MmWaveEnbPhy::DoSetBandwidth (uint8_t ulBandwidth, uint8_t dlBandwidth) private
Definition at line 1347 of file mmwave-enb-phy.cc.
DoSetBandwidth() [2/2]
void ns3::mmwave::MmWaveEnbPhy::DoSetBandwidth (uint8_t Bandwidth) private
DoSetEarfcn() [1/2]
void ns3::mmwave::MmWaveEnbPhy::DoSetEarfcn (uint16_t dlEarfcn, uint16_t ulEarfcn) private
Definition at line 1353 of file mmwave-enb-phy.cc.
DoSetEarfcn() [2/2]
void ns3::mmwave::MmWaveEnbPhy::DoSetEarfcn (uint16_t Earfcn) private
DoSetMasterInformationBlock()
void ns3::mmwave::MmWaveEnbPhy::DoSetMasterInformationBlock (LteRrcSap::MasterInformationBlock mib) private
Definition at line 1422 of file mmwave-enb-phy.cc.
DoSetPa()
void ns3::mmwave::MmWaveEnbPhy::DoSetPa (uint16_t rnti, double pa) private
Definition at line 1402 of file mmwave-enb-phy.cc.
DoSetSrsConfigurationIndex()
void ns3::mmwave::MmWaveEnbPhy::DoSetSrsConfigurationIndex (uint16_t rnti, uint16_t srcCi) private
Definition at line 1415 of file mmwave-enb-phy.cc.
DoSetSubChannels()
void ns3::mmwave::MmWaveEnbPhy::DoSetSubChannels ()
Definition at line 554 of file mmwave-enb-phy.cc.
DoSetSystemInformationBlockType1()
void ns3::mmwave::MmWaveEnbPhy::DoSetSystemInformationBlockType1 (LteRrcSap::SystemInformationBlockType1 sib1) private
Definition at line 1430 of file mmwave-enb-phy.cc.
References m_sib1.
DoSetTransmissionMode()
void ns3::mmwave::MmWaveEnbPhy::DoSetTransmissionMode (uint16_t rnti, uint8_t txMode) private
Definition at line 1408 of file mmwave-enb-phy.cc.
EndSlot()
void ns3::mmwave::MmWaveEnbPhy::EndSlot (void)
Marks the end of the current NR slot.
Periodically, it alternates with StartSlot in order to scan through the different NR slots. The various frame/subframe and slot counters get updated and, finally, a call to StartSlot is scheduled in order to start the next NR slot.
Definition at line 1131 of file mmwave-enb-phy.cc.
References ns3::mmwave::MmWavePhy::GetNextSlotDelay(), ns3::mmwave::MmWavePhy::m_frameNum, ns3::mmwave::MmWavePhy::m_phyMacConfig, ns3::mmwave::MmWavePhy::m_sfNum, ns3::mmwave::MmWavePhy::m_slotNum, ns3::mmwave::MmWavePhy::m_ttiIndex, and StartSlot().
Referenced by EndTti().
EndTti()
void ns3::mmwave::MmWaveEnbPhy::EndTti (void)
Marks the end of the current Transmission Time Interval (TTI).
Periodically, it alternates with StartTti in order to scan through the TTIs scheduled within a slot. If the end of the current TTI marks also the end of the current slot, EndSlot is called.
Definition at line 1109 of file mmwave-enb-phy.cc.
References EndSlot(), ns3::mmwave::MmWavePhy::GetNextSlotDelay(), m_currSlotAllocInfo, m_currSlotNumTti, ns3::mmwave::MmWavePhy::m_lastSlotStart, ns3::mmwave::MmWavePhy::m_phyMacConfig, ns3::mmwave::SlotAllocInfo::m_ttiAllocInfo, ns3::mmwave::MmWavePhy::m_ttiIndex, and StartTti().
Referenced by StartTti().
GenerateDataCqiReport()
void ns3::mmwave::MmWaveEnbPhy::GenerateDataCqiReport (const SpectrumValue & sinr)
Definition at line 1248 of file mmwave-enb-phy.cc.
References m_currSymStart, ns3::mmwave::MmWavePhy::m_frameNum, m_phySapUser, ns3::mmwave::MmWaveMacSchedSapProvider::SchedUlCqiInfoReqParameters::m_sfnSf, ns3::mmwave::MmWavePhy::m_sfNum, ns3::mmwave::UlCqiInfo::m_sinr, ns3::mmwave::MmWavePhy::m_slotNum, ns3::mmwave::UlCqiInfo::m_type, ns3::mmwave::MmWaveMacSchedSapProvider::SchedUlCqiInfoReqParameters::m_ulCqi, m_ulSinrTrace, ns3::mmwave::UlCqiInfo::PUSCH, and ns3::mmwave::MmWaveEnbPhySapUser::UlCqiReport().
Referenced by ns3::mmwave::MmWaveHelper::InstallSingleEnbDevice().
GetAbsoluteSubframeNo()
uint32_t ns3::mmwave::MmWaveEnbPhy::GetAbsoluteSubframeNo ()
Definition at line 1320 of file mmwave-enb-phy.cc.
References ns3::mmwave::MmWavePhy::m_frameNum, ns3::mmwave::MmWavePhy::m_phyMacConfig, and ns3::mmwave::MmWavePhy::m_slotNum.
GetDlSpectrumPhy()
Ptr< MmWaveSpectrumPhy > ns3::mmwave::MmWaveEnbPhy::GetDlSpectrumPhy () const
Definition at line 569 of file mmwave-enb-phy.cc.
References ns3::mmwave::MmWavePhy::m_downlinkSpectrumPhy.
Referenced by GetTypeId(), and UpdateUeSinrEstimate().
GetMmWaveEnbCphySapProvider()
LteEnbCphySapProvider * ns3::mmwave::MmWaveEnbPhy::GetMmWaveEnbCphySapProvider ()
Definition at line 511 of file mmwave-enb-phy.cc.
References m_enbCphySapProvider.
GetNoiseFigure()
double ns3::mmwave::MmWaveEnbPhy::GetNoiseFigure (void) const
Definition at line 534 of file mmwave-enb-phy.cc.
References ns3::mmwave::MmWavePhy::m_noiseFigure.
GetTxPower()
double ns3::mmwave::MmWaveEnbPhy::GetTxPower () const
Definition at line 523 of file mmwave-enb-phy.cc.
References ns3::mmwave::MmWavePhy::m_txPower.
Referenced by GetTypeId().
GetTypeId()
TypeId ns3::mmwave::MmWaveEnbPhy::GetTypeId (void) static
Definition at line 97 of file mmwave-enb-phy.cc.
References GetDlSpectrumPhy(), ns3::mmwave::MmWavePhy::GetNoiseFigure(), GetTxPower(), GetUlSpectrumPhy(), m_dlPhyTrace, m_noiseAndFilter, m_transient, m_ueUpdateSinrPeriod, m_ulSinrTrace, m_updateSinrPeriod, ns3::mmwave::MmWavePhy::SetNoiseFigure(), and SetTxPower().
GetUlSpectrumPhy()
Ptr< MmWaveSpectrumPhy > ns3::mmwave::MmWaveEnbPhy::GetUlSpectrumPhy () const
Definition at line 575 of file mmwave-enb-phy.cc.
References ns3::mmwave::MmWavePhy::m_uplinkSpectrumPhy.
Referenced by GetTypeId().
MakeAvg()
double ns3::mmwave::MmWaveEnbPhy::MakeAvg (std::vector< double > v)
Definition at line 212 of file mmwave-enb-phy.cc.
Referenced by ApplyFilter(), and MakeFilter().
MakeFilter()
std::vector< double > ns3::mmwave::MmWaveEnbPhy::MakeFilter (std::vector< double > noisySinr, std::vector< double > realSinr, std::pair< uint64_t, uint64_t > pairFiltering)
Definition at line 404 of file mmwave-enb-phy.cc.
References MakeAvg().
Referenced by UpdateUeSinrEstimate().
MakeVar()
double ns3::mmwave::MmWaveEnbPhy::MakeVar (std::vector< double > v, double mean)
Definition at line 229 of file mmwave-enb-phy.cc.
Referenced by ApplyFilter().
PhyCtrlMessagesReceived()
void ns3::mmwave::MmWaveEnbPhy::PhyCtrlMessagesReceived (std::list< Ptr< MmWaveControlMessage > > msgList)
Definition at line 1278 of file mmwave-enb-phy.cc.
References ns3::mmwave::MmWaveControlMessage::BSR, ns3::mmwave::MmWaveControlMessage::DL_CQI, ns3::mmwave::MmWaveControlMessage::DL_HARQ, ns3::mmwave::MmWavePhy::m_cellId, m_phySapUser, m_ueAttachedRnti, ns3::mmwave::MmWaveControlMessage::RACH_PREAMBLE, ns3::mmwave::MmWaveEnbPhySapUser::ReceiveControlMessage(), and ns3::mmwave::MmWaveEnbPhySapUser::ReceiveRachPreamble().
Referenced by ns3::mmwave::MmWaveHelper::InstallSingleEnbDevice().
PhyDataPacketReceived()
void ns3::mmwave::MmWaveEnbPhy::PhyDataPacketReceived (Ptr< Packet > p)
Definition at line 1237 of file mmwave-enb-phy.cc.
References ns3::mmwave::MmWavePhy::m_netDevice, ns3::mmwave::MmWavePhy::m_phyMacConfig, m_phySapUser, and ns3::mmwave::MmWaveEnbPhySapUser::ReceivePhyPdu().
Referenced by ns3::mmwave::MmWaveHelper::InstallSingleEnbDevice().
ReceiveUlHarqFeedback()
void ns3::mmwave::MmWaveEnbPhy::ReceiveUlHarqFeedback (UlHarqInfo mes)
Definition at line 1456 of file mmwave-enb-phy.cc.
References m_phySapUser, ns3::mmwave::UlHarqInfo::m_rnti, m_ueAttachedRnti, and ns3::mmwave::MmWaveEnbPhySapUser::UlHarqFeedback().
Referenced by ns3::mmwave::MmWaveHelper::InstallSingleEnbDevice().
SendCtrlChannels()
void ns3::mmwave::MmWaveEnbPhy::SendCtrlChannels (std::list< Ptr< MmWaveControlMessage > > ctrlMsg, Time slotPrd)
Definition at line 1208 of file mmwave-enb-phy.cc.
References ns3::mmwave::MmWavePhy::m_downlinkSpectrumPhy.
Referenced by StartTti().
SendDataChannels()
void ns3::mmwave::MmWaveEnbPhy::SendDataChannels (Ptr< PacketBurst > pb, Time slotPrd, TtiAllocInfo & slotInfo)
Definition at line 1161 of file mmwave-enb-phy.cc.
References ns3::mmwave::McUeNetDevice::GetMmWavePhy(), ns3::mmwave::MmWaveUeNetDevice::GetPhy(), ns3::mmwave::TtiAllocInfo::m_dci, m_deviceMap, ns3::mmwave::MmWavePhy::m_downlinkSpectrumPhy, ns3::mmwave::TtiAllocInfo::m_isOmni, ns3::mmwave::MmWavePhy::m_netDevice, ns3::mmwave::DciInfoElementTdma::m_rnti, and ns3::mmwave::TtiAllocInfo::m_ttiIdx.
Referenced by StartTti().
SetHarqPhyModule()
void ns3::mmwave::MmWaveEnbPhy::SetHarqPhyModule (Ptr< MmWaveHarqPhy > harq)
Definition at line 1450 of file mmwave-enb-phy.cc.
References m_harqPhyModule.
SetMmWaveEnbCphySapUser()
void ns3::mmwave::MmWaveEnbPhy::SetMmWaveEnbCphySapUser (LteEnbCphySapUser * s)
Definition at line 504 of file mmwave-enb-phy.cc.
References m_enbCphySapUser.
SetNoiseFigure()
void ns3::mmwave::MmWaveEnbPhy::SetNoiseFigure (double pf)
Definition at line 529 of file mmwave-enb-phy.cc.
References ns3::mmwave::MmWavePhy::m_noiseFigure.
SetPhySapUser()
void ns3::mmwave::MmWaveEnbPhy::SetPhySapUser (MmWaveEnbPhySapUser * ptr)
Definition at line 1444 of file mmwave-enb-phy.cc.
References m_phySapUser.
SetSubChannels()
void ns3::mmwave::MmWaveEnbPhy::SetSubChannels (std::vector< int > mask)
Definition at line 560 of file mmwave-enb-phy.cc.
References CreateTxPowerSpectralDensity(), ns3::mmwave::MmWavePhy::m_downlinkSpectrumPhy, and m_listOfSubchannels.
Referenced by DoInitialize().
SetTxPower()
void ns3::mmwave::MmWaveEnbPhy::SetTxPower (double pow)
Definition at line 518 of file mmwave-enb-phy.cc.
References ns3::mmwave::MmWavePhy::m_txPower.
Referenced by GetTypeId().
StartSlot()
void ns3::mmwave::MmWaveEnbPhy::StartSlot (void)
Marks the beginning of a new NR slot.
Periodically, it alternates with EndSlot in order to scan through the different NR slots. Additionally, it is in charge of the MIB and SIB management.
Definition at line 904 of file mmwave-enb-phy.cc.
References ns3::mmwave::MmWavePhy::m_controlMessageQueue, m_currSlotAllocInfo, m_currSlotNumTti, ns3::mmwave::SfnSf::m_frameNum, ns3::mmwave::MmWavePhy::m_frameNum, ns3::mmwave::MmWavePhy::m_lastSlotStart, ns3::mmwave::SlotAllocInfo::m_sfnSf, ns3::mmwave::SfnSf::m_sfNum, ns3::mmwave::MmWavePhy::m_sfNum, m_sib1, ns3::mmwave::MmWavePhy::m_slotAllocInfo, ns3::mmwave::SfnSf::m_slotNum, ns3::mmwave::MmWavePhy::m_slotNum, ns3::mmwave::SlotAllocInfo::m_ttiAllocInfo, and StartTti().
Referenced by EndSlot(), and MmWaveEnbPhy().
StartTti()
void ns3::mmwave::MmWaveEnbPhy::StartTti (void)
Marks the beginning of a new Transmission Time Interval (TTI).
Periodically, it alternates with EndTti in order to scan through the TTIs scheduled within a slot.
Definition at line 944 of file mmwave-enb-phy.cc.
References ns3::mmwave::PhyTransmissionTraceParams::CTRL, ns3::mmwave::TtiAllocInfo::CTRL, ns3::mmwave::PhyTransmissionTraceParams::DATA, ns3::mmwave::DciInfoElementTdma::DL_dci, ns3::mmwave::TtiAllocInfo::DL_slotAllocInfo, EndTti(), ns3::mmwave::MmWavePhy::GetControlMessages(), ns3::mmwave::MmWavePhy::GetPacketBurst(), ns3::mmwave::MmWaveMacPduTag::GetSfn(), ns3::mmwave::MmWavePhy::m_cellId, m_channelChunks, m_currSlotAllocInfo, m_currSlotNumTti, m_currSymStart, ns3::mmwave::TtiAllocInfo::m_dci, m_deviceMap, ns3::mmwave::MmWavePhy::m_downlinkSpectrumPhy, ns3::mmwave::DciInfoElementTdma::m_format, ns3::mmwave::SfnSf::m_frameNum, ns3::mmwave::MmWavePhy::m_frameNum, m_harqPhyModule, ns3::mmwave::DciInfoElementTdma::m_harqProcess, ns3::mmwave::DciInfoElementTdma::m_mcs, ns3::mmwave::DciInfoElementTdma::m_ndi, ns3::mmwave::MmWavePhy::m_netDevice, ns3::mmwave::DciInfoElementTdma::m_numSym, ns3::mmwave::MmWavePhy::m_phyMacConfig, m_phySapUser, m_prevTtiDir, ns3::mmwave::DciInfoElementTdma::m_rnti, ns3::mmwave::TtiAllocInfo::m_rnti, ns3::mmwave::DciInfoElementTdma::m_rv, ns3::mmwave::SfnSf::m_sfNum, ns3::mmwave::MmWavePhy::m_sfNum, ns3::mmwave::MmWavePhy::m_slotAllocInfo, ns3::mmwave::SfnSf::m_slotNum, ns3::mmwave::MmWavePhy::m_slotNum, ns3::mmwave::SfnSf::m_symStart, ns3::mmwave::DciInfoElementTdma::m_symStart, ns3::mmwave::DciInfoElementTdma::m_tbSize, ns3::mmwave::TtiAllocInfo::m_tddMode, ns3::mmwave::SlotAllocInfo::m_ttiAllocInfo, ns3::mmwave::MmWavePhy::m_ttiIndex, SendCtrlChannels(), SendDataChannels(), ns3::mmwave::MmWaveEnbPhySapUser::SlotIndication(), TraceDlPhyTransmission(), ns3::mmwave::DciInfoElementTdma::UL_dci, and ns3::mmwave::TtiAllocInfo::UL_slotAllocInfo.
Referenced by EndTti(), and StartSlot().
TraceDlPhyTransmission()
void ns3::mmwave::MmWaveEnbPhy::TraceDlPhyTransmission (DciInfoElementTdma dciInfo, uint8_t tddType) private
Triggers the callback for the ReportDlPhyTransmission Trace Source.
Sets up the necessary info for the ReportDlPhyTransmission source and triggers the related callback
Parameters
dciInfo the actual DCI info for the current DL transmission
tddType the TDD TTI type. Either DATA or CTRL
< Holds the current DL transmission info
Definition at line 1326 of file mmwave-enb-phy.cc.
References ns3::mmwave::PhyTransmissionTraceParams::DL, ns3::mmwave::PhyTransmissionTraceParams::m_ccId, ns3::mmwave::MmWavePhy::m_componentCarrierId, m_dlPhyTrace, ns3::mmwave::PhyTransmissionTraceParams::m_frameNum, ns3::mmwave::MmWavePhy::m_frameNum, ns3::mmwave::PhyTransmissionTraceParams::m_numSym, ns3::mmwave::DciInfoElementTdma::m_numSym, ns3::mmwave::PhyTransmissionTraceParams::m_rnti, ns3::mmwave::DciInfoElementTdma::m_rnti, ns3::mmwave::PhyTransmissionTraceParams::m_rv, ns3::mmwave::DciInfoElementTdma::m_rv, ns3::mmwave::PhyTransmissionTraceParams::m_sfNum, ns3::mmwave::MmWavePhy::m_sfNum, ns3::mmwave::PhyTransmissionTraceParams::m_slotNum, ns3::mmwave::MmWavePhy::m_slotNum, ns3::mmwave::PhyTransmissionTraceParams::m_symStart, ns3::mmwave::DciInfoElementTdma::m_symStart, ns3::mmwave::PhyTransmissionTraceParams::m_tddMode, and ns3::mmwave::PhyTransmissionTraceParams::m_ttiType.
Referenced by StartTti().
UpdateUeSinrEstimate()
void ns3::mmwave::MmWaveEnbPhy::UpdateUeSinrEstimate ()
Definition at line 581 of file mmwave-enb-phy.cc.
References AddGaussianNoise(), ApplyFilter(), ns3::mmwave::MmWaveSpectrumValueHelper::CreateNoisePowerSpectralDensity(), ns3::mmwave::MmWaveSpectrumValueHelper::CreateTxPowerSpectralDensity(), GetDlSpectrumPhy(), ns3::mmwave::MmWavePhy::m_cellId, ns3::mmwave::MmWavePhy::m_componentCarrierId, ns3::mmwave::MmWavePhy::m_downlinkSpectrumPhy, m_enbCphySapUser, m_finalSinrVector, m_listOfSubchannels, ns3::mmwave::MmWavePhy::m_netDevice, m_noiseAndFilter, ns3::mmwave::MmWavePhy::m_noiseFigure, ns3::mmwave::MmWavePhy::m_phyMacConfig, ns3::mmwave::MmWavePhy::m_propagationLoss, m_roundFromLastUeSinrUpdate, m_rxPsdMap, m_samplesFilter, m_sinrMap, m_sinrVector, m_sinrVectorNoisy, m_sinrVectorToFilter, ns3::mmwave::MmWavePhy::m_spectrumPropagationLossModel, m_transient, m_ueAttachedImsiMap, m_ueUpdateSinrPeriod, m_updateSinrPeriod, and MakeFilter().
Referenced by DoInitialize().
Friends And Related Function Documentation
MemberLteEnbCphySapProvider< MmWaveEnbPhy >
friend class MemberLteEnbCphySapProvider< MmWaveEnbPhy > friend
Definition at line 61 of file mmwave-enb-phy.h.
Referenced by MmWaveEnbPhy().
Member Data Documentation
m_channelChunks
std::vector<int> ns3::mmwave::MmWaveEnbPhy::m_channelChunks private
Definition at line 232 of file mmwave-enb-phy.h.
Referenced by DoInitialize(), and StartTti().
m_currSlotAllocInfo
SlotAllocInfo ns3::mmwave::MmWaveEnbPhy::m_currSlotAllocInfo
Holds the allocation info for the current NR slot.
Definition at line 125 of file mmwave-enb-phy.h.
Referenced by EndTti(), StartSlot(), and StartTti().
m_currSlotNumTti
uint8_t ns3::mmwave::MmWaveEnbPhy::m_currSlotNumTti private
The amount of TTIs scheduled in the current slot.
Definition at line 197 of file mmwave-enb-phy.h.
Referenced by EndTti(), StartSlot(), and StartTti().
m_currSymStart
uint8_t ns3::mmwave::MmWaveEnbPhy::m_currSymStart private
Beginning of the current TTI, expressed as OFDM symbol # within the NR slot.
Definition at line 234 of file mmwave-enb-phy.h.
Referenced by GenerateDataCqiReport(), and StartTti().
m_deviceMap
std::vector< Ptr<NetDevice> > ns3::mmwave::MmWaveEnbPhy::m_deviceMap private
Definition at line 207 of file mmwave-enb-phy.h.
Referenced by AddUePhy(), SendDataChannels(), and StartTti().
m_dlPhyTrace
TracedCallback<PhyTransmissionTraceParams> ns3::mmwave::MmWaveEnbPhy::m_dlPhyTrace private
Traces the current TTI allocation info, from the eNB side.
Definition at line 238 of file mmwave-enb-phy.h.
Referenced by GetTypeId(), and TraceDlPhyTransmission().
m_enbCphySapProvider
LteEnbCphySapProvider* ns3::mmwave::MmWaveEnbPhy::m_enbCphySapProvider private
Definition at line 211 of file mmwave-enb-phy.h.
Referenced by GetMmWaveEnbCphySapProvider(), and MmWaveEnbPhy().
m_enbCphySapUser
LteEnbCphySapUser* ns3::mmwave::MmWaveEnbPhy::m_enbCphySapUser private
Definition at line 212 of file mmwave-enb-phy.h.
Referenced by SetMmWaveEnbCphySapUser(), and UpdateUeSinrEstimate().
m_finalSinrVector
std::map<pairDevices_t, std::vector<double> > ns3::mmwave::MmWaveEnbPhy::m_finalSinrVector private
Definition at line 221 of file mmwave-enb-phy.h.
Referenced by UpdateUeSinrEstimate().
m_harqPhyModule
Ptr<MmWaveHarqPhy> ns3::mmwave::MmWaveEnbPhy::m_harqPhyModule private
Definition at line 231 of file mmwave-enb-phy.h.
Referenced by SetHarqPhyModule(), and StartTti().
m_listOfSubchannels
std::vector<int> ns3::mmwave::MmWaveEnbPhy::m_listOfSubchannels private
Definition at line 201 of file mmwave-enb-phy.h.
Referenced by CreateTxPowerSpectralDensity(), SetSubChannels(), and UpdateUeSinrEstimate().
m_noiseAndFilter
bool ns3::mmwave::MmWaveEnbPhy::m_noiseAndFilter private
Definition at line 229 of file mmwave-enb-phy.h.
Referenced by DoInitialize(), GetTypeId(), and UpdateUeSinrEstimate().
m_phySapUser
MmWaveEnbPhySapUser* ns3::mmwave::MmWaveEnbPhy::m_phySapUser private
Definition at line 209 of file mmwave-enb-phy.h.
Referenced by GenerateDataCqiReport(), PhyCtrlMessagesReceived(), PhyDataPacketReceived(), ReceiveUlHarqFeedback(), SetPhySapUser(), and StartTti().
m_prevSlot
uint8_t ns3::mmwave::MmWaveEnbPhy::m_prevSlot private
1->UL 0->DL 2->Unspecified
Definition at line 203 of file mmwave-enb-phy.h.
m_prevTtiDir
TtiAllocInfo::TddMode ns3::mmwave::MmWaveEnbPhy::m_prevTtiDir private
Previous TTI TDD mode; 0->Unspecified, 1->DL, 2->UL.
Definition at line 205 of file mmwave-enb-phy.h.
Referenced by StartTti().
m_roundFromLastUeSinrUpdate
uint16_t ns3::mmwave::MmWaveEnbPhy::m_roundFromLastUeSinrUpdate private
Definition at line 227 of file mmwave-enb-phy.h.
Referenced by MmWaveEnbPhy(), and UpdateUeSinrEstimate().
m_rxPsdMap
std::map<uint64_t, Ptr<SpectrumValue> > ns3::mmwave::MmWaveEnbPhy::m_rxPsdMap private
Definition at line 217 of file mmwave-enb-phy.h.
Referenced by UpdateUeSinrEstimate().
m_samplesFilter
std::map<pairDevices_t, std::pair <uint64_t,uint64_t> > ns3::mmwave::MmWaveEnbPhy::m_samplesFilter private
Definition at line 222 of file mmwave-enb-phy.h.
Referenced by UpdateUeSinrEstimate().
m_sib1
LteRrcSap::SystemInformationBlockType1 ns3::mmwave::MmWaveEnbPhy::m_sib1 private
Definition at line 213 of file mmwave-enb-phy.h.
Referenced by DoSetSystemInformationBlockType1(), and StartSlot().
m_sinrMap
std::map<uint64_t, double > ns3::mmwave::MmWaveEnbPhy::m_sinrMap private
Definition at line 216 of file mmwave-enb-phy.h.
Referenced by UpdateUeSinrEstimate().
m_sinrVector
std::map<pairDevices_t, std::vector<double> > ns3::mmwave::MmWaveEnbPhy::m_sinrVector private
Definition at line 218 of file mmwave-enb-phy.h.
Referenced by UpdateUeSinrEstimate().
m_sinrVectorNoisy
std::map<pairDevices_t, std::vector<double> > ns3::mmwave::MmWaveEnbPhy::m_sinrVectorNoisy private
Definition at line 220 of file mmwave-enb-phy.h.
Referenced by UpdateUeSinrEstimate().
m_sinrVectorToFilter
std::map<pairDevices_t, std::vector<double> > ns3::mmwave::MmWaveEnbPhy::m_sinrVectorToFilter private
Definition at line 219 of file mmwave-enb-phy.h.
Referenced by UpdateUeSinrEstimate().
m_transient
double ns3::mmwave::MmWaveEnbPhy::m_transient private
Definition at line 228 of file mmwave-enb-phy.h.
Referenced by DoInitialize(), GetTypeId(), and UpdateUeSinrEstimate().
m_ueAttached
std::set<uint64_t> ns3::mmwave::MmWaveEnbPhy::m_ueAttached private
Definition at line 199 of file mmwave-enb-phy.h.
Referenced by AddUePhy().
m_ueAttachedImsiMap
std::map<uint64_t, Ptr<NetDevice> > ns3::mmwave::MmWaveEnbPhy::m_ueAttachedImsiMap private
Definition at line 215 of file mmwave-enb-phy.h.
Referenced by AddUePhy(), and UpdateUeSinrEstimate().
m_ueAttachedRnti
std::set<uint16_t> ns3::mmwave::MmWaveEnbPhy::m_ueAttachedRnti private
Definition at line 214 of file mmwave-enb-phy.h.
Referenced by AddUePhy(), DoRemoveUe(), PhyCtrlMessagesReceived(), and ReceiveUlHarqFeedback().
m_ueUpdateSinrPeriod
double ns3::mmwave::MmWaveEnbPhy::m_ueUpdateSinrPeriod private
Definition at line 225 of file mmwave-enb-phy.h.
Referenced by GetTypeId(), and UpdateUeSinrEstimate().
m_ulSinrTrace
TracedCallback< uint64_t, SpectrumValue&, SpectrumValue& > ns3::mmwave::MmWaveEnbPhy::m_ulSinrTrace private
Definition at line 236 of file mmwave-enb-phy.h.
Referenced by GenerateDataCqiReport(), and GetTypeId().
m_updateSinrCollect
double ns3::mmwave::MmWaveEnbPhy::m_updateSinrCollect private
Definition at line 226 of file mmwave-enb-phy.h.
m_updateSinrPeriod
int ns3::mmwave::MmWaveEnbPhy::m_updateSinrPeriod private
Definition at line 224 of file mmwave-enb-phy.h.
Referenced by DoInitialize(), GetTypeId(), and UpdateUeSinrEstimate().
The documentation for this class was generated from the following files:
src/mmwave/model/mmwave-enb-phy.h
src/mmwave/model/mmwave-enb-phy.cc