ns3-mmwave: ns3::mmwave::MmWaveSpectrumPhy Class Reference
ns3::mmwave::MmWaveSpectrumPhy Class Reference
#include "mmwave-spectrum-phy.h"
Public Types
enum State { IDLE, TX, RX_DATA, RX_CTRL }
Public Member Functions
MmWaveSpectrumPhy ()
virtual ~MmWaveSpectrumPhy ()
void AddDataPowerChunkProcessor (Ptr< mmWaveChunkProcessor > p)
void AddDataSinrChunkProcessor (Ptr< mmWaveChunkProcessor > p)
void AddExpectedTb (uint16_t rnti, uint8_t ndi, uint32_t tbSize, uint8_t mcs, std::vector< int > map, uint8_t harqId, uint8_t rv, bool downlink, uint8_t symStart, uint8_t numSym)
Add the transport block that the spectrum should expect to receive.
void ConfigureBeamforming (Ptr< NetDevice > device)
Compute the beamforming vector and update the antenna configuration to point the beam towards the target device.
virtual void DoDispose () override
Ptr< MmWaveBeamformingModel > GetBeamformingModel () const
Returns the beamforming module.
Ptr< NetDevice > GetDevice () const override
Ptr< MobilityModel > GetMobility () override
Ptr< AntennaModel > GetRxAntenna () override
This function is used by SpectrumChannel to account for the antenna gain.
Ptr< const SpectrumModel > GetRxSpectrumModel () const override
Ptr< SpectrumChannel > GetSpectrumChannel ()
void Reset ()
void ResetSpectrumModel ()
void SetBeamformingModel (Ptr< MmWaveBeamformingModel > bfModule)
Set the beamforming module.
void SetCellId (uint16_t cellId)
void SetChannel (Ptr< SpectrumChannel > c) override
void SetComponentCarrierId (uint8_t componentCarrierId)
void SetDevice (Ptr< NetDevice > d) override
void SetHarqPhyModule (Ptr< MmWaveHarqPhy > harq)
void SetMobility (Ptr< MobilityModel > m) override
void SetNoisePowerSpectralDensity (Ptr< const SpectrumValue > noisePsd)
void SetPhyDlHarqFeedbackCallback (MmWavePhyDlHarqFeedbackCallback c)
void SetPhyRxCtrlEndOkCallback (MmWavePhyRxCtrlEndOkCallback c)
void SetPhyRxDataEndOkCallback (MmWavePhyRxDataEndOkCallback c)
void SetPhyUlHarqFeedbackCallback (MmWavePhyUlHarqFeedbackCallback c)
void SetTxPowerSpectralDensity (Ptr< SpectrumValue > TxPsd)
void StartRx (Ptr< SpectrumSignalParameters > params) override
void StartRxCtrl (Ptr< MmWaveSpectrumSignalParametersDlCtrlFrame > params)
void StartRxData (Ptr< MmwaveSpectrumSignalParametersDataFrame > params)
bool StartTxDataFrames (Ptr< PacketBurst > pb, std::list< Ptr< MmWaveControlMessage > > ctrlMsgList, Time duration, uint8_t slotInd)
bool StartTxDlControlFrames (std::list< Ptr< MmWaveControlMessage > > ctrlMsgList, Time duration)
bool StartTxUlControlFrames (void)
void UpdateSinrPerceived (const SpectrumValue &sinr)
Static Public Member Functions
static TypeId GetTypeId (void)
Private Member Functions
void ChangeState (State newState)
change the state
void EndRxCtrl ()
void EndRxData ()
void EndTx ()
Private Attributes
Ptr< AntennaModel > m_antenna
Ptr< MmWaveBeamformingModel > m_beamforming
used to compute the beamforming vector
uint16_t m_cellId
Ptr< SpectrumChannel > m_channel
uint8_t m_componentCarrierId
the component carrier ID
bool m_ctrlErrorModelEnabled
bool m_dataErrorModelEnabled
Ptr< NetDevice > m_device
EventId m_endRxDataEvent
EventId m_endRxDlCtrlEvent
EventId m_endTxEvent
ExpectedTbMap_t m_expectedTbs
std::string m_fileName
Time m_firstRxDuration
Time m_firstRxStart
Ptr< MmWaveHarqPhy > m_harqPhyModule
Ptr< mmWaveInterference > m_interferenceData
bool m_isEnb
Ptr< MobilityModel > m_mobility
MmWavePhyDlHarqFeedbackCallback m_phyDlHarqFeedbackCallback
MmWavePhyRxCtrlEndOkCallback m_phyRxCtrlEndOkCallback
MmWavePhyRxDataEndOkCallback m_phyRxDataEndOkCallback
MmWavePhyUlHarqFeedbackCallback m_phyUlHarqFeedbackCallback
Ptr< UniformRandomVariable > m_random
std::list< Ptr< MmWaveControlMessage > > m_rxControlMessageList
std::list< Ptr< PacketBurst > > m_rxPacketBurstList
TracedCallback< RxPacketTraceParams > m_rxPacketTraceEnb
TracedCallback< RxPacketTraceParams > m_rxPacketTraceUe
Ptr< const SpectrumModel > m_rxSpectrumModel
SpectrumValue m_sinrPerceived
State m_state
Ptr< SpectrumValue > m_txPsd
Detailed Description
Definition at line 100 of file mmwave-spectrum-phy.h.
Member Enumeration Documentation
State
enum ns3::mmwave::MmWaveSpectrumPhy::State
Enumerator
IDLE
TX
RX_DATA
RX_CTRL
Definition at line 106 of file mmwave-spectrum-phy.h.
Constructor & Destructor Documentation
MmWaveSpectrumPhy()
ns3::mmwave::MmWaveSpectrumPhy::MmWaveSpectrumPhy ()
Definition at line 98 of file mmwave-spectrum-phy.cc.
References m_interferenceData, and m_random.
~MmWaveSpectrumPhy()
ns3::mmwave::MmWaveSpectrumPhy::~MmWaveSpectrumPhy () virtual
Definition at line 108 of file mmwave-spectrum-phy.cc.
Member Function Documentation
AddDataPowerChunkProcessor()
void ns3::mmwave::MmWaveSpectrumPhy::AddDataPowerChunkProcessor (Ptr< mmWaveChunkProcessor > p)
Definition at line 896 of file mmwave-spectrum-phy.cc.
References m_interferenceData.
AddDataSinrChunkProcessor()
void ns3::mmwave::MmWaveSpectrumPhy::AddDataSinrChunkProcessor (Ptr< mmWaveChunkProcessor > p)
Definition at line 902 of file mmwave-spectrum-phy.cc.
References m_interferenceData.
AddExpectedTb()
void ns3::mmwave::MmWaveSpectrumPhy::AddExpectedTb (uint16_t rnti, uint8_t ndi, uint32_t tbSize, uint8_t mcs, std::vector< int > map, uint8_t harqId, uint8_t rv, bool downlink, uint8_t symStart, uint8_t numSym)
Add the transport block that the spectrum should expect to receive.
Parameters
rnti the RNTI of the UE
ndi the New Data Indicator
tbSize the size of the transport block
mcs the modulation and coding scheme to use
map a map of the resource blocks used
harqId the ID of the HARQ process
rv the number of retransmissions
downlink a boolean flag for a downlink transmission
symStart the first symbol of this TB
numSym the number of symbols of the TB
Definition at line 280 of file mmwave-spectrum-phy.cc.
References m_expectedTbs.
ChangeState()
void ns3::mmwave::MmWaveSpectrumPhy::ChangeState (State newState) private
change the state
Parameters
newState the new state
Definition at line 244 of file mmwave-spectrum-phy.cc.
References m_state.
Referenced by EndRxCtrl(), EndRxData(), EndTx(), Reset(), StartRxCtrl(), StartRxData(), StartTxDataFrames(), and StartTxDlControlFrames().
ConfigureBeamforming()
void ns3::mmwave::MmWaveSpectrumPhy::ConfigureBeamforming (Ptr< NetDevice > device)
Compute the beamforming vector and update the antenna configuration to point the beam towards the target device.
Parameters
device target device
Definition at line 311 of file mmwave-spectrum-phy.cc.
References m_beamforming, and m_componentCarrierId.
DoDispose()
void ns3::mmwave::MmWaveSpectrumPhy::DoDispose (void) override virtual
Definition at line 144 of file mmwave-spectrum-phy.cc.
EndRxCtrl()
void ns3::mmwave::MmWaveSpectrumPhy::EndRxCtrl () private
Definition at line 766 of file mmwave-spectrum-phy.cc.
References ChangeState(), IDLE, m_phyRxCtrlEndOkCallback, m_rxControlMessageList, m_state, and RX_CTRL.
Referenced by StartRxCtrl().
EndRxData()
void ns3::mmwave::MmWaveSpectrumPhy::EndRxData () private
Definition at line 554 of file mmwave-spectrum-phy.cc.
References ns3::mmwave::DlHarqInfo::ACK, ChangeState(), ns3::mmwave::MmWaveMacPduTag::GetSfn(), ns3::mmwave::MmWaveMiErrorModel::GetTbDecodificationStats(), IDLE, ns3::mmwave::RxPacketTraceParams::m_ccId, m_cellId, ns3::mmwave::RxPacketTraceParams::m_cellId, m_componentCarrierId, ns3::mmwave::RxPacketTraceParams::m_corrupt, m_dataErrorModelEnabled, m_expectedTbs, ns3::mmwave::SfnSf::m_frameNum, ns3::mmwave::RxPacketTraceParams::m_frameNum, m_harqPhyModule, ns3::mmwave::DlHarqInfo::m_harqProcessId, ns3::mmwave::UlHarqInfo::m_harqProcessId, ns3::mmwave::DlHarqInfo::m_harqStatus, m_interferenceData, ns3::mmwave::RxPacketTraceParams::m_mcs, ns3::mmwave::DlHarqInfo::m_numRetx, ns3::mmwave::UlHarqInfo::m_numRetx, ns3::mmwave::RxPacketTraceParams::m_numSym, m_phyDlHarqFeedbackCallback, m_phyRxCtrlEndOkCallback, m_phyRxDataEndOkCallback, m_phyUlHarqFeedbackCallback, m_random, ns3::mmwave::UlHarqInfo::m_receptionStatus, ns3::mmwave::RxPacketTraceParams::m_rnti, ns3::mmwave::DlHarqInfo::m_rnti, ns3::mmwave::UlHarqInfo::m_rnti, ns3::mmwave::RxPacketTraceParams::m_rv, m_rxControlMessageList, m_rxPacketBurstList, m_rxPacketTraceEnb, m_rxPacketTraceUe, ns3::mmwave::SfnSf::m_sfNum, ns3::mmwave::RxPacketTraceParams::m_sfNum, ns3::mmwave::RxPacketTraceParams::m_sinr, ns3::mmwave::RxPacketTraceParams::m_sinrMin, m_sinrPerceived, ns3::mmwave::SfnSf::m_slotNum, ns3::mmwave::RxPacketTraceParams::m_slotNum, m_state, ns3::mmwave::RxPacketTraceParams::m_symStart, ns3::mmwave::RxPacketTraceParams::m_tbler, ns3::mmwave::RxPacketTraceParams::m_tbSize, ns3::mmwave::MmWaveTbStats_t::miTotal, ns3::mmwave::DlHarqInfo::NACK, ns3::mmwave::UlHarqInfo::NotOk, ns3::mmwave::UlHarqInfo::Ok, RX_DATA, and ns3::mmwave::MmWaveTbStats_t::tbler.
Referenced by StartRxData().
EndTx()
void ns3::mmwave::MmWaveSpectrumPhy::EndTx () private
Definition at line 869 of file mmwave-spectrum-phy.cc.
References ChangeState(), IDLE, m_state, and TX.
Referenced by StartTxDataFrames(), and StartTxDlControlFrames().
GetBeamformingModel()
Ptr< MmWaveBeamformingModel > ns3::mmwave::MmWaveSpectrumPhy::GetBeamformingModel () const
Returns the beamforming module.
Returns
the beamforming module
Definition at line 236 of file mmwave-spectrum-phy.cc.
References m_beamforming.
GetDevice()
Ptr< NetDevice > ns3::mmwave::MmWaveSpectrumPhy::GetDevice (void) const override
Definition at line 190 of file mmwave-spectrum-phy.cc.
References m_device.
Referenced by SetDevice(), StartRx(), and StartRxCtrl().
GetMobility()
Ptr< MobilityModel > ns3::mmwave::MmWaveSpectrumPhy::GetMobility () override
Definition at line 202 of file mmwave-spectrum-phy.cc.
References m_mobility.
GetRxAntenna()
Ptr< AntennaModel > ns3::mmwave::MmWaveSpectrumPhy::GetRxAntenna () override
This function is used by SpectrumChannel to account for the antenna gain.
However, in our module the antenna gain is implicitly accounted in the channel model classes, therefore this function returns 0.
Returns
0
Definition at line 220 of file mmwave-spectrum-phy.cc.
Referenced by StartTxDataFrames(), and StartTxDlControlFrames().
GetRxSpectrumModel()
Ptr< const SpectrumModel > ns3::mmwave::MmWaveSpectrumPhy::GetRxSpectrumModel () const override
Definition at line 214 of file mmwave-spectrum-phy.cc.
References m_rxSpectrumModel.
GetSpectrumChannel()
Ptr< SpectrumChannel > ns3::mmwave::MmWaveSpectrumPhy::GetSpectrumChannel ()
Definition at line 877 of file mmwave-spectrum-phy.cc.
References m_channel.
GetTypeId()
TypeId ns3::mmwave::MmWaveSpectrumPhy::GetTypeId (void) static
Definition at line 114 of file mmwave-spectrum-phy.cc.
References m_dataErrorModelEnabled, m_fileName, m_rxPacketTraceEnb, and m_rxPacketTraceUe.
Reset()
void ns3::mmwave::MmWaveSpectrumPhy::Reset ()
Definition at line 150 of file mmwave-spectrum-phy.cc.
References ChangeState(), IDLE, m_cellId, m_endRxDataEvent, m_endRxDlCtrlEvent, m_endTxEvent, m_expectedTbs, m_rxControlMessageList, and m_rxPacketBurstList.
ResetSpectrumModel()
void ns3::mmwave::MmWaveSpectrumPhy::ResetSpectrumModel ()
Definition at line 166 of file mmwave-spectrum-phy.cc.
References m_rxSpectrumModel.
SetBeamformingModel()
void ns3::mmwave::MmWaveSpectrumPhy::SetBeamformingModel (Ptr< MmWaveBeamformingModel > bfModule)
Set the beamforming module.
Parameters
bfModule the beamforming module
Definition at line 228 of file mmwave-spectrum-phy.cc.
References m_beamforming.
SetCellId()
void ns3::mmwave::MmWaveSpectrumPhy::SetCellId (uint16_t cellId)
Definition at line 883 of file mmwave-spectrum-phy.cc.
References m_cellId.
SetChannel()
void ns3::mmwave::MmWaveSpectrumPhy::SetChannel (Ptr< SpectrumChannel > c) override
Definition at line 208 of file mmwave-spectrum-phy.cc.
References m_channel.
SetComponentCarrierId()
void ns3::mmwave::MmWaveSpectrumPhy::SetComponentCarrierId (uint8_t componentCarrierId)
Parameters
componentCarrierId the component carrier id
Definition at line 889 of file mmwave-spectrum-phy.cc.
References m_componentCarrierId.
SetDevice()
void ns3::mmwave::MmWaveSpectrumPhy::SetDevice (Ptr< NetDevice > d) override
Definition at line 172 of file mmwave-spectrum-phy.cc.
References GetDevice(), m_device, and m_isEnb.
SetHarqPhyModule()
void ns3::mmwave::MmWaveSpectrumPhy::SetHarqPhyModule (Ptr< MmWaveHarqPhy > harq)
Definition at line 915 of file mmwave-spectrum-phy.cc.
References m_harqPhyModule.
SetMobility()
void ns3::mmwave::MmWaveSpectrumPhy::SetMobility (Ptr< MobilityModel > m) override
Definition at line 196 of file mmwave-spectrum-phy.cc.
References m_mobility.
SetNoisePowerSpectralDensity()
void ns3::mmwave::MmWaveSpectrumPhy::SetNoisePowerSpectralDensity (Ptr< const SpectrumValue > noisePsd)
Definition at line 252 of file mmwave-spectrum-phy.cc.
References m_interferenceData, and m_rxSpectrumModel.
SetPhyDlHarqFeedbackCallback()
void ns3::mmwave::MmWaveSpectrumPhy::SetPhyDlHarqFeedbackCallback (MmWavePhyDlHarqFeedbackCallback c)
Definition at line 297 of file mmwave-spectrum-phy.cc.
References m_phyDlHarqFeedbackCallback.
SetPhyRxCtrlEndOkCallback()
void ns3::mmwave::MmWaveSpectrumPhy::SetPhyRxCtrlEndOkCallback (MmWavePhyRxCtrlEndOkCallback c)
Definition at line 274 of file mmwave-spectrum-phy.cc.
References m_phyRxCtrlEndOkCallback.
SetPhyRxDataEndOkCallback()
void ns3::mmwave::MmWaveSpectrumPhy::SetPhyRxDataEndOkCallback (MmWavePhyRxDataEndOkCallback c)
Definition at line 267 of file mmwave-spectrum-phy.cc.
References m_phyRxDataEndOkCallback.
SetPhyUlHarqFeedbackCallback()
void ns3::mmwave::MmWaveSpectrumPhy::SetPhyUlHarqFeedbackCallback (MmWavePhyUlHarqFeedbackCallback c)
Definition at line 304 of file mmwave-spectrum-phy.cc.
References m_phyUlHarqFeedbackCallback.
SetTxPowerSpectralDensity()
void ns3::mmwave::MmWaveSpectrumPhy::SetTxPowerSpectralDensity (Ptr< SpectrumValue > TxPsd)
Definition at line 261 of file mmwave-spectrum-phy.cc.
References m_txPsd.
StartRx()
void ns3::mmwave::MmWaveSpectrumPhy::StartRx (Ptr< SpectrumSignalParameters > params) override
Definition at line 334 of file mmwave-spectrum-phy.cc.
References GetDevice(), m_cellId, m_componentCarrierId, m_interferenceData, StartRxCtrl(), and StartRxData().
StartRxCtrl()
void ns3::mmwave::MmWaveSpectrumPhy::StartRxCtrl (Ptr< MmWaveSpectrumSignalParametersDlCtrlFrame > params)
Definition at line 479 of file mmwave-spectrum-phy.cc.
References ChangeState(), EndRxCtrl(), GetDevice(), IDLE, m_cellId, m_endRxDlCtrlEvent, m_firstRxDuration, m_firstRxStart, m_rxControlMessageList, m_state, RX_CTRL, RX_DATA, and TX.
Referenced by StartRx().
StartRxData()
void ns3::mmwave::MmWaveSpectrumPhy::StartRxData (Ptr< MmwaveSpectrumSignalParametersDataFrame > params)
Definition at line 418 of file mmwave-spectrum-phy.cc.
References ChangeState(), EndRxData(), IDLE, m_endRxDataEvent, m_firstRxDuration, m_firstRxStart, m_interferenceData, m_rxControlMessageList, m_rxPacketBurstList, m_state, RX_CTRL, RX_DATA, and TX.
Referenced by StartRx().
StartTxDataFrames()
bool ns3::mmwave::MmWaveSpectrumPhy::StartTxDataFrames (Ptr< PacketBurst > pb, std::list< Ptr< MmWaveControlMessage > > ctrlMsgList, Time duration, uint8_t slotInd)
Definition at line 785 of file mmwave-spectrum-phy.cc.
References ChangeState(), EndTx(), GetRxAntenna(), IDLE, m_cellId, m_channel, m_endTxEvent, m_state, m_txPsd, RX_CTRL, RX_DATA, and TX.
StartTxDlControlFrames()
bool ns3::mmwave::MmWaveSpectrumPhy::StartTxDlControlFrames (std::list< Ptr< MmWaveControlMessage > > ctrlMsgList, Time duration)
Definition at line 829 of file mmwave-spectrum-phy.cc.
References ChangeState(), EndTx(), GetRxAntenna(), IDLE, m_cellId, m_channel, m_endTxEvent, m_state, m_txPsd, RX_CTRL, RX_DATA, and TX.
StartTxUlControlFrames()
bool ns3::mmwave::MmWaveSpectrumPhy::StartTxUlControlFrames (void)
UpdateSinrPerceived()
void ns3::mmwave::MmWaveSpectrumPhy::UpdateSinrPerceived (const SpectrumValue & sinr)
Definition at line 908 of file mmwave-spectrum-phy.cc.
References m_sinrPerceived.
Referenced by ns3::mmwave::MmWaveHelper::InstallSingleEnbDevice(), ns3::mmwave::MmWaveHelper::InstallSingleMcUeDevice(), ns3::mmwave::MmWaveHelper::InstallSingleUeDevice(), and updateSnr().
Member Data Documentation
m_antenna
Ptr<AntennaModel> ns3::mmwave::MmWaveSpectrumPhy::m_antenna private
Definition at line 228 of file mmwave-spectrum-phy.h.
m_beamforming
Ptr<MmWaveBeamformingModel> ns3::mmwave::MmWaveSpectrumPhy::m_beamforming private
used to compute the beamforming vector
Definition at line 229 of file mmwave-spectrum-phy.h.
Referenced by ConfigureBeamforming(), GetBeamformingModel(), and SetBeamformingModel().
m_cellId
uint16_t ns3::mmwave::MmWaveSpectrumPhy::m_cellId private
Definition at line 231 of file mmwave-spectrum-phy.h.
Referenced by EndRxData(), Reset(), SetCellId(), StartRx(), StartRxCtrl(), StartTxDataFrames(), and StartTxDlControlFrames().
m_channel
Ptr<SpectrumChannel> ns3::mmwave::MmWaveSpectrumPhy::m_channel private
Definition at line 218 of file mmwave-spectrum-phy.h.
Referenced by GetSpectrumChannel(), SetChannel(), StartTxDataFrames(), and StartTxDlControlFrames().
m_componentCarrierId
uint8_t ns3::mmwave::MmWaveSpectrumPhy::m_componentCarrierId private
the component carrier ID
Definition at line 235 of file mmwave-spectrum-phy.h.
Referenced by ConfigureBeamforming(), EndRxData(), SetComponentCarrierId(), and StartRx().
m_ctrlErrorModelEnabled
bool ns3::mmwave::MmWaveSpectrumPhy::m_ctrlErrorModelEnabled private
Definition at line 253 of file mmwave-spectrum-phy.h.
m_dataErrorModelEnabled
bool ns3::mmwave::MmWaveSpectrumPhy::m_dataErrorModelEnabled private
Definition at line 252 of file mmwave-spectrum-phy.h.
Referenced by EndRxData(), and GetTypeId().
m_device
Ptr<NetDevice> ns3::mmwave::MmWaveSpectrumPhy::m_device private
Definition at line 217 of file mmwave-spectrum-phy.h.
Referenced by GetDevice(), and SetDevice().
m_endRxDataEvent
EventId ns3::mmwave::MmWaveSpectrumPhy::m_endRxDataEvent private
Definition at line 260 of file mmwave-spectrum-phy.h.
Referenced by Reset(), and StartRxData().
m_endRxDlCtrlEvent
EventId ns3::mmwave::MmWaveSpectrumPhy::m_endRxDlCtrlEvent private
Definition at line 261 of file mmwave-spectrum-phy.h.
Referenced by Reset(), and StartRxCtrl().
m_endTxEvent
EventId ns3::mmwave::MmWaveSpectrumPhy::m_endTxEvent private
Definition at line 259 of file mmwave-spectrum-phy.h.
Referenced by Reset(), StartTxDataFrames(), and StartTxDlControlFrames().
m_expectedTbs
ExpectedTbMap_t ns3::mmwave::MmWaveSpectrumPhy::m_expectedTbs private
Definition at line 248 of file mmwave-spectrum-phy.h.
Referenced by AddExpectedTb(), EndRxData(), and Reset().
m_fileName
std::string ns3::mmwave::MmWaveSpectrumPhy::m_fileName private
Definition at line 262 of file mmwave-spectrum-phy.h.
Referenced by GetTypeId().
m_firstRxDuration
Time ns3::mmwave::MmWaveSpectrumPhy::m_firstRxDuration private
Definition at line 226 of file mmwave-spectrum-phy.h.
Referenced by StartRxCtrl(), and StartRxData().
m_firstRxStart
Time ns3::mmwave::MmWaveSpectrumPhy::m_firstRxStart private
Definition at line 225 of file mmwave-spectrum-phy.h.
Referenced by StartRxCtrl(), and StartRxData().
m_harqPhyModule
Ptr<MmWaveHarqPhy> ns3::mmwave::MmWaveSpectrumPhy::m_harqPhyModule private
Definition at line 255 of file mmwave-spectrum-phy.h.
Referenced by EndRxData(), and SetHarqPhyModule().
m_interferenceData
Ptr<mmWaveInterference> ns3::mmwave::MmWaveSpectrumPhy::m_interferenceData private
Definition at line 215 of file mmwave-spectrum-phy.h.
Referenced by AddDataPowerChunkProcessor(), AddDataSinrChunkProcessor(), EndRxData(), MmWaveSpectrumPhy(), SetNoisePowerSpectralDensity(), StartRx(), and StartRxData().
m_isEnb
bool ns3::mmwave::MmWaveSpectrumPhy::m_isEnb private
Definition at line 257 of file mmwave-spectrum-phy.h.
Referenced by SetDevice().
m_mobility
Ptr<MobilityModel> ns3::mmwave::MmWaveSpectrumPhy::m_mobility private
Definition at line 216 of file mmwave-spectrum-phy.h.
Referenced by GetMobility(), and SetMobility().
m_phyDlHarqFeedbackCallback
MmWavePhyDlHarqFeedbackCallback ns3::mmwave::MmWaveSpectrumPhy::m_phyDlHarqFeedbackCallback private
Definition at line 240 of file mmwave-spectrum-phy.h.
Referenced by EndRxData(), and SetPhyDlHarqFeedbackCallback().
m_phyRxCtrlEndOkCallback
MmWavePhyRxCtrlEndOkCallback ns3::mmwave::MmWaveSpectrumPhy::m_phyRxCtrlEndOkCallback private
Definition at line 237 of file mmwave-spectrum-phy.h.
Referenced by EndRxCtrl(), EndRxData(), and SetPhyRxCtrlEndOkCallback().
m_phyRxDataEndOkCallback
MmWavePhyRxDataEndOkCallback ns3::mmwave::MmWaveSpectrumPhy::m_phyRxDataEndOkCallback private
Definition at line 238 of file mmwave-spectrum-phy.h.
Referenced by EndRxData(), and SetPhyRxDataEndOkCallback().
m_phyUlHarqFeedbackCallback
MmWavePhyUlHarqFeedbackCallback ns3::mmwave::MmWaveSpectrumPhy::m_phyUlHarqFeedbackCallback private
Definition at line 241 of file mmwave-spectrum-phy.h.
Referenced by EndRxData(), and SetPhyUlHarqFeedbackCallback().
m_random
Ptr<UniformRandomVariable> ns3::mmwave::MmWaveSpectrumPhy::m_random private
Definition at line 250 of file mmwave-spectrum-phy.h.
Referenced by EndRxData(), and MmWaveSpectrumPhy().
m_rxControlMessageList
std::list<Ptr<MmWaveControlMessage> > ns3::mmwave::MmWaveSpectrumPhy::m_rxControlMessageList private
Definition at line 223 of file mmwave-spectrum-phy.h.
Referenced by EndRxCtrl(), EndRxData(), Reset(), StartRxCtrl(), and StartRxData().
m_rxPacketBurstList
std::list<Ptr<PacketBurst> > ns3::mmwave::MmWaveSpectrumPhy::m_rxPacketBurstList private
Definition at line 222 of file mmwave-spectrum-phy.h.
Referenced by EndRxData(), Reset(), and StartRxData().
m_rxPacketTraceEnb
TracedCallback<RxPacketTraceParams> ns3::mmwave::MmWaveSpectrumPhy::m_rxPacketTraceEnb private
Definition at line 243 of file mmwave-spectrum-phy.h.
Referenced by EndRxData(), and GetTypeId().
m_rxPacketTraceUe
TracedCallback<RxPacketTraceParams> ns3::mmwave::MmWaveSpectrumPhy::m_rxPacketTraceUe private
Definition at line 244 of file mmwave-spectrum-phy.h.
Referenced by EndRxData(), and GetTypeId().
m_rxSpectrumModel
Ptr<const SpectrumModel> ns3::mmwave::MmWaveSpectrumPhy::m_rxSpectrumModel private
Definition at line 219 of file mmwave-spectrum-phy.h.
Referenced by GetRxSpectrumModel(), ResetSpectrumModel(), and SetNoisePowerSpectralDensity().
m_sinrPerceived
SpectrumValue ns3::mmwave::MmWaveSpectrumPhy::m_sinrPerceived private
Definition at line 246 of file mmwave-spectrum-phy.h.
Referenced by EndRxData(), and UpdateSinrPerceived().
m_state
State ns3::mmwave::MmWaveSpectrumPhy::m_state private
Definition at line 233 of file mmwave-spectrum-phy.h.
Referenced by ChangeState(), EndRxCtrl(), EndRxData(), EndTx(), StartRxCtrl(), StartRxData(), StartTxDataFrames(), and StartTxDlControlFrames().
m_txPsd
Ptr<SpectrumValue> ns3::mmwave::MmWaveSpectrumPhy::m_txPsd private
Definition at line 220 of file mmwave-spectrum-phy.h.
Referenced by SetTxPowerSpectralDensity(), StartTxDataFrames(), and StartTxDlControlFrames().
The documentation for this class was generated from the following files:
src/mmwave/model/mmwave-spectrum-phy.h
src/mmwave/model/mmwave-spectrum-phy.cc