ns3-mmwave: ns3::mmwave::UeMemberMmWaveUeCmacSapProvider Class Reference
ns3::mmwave::UeMemberMmWaveUeCmacSapProvider Class Reference
Public Member Functions
UeMemberMmWaveUeCmacSapProvider (MmWaveUeMac *mac)
virtual void AddLc (uint8_t lcId, LteUeCmacSapProvider::LogicalChannelConfig lcConfig, LteMacSapUser *msu)
virtual void ConfigureRach (RachConfig rc)
virtual void RemoveLc (uint8_t lcId)
virtual void Reset ()
virtual void SetRnti (uint16_t rnti)
virtual void StartContentionBasedRandomAccessProcedure ()
virtual void StartNonContentionBasedRandomAccessProcedure (uint16_t rnti, uint8_t preambleId, uint8_t prachMask)
Private Attributes
MmWaveUeMac * m_mac
Detailed Description
Definition at line 56 of file mmwave-ue-mac.cc.
Constructor & Destructor Documentation
UeMemberMmWaveUeCmacSapProvider()
ns3::mmwave::UeMemberMmWaveUeCmacSapProvider::UeMemberMmWaveUeCmacSapProvider (MmWaveUeMac * mac)
Definition at line 75 of file mmwave-ue-mac.cc.
Member Function Documentation
AddLc()
void ns3::mmwave::UeMemberMmWaveUeCmacSapProvider::AddLc (uint8_t lcId, LteUeCmacSapProvider::LogicalChannelConfig lcConfig, LteMacSapUser * msu) virtual
Definition at line 106 of file mmwave-ue-mac.cc.
References ns3::mmwave::MmWaveUeMac::AddLc(), and m_mac.
ConfigureRach()
void ns3::mmwave::UeMemberMmWaveUeCmacSapProvider::ConfigureRach (RachConfig rc) virtual
Definition at line 81 of file mmwave-ue-mac.cc.
References ns3::mmwave::MmWaveUeMac::DoConfigureRach(), and m_mac.
RemoveLc()
void ns3::mmwave::UeMemberMmWaveUeCmacSapProvider::RemoveLc (uint8_t lcId) virtual
Definition at line 112 of file mmwave-ue-mac.cc.
References ns3::mmwave::MmWaveUeMac::DoRemoveLc(), and m_mac.
Reset()
void ns3::mmwave::UeMemberMmWaveUeCmacSapProvider::Reset () virtual
Definition at line 118 of file mmwave-ue-mac.cc.
References ns3::mmwave::MmWaveUeMac::DoReset(), and m_mac.
SetRnti()
void ns3::mmwave::UeMemberMmWaveUeCmacSapProvider::SetRnti (uint16_t rnti) virtual
Definition at line 99 of file mmwave-ue-mac.cc.
References ns3::mmwave::MmWaveUeMac::DoSetRnti(), and m_mac.
StartContentionBasedRandomAccessProcedure()
void ns3::mmwave::UeMemberMmWaveUeCmacSapProvider::StartContentionBasedRandomAccessProcedure () virtual
Definition at line 87 of file mmwave-ue-mac.cc.
References ns3::mmwave::MmWaveUeMac::DoStartContentionBasedRandomAccessProcedure(), and m_mac.
StartNonContentionBasedRandomAccessProcedure()
void ns3::mmwave::UeMemberMmWaveUeCmacSapProvider::StartNonContentionBasedRandomAccessProcedure (uint16_t rnti, uint8_t preambleId, uint8_t prachMask) virtual
Definition at line 93 of file mmwave-ue-mac.cc.
References ns3::mmwave::MmWaveUeMac::DoStartNonContentionBasedRandomAccessProcedure(), and m_mac.
Member Data Documentation
m_mac
MmWaveUeMac* ns3::mmwave::UeMemberMmWaveUeCmacSapProvider::m_mac private
Definition at line 71 of file mmwave-ue-mac.cc.
Referenced by AddLc(), ConfigureRach(), RemoveLc(), Reset(), SetRnti(), StartContentionBasedRandomAccessProcedure(), and StartNonContentionBasedRandomAccessProcedure().
The documentation for this class was generated from the following file:
src/mmwave/model/mmwave-ue-mac.cc