ns3-mmwave: ns3::mmwave::MmWaveUePhySapUser Class Reference
ns3::mmwave::MmWaveUePhySapUser Class Reference abstract
#include "mmwave-phy-sap.h"
Public Member Functions
virtual ~MmWaveUePhySapUser ()
virtual void ReceiveControlMessage (Ptr< MmWaveControlMessage > msg)=0
Receive SendLteControlMessage (PDCCH map, CQI feedbacks) using the ideal control channel.
virtual void ReceivePhyPdu (Ptr< Packet > p)=0
Called by the Phy to notify the MAC of the reception of a new PHY-PDU.
virtual void SetConfigurationParameters (Ptr< MmWavePhyMacCommon > params)=0
When PHY connects to a new eNB, update the configuration parameters.
virtual void SlotIndication (SfnSf snf)=0
Send from the PHY layer the current frame, subframe, slot numbers and the current starting OFDM symbol within the slot.
Detailed Description
Definition at line 114 of file mmwave-phy-sap.h.
Constructor & Destructor Documentation
~MmWaveUePhySapUser()
virtual ns3::mmwave::MmWaveUePhySapUser::~MmWaveUePhySapUser () inline virtual
Definition at line 117 of file mmwave-phy-sap.h.
Member Function Documentation
ReceiveControlMessage()
virtual void ns3::mmwave::MmWaveUePhySapUser::ReceiveControlMessage (Ptr< MmWaveControlMessage > msg) pure virtual
Receive SendLteControlMessage (PDCCH map, CQI feedbacks) using the ideal control channel.
Parameters
msg the Ideal Control Message to receive
Implemented in ns3::mmwave::MacUeMemberPhySapUser.
Referenced by ns3::mmwave::MmWaveUePhy::ReceiveControlMessageList().
ReceivePhyPdu()
virtual void ns3::mmwave::MmWaveUePhySapUser::ReceivePhyPdu (Ptr< Packet > p) pure virtual
Called by the Phy to notify the MAC of the reception of a new PHY-PDU.
Parameters
p
Implemented in ns3::mmwave::MacUeMemberPhySapUser.
Referenced by ns3::mmwave::MmWaveUePhy::DelayPhyDataPacketReceived().
SetConfigurationParameters()
virtual void ns3::mmwave::MmWaveUePhySapUser::SetConfigurationParameters (Ptr< MmWavePhyMacCommon > params) pure virtual
When PHY connects to a new eNB, update the configuration parameters.
Implemented in ns3::mmwave::MacUeMemberPhySapUser.
Referenced by ns3::mmwave::MmWaveUePhy::RegisterToEnb().
SlotIndication()
virtual void ns3::mmwave::MmWaveUePhySapUser::SlotIndication (SfnSf snf) pure virtual
Send from the PHY layer the current frame, subframe, slot numbers and the current starting OFDM symbol within the slot.
Parameters
snf The current frame, subframe, slot and starting OFDM symbol counters
Implemented in ns3::mmwave::MacUeMemberPhySapUser.
Referenced by ns3::mmwave::MmWaveUePhy::StartTti().
The documentation for this class was generated from the following file:
src/mmwave/model/mmwave-phy-sap.h