ns3-mmwave: ns3::mmwave::MmWaveEnbPhySapUser Class Reference
ns3::mmwave::MmWaveEnbPhySapUser Class Reference abstract
#include "mmwave-phy-sap.h"
Public Member Functions
virtual ~MmWaveEnbPhySapUser ()
virtual void ReceiveControlMessage (Ptr< MmWaveControlMessage > msg)=0
Receive SendLteControlMessage (PDCCH map, CQI feedbacks) using the ideal control channel.
virtual void ReceivePhyPdu (Ptr< Packet > p)=0
Called by the Phy to notify the MAC of the reception of a new PHY-PDU.
virtual void ReceiveRachPreamble (uint32_t raId)=0
notify the reception of a RACH preamble on the PRACH
virtual void SlotIndication (SfnSf snf)=0
Send from the PHY layer the current frame, subframe, slot numbers and the current starting OFDM symbol within the slot.
virtual void UlCqiReport (MmWaveMacSchedSapProvider::SchedUlCqiInfoReqParameters ulcqi)=0
Returns to MAC level the UL-CQI evaluated.
virtual void UlHarqFeedback (UlHarqInfo params)=0
Notify the HARQ on the UL tranmission status.
Detailed Description
Definition at line 67 of file mmwave-phy-sap.h.
Constructor & Destructor Documentation
~MmWaveEnbPhySapUser()
virtual ns3::mmwave::MmWaveEnbPhySapUser::~MmWaveEnbPhySapUser () inline virtual
Definition at line 70 of file mmwave-phy-sap.h.
Member Function Documentation
ReceiveControlMessage()
virtual void ns3::mmwave::MmWaveEnbPhySapUser::ReceiveControlMessage (Ptr< MmWaveControlMessage > msg) pure virtual
Receive SendLteControlMessage (PDCCH map, CQI feedbacks) using the ideal control channel.
Parameters
msg the Ideal Control Message to receive
Implemented in ns3::mmwave::MmWaveMacEnbMemberPhySapUser.
Referenced by ns3::mmwave::MmWaveEnbPhy::PhyCtrlMessagesReceived().
ReceivePhyPdu()
virtual void ns3::mmwave::MmWaveEnbPhySapUser::ReceivePhyPdu (Ptr< Packet > p) pure virtual
Called by the Phy to notify the MAC of the reception of a new PHY-PDU.
Parameters
p
Implemented in ns3::mmwave::MmWaveMacEnbMemberPhySapUser.
Referenced by ns3::mmwave::MmWaveEnbPhy::PhyDataPacketReceived().
ReceiveRachPreamble()
virtual void ns3::mmwave::MmWaveEnbPhySapUser::ReceiveRachPreamble (uint32_t raId) pure virtual
notify the reception of a RACH preamble on the PRACH
Parameters
raId the ID of the preamble
Implemented in ns3::mmwave::MmWaveMacEnbMemberPhySapUser.
Referenced by ns3::mmwave::MmWaveEnbPhy::PhyCtrlMessagesReceived().
SlotIndication()
virtual void ns3::mmwave::MmWaveEnbPhySapUser::SlotIndication (SfnSf snf) pure virtual
Send from the PHY layer the current frame, subframe, slot numbers and the current starting OFDM symbol within the slot.
Parameters
snf The current frame, subframe, slot and starting OFDM symbol counters
Implemented in ns3::mmwave::MmWaveMacEnbMemberPhySapUser.
Referenced by ns3::mmwave::MmWaveEnbPhy::StartTti().
UlCqiReport()
virtual void ns3::mmwave::MmWaveEnbPhySapUser::UlCqiReport (MmWaveMacSchedSapProvider::SchedUlCqiInfoReqParameters ulcqi) pure virtual
Returns to MAC level the UL-CQI evaluated.
Parameters
ulcqi the UL-CQI (see FF MAC API 4.3.29)
Implemented in ns3::mmwave::MmWaveMacEnbMemberPhySapUser.
Referenced by ns3::mmwave::MmWaveEnbPhy::GenerateDataCqiReport().
UlHarqFeedback()
virtual void ns3::mmwave::MmWaveEnbPhySapUser::UlHarqFeedback (UlHarqInfo params) pure virtual
Notify the HARQ on the UL tranmission status.
Parameters
params
Implemented in ns3::mmwave::MmWaveMacEnbMemberPhySapUser.
Referenced by ns3::mmwave::MmWaveEnbPhy::ReceiveUlHarqFeedback().
The documentation for this class was generated from the following file:
src/mmwave/model/mmwave-phy-sap.h