ns3-mmwave: ns3::mmwave::MmWaveSvdBeamforming Class Reference
ns3::mmwave::MmWaveSvdBeamforming Class Reference
This class extends the MmWaveBeamformingModel interface.
#include "mmwave-beamforming-model.h"
Public Member Functions
MmWaveSvdBeamforming ()
Constructor.
virtual ~MmWaveSvdBeamforming () override
Destructor.
void SetBeamformingVectorForDevice (Ptr< NetDevice > otherDevice, Ptr< ThreeGppAntennaArrayModel > otherAntenna) override
Computes the beamforming vector to communicate with the target device and sets the antenna.
Public Member Functions inherited from ns3::mmwave::MmWaveBeamformingModel
MmWaveBeamformingModel ()
Constructor.
virtual ~MmWaveBeamformingModel () override
Destructor.
Ptr< ThreeGppAntennaArrayModel > GetAntenna (void) const
Get the antenna on which beamforming is applied.
Ptr< NetDevice > GetDevice (void) const
Returns the NetDevice.
void SetAntenna (Ptr< ThreeGppAntennaArrayModel > antenna)
Set the antenna on which beamforming is applied.
void SetDevice (Ptr< NetDevice > device)
Set the NetDevice.
Static Public Member Functions
static TypeId GetTypeId (void)
Returns the object type id.
Static Public Member Functions inherited from ns3::mmwave::MmWaveBeamformingModel
static TypeId GetTypeId (void)
Returns the object type id.
Private Member Functions
std::pair< ThreeGppAntennaArrayModel::ComplexVector, ThreeGppAntennaArrayModel::ComplexVector > ComputeBeamformingVectors (Ptr< const MatrixBasedChannelModel::ChannelMatrix > params) const
Compute the beamforming vectors using SVD.
void DoDispose (void) override
ThreeGppAntennaArrayModel::ComplexVector GetFirstEigenvector (MatrixBasedChannelModel::Complex2DVector A) const
Compute eigenvector related to highest eigenvalue.
Private Attributes
std::map< Ptr< NetDevice >, std::pair< ThreeGppAntennaArrayModel::ComplexVector, ThreeGppAntennaArrayModel::ComplexVector > > m_cacheBfVectors
map that stores the previous bf vectors
std::map< Ptr< NetDevice >, Ptr< const MatrixBasedChannelModel::ChannelMatrix > > m_cacheChannelMap
map that stores the channel previously computed
Ptr< MatrixBasedChannelModel > m_channel
pointer to the MatrixChannel, to retrieve the matrix on which the SVD should be computed
uint32_t m_maxIterations
Maximum number of iterations to numerically approximate the SVD decomposition.
double m_tolerance
Tolerance to numerically approximate the SVD decomposition.
bool m_useCache
Cache the channel matrix whenever possible.
Additional Inherited Members
Protected Attributes inherited from ns3::mmwave::MmWaveBeamformingModel
Ptr< ThreeGppAntennaArrayModel > m_antenna
The antenna of the device on which the beamforming is applied.
Ptr< NetDevice > m_device
pointer to the NetDevice
Detailed Description
This class extends the MmWaveBeamformingModel interface.
It implements an SVD-based beamforming algorithm. See Sec. 5.1 for references https://arxiv.org/pdf/1702.04822.pdf
Definition at line 137 of file mmwave-beamforming-model.h.
Constructor & Destructor Documentation
MmWaveSvdBeamforming()
ns3::mmwave::MmWaveSvdBeamforming::MmWaveSvdBeamforming ()
Constructor.
Definition at line 217 of file mmwave-beamforming-model.cc.
~MmWaveSvdBeamforming()
ns3::mmwave::MmWaveSvdBeamforming::~MmWaveSvdBeamforming () override virtual
Destructor.
Definition at line 223 of file mmwave-beamforming-model.cc.
Member Function Documentation
ComputeBeamformingVectors()
std::pair< ThreeGppAntennaArrayModel::ComplexVector, ThreeGppAntennaArrayModel::ComplexVector > ns3::mmwave::MmWaveSvdBeamforming::ComputeBeamformingVectors (Ptr< const MatrixBasedChannelModel::ChannelMatrix > params) const private
Compute the beamforming vectors using SVD.
Parameters
params the channel matrix
Returns
a pair with the beamforming vectors
Definition at line 328 of file mmwave-beamforming-model.cc.
References GetFirstEigenvector().
Referenced by SetBeamformingVectorForDevice().
DoDispose()
void ns3::mmwave::MmWaveSvdBeamforming::DoDispose (void) override private virtual
Reimplemented from ns3::mmwave::MmWaveBeamformingModel.
Definition at line 228 of file mmwave-beamforming-model.cc.
References ns3::mmwave::MmWaveBeamformingModel::DoDispose(), and m_channel.
GetFirstEigenvector()
ThreeGppAntennaArrayModel::ComplexVector ns3::mmwave::MmWaveSvdBeamforming::GetFirstEigenvector (MatrixBasedChannelModel::Complex2DVector A) const private
Compute eigenvector related to highest eigenvalue.
Parameters
A spatial correlation matrix (complex, hermitian)
Returns
eigenvector
Definition at line 416 of file mmwave-beamforming-model.cc.
References m_tolerance.
Referenced by ComputeBeamformingVectors().
GetTypeId()
TypeId ns3::mmwave::MmWaveSvdBeamforming::GetTypeId (void) static
Returns the object type id.
Returns
the type id
Definition at line 186 of file mmwave-beamforming-model.cc.
References m_channel, m_maxIterations, m_tolerance, and m_useCache.
Referenced by ns3::mmwave::MmWaveHelper::MmWaveHelper().
SetBeamformingVectorForDevice()
void ns3::mmwave::MmWaveSvdBeamforming::SetBeamformingVectorForDevice (Ptr< NetDevice > otherDevice, Ptr< ThreeGppAntennaArrayModel > otherAntenna) override virtual
Computes the beamforming vector to communicate with the target device and sets the antenna.
The beamforming vector is computed using a SVD-based beamforming algorithm.
Parameters
otherDevice the target device
otherAntenna the target antenna of otherDevice
Implements ns3::mmwave::MmWaveBeamformingModel.
Definition at line 236 of file mmwave-beamforming-model.cc.
References ComputeBeamformingVectors(), ns3::mmwave::MmWaveBeamformingModel::m_antenna, m_cacheBfVectors, m_cacheChannelMap, m_channel, ns3::mmwave::MmWaveBeamformingModel::m_device, and m_useCache.
Member Data Documentation
m_cacheBfVectors
std::map<Ptr<NetDevice>, std::pair<ThreeGppAntennaArrayModel::ComplexVector, ThreeGppAntennaArrayModel::ComplexVector> > ns3::mmwave::MmWaveSvdBeamforming::m_cacheBfVectors private
map that stores the previous bf vectors
Definition at line 186 of file mmwave-beamforming-model.h.
Referenced by SetBeamformingVectorForDevice().
m_cacheChannelMap
std::map<Ptr<NetDevice>, Ptr<const MatrixBasedChannelModel::ChannelMatrix> > ns3::mmwave::MmWaveSvdBeamforming::m_cacheChannelMap private
map that stores the channel previously computed
Definition at line 185 of file mmwave-beamforming-model.h.
Referenced by SetBeamformingVectorForDevice().
m_channel
Ptr<MatrixBasedChannelModel> ns3::mmwave::MmWaveSvdBeamforming::m_channel private
pointer to the MatrixChannel, to retrieve the matrix on which the SVD should be computed
Definition at line 183 of file mmwave-beamforming-model.h.
Referenced by DoDispose(), GetTypeId(), and SetBeamformingVectorForDevice().
m_maxIterations
uint32_t ns3::mmwave::MmWaveSvdBeamforming::m_maxIterations private
Maximum number of iterations to numerically approximate the SVD decomposition.
Definition at line 187 of file mmwave-beamforming-model.h.
Referenced by GetTypeId().
m_tolerance
double ns3::mmwave::MmWaveSvdBeamforming::m_tolerance private
Tolerance to numerically approximate the SVD decomposition.
Definition at line 188 of file mmwave-beamforming-model.h.
Referenced by GetFirstEigenvector(), and GetTypeId().
m_useCache
bool ns3::mmwave::MmWaveSvdBeamforming::m_useCache private
Cache the channel matrix whenever possible.
NOTE: the SVD decomposition can be extremely computationally expensive, caching is suggested.
Definition at line 189 of file mmwave-beamforming-model.h.
Referenced by GetTypeId(), and SetBeamformingVectorForDevice().
The documentation for this class was generated from the following files:
src/mmwave/model/mmwave-beamforming-model.h
src/mmwave/model/mmwave-beamforming-model.cc