ns3-mmwave: ns3::mmwave::MmWavePhySapProvider Class Reference
ns3::mmwave::MmWavePhySapProvider Class Reference abstract
#include "mmwave-phy-sap.h"
Public Member Functions
virtual ~MmWavePhySapProvider ()
virtual void SendControlMessage (Ptr< MmWaveControlMessage > msg)=0
virtual void SendMacPdu (Ptr< Packet > p)=0
virtual void SendRachPreamble (uint8_t PreambleId, uint8_t Rnti)=0
virtual void SetSlotAllocInfo (SlotAllocInfo slotAllocInfo)=0
Updates the current NR slot with the allocation info provided by the scheduler.
Detailed Description
Definition at line 47 of file mmwave-phy-sap.h.
Constructor & Destructor Documentation
~MmWavePhySapProvider()
ns3::mmwave::MmWavePhySapProvider::~MmWavePhySapProvider () virtual
Definition at line 35 of file mmwave-phy-sap.cc.
Member Function Documentation
SendControlMessage()
virtual void ns3::mmwave::MmWavePhySapProvider::SendControlMessage (Ptr< MmWaveControlMessage > msg) pure virtual
Implemented in ns3::mmwave::MmWaveMemberPhySapProvider.
Referenced by ns3::mmwave::MmWaveEnbMac::DoSlotIndication(), and ns3::mmwave::MmWaveUeMac::SendReportBufferStatus().
SendMacPdu()
virtual void ns3::mmwave::MmWavePhySapProvider::SendMacPdu (Ptr< Packet > p) pure virtual
Implemented in ns3::mmwave::MmWaveMemberPhySapProvider.
Referenced by ns3::mmwave::MmWaveUeMac::DoReceiveControlMessage(), ns3::mmwave::MmWaveEnbMac::DoSchedConfigIndication(), and ns3::mmwave::MmWaveUeMac::DoTransmitPdu().
SendRachPreamble()
virtual void ns3::mmwave::MmWavePhySapProvider::SendRachPreamble (uint8_t PreambleId, uint8_t Rnti) pure virtual
Implemented in ns3::mmwave::MmWaveMemberPhySapProvider.
Referenced by ns3::mmwave::MmWaveUeMac::SendRaPreamble().
SetSlotAllocInfo()
virtual void ns3::mmwave::MmWavePhySapProvider::SetSlotAllocInfo (SlotAllocInfo slotAllocInfo) pure virtual
Updates the current NR slot with the allocation info provided by the scheduler.
Parameters
slotAllocInfo the slot allocation info created by the scheduler.
Implemented in ns3::mmwave::MmWaveMemberPhySapProvider.
Referenced by ns3::mmwave::MmWaveEnbMac::DoSchedConfigIndication().
The documentation for this class was generated from the following files:
src/mmwave/model/mmwave-phy-sap.h
src/mmwave/model/mmwave-phy-sap.cc