ns3-mmwave: ns3::mmwave::MmWaveMiErrorModel Class Reference
ns3::mmwave::MmWaveMiErrorModel Class Reference
This class provides the BLER estimation based on mutual information metrics.
#include "mmwave-mi-error-model.h"
Static Public Member Functions
static MmWaveTbStats_t GetTbDecodificationStats (const SpectrumValue &sinr, const std::vector< int > &map, uint32_t size, uint8_t mcs, MmWaveHarqProcessInfoList_t miHistory)
Run the error-model algorithm for the specified TB.
static double MappingMiBler (double mib, uint8_t ecrId, uint32_t cbSize)
map the mmib (mean mutual information per bit) for different MCS
static double Mib (const SpectrumValue &sinr, const std::vector< int > &map, uint8_t mcs)
find the mmib (mean mutual information per bit) for different modulations of the specified TB
Detailed Description
This class provides the BLER estimation based on mutual information metrics.
Definition at line 327 of file mmwave-mi-error-model.h.
Member Function Documentation
GetTbDecodificationStats()
MmWaveTbStats_t ns3::mmwave::MmWaveMiErrorModel::GetTbDecodificationStats (const SpectrumValue & sinr, const std::vector< int > & map, uint32_t size, uint8_t mcs, MmWaveHarqProcessInfoList_t miHistory) static
Run the error-model algorithm for the specified TB.
Parameters
sinr the perceived sinrs in the whole bandwidth
map the actives RBs for the TB
size the size in bytes of the TB
mcs the MCS of the TB
miHistory the MI history
Returns
the TB error rate and MI
Definition at line 183 of file mmwave-mi-error-model.cc.
References ns3::mmwave::BlerCurvesEcrMap, ns3::mmwave::cbSizeTable, MappingMiBler(), ns3::mmwave::McsEcrBlerTableMapping, ns3::mmwave::McsEcrTable, ns3::mmwave::MmWaveTbStats_t::mi, Mib(), ns3::mmwave::MmWaveTbStats_t::miTotal, ns3::mmwave::MMWAVE_MI_16QAM_BLER_MAX_ID, ns3::mmwave::MMWAVE_MI_16QAM_MAX_ID, ns3::mmwave::MMWAVE_MI_64QAM_BLER_MAX_ID, ns3::mmwave::MMWAVE_MI_QPSK_BLER_MAX_ID, ns3::mmwave::MMWAVE_MI_QPSK_MAX_ID, and ns3::mmwave::MmWaveTbStats_t::tbler.
Referenced by ns3::mmwave::MmWaveAmc::CreateCqiFeedbacks(), ns3::mmwave::MmWaveAmc::CreateCqiFeedbacksTdma(), ns3::mmwave::MmWaveAmc::CreateCqiFeedbackWbTdma(), and ns3::mmwave::MmWaveSpectrumPhy::EndRxData().
MappingMiBler()
double ns3::mmwave::MmWaveMiErrorModel::MappingMiBler (double mib, uint8_t ecrId, uint32_t cbSize) static
map the mmib (mean mutual information per bit) for different MCS
Parameters
mib mean mutual information per bit of a code-block
ecrId Effective Code Rate ID
cbSize the size of the CB
Returns
the code block error rate
Definition at line 139 of file mmwave-mi-error-model.cc.
References ns3::mmwave::bEcrTable, ns3::mmwave::BlerCurvesEcrMap, ns3::mmwave::cbMiSizeTable, ns3::mmwave::cEcrTable, and ns3::mmwave::MMWAVE_MI_64QAM_BLER_MAX_ID.
Referenced by GetTbDecodificationStats().
Mib()
double ns3::mmwave::MmWaveMiErrorModel::Mib (const SpectrumValue & sinr, const std::vector< int > & map, uint8_t mcs) static
find the mmib (mean mutual information per bit) for different modulations of the specified TB
Parameters
sinr the perceived sinrs in the whole bandwidth
map the actives RBs for the TB
mcs the MCS of the TB
Returns
the mmib
Definition at line 54 of file mmwave-mi-error-model.cc.
References ns3::mmwave::MI_map_16qam, ns3::mmwave::MI_map_16qam_axis, ns3::mmwave::MI_map_64qam, ns3::mmwave::MI_map_64qam_axis, ns3::mmwave::MI_map_qpsk, ns3::mmwave::MI_map_qpsk_axis, ns3::mmwave::MMWAVE_MI_16QAM_MAX_ID, ns3::mmwave::MMWAVE_MI_MAP_16QAM_SIZE, ns3::mmwave::MMWAVE_MI_MAP_64QAM_SIZE, ns3::mmwave::MMWAVE_MI_MAP_QPSK_SIZE, and ns3::mmwave::MMWAVE_MI_QPSK_MAX_ID.
Referenced by GetTbDecodificationStats().
The documentation for this class was generated from the following files:
src/mmwave/model/mmwave-mi-error-model.h
src/mmwave/model/mmwave-mi-error-model.cc