ns3-mmwave: ns3::mmwave::MmWaveMacCschedSapProvider Class Reference
ns3::mmwave::MmWaveMacCschedSapProvider Class Reference abstract
Provides the CSCHED SAP.
#include "mmwave-mac-csched-sap.h"
Classes
struct CschedCellConfigReqParameters
Parameters of the API primitives.
struct CschedLcConfigReqParameters
Parameters of the CSCHED_LC_CONFIG_REQ primitive.
struct CschedLcReleaseReqParameters
Parameters of the CSCHED_LC_RELEASE_REQ primitive.
struct CschedUeConfigReqParameters
Parameters of the CSCHED_UE_CONFIG_REQ primitive.
struct CschedUeReleaseReqParameters
Parameters of the CSCHED_UE_RELEASE_REQ primitive.
Public Member Functions
virtual ~MmWaveMacCschedSapProvider ()
virtual void CschedCellConfigReq (const struct CschedCellConfigReqParameters &params)=0
CSCHED_CELL_CONFIG_REQ.
virtual void CschedLcConfigReq (const struct CschedLcConfigReqParameters &params)=0
virtual void CschedLcReleaseReq (const struct CschedLcReleaseReqParameters &params)=0
virtual void CschedUeConfigReq (const struct CschedUeConfigReqParameters &params)=0
virtual void CschedUeReleaseReq (const struct CschedUeReleaseReqParameters &params)=0
Detailed Description
Provides the CSCHED SAP.
This abstract class defines the MAC Scheduler interface specified in the Femto Forum Technical Document:
LTE MAC Scheduler Interface Specification v1.11
The Technical Document contains a detailed description of the API. The documentation of this class refers to sections of this Technical Document.
You can found an example of the implementation of this interface in the SampleMmWaveMacCschedSapProvider and SampleFfMacCschedSapuser classes
Definition at line 55 of file mmwave-mac-csched-sap.h.
Constructor & Destructor Documentation
~MmWaveMacCschedSapProvider()
ns3::mmwave::MmWaveMacCschedSapProvider::~MmWaveMacCschedSapProvider () virtual
Definition at line 35 of file mmwave-mac-csched-sap.cc.
Member Function Documentation
CschedCellConfigReq()
virtual void ns3::mmwave::MmWaveMacCschedSapProvider::CschedCellConfigReq (const struct CschedCellConfigReqParameters & params) pure virtual
CSCHED_CELL_CONFIG_REQ.
Implemented in ns3::mmwave::MmWaveFlexTtiMacCschedSapProvider, ns3::mmwave::MmWaveFlexTtiMaxRateMacCschedSapProvider, ns3::mmwave::MmWaveFlexTtiMaxWeightMacCschedSapProvider, and ns3::mmwave::MmWaveFlexTtiPfMacCschedSapProvider.
Referenced by ns3::mmwave::MmWaveEnbMac::DoConfigureMac().
CschedLcConfigReq()
virtual void ns3::mmwave::MmWaveMacCschedSapProvider::CschedLcConfigReq (const struct CschedLcConfigReqParameters & params) pure virtual
Implemented in ns3::mmwave::MmWaveFlexTtiMacCschedSapProvider, ns3::mmwave::MmWaveFlexTtiMaxRateMacCschedSapProvider, ns3::mmwave::MmWaveFlexTtiMaxWeightMacCschedSapProvider, and ns3::mmwave::MmWaveFlexTtiPfMacCschedSapProvider.
Referenced by ns3::mmwave::MmWaveEnbMac::DoAddLc().
CschedLcReleaseReq()
virtual void ns3::mmwave::MmWaveMacCschedSapProvider::CschedLcReleaseReq (const struct CschedLcReleaseReqParameters & params) pure virtual
Implemented in ns3::mmwave::MmWaveFlexTtiMacCschedSapProvider, ns3::mmwave::MmWaveFlexTtiMaxRateMacCschedSapProvider, ns3::mmwave::MmWaveFlexTtiMaxWeightMacCschedSapProvider, and ns3::mmwave::MmWaveFlexTtiPfMacCschedSapProvider.
Referenced by ns3::mmwave::MmWaveEnbMac::DoReleaseLc().
CschedUeConfigReq()
virtual void ns3::mmwave::MmWaveMacCschedSapProvider::CschedUeConfigReq (const struct CschedUeConfigReqParameters & params) pure virtual
Implemented in ns3::mmwave::MmWaveFlexTtiMacCschedSapProvider, ns3::mmwave::MmWaveFlexTtiMaxRateMacCschedSapProvider, ns3::mmwave::MmWaveFlexTtiMaxWeightMacCschedSapProvider, and ns3::mmwave::MmWaveFlexTtiPfMacCschedSapProvider.
Referenced by ns3::mmwave::MmWaveEnbMac::DoAddUe(), and ns3::mmwave::MmWaveEnbMac::UeUpdateConfigurationReq().
CschedUeReleaseReq()
virtual void ns3::mmwave::MmWaveMacCschedSapProvider::CschedUeReleaseReq (const struct CschedUeReleaseReqParameters & params) pure virtual
Implemented in ns3::mmwave::MmWaveFlexTtiMacCschedSapProvider, ns3::mmwave::MmWaveFlexTtiMaxRateMacCschedSapProvider, ns3::mmwave::MmWaveFlexTtiMaxWeightMacCschedSapProvider, and ns3::mmwave::MmWaveFlexTtiPfMacCschedSapProvider.
Referenced by ns3::mmwave::MmWaveEnbMac::DoRemoveUe().
The documentation for this class was generated from the following files:
src/mmwave/model/mmwave-mac-csched-sap.h
src/mmwave/model/mmwave-mac-csched-sap.cc