ns3-mmwave: ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler Class Reference
ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler Class Reference
#include "mmwave-flex-tti-maxrate-mac-scheduler.h"
Classes
struct AllocMapElem
struct FlowStats
struct UeSchedInfo
struct UlCqiMapElem
Public Types
typedef std::vector< DciInfoElementTdma > DlHarqProcessesDciInfoList_t
typedef std::vector< uint8_t > DlHarqProcessesStatus_t
typedef std::vector< uint8_t > DlHarqProcessesTimer_t
typedef std::vector< std::vector< struct RlcPduInfo > > DlHarqRlcPduList_t
typedef std::vector< DciInfoElementTdma > UlHarqProcessesDciInfoList_t
typedef std::vector< uint8_t > UlHarqProcessesStatus_t
typedef std::vector< uint8_t > UlHarqProcessesTimer_t
Public Member Functions
MmWaveFlexTtiMaxRateMacScheduler ()
virtual ~MmWaveFlexTtiMaxRateMacScheduler ()
virtual void ConfigureCommonParameters (Ptr< MmWavePhyMacCommon > config) override
virtual void DoDispose (void) override
virtual MmWaveMacCschedSapProvider * GetMacCschedSapProvider () override
virtual MmWaveMacSchedSapProvider * GetMacSchedSapProvider () override
void RefreshDlCqiMaps (void)
void RefreshUlCqiMaps (void)
virtual void SetMacCschedSapUser (MmWaveMacCschedSapUser *s) override
virtual void SetMacSchedSapUser (MmWaveMacSchedSapUser *sap) override
void UpdateDlRlcBufferInfo (uint16_t rnti, uint8_t lcid, uint16_t size)
void UpdateUlRlcBufferInfo (uint16_t rnti, uint16_t size)
Public Member Functions inherited from ns3::mmwave::MmWaveMacScheduler
MmWaveMacScheduler ()
virtual ~MmWaveMacScheduler ()
Static Public Member Functions
static TypeId GetTypeId (void)
static bool SortRlcBufferReq (MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters i, MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters j)
Static Public Member Functions inherited from ns3::mmwave::MmWaveMacScheduler
static TypeId GetTypeId (void)
Private Member Functions
uint32_t BsrId2BufferSize (uint8_t val)
uint8_t BufferSize2BsrId (uint32_t val)
unsigned CalcMinTbSizeNumSym (unsigned mcs, unsigned bufSize, unsigned &tbSize)
void DoCschedCellConfigReq (const struct MmWaveMacCschedSapProvider::CschedCellConfigReqParameters &params)
void DoCschedLcConfigReq (const struct MmWaveMacCschedSapProvider::CschedLcConfigReqParameters &params)
void DoCschedLcReleaseReq (const struct MmWaveMacCschedSapProvider::CschedLcReleaseReqParameters &params)
void DoCschedUeConfigReq (const struct MmWaveMacCschedSapProvider::CschedUeConfigReqParameters &params)
void DoCschedUeReleaseReq (const struct MmWaveMacCschedSapProvider::CschedUeReleaseReqParameters &params)
void DoSchedDlCqiInfoReq (const MmWaveMacSchedSapProvider::SchedDlCqiInfoReqParameters &params)
void DoSchedDlRlcBufferReq (const struct MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters &params)
bool DoSchedDlTriggerReq (const struct MmWaveMacSchedSapProvider::SchedTriggerReqParameters &params, MmWaveMacSchedSapUser::SchedConfigIndParameters &ret, unsigned int frameNum, unsigned int sfNum, unsigned int islot)
void DoSchedSetMcs (int mcs)
void DoSchedTriggerReq (const struct MmWaveMacSchedSapProvider::SchedTriggerReqParameters &params)
void DoSchedUlCqiInfoReq (const struct MmWaveMacSchedSapProvider::SchedUlCqiInfoReqParameters &params)
void DoSchedUlMacCtrlInfoReq (const struct MmWaveMacSchedSapProvider::SchedUlMacCtrlInfoReqParameters &params)
bool DoSchedUlTriggerReq (const struct MmWaveMacSchedSapProvider::SchedTriggerReqParameters &params, MmWaveMacSchedSapUser::SchedConfigIndParameters &ret, unsigned int frameNum, unsigned int sfNum, unsigned int islot)
void RefreshHarqProcesses ()
Refresh HARQ processes according to the timers.
uint8_t UpdateDlHarqProcessId (uint16_t rnti)
uint8_t UpdateUlHarqProcessId (uint16_t rnti)
Static Private Member Functions
static bool CompareUeWeightsMaxRate (UeSchedInfo *lue, UeSchedInfo *rue)
Private Attributes
Ptr< MmWaveAmc > m_amc
double m_berDl
std::map< uint16_t, uint32_t > m_ceBsrRxed
uint32_t m_cqiTimersThreshold
MmWaveMacCschedSapProvider::CschedCellConfigReqParameters m_cschedCellConfig
std::map< uint16_t, uint8_t > m_dlHarqCurrentProcessId
std::vector< DlHarqInfo > m_dlHarqInfoList
std::map< uint16_t, DlHarqProcessesDciInfoList_t > m_dlHarqProcessesDciInfoMap
std::map< uint16_t, DlHarqRlcPduList_t > m_dlHarqProcessesRlcPduMap
std::map< uint16_t, DlHarqProcessesStatus_t > m_dlHarqProcessesStatus
std::map< uint16_t, DlHarqProcessesTimer_t > m_dlHarqProcessesTimer
bool m_dlOnly
bool m_fixedMcsDl
bool m_fixedMcsUl
bool m_fixedTti
std::vector< FlowStats * > m_flowHeap
uint32_t m_frameNo
bool m_harqOn
m_harqOn when false inhibit te HARQ mechanisms (by default active)
uint8_t m_harqTimeout
MmWaveMacCschedSapProvider * m_macCschedSapProvider
MmWaveMacCschedSapUser * m_macCschedSapUser
MmWaveMacSchedSapProvider * m_macSchedSapProvider
MmWaveMacSchedSapUser * m_macSchedSapUser
uint8_t m_mcsDefaultDl
uint8_t m_mcsDefaultUl
uint16_t m_nextRnti
uint64_t m_nextRntiDl
uint64_t m_nextRntiUl
uint32_t m_numChunks
uint32_t m_numDataSymbols
uint8_t m_numHarqProcess
std::list< MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters > m_rlcBufferReq
uint8_t m_symPerSlot
uint8_t m_tbUid
double m_timeWindow
std::map< uint16_t, uint32_t > m_ueCqiTimers
std::vector< UeSchedInfo * > m_ueSchedInfoHeap
std::map< uint16_t, UeSchedInfo > m_ueSchedInfoMap
std::vector< UeSchedInfo * > m_ueStatHeap
std::map< uint16_t, struct UlCqiMapElem > m_ueUlCqi
std::map< uint32_t, struct AllocMapElem > m_ulAllocationMap
std::map< uint16_t, uint8_t > m_ulHarqCurrentProcessId
std::vector< UlHarqInfo > m_ulHarqInfoList
std::map< uint16_t, UlHarqProcessesDciInfoList_t > m_ulHarqProcessesDciInfoMap
std::map< uint16_t, UlHarqProcessesStatus_t > m_ulHarqProcessesStatus
std::map< uint16_t, UlHarqProcessesTimer_t > m_ulHarqProcessesTimer
bool m_ulOnly
std::list< struct SlotAllocInfo > m_ulSfAllocInfo
std::map< uint16_t, uint8_t > m_wbCqiRxed
std::map< uint16_t, uint32_t > m_wbCqiTimers
Static Private Attributes
static const unsigned m_macHdrSize = 0
static const unsigned m_rlcHdrSize = 3
static const unsigned m_subHdrSize = 4
Friends
class MmWaveFlexTtiMaxRateMacCschedSapProvider
class MmWaveFlexTtiMaxRateMacSchedSapProvider
Additional Inherited Members
Protected Attributes inherited from ns3::mmwave::MmWaveMacScheduler
Ptr< MmWavePhyMacCommon > m_phyMacConfig
uint32_t m_rbgSize
Detailed Description
Definition at line 26 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Member Typedef Documentation
DlHarqProcessesDciInfoList_t
typedef std::vector< DciInfoElementTdma > ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::DlHarqProcessesDciInfoList_t
Definition at line 31 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
DlHarqProcessesStatus_t
typedef std::vector< uint8_t > ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::DlHarqProcessesStatus_t
Definition at line 29 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
DlHarqProcessesTimer_t
typedef std::vector< uint8_t > ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::DlHarqProcessesTimer_t
Definition at line 30 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
DlHarqRlcPduList_t
typedef std::vector< std::vector <struct RlcPduInfo> > ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::DlHarqRlcPduList_t
Definition at line 32 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
UlHarqProcessesDciInfoList_t
typedef std::vector< DciInfoElementTdma > ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::UlHarqProcessesDciInfoList_t
Definition at line 36 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
UlHarqProcessesStatus_t
typedef std::vector< uint8_t > ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::UlHarqProcessesStatus_t
Definition at line 37 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
UlHarqProcessesTimer_t
typedef std::vector< uint8_t > ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::UlHarqProcessesTimer_t
Definition at line 35 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Constructor & Destructor Documentation
MmWaveFlexTtiMaxRateMacScheduler()
ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::MmWaveFlexTtiMaxRateMacScheduler ()
Definition at line 151 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
References m_macCschedSapProvider, m_macSchedSapProvider, MmWaveFlexTtiMaxRateMacCschedSapProvider, and MmWaveFlexTtiMaxRateMacSchedSapProvider.
~MmWaveFlexTtiMaxRateMacScheduler()
ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::~MmWaveFlexTtiMaxRateMacScheduler () virtual
Definition at line 163 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
Member Function Documentation
BsrId2BufferSize()
uint32_t ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::BsrId2BufferSize (uint8_t val) inline private
Definition at line 219 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
References ns3::mmwave::BufferSizeLevelBsrTable.
Referenced by DoSchedUlMacCtrlInfoReq().
BufferSize2BsrId()
uint8_t ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::BufferSize2BsrId (uint32_t val) inline private
Definition at line 226 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
References ns3::mmwave::BufferSizeLevelBsrTable, DoCschedCellConfigReq(), DoCschedLcConfigReq(), DoCschedLcReleaseReq(), DoCschedUeConfigReq(), DoCschedUeReleaseReq(), DoSchedDlCqiInfoReq(), DoSchedDlRlcBufferReq(), DoSchedDlTriggerReq(), DoSchedSetMcs(), DoSchedTriggerReq(), DoSchedUlCqiInfoReq(), DoSchedUlMacCtrlInfoReq(), DoSchedUlTriggerReq(), RefreshHarqProcesses(), UpdateDlHarqProcessId(), and UpdateUlHarqProcessId().
CalcMinTbSizeNumSym()
unsigned ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::CalcMinTbSizeNumSym (unsigned mcs, unsigned bufSize, unsigned & tbSize) private
Definition at line 699 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
References m_amc, and ns3::mmwave::MmWaveMacScheduler::m_phyMacConfig.
Referenced by CompareUeWeightsMaxRate().
CompareUeWeightsMaxRate()
static bool ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::CompareUeWeightsMaxRate (UeSchedInfo * lue, UeSchedInfo * rue) inline static private
Definition at line 208 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
References CalcMinTbSizeNumSym(), ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::UeSchedInfo::m_currTputDl, and ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::UeSchedInfo::m_currTputUl.
ConfigureCommonParameters()
void ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::ConfigureCommonParameters (Ptr< MmWavePhyMacCommon > config) override virtual
Implements ns3::mmwave::MmWaveMacScheduler.
Definition at line 272 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
References m_amc, m_harqTimeout, m_numDataSymbols, m_numHarqProcess, and ns3::mmwave::MmWaveMacScheduler::m_phyMacConfig.
DoCschedCellConfigReq()
void ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::DoCschedCellConfigReq (const struct MmWaveMacCschedSapProvider::CschedCellConfigReqParameters & params) private
Definition at line 1629 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
References ns3::mmwave::MmWaveMacCschedSapUser::CschedUeConfigCnf(), m_cschedCellConfig, m_macCschedSapUser, and ns3::mmwave::MmWaveMacCschedSapUser::CschedUeConfigCnfParameters::m_result.
Referenced by BufferSize2BsrId(), and ns3::mmwave::MmWaveFlexTtiMaxRateMacCschedSapProvider::CschedCellConfigReq().
DoCschedLcConfigReq()
void ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::DoCschedLcConfigReq (const struct MmWaveMacCschedSapProvider::CschedLcConfigReqParameters & params) private
Definition at line 1690 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
References m_flowHeap, ns3::mmwave::MmWaveMacCschedSapProvider::CschedLcConfigReqParameters::m_logicalChannelConfigList, ns3::mmwave::MmWaveMacCschedSapProvider::CschedLcConfigReqParameters::m_rnti, and m_ueSchedInfoMap.
Referenced by BufferSize2BsrId(), and ns3::mmwave::MmWaveFlexTtiMaxRateMacCschedSapProvider::CschedLcConfigReq().
DoCschedLcReleaseReq()
void ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::DoCschedLcReleaseReq (const struct MmWaveMacCschedSapProvider::CschedLcReleaseReqParameters & params) private
Definition at line 1763 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
References ns3::mmwave::MmWaveMacCschedSapProvider::CschedLcReleaseReqParameters::m_logicalChannelIdentity, m_rlcBufferReq, and ns3::mmwave::MmWaveMacCschedSapProvider::CschedLcReleaseReqParameters::m_rnti.
Referenced by BufferSize2BsrId(), and ns3::mmwave::MmWaveFlexTtiMaxRateMacCschedSapProvider::CschedLcReleaseReq().
DoCschedUeConfigReq()
void ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::DoCschedUeConfigReq (const struct MmWaveMacCschedSapProvider::CschedUeConfigReqParameters & params) private
Definition at line 1642 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
References m_dlHarqProcessesDciInfoMap, m_dlHarqProcessesRlcPduMap, m_dlHarqProcessesStatus, m_dlHarqProcessesTimer, ns3::mmwave::MmWaveMacScheduler::m_phyMacConfig, ns3::mmwave::MmWaveMacCschedSapProvider::CschedUeConfigReqParameters::m_rnti, ns3::mmwave::MmWaveMacCschedSapProvider::CschedUeConfigReqParameters::m_transmissionMode, m_ueSchedInfoMap, m_ulHarqProcessesDciInfoMap, m_ulHarqProcessesStatus, and m_ulHarqProcessesTimer.
Referenced by BufferSize2BsrId(), and ns3::mmwave::MmWaveFlexTtiMaxRateMacCschedSapProvider::CschedUeConfigReq().
DoCschedUeReleaseReq()
void ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::DoCschedUeReleaseReq (const struct MmWaveMacCschedSapProvider::CschedUeReleaseReqParameters & params) private
Definition at line 1785 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
References m_ceBsrRxed, m_dlHarqProcessesDciInfoMap, m_dlHarqProcessesRlcPduMap, m_dlHarqProcessesStatus, m_dlHarqProcessesTimer, m_nextRntiDl, m_nextRntiUl, m_rlcBufferReq, ns3::mmwave::MmWaveMacCschedSapProvider::CschedUeReleaseReqParameters::m_rnti, m_ueSchedInfoMap, m_ulHarqProcessesDciInfoMap, m_ulHarqProcessesStatus, and m_ulHarqProcessesTimer.
Referenced by BufferSize2BsrId(), and ns3::mmwave::MmWaveFlexTtiMaxRateMacCschedSapProvider::CschedUeReleaseReq().
DoDispose()
void ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::DoDispose (void) override virtual
Reimplemented from ns3::mmwave::MmWaveMacScheduler.
Definition at line 169 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
References m_dlHarqInfoList, m_dlHarqProcessesDciInfoMap, m_dlHarqProcessesRlcPduMap, m_dlHarqProcessesTimer, m_macCschedSapProvider, m_macSchedSapProvider, m_ulHarqCurrentProcessId, m_ulHarqProcessesDciInfoMap, m_ulHarqProcessesStatus, m_ulHarqProcessesTimer, and m_wbCqiRxed.
DoSchedDlCqiInfoReq()
void ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::DoSchedDlCqiInfoReq (const MmWaveMacSchedSapProvider::SchedDlCqiInfoReqParameters & params) private
Definition at line 406 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
References ns3::mmwave::MmWaveMacSchedSapProvider::SchedDlCqiInfoReqParameters::m_cqiList, m_cqiTimersThreshold, m_wbCqiRxed, m_wbCqiTimers, ns3::mmwave::DlCqiInfo::SB, and ns3::mmwave::DlCqiInfo::WB.
Referenced by BufferSize2BsrId(), and ns3::mmwave::MmWaveFlexTtiMaxRateMacSchedSapProvider::SchedDlCqiInfoReq().
DoSchedDlRlcBufferReq()
void ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::DoSchedDlRlcBufferReq (const struct MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters & params) private
Definition at line 282 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
References ns3::mmwave::MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters::m_logicalChannelIdentity, ns3::mmwave::MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters::m_rlcTransmissionQueueSize, ns3::mmwave::MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters::m_rnti, ns3::mmwave::MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters::m_txPacketDelays, ns3::mmwave::MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters::m_txPacketSizes, and m_ueSchedInfoMap.
Referenced by BufferSize2BsrId(), and ns3::mmwave::MmWaveFlexTtiMaxRateMacSchedSapProvider::SchedDlRlcBufferReq().
DoSchedDlTriggerReq()
bool ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::DoSchedDlTriggerReq (const struct MmWaveMacSchedSapProvider::SchedTriggerReqParameters & params, MmWaveMacSchedSapUser::SchedConfigIndParameters & ret, unsigned int frameNum, unsigned int sfNum, unsigned int islot) private
Referenced by BufferSize2BsrId().
DoSchedSetMcs()
void ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::DoSchedSetMcs (int mcs) private
Definition at line 528 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
References m_mcsDefaultDl, and m_mcsDefaultUl.
Referenced by BufferSize2BsrId(), and ns3::mmwave::MmWaveFlexTtiMaxRateMacSchedSapProvider::SchedSetMcs().
DoSchedTriggerReq()
void ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::DoSchedTriggerReq (const struct MmWaveMacSchedSapProvider::SchedTriggerReqParameters & params) private
Definition at line 751 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
References ns3::mmwave::DlHarqInfo::ACK, ns3::mmwave::TtiAllocInfo::CTRL, ns3::mmwave::TtiAllocInfo::CTRL_DATA, ns3::mmwave::TtiAllocInfo::DL_slotAllocInfo, ns3::mmwave::SfnSf::Encode(), ns3::mmwave::MmWaveSpectrumValueHelper::GetSpectrumModel(), ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::UeSchedInfo::m_allocUlLast, m_amc, ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::UeSchedInfo::m_avgTputDl, ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::UeSchedInfo::m_avgTputUl, ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::UeSchedInfo::m_currTputDl, ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::UeSchedInfo::m_currTputUl, ns3::mmwave::TtiAllocInfo::m_dci, ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::UeSchedInfo::m_dlAllocDone, ns3::mmwave::MmWaveMacSchedSapProvider::SchedTriggerReqParameters::m_dlHarqInfoList, m_dlHarqInfoList, m_dlHarqProcessesDciInfoMap, m_dlHarqProcessesRlcPduMap, m_dlHarqProcessesStatus, m_dlHarqProcessesTimer, ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::UeSchedInfo::m_dlMcs, ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::UeSchedInfo::m_dlSymbols, ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::UeSchedInfo::m_dlTbSize, ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::UeSchedInfo::m_flowStatsDl, ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::UeSchedInfo::m_flowStatsUl, ns3::mmwave::DciInfoElementTdma::m_format, ns3::mmwave::SfnSf::m_frameNum, m_harqOn, ns3::mmwave::DciInfoElementTdma::m_harqProcess, ns3::mmwave::UlHarqInfo::m_harqProcessId, ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::UeSchedInfo::m_lastAvgTputDl, ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::UeSchedInfo::m_lastAvgTputUl, ns3::mmwave::RlcPduInfo::m_lcid, m_macSchedSapUser, ns3::mmwave::DciInfoElementTdma::m_mcs, ns3::mmwave::DciInfoElementTdma::m_ndi, ns3::mmwave::DciInfoElementTdma::m_numSym, ns3::mmwave::SlotAllocInfo::m_numSymAlloc, ns3::mmwave::MmWaveMacScheduler::m_phyMacConfig, ns3::mmwave::UlHarqInfo::m_receptionStatus, ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::UeSchedInfo::m_rlcPduInfo, ns3::mmwave::TtiAllocInfo::m_rlcPduInfo, ns3::mmwave::DciInfoElementTdma::m_rnti, ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::UeSchedInfo::m_rnti, ns3::mmwave::UlHarqInfo::m_rnti, ns3::mmwave::DciInfoElementTdma::m_rv, ns3::mmwave::MmWaveMacSchedSapUser::SchedConfigIndParameters::m_sfnSf, ns3::mmwave::SlotAllocInfo::m_sfnSf, ns3::mmwave::SfnSf::m_sfNum, ns3::mmwave::RlcPduInfo::m_size, ns3::mmwave::MmWaveMacSchedSapUser::SchedConfigIndParameters::m_slotAllocInfo, ns3::mmwave::SfnSf::m_slotNum, ns3::mmwave::MmWaveMacSchedSapProvider::SchedTriggerReqParameters::m_snfSf, m_subHdrSize, ns3::mmwave::DciInfoElementTdma::m_symStart, ns3::mmwave::DciInfoElementTdma::m_tbSize, m_timeWindow, ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::UeSchedInfo::m_totBufDl, ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::UeSchedInfo::m_totBufUl, ns3::mmwave::SlotAllocInfo::m_ttiAllocInfo, m_ueSchedInfoMap, m_ueStatHeap, m_ueUlCqi, m_ulAllocationMap, ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::UeSchedInfo::m_ulAllocDone, ns3::mmwave::MmWaveMacSchedSapProvider::SchedTriggerReqParameters::m_ulHarqInfoList, m_ulHarqInfoList, m_ulHarqProcessesDciInfoMap, m_ulHarqProcessesStatus, m_ulHarqProcessesTimer, ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::UeSchedInfo::m_ulMcs, ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::UeSchedInfo::m_ulSymbols, ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::UeSchedInfo::m_ulTbSize, m_wbCqiRxed, ns3::mmwave::DlHarqInfo::NACK, ns3::mmwave::UlHarqInfo::NotOk, ns3::mmwave::UlHarqInfo::Ok, RefreshDlCqiMaps(), RefreshHarqProcesses(), RefreshUlCqiMaps(), ns3::mmwave::MmWaveMacSchedSapUser::SchedConfigInd(), ns3::mmwave::TtiAllocInfo::UL_slotAllocInfo, UpdateDlHarqProcessId(), UpdateDlRlcBufferInfo(), and UpdateUlHarqProcessId().
Referenced by BufferSize2BsrId(), and ns3::mmwave::MmWaveFlexTtiMaxRateMacSchedSapProvider::SchedTriggerReq().
DoSchedUlCqiInfoReq()
void ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::DoSchedUlCqiInfoReq (const struct MmWaveMacSchedSapProvider::SchedUlCqiInfoReqParameters & params) private
Definition at line 450 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
References ns3::mmwave::SfnSf::Encode(), m_cqiTimersThreshold, ns3::mmwave::SfnSf::m_frameNum, ns3::mmwave::MmWaveMacScheduler::m_phyMacConfig, ns3::mmwave::MmWaveMacSchedSapProvider::SchedUlCqiInfoReqParameters::m_sfnSf, ns3::mmwave::SfnSf::m_sfNum, ns3::mmwave::UlCqiInfo::m_sinr, ns3::mmwave::SfnSf::m_slotNum, ns3::mmwave::UlCqiInfo::m_type, m_ueCqiTimers, m_ueUlCqi, m_ulAllocationMap, ns3::mmwave::MmWaveMacSchedSapProvider::SchedUlCqiInfoReqParameters::m_ulCqi, and ns3::mmwave::UlCqiInfo::PUSCH.
Referenced by BufferSize2BsrId(), and ns3::mmwave::MmWaveFlexTtiMaxRateMacSchedSapProvider::SchedUlCqiInfoReq().
DoSchedUlMacCtrlInfoReq()
void ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::DoSchedUlMacCtrlInfoReq (const struct MmWaveMacSchedSapProvider::SchedUlMacCtrlInfoReqParameters & params) private
Definition at line 349 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
References ns3::mmwave::MacCeElement::BSR, BsrId2BufferSize(), ns3::mmwave::MmWaveMacSchedSapProvider::SchedUlMacCtrlInfoReqParameters::m_macCeList, ns3::mmwave::MmWaveMacScheduler::m_phyMacConfig, and m_ueSchedInfoMap.
Referenced by BufferSize2BsrId(), and ns3::mmwave::MmWaveFlexTtiMaxRateMacSchedSapProvider::SchedUlMacCtrlInfoReq().
DoSchedUlTriggerReq()
bool ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::DoSchedUlTriggerReq (const struct MmWaveMacSchedSapProvider::SchedTriggerReqParameters & params, MmWaveMacSchedSapUser::SchedConfigIndParameters & ret, unsigned int frameNum, unsigned int sfNum, unsigned int islot) private
Referenced by BufferSize2BsrId().
GetMacCschedSapProvider()
MmWaveMacCschedSapProvider * ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::GetMacCschedSapProvider () override virtual
Implements ns3::mmwave::MmWaveMacScheduler.
Definition at line 266 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
References m_macCschedSapProvider.
GetMacSchedSapProvider()
MmWaveMacSchedSapProvider * ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::GetMacSchedSapProvider () override virtual
Implements ns3::mmwave::MmWaveMacScheduler.
Definition at line 260 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
References m_macSchedSapProvider.
GetTypeId()
TypeId ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::GetTypeId (void) static
Definition at line 186 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
References m_cqiTimersThreshold, m_dlOnly, m_fixedMcsDl, m_fixedMcsUl, m_fixedTti, m_harqOn, m_mcsDefaultDl, m_mcsDefaultUl, m_symPerSlot, and m_ulOnly.
RefreshDlCqiMaps()
void ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::RefreshDlCqiMaps (void)
Definition at line 1491 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
References m_cqiTimersThreshold, m_wbCqiRxed, and m_wbCqiTimers.
Referenced by DoSchedTriggerReq().
RefreshHarqProcesses()
void ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::RefreshHarqProcesses () private
Refresh HARQ processes according to the timers.
Definition at line 538 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
References m_dlHarqProcessesStatus, m_dlHarqProcessesTimer, ns3::mmwave::MmWaveMacScheduler::m_phyMacConfig, m_ulHarqProcessesStatus, and m_ulHarqProcessesTimer.
Referenced by BufferSize2BsrId(), and DoSchedTriggerReq().
RefreshUlCqiMaps()
void ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::RefreshUlCqiMaps (void)
Definition at line 1522 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
References m_cqiTimersThreshold, m_ueCqiTimers, and m_ueUlCqi.
Referenced by DoSchedTriggerReq().
SetMacCschedSapUser()
void ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::SetMacCschedSapUser (MmWaveMacCschedSapUser * s) override virtual
Implements ns3::mmwave::MmWaveMacScheduler.
Definition at line 253 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
References m_macCschedSapUser.
SetMacSchedSapUser()
void ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::SetMacSchedSapUser (MmWaveMacSchedSapUser * sap) override virtual
Implements ns3::mmwave::MmWaveMacScheduler.
Definition at line 247 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
References m_macSchedSapUser.
SortRlcBufferReq()
bool ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::SortRlcBufferReq (MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters i, MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters j) static
Definition at line 1484 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
References ns3::mmwave::MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters::m_rnti.
UpdateDlHarqProcessId()
uint8_t ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::UpdateDlHarqProcessId (uint16_t rnti) private
Definition at line 591 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
References m_dlHarqProcessesStatus, m_harqOn, ns3::mmwave::MmWaveMacScheduler::m_phyMacConfig, and m_tbUid.
Referenced by BufferSize2BsrId(), and DoSchedTriggerReq().
UpdateDlRlcBufferInfo()
void ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::UpdateDlRlcBufferInfo (uint16_t rnti, uint8_t lcid, uint16_t size)
Definition at line 1552 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
References m_rlcBufferReq.
Referenced by DoSchedTriggerReq().
UpdateUlHarqProcessId()
uint8_t ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::UpdateUlHarqProcessId (uint16_t rnti) private
Definition at line 647 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
References m_harqOn, ns3::mmwave::MmWaveMacScheduler::m_phyMacConfig, m_tbUid, and m_ulHarqProcessesStatus.
Referenced by BufferSize2BsrId(), and DoSchedTriggerReq().
UpdateUlRlcBufferInfo()
void ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::UpdateUlRlcBufferInfo (uint16_t rnti, uint16_t size)
Definition at line 1603 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
References m_ceBsrRxed.
Friends And Related Function Documentation
MmWaveFlexTtiMaxRateMacCschedSapProvider
friend class MmWaveFlexTtiMaxRateMacCschedSapProvider friend
Definition at line 63 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by MmWaveFlexTtiMaxRateMacScheduler().
MmWaveFlexTtiMaxRateMacSchedSapProvider
friend class MmWaveFlexTtiMaxRateMacSchedSapProvider friend
Definition at line 62 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by MmWaveFlexTtiMaxRateMacScheduler().
Member Data Documentation
m_amc
Ptr<MmWaveAmc> ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_amc private
Definition at line 297 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by CalcMinTbSizeNumSym(), ConfigureCommonParameters(), and DoSchedTriggerReq().
m_berDl
double ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_berDl private
Definition at line 411 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
m_ceBsrRxed
std::map<uint16_t,uint32_t> ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_ceBsrRxed private
Definition at line 340 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by DoCschedUeReleaseReq(), and UpdateUlRlcBufferInfo().
m_cqiTimersThreshold
uint32_t ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_cqiTimersThreshold private
Definition at line 313 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by DoSchedDlCqiInfoReq(), DoSchedUlCqiInfoReq(), GetTypeId(), RefreshDlCqiMaps(), and RefreshUlCqiMaps().
m_cschedCellConfig
MmWaveMacCschedSapProvider::CschedCellConfigReqParameters ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_cschedCellConfig private
Definition at line 356 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by DoCschedCellConfigReq().
m_dlHarqCurrentProcessId
std::map<uint16_t, uint8_t> ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_dlHarqCurrentProcessId private
Definition at line 385 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
m_dlHarqInfoList
std::vector<DlHarqInfo> ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_dlHarqInfoList private
Definition at line 393 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by DoDispose(), and DoSchedTriggerReq().
m_dlHarqProcessesDciInfoMap
std::map<uint16_t, DlHarqProcessesDciInfoList_t> ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_dlHarqProcessesDciInfoMap private
Definition at line 391 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by DoCschedUeConfigReq(), DoCschedUeReleaseReq(), DoDispose(), and DoSchedTriggerReq().
m_dlHarqProcessesRlcPduMap
std::map<uint16_t, DlHarqRlcPduList_t> ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_dlHarqProcessesRlcPduMap private
Definition at line 392 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by DoCschedUeConfigReq(), DoCschedUeReleaseReq(), DoDispose(), and DoSchedTriggerReq().
m_dlHarqProcessesStatus
std::map<uint16_t, DlHarqProcessesStatus_t> ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_dlHarqProcessesStatus private
Definition at line 389 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by DoCschedUeConfigReq(), DoCschedUeReleaseReq(), DoSchedTriggerReq(), RefreshHarqProcesses(), and UpdateDlHarqProcessId().
m_dlHarqProcessesTimer
std::map<uint16_t, DlHarqProcessesTimer_t> ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_dlHarqProcessesTimer private
Definition at line 390 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by DoCschedUeConfigReq(), DoCschedUeReleaseReq(), DoDispose(), DoSchedTriggerReq(), and RefreshHarqProcesses().
m_dlOnly
bool ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_dlOnly private
Definition at line 418 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by GetTypeId().
m_fixedMcsDl
bool ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_fixedMcsDl private
Definition at line 414 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by GetTypeId().
m_fixedMcsUl
bool ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_fixedMcsUl private
Definition at line 415 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by GetTypeId().
m_fixedTti
bool ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_fixedTti private
Definition at line 428 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by GetTypeId().
m_flowHeap
std::vector<FlowStats*> ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_flowHeap private
Definition at line 433 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by DoCschedLcConfigReq().
m_frameNo
uint32_t ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_frameNo private
Definition at line 346 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
m_harqOn
bool ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_harqOn private
m_harqOn when false inhibit te HARQ mechanisms (by default active)
Definition at line 381 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by DoSchedTriggerReq(), GetTypeId(), UpdateDlHarqProcessId(), and UpdateUlHarqProcessId().
m_harqTimeout
uint8_t ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_harqTimeout private
Definition at line 383 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by ConfigureCommonParameters().
m_macCschedSapProvider
MmWaveMacCschedSapProvider* ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_macCschedSapProvider private
Definition at line 354 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by DoDispose(), GetMacCschedSapProvider(), and MmWaveFlexTtiMaxRateMacScheduler().
m_macCschedSapUser
MmWaveMacCschedSapUser* ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_macCschedSapUser private
Definition at line 353 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by DoCschedCellConfigReq(), and SetMacCschedSapUser().
m_macHdrSize
const unsigned ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_macHdrSize = 0 static private
Definition at line 407 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by ns3::mmwave::MmWaveFlexTtiMaxRateMacSchedSapProvider::SchedSetMcs().
m_macSchedSapProvider
MmWaveMacSchedSapProvider* ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_macSchedSapProvider private
Definition at line 351 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by DoDispose(), GetMacSchedSapProvider(), and MmWaveFlexTtiMaxRateMacScheduler().
m_macSchedSapUser
MmWaveMacSchedSapUser* ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_macSchedSapUser private
Definition at line 352 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by DoSchedTriggerReq(), and SetMacSchedSapUser().
m_mcsDefaultDl
uint8_t ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_mcsDefaultDl private
Definition at line 416 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by DoSchedSetMcs(), and GetTypeId().
m_mcsDefaultUl
uint8_t ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_mcsDefaultUl private
Definition at line 417 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by DoSchedSetMcs(), and GetTypeId().
m_nextRnti
uint16_t ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_nextRnti private
Definition at line 342 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
m_nextRntiDl
uint64_t ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_nextRntiDl private
Definition at line 343 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by DoCschedUeReleaseReq().
m_nextRntiUl
uint64_t ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_nextRntiUl private
Definition at line 344 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by DoCschedUeReleaseReq().
m_numChunks
uint32_t ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_numChunks private
Definition at line 348 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
m_numDataSymbols
uint32_t ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_numDataSymbols private
Definition at line 349 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by ConfigureCommonParameters().
m_numHarqProcess
uint8_t ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_numHarqProcess private
Definition at line 382 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by ConfigureCommonParameters().
m_rlcBufferReq
std::list<MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters> ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_rlcBufferReq private
Definition at line 302 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by DoCschedLcReleaseReq(), DoCschedUeReleaseReq(), and UpdateDlRlcBufferInfo().
m_rlcHdrSize
const unsigned ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_rlcHdrSize = 3 static private
Definition at line 409 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by ns3::mmwave::MmWaveFlexTtiMaxRateMacSchedSapProvider::SchedSetMcs().
m_subHdrSize
const unsigned ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_subHdrSize = 4 static private
Definition at line 408 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by DoSchedTriggerReq(), and ns3::mmwave::MmWaveFlexTtiMaxRateMacSchedSapProvider::SchedSetMcs().
m_symPerSlot
uint8_t ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_symPerSlot private
Definition at line 429 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by GetTypeId().
m_tbUid
uint8_t ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_tbUid private
Definition at line 347 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by UpdateDlHarqProcessId(), and UpdateUlHarqProcessId().
m_timeWindow
double ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_timeWindow private
Definition at line 431 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by DoSchedTriggerReq().
m_ueCqiTimers
std::map<uint16_t, uint32_t> ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_ueCqiTimers private
Definition at line 335 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by DoSchedUlCqiInfoReq(), and RefreshUlCqiMaps().
m_ueSchedInfoHeap
std::vector<UeSchedInfo*> ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_ueSchedInfoHeap private
Definition at line 426 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
m_ueSchedInfoMap
std::map<uint16_t, UeSchedInfo> ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_ueSchedInfoMap private
Definition at line 425 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by DoCschedLcConfigReq(), DoCschedUeConfigReq(), DoCschedUeReleaseReq(), DoSchedDlRlcBufferReq(), DoSchedTriggerReq(), and DoSchedUlMacCtrlInfoReq().
m_ueStatHeap
std::vector<UeSchedInfo*> ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_ueStatHeap private
Definition at line 434 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by DoSchedTriggerReq().
m_ueUlCqi
std::map<uint16_t, struct UlCqiMapElem> ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_ueUlCqi private
Definition at line 331 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by DoSchedTriggerReq(), DoSchedUlCqiInfoReq(), and RefreshUlCqiMaps().
m_ulAllocationMap
std::map<uint32_t, struct AllocMapElem> ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_ulAllocationMap private
Definition at line 375 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by DoSchedTriggerReq(), and DoSchedUlCqiInfoReq().
m_ulHarqCurrentProcessId
std::map<uint16_t, uint8_t> ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_ulHarqCurrentProcessId private
Definition at line 396 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by DoDispose().
m_ulHarqInfoList
std::vector<UlHarqInfo> ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_ulHarqInfoList private
Definition at line 394 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by DoSchedTriggerReq().
m_ulHarqProcessesDciInfoMap
std::map<uint16_t, UlHarqProcessesDciInfoList_t> ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_ulHarqProcessesDciInfoMap private
Definition at line 402 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by DoCschedUeConfigReq(), DoCschedUeReleaseReq(), DoDispose(), and DoSchedTriggerReq().
m_ulHarqProcessesStatus
std::map<uint16_t, UlHarqProcessesStatus_t> ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_ulHarqProcessesStatus private
Definition at line 400 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by DoCschedUeConfigReq(), DoCschedUeReleaseReq(), DoDispose(), DoSchedTriggerReq(), RefreshHarqProcesses(), and UpdateUlHarqProcessId().
m_ulHarqProcessesTimer
std::map<uint16_t, UlHarqProcessesTimer_t> ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_ulHarqProcessesTimer private
Definition at line 401 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by DoCschedUeConfigReq(), DoCschedUeReleaseReq(), DoDispose(), DoSchedTriggerReq(), and RefreshHarqProcesses().
m_ulOnly
bool ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_ulOnly private
Definition at line 419 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by GetTypeId().
m_ulSfAllocInfo
std::list<struct SlotAllocInfo> ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_ulSfAllocInfo private
Definition at line 405 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
m_wbCqiRxed
std::map<uint16_t,uint8_t> ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_wbCqiRxed private
Definition at line 307 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by DoDispose(), DoSchedDlCqiInfoReq(), DoSchedTriggerReq(), and RefreshDlCqiMaps().
m_wbCqiTimers
std::map<uint16_t,uint32_t> ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_wbCqiTimers private
Definition at line 311 of file mmwave-flex-tti-maxrate-mac-scheduler.h.
Referenced by DoSchedDlCqiInfoReq(), and RefreshDlCqiMaps().
The documentation for this class was generated from the following files:
src/mmwave/model/mmwave-flex-tti-maxrate-mac-scheduler.h
src/mmwave/model/mmwave-flex-tti-maxrate-mac-scheduler.cc