ns3-mmwave: ns3::mmwave::MmWaveComponentCarrier Class Reference
ns3::mmwave::MmWaveComponentCarrier Class Reference
ComponentCarrier Object, it defines a single Carrier This is the parent class for both ComponentCarrierEnb and ComponentCarrierUe.
#include "mmwave-component-carrier.h"
Public Member Functions
MmWaveComponentCarrier ()
virtual ~MmWaveComponentCarrier (void)
virtual void DoDispose (void) override
Ptr< ThreeGppAntennaArrayModel > GetAntenna (void) const
Get the antenna used by the device in the component carrier.
uint32_t GetBandwidthInRb () const
double GetCenterFrequency () const
Ptr< MmWavePhyMacCommon > GetConfigurationParameters (void) const
uint32_t GetCsgId () const
Returns the CSG ID of the eNodeB.
bool GetCsgIndication () const
Returns the CSG indication flag of the eNodeB.
bool IsPrimary () const
Checks if the carrier is the primary carrier.
void SetAntenna (Ptr< ThreeGppAntennaArrayModel > antenna)
Set the antenna used by the device in the component carrier.
void SetAsPrimary (bool primaryCarrier)
Set as primary carrier.
void SetConfigurationParameters (Ptr< MmWavePhyMacCommon > ptrConfig)
void SetCsgId (uint32_t csgId)
Associate the eNodeB device with a particular CSG.
void SetCsgIndication (bool csgIndication)
Enable or disable the CSG indication flag.
Static Public Member Functions
static TypeId GetTypeId (void)
Get the type ID.
Protected Member Functions
virtual void DoInitialize (void) override
Protected Attributes
Ptr< ThreeGppAntennaArrayModel > m_antenna
the antenna used by the device in the component carrier
uint16_t m_csgId
CSG ID.
bool m_csgIndication
CSG indication.
bool m_isConstructed
whether the instance is constructed
Ptr< MmWavePhyMacCommon > m_phyMacConfig
bool m_primaryCarrier
whether the carrier is primary
Detailed Description
ComponentCarrier Object, it defines a single Carrier This is the parent class for both ComponentCarrierEnb and ComponentCarrierUe.
This class contains the main physical configuration parameters for a carrier. Does not contain pointers to the MAC/PHY objects of the carrier.
Definition at line 52 of file mmwave-component-carrier.h.
Constructor & Destructor Documentation
MmWaveComponentCarrier()
ns3::mmwave::MmWaveComponentCarrier::MmWaveComponentCarrier ()
Definition at line 79 of file mmwave-component-carrier.cc.
~MmWaveComponentCarrier()
ns3::mmwave::MmWaveComponentCarrier::~MmWaveComponentCarrier (void) virtual
Definition at line 85 of file mmwave-component-carrier.cc.
Member Function Documentation
DoDispose()
void ns3::mmwave::MmWaveComponentCarrier::DoDispose (void) override virtual
Reimplemented in ns3::mmwave::MmWaveComponentCarrierEnb, and ns3::mmwave::MmWaveComponentCarrierUe.
Definition at line 91 of file mmwave-component-carrier.cc.
References m_antenna.
Referenced by ns3::mmwave::MmWaveComponentCarrierUe::DoDispose(), and ns3::mmwave::MmWaveComponentCarrierEnb::DoDispose().
DoInitialize()
void ns3::mmwave::MmWaveComponentCarrier::DoInitialize (void) override protected virtual
Reimplemented in ns3::mmwave::MmWaveComponentCarrierEnb, and ns3::mmwave::MmWaveComponentCarrierUe.
Definition at line 150 of file mmwave-component-carrier.cc.
References m_isConstructed.
GetAntenna()
Ptr< ThreeGppAntennaArrayModel > ns3::mmwave::MmWaveComponentCarrier::GetAntenna (void) const
Get the antenna used by the device in the component carrier.
Returns
pointer to ThreeGppAntennaArrayModel object
Definition at line 179 of file mmwave-component-carrier.cc.
References m_antenna.
Referenced by GetTypeId().
GetBandwidthInRb()
uint32_t ns3::mmwave::MmWaveComponentCarrier::GetBandwidthInRb () const
Returns
the bandwidth in RBs
Definition at line 99 of file mmwave-component-carrier.cc.
References m_phyMacConfig.
GetCenterFrequency()
double ns3::mmwave::MmWaveComponentCarrier::GetCenterFrequency () const
Returns
the carrier frequency in Hz
Definition at line 105 of file mmwave-component-carrier.cc.
References m_phyMacConfig.
GetConfigurationParameters()
Ptr< MmWavePhyMacCommon > ns3::mmwave::MmWaveComponentCarrier::GetConfigurationParameters (void) const
Definition at line 164 of file mmwave-component-carrier.cc.
References m_phyMacConfig.
GetCsgId()
uint32_t ns3::mmwave::MmWaveComponentCarrier::GetCsgId () const
Returns the CSG ID of the eNodeB.
Returns
the Closed Subscriber Group identity
See also
LteEnbNetDevice::SetCsgId
Definition at line 111 of file mmwave-component-carrier.cc.
References m_csgId.
Referenced by GetTypeId().
GetCsgIndication()
bool ns3::mmwave::MmWaveComponentCarrier::GetCsgIndication () const
Returns the CSG indication flag of the eNodeB.
Returns
the CSG indication flag
See also
LteEnbNetDevice::SetCsgIndication
Definition at line 124 of file mmwave-component-carrier.cc.
References m_csgIndication.
Referenced by GetTypeId().
GetTypeId()
TypeId ns3::mmwave::MmWaveComponentCarrier::GetTypeId (void) static
Get the type ID.
Returns
the object TypeId
Definition at line 42 of file mmwave-component-carrier.cc.
References GetAntenna(), GetCsgId(), GetCsgIndication(), IsPrimary(), SetAntenna(), SetAsPrimary(), SetCsgId(), and SetCsgIndication().
IsPrimary()
bool ns3::mmwave::MmWaveComponentCarrier::IsPrimary () const
Checks if the carrier is the primary carrier.
Returns
true if the carrier is primary
Definition at line 137 of file mmwave-component-carrier.cc.
References m_primaryCarrier.
Referenced by GetTypeId().
SetAntenna()
void ns3::mmwave::MmWaveComponentCarrier::SetAntenna (Ptr< ThreeGppAntennaArrayModel > antenna)
Set the antenna used by the device in the component carrier.
Parameters
antenna pointer to ThreeGppAntennaArrayModel object
Definition at line 172 of file mmwave-component-carrier.cc.
References m_antenna.
Referenced by GetTypeId().
SetAsPrimary()
void ns3::mmwave::MmWaveComponentCarrier::SetAsPrimary (bool primaryCarrier)
Set as primary carrier.
Parameters
primaryCarrier true to set as primary carrier
Definition at line 143 of file mmwave-component-carrier.cc.
References m_primaryCarrier.
Referenced by GetTypeId().
SetConfigurationParameters()
void ns3::mmwave::MmWaveComponentCarrier::SetConfigurationParameters (Ptr< MmWavePhyMacCommon > ptrConfig)
Definition at line 157 of file mmwave-component-carrier.cc.
References m_phyMacConfig.
SetCsgId()
void ns3::mmwave::MmWaveComponentCarrier::SetCsgId (uint32_t csgId)
Associate the eNodeB device with a particular CSG.
Parameters
csgId the intended Closed Subscriber Group identity
CSG identity is a number identifying a Closed Subscriber Group which the cell belongs to. eNodeB is associated with a single CSG identity.
The same CSG identity can also be associated to several UEs, which is equivalent as enlisting these UEs as the members of this particular CSG.
See also
LteEnbNetDevice::SetCsgIndication
Definition at line 117 of file mmwave-component-carrier.cc.
References m_csgId.
Referenced by GetTypeId().
SetCsgIndication()
void ns3::mmwave::MmWaveComponentCarrier::SetCsgIndication (bool csgIndication)
Enable or disable the CSG indication flag.
Parameters
csgIndication if TRUE, only CSG members are allowed to access this cell
When the CSG indication field is set to TRUE, only UEs which are members of the CSG (i.e. same CSG ID) can gain access to the eNodeB, therefore enforcing closed access mode. Otherwise, the eNodeB operates as a non-CSG cell and implements open access mode.
Note
This restriction only applies to initial cell selection and EPC-enabled simulation.
See also
LteEnbNetDevice::SetCsgIndication
Definition at line 130 of file mmwave-component-carrier.cc.
References m_csgIndication.
Referenced by GetTypeId().
Member Data Documentation
m_antenna
Ptr<ThreeGppAntennaArrayModel> ns3::mmwave::MmWaveComponentCarrier::m_antenna protected
the antenna used by the device in the component carrier
Definition at line 160 of file mmwave-component-carrier.h.
Referenced by DoDispose(), GetAntenna(), and SetAntenna().
m_csgId
uint16_t ns3::mmwave::MmWaveComponentCarrier::m_csgId protected
CSG ID.
Definition at line 153 of file mmwave-component-carrier.h.
Referenced by GetCsgId(), and SetCsgId().
m_csgIndication
bool ns3::mmwave::MmWaveComponentCarrier::m_csgIndication protected
CSG indication.
Definition at line 154 of file mmwave-component-carrier.h.
Referenced by GetCsgIndication(), and SetCsgIndication().
m_isConstructed
bool ns3::mmwave::MmWaveComponentCarrier::m_isConstructed protected
whether the instance is constructed
Definition at line 157 of file mmwave-component-carrier.h.
Referenced by ns3::mmwave::MmWaveComponentCarrierUe::DoInitialize(), ns3::mmwave::MmWaveComponentCarrierEnb::DoInitialize(), and DoInitialize().
m_phyMacConfig
Ptr<MmWavePhyMacCommon> ns3::mmwave::MmWaveComponentCarrier::m_phyMacConfig protected
Definition at line 159 of file mmwave-component-carrier.h.
Referenced by GetBandwidthInRb(), GetCenterFrequency(), GetConfigurationParameters(), and SetConfigurationParameters().
m_primaryCarrier
bool ns3::mmwave::MmWaveComponentCarrier::m_primaryCarrier protected
whether the carrier is primary
Definition at line 156 of file mmwave-component-carrier.h.
Referenced by IsPrimary(), and SetAsPrimary().
The documentation for this class was generated from the following files:
src/mmwave/model/mmwave-component-carrier.h
src/mmwave/model/mmwave-component-carrier.cc