ns3-mmwave: ns3::mmwave::MmWavePhyTrace Class Reference
ns3::mmwave::MmWavePhyTrace Class Reference
#include "mmwave-phy-trace.h"
Public Member Functions
MmWavePhyTrace ()
virtual ~MmWavePhyTrace ()
void SetDlPhyTxOutputFilename (std::string fileName)
Sets the filename of the DL PHY tranmission traces.
void SetPhyRxOutputFilename (std::string fileName)
Sets the filename of the PHY reception traces.
void SetUlPhyTxOutputFilename (std::string fileName)
Sets the filename of the UL PHY tranmission traces.
Static Public Member Functions
static TypeId GetTypeId (void)
static void ReportCurrentCellRsrpSinrCallback (Ptr< MmWavePhyTrace > phyStats, std::string path, uint64_t imsi, SpectrumValue &sinr, SpectrumValue &power)
static void ReportDlPhyTransmissionCallback (Ptr< MmWavePhyTrace > phyStats, PhyTransmissionTraceParams param)
Callback used to trace a DL PHY tranmission.
static void ReportDownLinkTBSize (Ptr< MmWavePhyTrace > phyStats, std::string path, uint64_t imsi, uint64_t tbSize)
static void ReportUlPhyTransmissionCallback (Ptr< MmWavePhyTrace > phyStats, PhyTransmissionTraceParams param)
Callback used to trace an UL PHY tranmission.
static void RxPacketTraceEnbCallback (Ptr< MmWavePhyTrace > phyStats, std::string path, RxPacketTraceParams param)
static void RxPacketTraceUeCallback (Ptr< MmWavePhyTrace > phyStats, std::string path, RxPacketTraceParams param)
Static Private Attributes
static std::ofstream m_dlPhyTraceFile {}
Output stream for the DL PHY transmission trace.
static std::string m_dlPhyTraceFilename {}
Output filename for the DL PHY transmission trace.
static std::ofstream m_rxPacketTraceFile
Output stream for the PHY reception trace.
static std::string m_rxPacketTraceFilename
Output filename for the PHY reception trace.
static std::ofstream m_ulPhyTraceFile {}
Output stream for the UL PHY transmission trace.
static std::string m_ulPhyTraceFilename {}
Output filename for the UL PHY transmission trace.
Detailed Description
Definition at line 46 of file mmwave-phy-trace.h.
Constructor & Destructor Documentation
MmWavePhyTrace()
ns3::mmwave::MmWavePhyTrace::MmWavePhyTrace ()
Definition at line 58 of file mmwave-phy-trace.cc.
~MmWavePhyTrace()
ns3::mmwave::MmWavePhyTrace::~MmWavePhyTrace () virtual
Definition at line 62 of file mmwave-phy-trace.cc.
References m_rxPacketTraceFile.
Member Function Documentation
GetTypeId()
TypeId ns3::mmwave::MmWavePhyTrace::GetTypeId (void) static
Definition at line 71 of file mmwave-phy-trace.cc.
References SetDlPhyTxOutputFilename(), SetPhyRxOutputFilename(), and SetUlPhyTxOutputFilename().
ReportCurrentCellRsrpSinrCallback()
void ns3::mmwave::MmWavePhyTrace::ReportCurrentCellRsrpSinrCallback (Ptr< MmWavePhyTrace > phyStats, std::string path, uint64_t imsi, SpectrumValue & sinr, SpectrumValue & power) static
Definition at line 118 of file mmwave-phy-trace.cc.
ReportDlPhyTransmissionCallback()
void ns3::mmwave::MmWavePhyTrace::ReportDlPhyTransmissionCallback (Ptr< MmWavePhyTrace > phyStats, PhyTransmissionTraceParams param) static
Callback used to trace a DL PHY tranmission.
Definition at line 213 of file mmwave-phy-trace.cc.
References ns3::mmwave::PhyTransmissionTraceParams::m_ccId, m_dlPhyTraceFile, m_dlPhyTraceFilename, ns3::mmwave::PhyTransmissionTraceParams::m_frameNum, ns3::mmwave::PhyTransmissionTraceParams::m_numSym, ns3::mmwave::PhyTransmissionTraceParams::m_rnti, ns3::mmwave::PhyTransmissionTraceParams::m_rv, ns3::mmwave::PhyTransmissionTraceParams::m_sfNum, ns3::mmwave::PhyTransmissionTraceParams::m_slotNum, ns3::mmwave::PhyTransmissionTraceParams::m_symStart, ns3::mmwave::PhyTransmissionTraceParams::m_tddMode, and ns3::mmwave::PhyTransmissionTraceParams::m_ttiType.
Referenced by ns3::mmwave::MmWaveHelper::EnableDlPhyTrace().
ReportDownLinkTBSize()
void ns3::mmwave::MmWavePhyTrace::ReportDownLinkTBSize (Ptr< MmWavePhyTrace > phyStats, std::string path, uint64_t imsi, uint64_t tbSize) static
Definition at line 149 of file mmwave-phy-trace.cc.
Referenced by ns3::mmwave::MmWaveHelper::EnableTransportBlockTrace().
ReportUlPhyTransmissionCallback()
void ns3::mmwave::MmWavePhyTrace::ReportUlPhyTransmissionCallback (Ptr< MmWavePhyTrace > phyStats, PhyTransmissionTraceParams param) static
Callback used to trace an UL PHY tranmission.
Definition at line 192 of file mmwave-phy-trace.cc.
References ns3::mmwave::PhyTransmissionTraceParams::m_ccId, ns3::mmwave::PhyTransmissionTraceParams::m_frameNum, ns3::mmwave::PhyTransmissionTraceParams::m_numSym, ns3::mmwave::PhyTransmissionTraceParams::m_rnti, ns3::mmwave::PhyTransmissionTraceParams::m_rv, ns3::mmwave::PhyTransmissionTraceParams::m_sfNum, ns3::mmwave::PhyTransmissionTraceParams::m_slotNum, ns3::mmwave::PhyTransmissionTraceParams::m_symStart, ns3::mmwave::PhyTransmissionTraceParams::m_tddMode, ns3::mmwave::PhyTransmissionTraceParams::m_ttiType, m_ulPhyTraceFile, and m_ulPhyTraceFilename.
Referenced by ns3::mmwave::MmWaveHelper::EnableUlPhyTrace().
RxPacketTraceEnbCallback()
void ns3::mmwave::MmWavePhyTrace::RxPacketTraceEnbCallback (Ptr< MmWavePhyTrace > phyStats, std::string path, RxPacketTraceParams param) static
Definition at line 266 of file mmwave-phy-trace.cc.
References ns3::mmwave::RxPacketTraceParams::m_ccId, ns3::mmwave::RxPacketTraceParams::m_cellId, ns3::mmwave::RxPacketTraceParams::m_corrupt, ns3::mmwave::RxPacketTraceParams::m_frameNum, ns3::mmwave::RxPacketTraceParams::m_mcs, ns3::mmwave::RxPacketTraceParams::m_numSym, ns3::mmwave::RxPacketTraceParams::m_rnti, ns3::mmwave::RxPacketTraceParams::m_rv, m_rxPacketTraceFile, m_rxPacketTraceFilename, ns3::mmwave::RxPacketTraceParams::m_sfNum, ns3::mmwave::RxPacketTraceParams::m_sinr, ns3::mmwave::RxPacketTraceParams::m_sinrMin, ns3::mmwave::RxPacketTraceParams::m_slotNum, ns3::mmwave::RxPacketTraceParams::m_symStart, ns3::mmwave::RxPacketTraceParams::m_tbler, and ns3::mmwave::RxPacketTraceParams::m_tbSize.
Referenced by ns3::mmwave::MmWaveHelper::EnableUlPhyTrace().
RxPacketTraceUeCallback()
void ns3::mmwave::MmWavePhyTrace::RxPacketTraceUeCallback (Ptr< MmWavePhyTrace > phyStats, std::string path, RxPacketTraceParams param) static
Definition at line 234 of file mmwave-phy-trace.cc.
References ns3::mmwave::RxPacketTraceParams::m_ccId, ns3::mmwave::RxPacketTraceParams::m_cellId, ns3::mmwave::RxPacketTraceParams::m_corrupt, ns3::mmwave::RxPacketTraceParams::m_frameNum, ns3::mmwave::RxPacketTraceParams::m_mcs, ns3::mmwave::RxPacketTraceParams::m_numSym, ns3::mmwave::RxPacketTraceParams::m_rnti, ns3::mmwave::RxPacketTraceParams::m_rv, m_rxPacketTraceFile, m_rxPacketTraceFilename, ns3::mmwave::RxPacketTraceParams::m_sfNum, ns3::mmwave::RxPacketTraceParams::m_sinr, ns3::mmwave::RxPacketTraceParams::m_slotNum, ns3::mmwave::RxPacketTraceParams::m_symStart, ns3::mmwave::RxPacketTraceParams::m_tbler, and ns3::mmwave::RxPacketTraceParams::m_tbSize.
Referenced by ns3::mmwave::MmWaveHelper::EnableDlPhyTrace().
SetDlPhyTxOutputFilename()
void ns3::mmwave::MmWavePhyTrace::SetDlPhyTxOutputFilename (std::string fileName)
Sets the filename of the DL PHY tranmission traces.
Parameters
fileName the file name
Definition at line 111 of file mmwave-phy-trace.cc.
References m_dlPhyTraceFilename.
Referenced by GetTypeId().
SetPhyRxOutputFilename()
void ns3::mmwave::MmWavePhyTrace::SetPhyRxOutputFilename (std::string fileName)
Sets the filename of the PHY reception traces.
Parameters
fileName the file name
Definition at line 97 of file mmwave-phy-trace.cc.
References m_rxPacketTraceFilename.
Referenced by GetTypeId().
SetUlPhyTxOutputFilename()
void ns3::mmwave::MmWavePhyTrace::SetUlPhyTxOutputFilename (std::string fileName)
Sets the filename of the UL PHY tranmission traces.
Parameters
fileName the file name
Definition at line 104 of file mmwave-phy-trace.cc.
References m_ulPhyTraceFilename.
Referenced by GetTypeId().
Member Data Documentation
m_dlPhyTraceFile
std::ofstream ns3::mmwave::MmWavePhyTrace::m_dlPhyTraceFile {} static private
Output stream for the DL PHY transmission trace.
Definition at line 96 of file mmwave-phy-trace.h.
Referenced by ReportDlPhyTransmissionCallback().
m_dlPhyTraceFilename
std::string ns3::mmwave::MmWavePhyTrace::m_dlPhyTraceFilename {} static private
Output filename for the DL PHY transmission trace.
Definition at line 97 of file mmwave-phy-trace.h.
Referenced by ReportDlPhyTransmissionCallback(), and SetDlPhyTxOutputFilename().
m_rxPacketTraceFile
std::ofstream ns3::mmwave::MmWavePhyTrace::m_rxPacketTraceFile static private
Output stream for the PHY reception trace.
Definition at line 90 of file mmwave-phy-trace.h.
Referenced by RxPacketTraceEnbCallback(), RxPacketTraceUeCallback(), and ~MmWavePhyTrace().
m_rxPacketTraceFilename
std::string ns3::mmwave::MmWavePhyTrace::m_rxPacketTraceFilename static private
Output filename for the PHY reception trace.
Definition at line 91 of file mmwave-phy-trace.h.
Referenced by RxPacketTraceEnbCallback(), RxPacketTraceUeCallback(), and SetPhyRxOutputFilename().
m_ulPhyTraceFile
std::ofstream ns3::mmwave::MmWavePhyTrace::m_ulPhyTraceFile {} static private
Output stream for the UL PHY transmission trace.
Definition at line 93 of file mmwave-phy-trace.h.
Referenced by ReportUlPhyTransmissionCallback().
m_ulPhyTraceFilename
std::string ns3::mmwave::MmWavePhyTrace::m_ulPhyTraceFilename {} static private
Output filename for the UL PHY transmission trace.
Definition at line 94 of file mmwave-phy-trace.h.
Referenced by ReportUlPhyTransmissionCallback(), and SetUlPhyTxOutputFilename().
The documentation for this class was generated from the following files:
src/mmwave/helper/mmwave-phy-trace.h
src/mmwave/helper/mmwave-phy-trace.cc