ns3-mmwave: ns3::mmwave::MmWaveMacCschedSapUser Class Reference
ns3::mmwave::MmWaveMacCschedSapUser Class Reference abstract
#include "mmwave-mac-csched-sap.h"
Classes
struct CschedCellConfigCnfParameters
Parameters of the API primitives.
struct CschedCellConfigUpdateIndParameters
Parameters of the CSCHED_CELL_CONFIG_UPDATE_IND primitive.
struct CschedLcConfigCnfParameters
Parameters of the CSCHED_LC_CONFIG_CNF primitive.
struct CschedLcReleaseCnfParameters
Parameters of the CSCHED_LC_RELEASE_CNF primitive.
struct CschedUeConfigCnfParameters
Parameters of the CSCHED_UE_CONFIG_CNF primitive.
struct CschedUeConfigUpdateIndParameters
Parameters of the CSCHED_UE_CONFIG_UPDATE_IND primitive.
struct CschedUeReleaseCnfParameters
Parameters of the CSCHED_UE_RELEASE_CNF primitive.
Public Member Functions
virtual ~MmWaveMacCschedSapUser ()
virtual void CschedCellConfigCnf (const struct CschedCellConfigCnfParameters &params)=0
virtual void CschedCellConfigUpdateInd (const struct CschedCellConfigUpdateIndParameters &params)=0
virtual void CschedLcConfigCnf (const struct CschedLcConfigCnfParameters &params)=0
virtual void CschedLcReleaseCnf (const struct CschedLcReleaseCnfParameters &params)=0
virtual void CschedUeConfigCnf (const struct CschedUeConfigCnfParameters &params)=0
virtual void CschedUeConfigUpdateInd (const struct CschedUeConfigUpdateIndParameters &params)=0
virtual void CschedUeReleaseCnf (const struct CschedUeReleaseCnfParameters &params)=0
Detailed Description
Definition at line 259 of file mmwave-mac-csched-sap.h.
Constructor & Destructor Documentation
~MmWaveMacCschedSapUser()
ns3::mmwave::MmWaveMacCschedSapUser::~MmWaveMacCschedSapUser () virtual
Definition at line 39 of file mmwave-mac-csched-sap.cc.
Member Function Documentation
CschedCellConfigCnf()
virtual void ns3::mmwave::MmWaveMacCschedSapUser::CschedCellConfigCnf (const struct CschedCellConfigCnfParameters & params) pure virtual
Implemented in ns3::mmwave::MmWaveMacMemberMacCschedSapUser.
CschedCellConfigUpdateInd()
virtual void ns3::mmwave::MmWaveMacCschedSapUser::CschedCellConfigUpdateInd (const struct CschedCellConfigUpdateIndParameters & params) pure virtual
Implemented in ns3::mmwave::MmWaveMacMemberMacCschedSapUser.
CschedLcConfigCnf()
virtual void ns3::mmwave::MmWaveMacCschedSapUser::CschedLcConfigCnf (const struct CschedLcConfigCnfParameters & params) pure virtual
Implemented in ns3::mmwave::MmWaveMacMemberMacCschedSapUser.
CschedLcReleaseCnf()
virtual void ns3::mmwave::MmWaveMacCschedSapUser::CschedLcReleaseCnf (const struct CschedLcReleaseCnfParameters & params) pure virtual
Implemented in ns3::mmwave::MmWaveMacMemberMacCschedSapUser.
CschedUeConfigCnf()
virtual void ns3::mmwave::MmWaveMacCschedSapUser::CschedUeConfigCnf (const struct CschedUeConfigCnfParameters & params) pure virtual
Implemented in ns3::mmwave::MmWaveMacMemberMacCschedSapUser.
Referenced by ns3::mmwave::MmWaveFlexTtiMacScheduler::DoCschedCellConfigReq(), ns3::mmwave::MmWaveFlexTtiPfMacScheduler::DoCschedCellConfigReq(), ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::DoCschedCellConfigReq(), and ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::DoCschedCellConfigReq().
CschedUeConfigUpdateInd()
virtual void ns3::mmwave::MmWaveMacCschedSapUser::CschedUeConfigUpdateInd (const struct CschedUeConfigUpdateIndParameters & params) pure virtual
Implemented in ns3::mmwave::MmWaveMacMemberMacCschedSapUser.
CschedUeReleaseCnf()
virtual void ns3::mmwave::MmWaveMacCschedSapUser::CschedUeReleaseCnf (const struct CschedUeReleaseCnfParameters & params) pure virtual
Implemented in ns3::mmwave::MmWaveMacMemberMacCschedSapUser.
The documentation for this class was generated from the following files:
src/mmwave/model/mmwave-mac-csched-sap.h
src/mmwave/model/mmwave-mac-csched-sap.cc