ns3-mmwave: ns3::mmwave::MmWaveMacEnbMemberPhySapUser Class Reference
ns3::mmwave::MmWaveMacEnbMemberPhySapUser Class Reference
Public Member Functions
MmWaveMacEnbMemberPhySapUser (MmWaveEnbMac *mac)
virtual void ReceiveControlMessage (Ptr< MmWaveControlMessage > msg)
Receive SendLteControlMessage (PDCCH map, CQI feedbacks) using the ideal control channel.
virtual void ReceivePhyPdu (Ptr< Packet > p)
Called by the Phy to notify the MAC of the reception of a new PHY-PDU.
virtual void ReceiveRachPreamble (uint32_t raId)
notify the reception of a RACH preamble on the PRACH
virtual void SlotIndication (SfnSf snf)
Send from the PHY layer the current frame, subframe, slot numbers and the current starting OFDM symbol within the slot.
virtual void UlCqiReport (MmWaveMacSchedSapProvider::SchedUlCqiInfoReqParameters cqi)
Returns to MAC level the UL-CQI evaluated.
virtual void UlHarqFeedback (UlHarqInfo params)
Notify the HARQ on the UL tranmission status.
Public Member Functions inherited from ns3::mmwave::MmWaveEnbPhySapUser
virtual ~MmWaveEnbPhySapUser ()
Private Attributes
MmWaveEnbMac * m_mac
Detailed Description
Definition at line 146 of file mmwave-enb-mac.cc.
Constructor & Destructor Documentation
MmWaveMacEnbMemberPhySapUser()
ns3::mmwave::MmWaveMacEnbMemberPhySapUser::MmWaveMacEnbMemberPhySapUser (MmWaveEnbMac * mac)
Definition at line 167 of file mmwave-enb-mac.cc.
Member Function Documentation
ReceiveControlMessage()
void ns3::mmwave::MmWaveMacEnbMemberPhySapUser::ReceiveControlMessage (Ptr< MmWaveControlMessage > msg) virtual
Receive SendLteControlMessage (PDCCH map, CQI feedbacks) using the ideal control channel.
Parameters
msg the Ideal Control Message to receive
Implements ns3::mmwave::MmWaveEnbPhySapUser.
Definition at line 180 of file mmwave-enb-mac.cc.
References ns3::mmwave::MmWaveEnbMac::DoReceiveControlMessage(), and m_mac.
ReceivePhyPdu()
void ns3::mmwave::MmWaveMacEnbMemberPhySapUser::ReceivePhyPdu (Ptr< Packet > p) virtual
Called by the Phy to notify the MAC of the reception of a new PHY-PDU.
Parameters
p
Implements ns3::mmwave::MmWaveEnbPhySapUser.
Definition at line 174 of file mmwave-enb-mac.cc.
References ns3::mmwave::MmWaveEnbMac::DoReceivePhyPdu(), and m_mac.
ReceiveRachPreamble()
void ns3::mmwave::MmWaveMacEnbMemberPhySapUser::ReceiveRachPreamble (uint32_t raId) virtual
notify the reception of a RACH preamble on the PRACH
Parameters
raId the ID of the preamble
Implements ns3::mmwave::MmWaveEnbPhySapUser.
Definition at line 198 of file mmwave-enb-mac.cc.
References m_mac, and ns3::mmwave::MmWaveEnbMac::ReceiveRachPreamble().
SlotIndication()
void ns3::mmwave::MmWaveMacEnbMemberPhySapUser::SlotIndication (SfnSf snf) virtual
Send from the PHY layer the current frame, subframe, slot numbers and the current starting OFDM symbol within the slot.
Parameters
snf The current frame, subframe, slot and starting OFDM symbol counters
Implements ns3::mmwave::MmWaveEnbPhySapUser.
Definition at line 186 of file mmwave-enb-mac.cc.
References ns3::mmwave::MmWaveEnbMac::DoSlotIndication(), and m_mac.
UlCqiReport()
void ns3::mmwave::MmWaveMacEnbMemberPhySapUser::UlCqiReport (MmWaveMacSchedSapProvider::SchedUlCqiInfoReqParameters ulcqi) virtual
Returns to MAC level the UL-CQI evaluated.
Parameters
ulcqi the UL-CQI (see FF MAC API 4.3.29)
Implements ns3::mmwave::MmWaveEnbPhySapUser.
Definition at line 192 of file mmwave-enb-mac.cc.
References ns3::mmwave::MmWaveEnbMac::DoUlCqiReport(), and m_mac.
UlHarqFeedback()
void ns3::mmwave::MmWaveMacEnbMemberPhySapUser::UlHarqFeedback (UlHarqInfo params) virtual
Notify the HARQ on the UL tranmission status.
Parameters
params
Implements ns3::mmwave::MmWaveEnbPhySapUser.
Definition at line 204 of file mmwave-enb-mac.cc.
References ns3::mmwave::MmWaveEnbMac::DoUlHarqFeedback(), and m_mac.
Member Data Documentation
m_mac
MmWaveEnbMac* ns3::mmwave::MmWaveMacEnbMemberPhySapUser::m_mac private
Definition at line 164 of file mmwave-enb-mac.cc.
Referenced by ReceiveControlMessage(), ReceivePhyPdu(), ReceiveRachPreamble(), SlotIndication(), UlCqiReport(), and UlHarqFeedback().
The documentation for this class was generated from the following file:
src/mmwave/model/mmwave-enb-mac.cc