ns3-mmwave: ns3::mmwave::MmWaveUeNetDevice Class Reference
ns3::mmwave::MmWaveUeNetDevice Class Reference
#include "mmwave-ue-net-device.h"
Public Member Functions
MmWaveUeNetDevice (void)
virtual ~MmWaveUeNetDevice (void)
virtual void DoDispose () override
virtual bool DoSend (Ptr< Packet > packet, const Address &dest, uint16_t protocolNumber) override
Ptr< LteUeComponentCarrierManager > GetComponentCarrierManager (void) const
uint32_t GetCsgId () const
uint64_t GetImsi () const
Ptr< MmWaveUeMac > GetMac (void) const
Ptr< EpcUeNas > GetNas (void) const
Ptr< MmWaveUePhy > GetPhy (void) const
Ptr< MmWaveUePhy > GetPhy (uint8_t index) const
Ptr< LteUeRrc > GetRrc () const
Ptr< MmWaveEnbNetDevice > GetTargetEnb (void)
void SetCsgId (uint32_t csgId)
void SetTargetEnb (Ptr< MmWaveEnbNetDevice > enb)
void UpdateConfig (void)
Public Member Functions inherited from ns3::mmwave::MmWaveNetDevice
MmWaveNetDevice (void)
virtual ~MmWaveNetDevice (void)
virtual void AddLinkChangeCallback (Callback< void > callback) override
virtual Address GetAddress (void) const override
Ptr< ThreeGppAntennaArrayModel > GetAntenna (uint8_t ccId) const
Get the antenna for the component carrier.
virtual uint16_t GetAntennaNum () const
virtual Address GetBroadcast (void) const override
virtual std::map< uint8_t, Ptr< MmWaveComponentCarrier > > GetCcMap () const
virtual Ptr< Channel > GetChannel (void) const override
virtual uint16_t GetEarfcn () const
virtual uint32_t GetIfIndex (void) const override
virtual uint16_t GetMtu (void) const override
virtual Address GetMulticast (Ipv4Address multicastGroup) const override
virtual Address GetMulticast (Ipv6Address addr) const override
virtual Ptr< Node > GetNode (void) const override
Ipv4Address GetPacketDestination (Ptr< Packet > packet)
virtual bool IsBridge (void) const override
virtual bool IsBroadcast (void) const override
virtual bool IsLinkUp (void) const override
virtual bool IsMulticast (void) const override
virtual bool IsPointToPoint (void) const override
virtual bool NeedsArp (void) const override
void Receive (Ptr< Packet > p)
virtual bool Send (Ptr< Packet > packet, const Address &dest, uint16_t protocolNumber) override
virtual bool SendFrom (Ptr< Packet > packet, const Address &source, const Address &dest, uint16_t protocolNumber) override
virtual void SetAddress (Address address) override
virtual void SetAntennaNum (uint16_t antennaNum)
virtual void SetCcMap (std::map< uint8_t, Ptr< MmWaveComponentCarrier > > ccm)
virtual void SetEarfcn (uint16_t earfcn)
virtual void SetIfIndex (const uint32_t index) override
virtual bool SetMtu (const uint16_t mtu) override
virtual void SetNode (Ptr< Node > node) override
virtual void SetPromiscReceiveCallback (PromiscReceiveCallback cb) override
virtual void SetReceiveCallback (ReceiveCallback cb) override
virtual bool SupportsSendFrom (void) const override
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::mmwave::MmWaveNetDevice
static TypeId GetTypeId (void)
Protected Member Functions
virtual void DoInitialize (void) override
Private Member Functions
MmWaveUeNetDevice (const MmWaveUeNetDevice &)
Private Attributes
Ptr< LteUeComponentCarrierManager > m_componentCarrierManager
the component carrier manager
uint32_t m_csgId
uint64_t m_imsi
Ptr< EpcUeNas > m_nas
Ptr< LteUeRrc > m_rrc
Ptr< MmWaveEnbNetDevice > m_targetEnb
Additional Inherited Members
Protected Attributes inherited from ns3::mmwave::MmWaveNetDevice
uint16_t m_antennaNum
Number of antenna elements for the device.
std::map< uint8_t, Ptr< MmWaveComponentCarrier > > m_ccMap
ComponentCarrier map.
uint16_t m_earfcn
Carrier frequency.
bool m_isConstructed
indicates if the object has been initialized
NetDevice::ReceiveCallback m_rxCallback
Detailed Description
Definition at line 60 of file mmwave-ue-net-device.h.
Constructor & Destructor Documentation
MmWaveUeNetDevice() [1/2]
ns3::mmwave::MmWaveUeNetDevice::MmWaveUeNetDevice (void)
Definition at line 103 of file mmwave-ue-net-device.cc.
~MmWaveUeNetDevice()
ns3::mmwave::MmWaveUeNetDevice::~MmWaveUeNetDevice (void) virtual
Definition at line 108 of file mmwave-ue-net-device.cc.
MmWaveUeNetDevice() [2/2]
ns3::mmwave::MmWaveUeNetDevice::MmWaveUeNetDevice (const MmWaveUeNetDevice &) private
Member Function Documentation
DoDispose()
void ns3::mmwave::MmWaveUeNetDevice::DoDispose (void) override virtual
Reimplemented from ns3::mmwave::MmWaveNetDevice.
Definition at line 130 of file mmwave-ue-net-device.cc.
References ns3::mmwave::MmWaveNetDevice::m_ccMap, m_componentCarrierManager, m_nas, m_rrc, and m_targetEnb.
DoInitialize()
void ns3::mmwave::MmWaveUeNetDevice::DoInitialize (void) override protected virtual
Definition at line 114 of file mmwave-ue-net-device.cc.
References ns3::mmwave::MmWaveNetDevice::m_ccMap, ns3::mmwave::MmWaveNetDevice::m_isConstructed, m_rrc, and UpdateConfig().
DoSend()
bool ns3::mmwave::MmWaveUeNetDevice::DoSend (Ptr< Packet > packet, const Address & dest, uint16_t protocolNumber) override virtual
Implements ns3::mmwave::MmWaveNetDevice.
Definition at line 186 of file mmwave-ue-net-device.cc.
References m_nas.
GetComponentCarrierManager()
Ptr< LteUeComponentCarrierManager > ns3::mmwave::MmWaveUeNetDevice::GetComponentCarrierManager (void) const
Definition at line 211 of file mmwave-ue-net-device.cc.
References m_componentCarrierManager.
GetCsgId()
uint32_t ns3::mmwave::MmWaveUeNetDevice::GetCsgId () const
Definition at line 149 of file mmwave-ue-net-device.cc.
References m_csgId.
GetImsi()
uint64_t ns3::mmwave::MmWaveUeNetDevice::GetImsi () const
Definition at line 240 of file mmwave-ue-net-device.cc.
References m_imsi.
Referenced by ns3::mmwave::MmWaveHelper::AttachToEnbWithIndex().
GetMac()
Ptr< MmWaveUeMac > ns3::mmwave::MmWaveUeNetDevice::GetMac (void) const
Definition at line 218 of file mmwave-ue-net-device.cc.
References ns3::mmwave::MmWaveNetDevice::m_ccMap.
GetNas()
Ptr< EpcUeNas > ns3::mmwave::MmWaveUeNetDevice::GetNas (void) const
Definition at line 225 of file mmwave-ue-net-device.cc.
References m_nas.
GetPhy() [1/2]
Ptr< MmWaveUePhy > ns3::mmwave::MmWaveUeNetDevice::GetPhy (void) const
Definition at line 197 of file mmwave-ue-net-device.cc.
References ns3::mmwave::MmWaveNetDevice::m_ccMap.
Referenced by GetPhy(), and ns3::mmwave::MmWaveEnbPhy::SendDataChannels().
GetPhy() [2/2]
Ptr< MmWaveUePhy > ns3::mmwave::MmWaveUeNetDevice::GetPhy (uint8_t index) const
Definition at line 204 of file mmwave-ue-net-device.cc.
References GetPhy(), and ns3::mmwave::MmWaveNetDevice::m_ccMap.
GetRrc()
Ptr< LteUeRrc > ns3::mmwave::MmWaveUeNetDevice::GetRrc (void) const
Definition at line 233 of file mmwave-ue-net-device.cc.
References m_rrc.
Referenced by ns3::mmwave::MmWaveEnbRrcProtocolIdeal::DoSendSystemInformation(), and ns3::mmwave::MmWaveLteEnbRrcProtocolReal::DoSendSystemInformation().
GetTargetEnb()
Ptr< MmWaveEnbNetDevice > ns3::mmwave::MmWaveUeNetDevice::GetTargetEnb (void)
Definition at line 254 of file mmwave-ue-net-device.cc.
References m_targetEnb.
GetTypeId()
TypeId ns3::mmwave::MmWaveUeNetDevice::GetTypeId (void) static
Definition at line 67 of file mmwave-ue-net-device.cc.
References m_componentCarrierManager, m_imsi, m_nas, and m_rrc.
Referenced by ns3::mmwave::MmWaveHelper::MmWaveHelper().
SetCsgId()
void ns3::mmwave::MmWaveUeNetDevice::SetCsgId (uint32_t csgId)
Definition at line 156 of file mmwave-ue-net-device.cc.
References m_csgId, and UpdateConfig().
SetTargetEnb()
void ns3::mmwave::MmWaveUeNetDevice::SetTargetEnb (Ptr< MmWaveEnbNetDevice > enb)
Definition at line 247 of file mmwave-ue-net-device.cc.
References m_targetEnb.
UpdateConfig()
void ns3::mmwave::MmWaveUeNetDevice::UpdateConfig (void)
Definition at line 164 of file mmwave-ue-net-device.cc.
References m_csgId, m_imsi, ns3::mmwave::MmWaveNetDevice::m_isConstructed, m_nas, and m_rrc.
Referenced by DoInitialize(), and SetCsgId().
Member Data Documentation
m_componentCarrierManager
Ptr<LteUeComponentCarrierManager> ns3::mmwave::MmWaveUeNetDevice::m_componentCarrierManager private
the component carrier manager
Definition at line 106 of file mmwave-ue-net-device.h.
Referenced by DoDispose(), GetComponentCarrierManager(), and GetTypeId().
m_csgId
uint32_t ns3::mmwave::MmWaveUeNetDevice::m_csgId private
Definition at line 110 of file mmwave-ue-net-device.h.
Referenced by GetCsgId(), SetCsgId(), and UpdateConfig().
m_imsi
uint64_t ns3::mmwave::MmWaveUeNetDevice::m_imsi private
Definition at line 108 of file mmwave-ue-net-device.h.
Referenced by GetImsi(), GetTypeId(), and UpdateConfig().
m_nas
Ptr<EpcUeNas> ns3::mmwave::MmWaveUeNetDevice::m_nas private
Definition at line 105 of file mmwave-ue-net-device.h.
Referenced by DoDispose(), DoSend(), GetNas(), GetTypeId(), and UpdateConfig().
m_rrc
Ptr<LteUeRrc> ns3::mmwave::MmWaveUeNetDevice::m_rrc private
Definition at line 104 of file mmwave-ue-net-device.h.
Referenced by DoDispose(), DoInitialize(), GetRrc(), GetTypeId(), and UpdateConfig().
m_targetEnb
Ptr<MmWaveEnbNetDevice> ns3::mmwave::MmWaveUeNetDevice::m_targetEnb private
Definition at line 102 of file mmwave-ue-net-device.h.
Referenced by DoDispose(), GetTargetEnb(), and SetTargetEnb().
The documentation for this class was generated from the following files:
src/mmwave/model/mmwave-ue-net-device.h
src/mmwave/model/mmwave-ue-net-device.cc