ns3-mmwave: ns3::mmwave::MmWaveFlexTtiMaxRateMacSchedSapProvider Class Reference
ns3::mmwave::MmWaveFlexTtiMaxRateMacSchedSapProvider Class Reference
Public Member Functions
MmWaveFlexTtiMaxRateMacSchedSapProvider (MmWaveFlexTtiMaxRateMacScheduler *sched)
virtual void SchedDlCqiInfoReq (const struct MmWaveMacSchedSapProvider::SchedDlCqiInfoReqParameters &params)
virtual void SchedDlRlcBufferReq (const struct MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters &params)
virtual void SchedSetMcs (int mcs)
virtual void SchedTriggerReq (const struct MmWaveMacSchedSapProvider::SchedTriggerReqParameters &params)
virtual void SchedUlCqiInfoReq (const struct MmWaveMacSchedSapProvider::SchedUlCqiInfoReqParameters &params)
virtual void SchedUlMacCtrlInfoReq (const struct MmWaveMacSchedSapProvider::SchedUlMacCtrlInfoReqParameters &params)
Public Member Functions inherited from ns3::mmwave::MmWaveMacSchedSapProvider
virtual ~MmWaveMacSchedSapProvider ()
virtual void SchedDlCqiInfoReq (const SchedDlCqiInfoReqParameters &params)=0
Private Member Functions
MmWaveFlexTtiMaxRateMacSchedSapProvider ()
Private Attributes
MmWaveFlexTtiMaxRateMacScheduler * m_scheduler
Detailed Description
Definition at line 86 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
Constructor & Destructor Documentation
MmWaveFlexTtiMaxRateMacSchedSapProvider() [1/2]
ns3::mmwave::MmWaveFlexTtiMaxRateMacSchedSapProvider::MmWaveFlexTtiMaxRateMacSchedSapProvider (MmWaveFlexTtiMaxRateMacScheduler * sched)
Definition at line 106 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
MmWaveFlexTtiMaxRateMacSchedSapProvider() [2/2]
ns3::mmwave::MmWaveFlexTtiMaxRateMacSchedSapProvider::MmWaveFlexTtiMaxRateMacSchedSapProvider () private
Definition at line 102 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
Member Function Documentation
SchedDlCqiInfoReq()
void ns3::mmwave::MmWaveFlexTtiMaxRateMacSchedSapProvider::SchedDlCqiInfoReq (const struct MmWaveMacSchedSapProvider::SchedDlCqiInfoReqParameters & params) virtual
Definition at line 124 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::DoSchedDlCqiInfoReq(), and m_scheduler.
SchedDlRlcBufferReq()
void ns3::mmwave::MmWaveFlexTtiMaxRateMacSchedSapProvider::SchedDlRlcBufferReq (const struct MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters & params) virtual
Implements ns3::mmwave::MmWaveMacSchedSapProvider.
Definition at line 112 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::DoSchedDlRlcBufferReq(), and m_scheduler.
SchedSetMcs()
void ns3::mmwave::MmWaveFlexTtiMaxRateMacSchedSapProvider::SchedSetMcs (int mcs) virtual
Reimplemented from ns3::mmwave::MmWaveMacSchedSapProvider.
Definition at line 142 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::DoSchedSetMcs(), ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_macHdrSize, ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_rlcHdrSize, m_scheduler, and ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::m_subHdrSize.
SchedTriggerReq()
void ns3::mmwave::MmWaveFlexTtiMaxRateMacSchedSapProvider::SchedTriggerReq (const struct MmWaveMacSchedSapProvider::SchedTriggerReqParameters & params) virtual
Implements ns3::mmwave::MmWaveMacSchedSapProvider.
Definition at line 118 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::DoSchedTriggerReq(), and m_scheduler.
SchedUlCqiInfoReq()
void ns3::mmwave::MmWaveFlexTtiMaxRateMacSchedSapProvider::SchedUlCqiInfoReq (const struct MmWaveMacSchedSapProvider::SchedUlCqiInfoReqParameters & params) virtual
Implements ns3::mmwave::MmWaveMacSchedSapProvider.
Definition at line 130 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::DoSchedUlCqiInfoReq(), and m_scheduler.
SchedUlMacCtrlInfoReq()
void ns3::mmwave::MmWaveFlexTtiMaxRateMacSchedSapProvider::SchedUlMacCtrlInfoReq (const struct MmWaveMacSchedSapProvider::SchedUlMacCtrlInfoReqParameters & params) virtual
Implements ns3::mmwave::MmWaveMacSchedSapProvider.
Definition at line 136 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::DoSchedUlMacCtrlInfoReq(), and m_scheduler.
Member Data Documentation
m_scheduler
MmWaveFlexTtiMaxRateMacScheduler* ns3::mmwave::MmWaveFlexTtiMaxRateMacSchedSapProvider::m_scheduler private
Definition at line 99 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
Referenced by SchedDlCqiInfoReq(), SchedDlRlcBufferReq(), SchedSetMcs(), SchedTriggerReq(), SchedUlCqiInfoReq(), and SchedUlMacCtrlInfoReq().
The documentation for this class was generated from the following file:
src/mmwave/model/mmwave-flex-tti-maxrate-mac-scheduler.cc