ns3-mmwave: ns3::mmwave::MmWaveMacSchedSapUser Class Reference
ns3::mmwave::MmWaveMacSchedSapUser Class Reference abstract
#include "mmwave-mac-sched-sap.h"
Classes
struct SchedConfigIndParameters
Public Member Functions
virtual ~MmWaveMacSchedSapUser ()
virtual void SchedConfigInd (const struct SchedConfigIndParameters &params)=0
Detailed Description
Definition at line 105 of file mmwave-mac-sched-sap.h.
Constructor & Destructor Documentation
~MmWaveMacSchedSapUser()
ns3::mmwave::MmWaveMacSchedSapUser::~MmWaveMacSchedSapUser () virtual
Definition at line 41 of file mmwave-mac-sched-sap.cc.
Member Function Documentation
SchedConfigInd()
virtual void ns3::mmwave::MmWaveMacSchedSapUser::SchedConfigInd (const struct SchedConfigIndParameters & params) pure virtual
Implemented in ns3::mmwave::MmWaveMacMemberMacSchedSapUser.
Referenced by ns3::mmwave::MmWaveFlexTtiMacScheduler::DoSchedTriggerReq(), ns3::mmwave::MmWaveFlexTtiPfMacScheduler::DoSchedTriggerReq(), ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::DoSchedTriggerReq(), and ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::DoSchedTriggerReq().
The documentation for this class was generated from the following files:
src/mmwave/model/mmwave-mac-sched-sap.h
src/mmwave/model/mmwave-mac-sched-sap.cc