ns3-mmwave: ns3::mmwave::MmWaveMacPduTag Class Reference
ns3::mmwave::MmWaveMacPduTag Class Reference
#include "mmwave-mac-pdu-tag.h"
Public Member Functions
MmWaveMacPduTag (SfnSf sfn=SfnSf(), uint8_t numSym=0)
virtual void Deserialize (TagBuffer i)
virtual TypeId GetInstanceTypeId (void) const
virtual uint32_t GetSerializedSize () const
SfnSf GetSfn () const
virtual void Print (std::ostream &os) const
virtual void Serialize (TagBuffer i) const
void SetNumSym (uint8_t numSym)
void SetSfn (SfnSf sfn)
Static Public Member Functions
static TypeId GetTypeId (void)
Protected Attributes
uint8_t m_numSym
SfnSf m_sfnSf
uint32_t m_tagSize
Detailed Description
Definition at line 44 of file mmwave-mac-pdu-tag.h.
Constructor & Destructor Documentation
MmWaveMacPduTag()
ns3::mmwave::MmWaveMacPduTag::MmWaveMacPduTag (SfnSf sfn = SfnSf (), uint8_t numSym = 0)
Definition at line 41 of file mmwave-mac-pdu-tag.cc.
Member Function Documentation
Deserialize()
void ns3::mmwave::MmWaveMacPduTag::Deserialize (TagBuffer i) virtual
Definition at line 80 of file mmwave-mac-pdu-tag.cc.
References ns3::mmwave::SfnSf::m_frameNum, m_numSym, m_sfnSf, ns3::mmwave::SfnSf::m_sfNum, ns3::mmwave::SfnSf::m_slotNum, ns3::mmwave::SfnSf::m_symStart, and m_tagSize.
GetInstanceTypeId()
TypeId ns3::mmwave::MmWaveMacPduTag::GetInstanceTypeId (void) const virtual
Definition at line 58 of file mmwave-mac-pdu-tag.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::mmwave::MmWaveMacPduTag::GetSerializedSize (void) const virtual
Definition at line 64 of file mmwave-mac-pdu-tag.cc.
References m_tagSize.
GetSfn()
SfnSf ns3::mmwave::MmWaveMacPduTag::GetSfn () const inline
Definition at line 57 of file mmwave-mac-pdu-tag.h.
References m_sfnSf.
Referenced by ns3::mmwave::MmWaveUeMac::DoTransmitPdu(), ns3::mmwave::MmWaveSpectrumPhy::EndRxData(), ns3::mmwave::MmWavePhy::SetMacPdu(), ns3::mmwave::MmWaveEnbPhy::StartTti(), and ns3::mmwave::MmWaveUePhy::StartTti().
GetTypeId()
TypeId ns3::mmwave::MmWaveMacPduTag::GetTypeId (void) static
Definition at line 49 of file mmwave-mac-pdu-tag.cc.
Referenced by GetInstanceTypeId().
Print()
void ns3::mmwave::MmWaveMacPduTag::Print (std::ostream & os) const virtual
Definition at line 91 of file mmwave-mac-pdu-tag.cc.
References m_sfnSf, ns3::mmwave::SfnSf::m_sfNum, and ns3::mmwave::SfnSf::m_slotNum.
Serialize()
void ns3::mmwave::MmWaveMacPduTag::Serialize (TagBuffer i) const virtual
Definition at line 70 of file mmwave-mac-pdu-tag.cc.
References ns3::mmwave::SfnSf::m_frameNum, m_numSym, m_sfnSf, ns3::mmwave::SfnSf::m_sfNum, ns3::mmwave::SfnSf::m_slotNum, and ns3::mmwave::SfnSf::m_symStart.
SetNumSym()
void ns3::mmwave::MmWaveMacPduTag::SetNumSym (uint8_t numSym) inline
Definition at line 67 of file mmwave-mac-pdu-tag.h.
References m_numSym.
Referenced by ns3::mmwave::MmWaveEnbMac::DoSchedConfigIndication().
SetSfn()
void ns3::mmwave::MmWaveMacPduTag::SetSfn (SfnSf sfn) inline
Definition at line 62 of file mmwave-mac-pdu-tag.h.
References m_sfnSf.
Referenced by ns3::mmwave::MmWaveUeMac::DoReceiveControlMessage(), and ns3::mmwave::MmWaveEnbMac::DoSchedConfigIndication().
Member Data Documentation
m_numSym
uint8_t ns3::mmwave::MmWaveMacPduTag::m_numSym protected
Definition at line 74 of file mmwave-mac-pdu-tag.h.
Referenced by Deserialize(), Serialize(), and SetNumSym().
m_sfnSf
SfnSf ns3::mmwave::MmWaveMacPduTag::m_sfnSf protected
Definition at line 73 of file mmwave-mac-pdu-tag.h.
Referenced by Deserialize(), GetSfn(), Print(), Serialize(), and SetSfn().
m_tagSize
uint32_t ns3::mmwave::MmWaveMacPduTag::m_tagSize protected
Definition at line 75 of file mmwave-mac-pdu-tag.h.
Referenced by Deserialize(), and GetSerializedSize().
The documentation for this class was generated from the following files:
src/mmwave/model/mmwave-mac-pdu-tag.h
src/mmwave/model/mmwave-mac-pdu-tag.cc