ns3-mmwave: ns3::mmwave::MmWaveAmc Class Reference
ns3::mmwave::MmWaveAmc Class Reference
#include "mmwave-amc.h"
Public Types
enum AmcModel { PiroEW2010, MiErrorModel }
Public Member Functions
MmWaveAmc ()
MmWaveAmc (Ptr< MmWavePhyMacCommon > ConfigParams)
virtual ~MmWaveAmc ()
std::vector< int > CreateCqiFeedbacks (const SpectrumValue &sinr, uint8_t rbgSize)
std::vector< int > CreateCqiFeedbacksTdma (const SpectrumValue &sinr, uint8_t numSym)
int CreateCqiFeedbackWbTdma (const SpectrumValue &sinr, uint8_t numSym, uint32_t tbs, int &mcsWb)
int GetCqiFromSpectralEfficiency (double s)
int GetMcsFromCqi (int cqi)
int GetMcsFromSpectralEfficiency (double s)
int GetNumSymbolsFromTbsMcs (unsigned tbSize, unsigned mcs)
int GetTbSizeFromMcs (unsigned mcs, unsigned nprb)
int GetTbSizeFromMcsSymbols (unsigned mcs, unsigned nsym)
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Attributes
static const unsigned int m_crcLen = 24
Private Attributes
AmcModel m_amcModel
double m_ber
Ptr< SpectrumModel > m_lteRbModel
Ptr< MmWavePhyMacCommon > m_phyMacConfig
Detailed Description
Definition at line 40 of file mmwave-amc.h.
Member Enumeration Documentation
AmcModel
enum ns3::mmwave::MmWaveAmc::AmcModel
Enumerator
PiroEW2010
MiErrorModel
Definition at line 47 of file mmwave-amc.h.
Constructor & Destructor Documentation
MmWaveAmc() [1/2]
ns3::mmwave::MmWaveAmc::MmWaveAmc ()
Definition at line 111 of file mmwave-amc.cc.
MmWaveAmc() [2/2]
ns3::mmwave::MmWaveAmc::MmWaveAmc (Ptr< MmWavePhyMacCommon > ConfigParams)
Definition at line 116 of file mmwave-amc.cc.
~MmWaveAmc()
ns3::mmwave::MmWaveAmc::~MmWaveAmc () virtual
Definition at line 122 of file mmwave-amc.cc.
Member Function Documentation
CreateCqiFeedbacks()
std::vector< int > ns3::mmwave::MmWaveAmc::CreateCqiFeedbacks (const SpectrumValue & sinr, uint8_t rbgSize)
Definition at line 229 of file mmwave-amc.cc.
References GetCqiFromSpectralEfficiency(), ns3::mmwave::MmWaveMiErrorModel::GetTbDecodificationStats(), GetTbSizeFromMcs(), m_amcModel, m_ber, MiErrorModel, PiroEW2010, and ns3::mmwave::MmWaveTbStats_t::tbler.
CreateCqiFeedbacksTdma()
std::vector< int > ns3::mmwave::MmWaveAmc::CreateCqiFeedbacksTdma (const SpectrumValue & sinr, uint8_t numSym)
Definition at line 329 of file mmwave-amc.cc.
References GetCqiFromSpectralEfficiency(), ns3::mmwave::MmWaveMiErrorModel::GetTbDecodificationStats(), GetTbSizeFromMcsSymbols(), m_amcModel, m_ber, MiErrorModel, PiroEW2010, and ns3::mmwave::MmWaveTbStats_t::tbler.
CreateCqiFeedbackWbTdma()
int ns3::mmwave::MmWaveAmc::CreateCqiFeedbackWbTdma (const SpectrumValue & sinr, uint8_t numSym, uint32_t tbs, int & mcsWb)
Definition at line 420 of file mmwave-amc.cc.
References GetCqiFromSpectralEfficiency(), GetMcsFromSpectralEfficiency(), ns3::mmwave::MmWaveMiErrorModel::GetTbDecodificationStats(), m_amcModel, m_ber, MiErrorModel, PiroEW2010, and ns3::mmwave::MmWaveTbStats_t::tbler.
GetCqiFromSpectralEfficiency()
int ns3::mmwave::MmWaveAmc::GetCqiFromSpectralEfficiency (double s)
Definition at line 530 of file mmwave-amc.cc.
Referenced by CreateCqiFeedbacks(), CreateCqiFeedbacksTdma(), and CreateCqiFeedbackWbTdma().
GetMcsFromCqi()
int ns3::mmwave::MmWaveAmc::GetMcsFromCqi (int cqi)
Definition at line 149 of file mmwave-amc.cc.
GetMcsFromSpectralEfficiency()
int ns3::mmwave::MmWaveAmc::GetMcsFromSpectralEfficiency (double s)
Definition at line 544 of file mmwave-amc.cc.
Referenced by CreateCqiFeedbackWbTdma().
GetNumSymbolsFromTbsMcs()
int ns3::mmwave::MmWaveAmc::GetNumSymbolsFromTbsMcs (unsigned tbSize, unsigned mcs)
Definition at line 208 of file mmwave-amc.cc.
References m_crcLen, m_phyMacConfig, and ns3::mmwave::McsEcrTable.
GetTbSizeFromMcs()
int ns3::mmwave::MmWaveAmc::GetTbSizeFromMcs (unsigned mcs, unsigned nprb)
Definition at line 165 of file mmwave-amc.cc.
References m_crcLen, and m_phyMacConfig.
Referenced by CreateCqiFeedbacks().
GetTbSizeFromMcsSymbols()
int ns3::mmwave::MmWaveAmc::GetTbSizeFromMcsSymbols (unsigned mcs, unsigned nsym)
Definition at line 187 of file mmwave-amc.cc.
References m_crcLen, m_phyMacConfig, and ns3::mmwave::McsEcrTable.
Referenced by CreateCqiFeedbacksTdma().
GetTypeId()
TypeId ns3::mmwave::MmWaveAmc::GetTypeId (void) static
Definition at line 128 of file mmwave-amc.cc.
References m_amcModel, m_ber, MiErrorModel, and PiroEW2010.
Member Data Documentation
m_amcModel
AmcModel ns3::mmwave::MmWaveAmc::m_amcModel private
Definition at line 67 of file mmwave-amc.h.
Referenced by CreateCqiFeedbacks(), CreateCqiFeedbacksTdma(), CreateCqiFeedbackWbTdma(), and GetTypeId().
m_ber
double ns3::mmwave::MmWaveAmc::m_ber private
Definition at line 66 of file mmwave-amc.h.
Referenced by CreateCqiFeedbacks(), CreateCqiFeedbacksTdma(), CreateCqiFeedbackWbTdma(), and GetTypeId().
m_crcLen
const unsigned int ns3::mmwave::MmWaveAmc::m_crcLen = 24 static
Definition at line 63 of file mmwave-amc.h.
Referenced by GetNumSymbolsFromTbsMcs(), GetTbSizeFromMcs(), and GetTbSizeFromMcsSymbols().
m_lteRbModel
Ptr<SpectrumModel> ns3::mmwave::MmWaveAmc::m_lteRbModel private
Definition at line 70 of file mmwave-amc.h.
m_phyMacConfig
Ptr<MmWavePhyMacCommon> ns3::mmwave::MmWaveAmc::m_phyMacConfig private
Definition at line 69 of file mmwave-amc.h.
Referenced by GetNumSymbolsFromTbsMcs(), GetTbSizeFromMcs(), and GetTbSizeFromMcsSymbols().
The documentation for this class was generated from the following files:
src/mmwave/model/mmwave-amc.h
src/mmwave/model/mmwave-amc.cc