ns3-mmwave: ns3::mmwave::MmWaveFlexTtiMacScheduler Class Reference
ns3::mmwave::MmWaveFlexTtiMacScheduler Class Reference
#include "mmwave-flex-tti-mac-scheduler.h"
Classes
struct AllocMapElem
struct UeSchedInfo
struct UlCqiMapElem
Public Types
typedef std::vector< DciInfoElementTdma > DlHarqProcessesDciInfoList_t
typedef std::vector< uint8_t > DlHarqProcessesStatus_t
typedef std::vector< uint8_t > DlHarqProcessesTimer_t
typedef std::vector< std::vector< struct RlcPduInfo > > DlHarqRlcPduList_t
typedef std::vector< DciInfoElementTdma > UlHarqProcessesDciInfoList_t
typedef std::vector< uint8_t > UlHarqProcessesStatus_t
typedef std::vector< uint8_t > UlHarqProcessesTimer_t
Public Member Functions
MmWaveFlexTtiMacScheduler ()
virtual ~MmWaveFlexTtiMacScheduler ()
virtual void ConfigureCommonParameters (Ptr< MmWavePhyMacCommon > config) override
virtual void DoDispose (void) override
virtual MmWaveMacCschedSapProvider * GetMacCschedSapProvider () override
virtual MmWaveMacSchedSapProvider * GetMacSchedSapProvider () override
void RefreshDlCqiMaps (void)
void RefreshUlCqiMaps (void)
virtual void SetMacCschedSapUser (MmWaveMacCschedSapUser *s) override
virtual void SetMacSchedSapUser (MmWaveMacSchedSapUser *sap) override
void UpdateDlRlcBufferInfo (uint16_t rnti, uint8_t lcid, uint16_t size)
void UpdateUlRlcBufferInfo (uint16_t rnti, uint16_t size)
Public Member Functions inherited from ns3::mmwave::MmWaveMacScheduler
MmWaveMacScheduler ()
virtual ~MmWaveMacScheduler ()
Static Public Member Functions
static TypeId GetTypeId (void)
static bool SortRlcBufferReq (MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters i, MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters j)
Static Public Member Functions inherited from ns3::mmwave::MmWaveMacScheduler
static TypeId GetTypeId (void)
Private Member Functions
uint32_t BsrId2BufferSize (uint8_t val)
uint8_t BufferSize2BsrId (uint32_t val)
unsigned CalcMinTbSizeNumSym (unsigned mcs, unsigned bufSize, unsigned &tbSize)
void DoCschedCellConfigReq (const struct MmWaveMacCschedSapProvider::CschedCellConfigReqParameters &params)
void DoCschedLcConfigReq (const struct MmWaveMacCschedSapProvider::CschedLcConfigReqParameters &params)
void DoCschedLcReleaseReq (const struct MmWaveMacCschedSapProvider::CschedLcReleaseReqParameters &params)
void DoCschedUeConfigReq (const struct MmWaveMacCschedSapProvider::CschedUeConfigReqParameters &params)
void DoCschedUeReleaseReq (const struct MmWaveMacCschedSapProvider::CschedUeReleaseReqParameters &params)
void DoSchedDlCqiInfoReq (const MmWaveMacSchedSapProvider::SchedDlCqiInfoReqParameters &params)
void DoSchedDlRlcBufferReq (const struct MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters &params)
bool DoSchedDlTriggerReq (const struct MmWaveMacSchedSapProvider::SchedTriggerReqParameters &params, MmWaveMacSchedSapUser::SchedConfigIndParameters &ret, unsigned int frameNum, unsigned int sfNum, unsigned int islot)
void DoSchedSetMcs (int mcs)
void DoSchedTriggerReq (const struct MmWaveMacSchedSapProvider::SchedTriggerReqParameters &params)
void DoSchedUlCqiInfoReq (const struct MmWaveMacSchedSapProvider::SchedUlCqiInfoReqParameters &params)
void DoSchedUlMacCtrlInfoReq (const struct MmWaveMacSchedSapProvider::SchedUlMacCtrlInfoReqParameters &params)
bool DoSchedUlTriggerReq (const struct MmWaveMacSchedSapProvider::SchedTriggerReqParameters &params, MmWaveMacSchedSapUser::SchedConfigIndParameters &ret, unsigned int frameNum, unsigned int sfNum, unsigned int islot)
void RefreshHarqProcesses ()
Refresh HARQ processes according to the timers.
uint8_t UpdateDlHarqProcessId (uint16_t rnti)
uint8_t UpdateUlHarqProcessId (uint16_t rnti)
Private Attributes
Ptr< MmWaveAmc > m_amc
std::map< uint16_t, uint32_t > m_ceBsrRxed
uint32_t m_cqiTimersThreshold
MmWaveMacCschedSapProvider::CschedCellConfigReqParameters m_cschedCellConfig
std::map< uint16_t, uint8_t > m_dlHarqCurrentProcessId
std::vector< DlHarqInfo > m_dlHarqInfoList
std::map< uint16_t, DlHarqProcessesDciInfoList_t > m_dlHarqProcessesDciInfoMap
std::map< uint16_t, DlHarqRlcPduList_t > m_dlHarqProcessesRlcPduMap
std::map< uint16_t, DlHarqProcessesStatus_t > m_dlHarqProcessesStatus
std::map< uint16_t, DlHarqProcessesTimer_t > m_dlHarqProcessesTimer
bool m_dlOnly
bool m_fixedMcsDl
bool m_fixedMcsUl
bool m_fixedTti
bool m_harqOn
m_harqOn when false inhibit te HARQ mechanisms (by default active)
uint8_t m_harqTimeout
MmWaveMacCschedSapProvider * m_macCschedSapProvider
MmWaveMacCschedSapUser * m_macCschedSapUser
MmWaveMacSchedSapProvider * m_macSchedSapProvider
MmWaveMacSchedSapUser * m_macSchedSapUser
uint8_t m_mcsDefaultDl
uint8_t m_mcsDefaultUl
uint16_t m_nextRnti
uint64_t m_nextRntiDl
uint64_t m_nextRntiUl
uint32_t m_numChunks
uint32_t m_numDataSymbols
uint8_t m_numHarqProcess
std::list< MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters > m_rlcBufferReq
uint8_t m_symPerSlot
uint8_t m_tbUid
std::map< uint16_t, uint32_t > m_ueCqiTimers
std::map< uint16_t, struct UlCqiMapElem > m_ueUlCqi
std::map< uint32_t, struct AllocMapElem > m_ulAllocationMap
std::map< uint16_t, uint8_t > m_ulHarqCurrentProcessId
std::vector< UlHarqInfo > m_ulHarqInfoList
std::map< uint16_t, UlHarqProcessesDciInfoList_t > m_ulHarqProcessesDciInfoMap
std::map< uint16_t, UlHarqProcessesStatus_t > m_ulHarqProcessesStatus
std::map< uint16_t, UlHarqProcessesTimer_t > m_ulHarqProcessesTimer
bool m_ulOnly
std::map< uint16_t, uint8_t > m_wbCqiRxed
std::map< uint16_t, uint32_t > m_wbCqiTimers
Static Private Attributes
static const double m_berDl = 0.001
static const unsigned m_macHdrSize = 0
static const unsigned m_rlcHdrSize = 3
static const unsigned m_subHdrSize = 4
Friends
class MmWaveFlexTtiMacCschedSapProvider
class MmWaveFlexTtiMacSchedSapProvider
Additional Inherited Members
Protected Attributes inherited from ns3::mmwave::MmWaveMacScheduler
Ptr< MmWavePhyMacCommon > m_phyMacConfig
uint32_t m_rbgSize
Detailed Description
Definition at line 46 of file mmwave-flex-tti-mac-scheduler.h.
Member Typedef Documentation
DlHarqProcessesDciInfoList_t
typedef std::vector< DciInfoElementTdma > ns3::mmwave::MmWaveFlexTtiMacScheduler::DlHarqProcessesDciInfoList_t
Definition at line 51 of file mmwave-flex-tti-mac-scheduler.h.
DlHarqProcessesStatus_t
typedef std::vector< uint8_t > ns3::mmwave::MmWaveFlexTtiMacScheduler::DlHarqProcessesStatus_t
Definition at line 49 of file mmwave-flex-tti-mac-scheduler.h.
DlHarqProcessesTimer_t
typedef std::vector< uint8_t > ns3::mmwave::MmWaveFlexTtiMacScheduler::DlHarqProcessesTimer_t
Definition at line 50 of file mmwave-flex-tti-mac-scheduler.h.
DlHarqRlcPduList_t
typedef std::vector< std::vector <struct RlcPduInfo> > ns3::mmwave::MmWaveFlexTtiMacScheduler::DlHarqRlcPduList_t
Definition at line 52 of file mmwave-flex-tti-mac-scheduler.h.
UlHarqProcessesDciInfoList_t
typedef std::vector< DciInfoElementTdma > ns3::mmwave::MmWaveFlexTtiMacScheduler::UlHarqProcessesDciInfoList_t
Definition at line 56 of file mmwave-flex-tti-mac-scheduler.h.
UlHarqProcessesStatus_t
typedef std::vector< uint8_t > ns3::mmwave::MmWaveFlexTtiMacScheduler::UlHarqProcessesStatus_t
Definition at line 57 of file mmwave-flex-tti-mac-scheduler.h.
UlHarqProcessesTimer_t
typedef std::vector< uint8_t > ns3::mmwave::MmWaveFlexTtiMacScheduler::UlHarqProcessesTimer_t
Definition at line 55 of file mmwave-flex-tti-mac-scheduler.h.
Constructor & Destructor Documentation
MmWaveFlexTtiMacScheduler()
ns3::mmwave::MmWaveFlexTtiMacScheduler::MmWaveFlexTtiMacScheduler ()
Definition at line 173 of file mmwave-flex-tti-mac-scheduler.cc.
References m_macCschedSapProvider, m_macSchedSapProvider, MmWaveFlexTtiMacCschedSapProvider, and MmWaveFlexTtiMacSchedSapProvider.
~MmWaveFlexTtiMacScheduler()
ns3::mmwave::MmWaveFlexTtiMacScheduler::~MmWaveFlexTtiMacScheduler () virtual
Definition at line 184 of file mmwave-flex-tti-mac-scheduler.cc.
Member Function Documentation
BsrId2BufferSize()
uint32_t ns3::mmwave::MmWaveFlexTtiMacScheduler::BsrId2BufferSize (uint8_t val) inline private
Definition at line 126 of file mmwave-flex-tti-mac-scheduler.h.
References ns3::mmwave::BufferSizeLevelBsrTable.
Referenced by DoSchedUlMacCtrlInfoReq().
BufferSize2BsrId()
uint8_t ns3::mmwave::MmWaveFlexTtiMacScheduler::BufferSize2BsrId (uint32_t val) inline private
Definition at line 133 of file mmwave-flex-tti-mac-scheduler.h.
References ns3::mmwave::BufferSizeLevelBsrTable, DoCschedCellConfigReq(), DoCschedLcConfigReq(), DoCschedLcReleaseReq(), DoCschedUeConfigReq(), DoCschedUeReleaseReq(), DoSchedDlCqiInfoReq(), DoSchedDlRlcBufferReq(), DoSchedDlTriggerReq(), DoSchedSetMcs(), DoSchedTriggerReq(), DoSchedUlCqiInfoReq(), DoSchedUlMacCtrlInfoReq(), DoSchedUlTriggerReq(), RefreshHarqProcesses(), UpdateDlHarqProcessId(), and UpdateUlHarqProcessId().
CalcMinTbSizeNumSym()
unsigned ns3::mmwave::MmWaveFlexTtiMacScheduler::CalcMinTbSizeNumSym (unsigned mcs, unsigned bufSize, unsigned & tbSize) private
Definition at line 605 of file mmwave-flex-tti-mac-scheduler.cc.
References m_amc, and ns3::mmwave::MmWaveMacScheduler::m_phyMacConfig.
Referenced by DoSchedTriggerReq().
ConfigureCommonParameters()
void ns3::mmwave::MmWaveFlexTtiMacScheduler::ConfigureCommonParameters (Ptr< MmWavePhyMacCommon > config) override virtual
Implements ns3::mmwave::MmWaveMacScheduler.
Definition at line 293 of file mmwave-flex-tti-mac-scheduler.cc.
References m_amc, m_harqTimeout, m_numDataSymbols, m_numHarqProcess, and ns3::mmwave::MmWaveMacScheduler::m_phyMacConfig.
DoCschedCellConfigReq()
void ns3::mmwave::MmWaveFlexTtiMacScheduler::DoCschedCellConfigReq (const struct MmWaveMacCschedSapProvider::CschedCellConfigReqParameters & params) private
Definition at line 1726 of file mmwave-flex-tti-mac-scheduler.cc.
References ns3::mmwave::MmWaveMacCschedSapUser::CschedUeConfigCnf(), m_cschedCellConfig, m_macCschedSapUser, and ns3::mmwave::MmWaveMacCschedSapUser::CschedUeConfigCnfParameters::m_result.
Referenced by BufferSize2BsrId(), and ns3::mmwave::MmWaveFlexTtiMacCschedSapProvider::CschedCellConfigReq().
DoCschedLcConfigReq()
void ns3::mmwave::MmWaveFlexTtiMacScheduler::DoCschedLcConfigReq (const struct MmWaveMacCschedSapProvider::CschedLcConfigReqParameters & params) private
Definition at line 1776 of file mmwave-flex-tti-mac-scheduler.cc.
Referenced by BufferSize2BsrId(), and ns3::mmwave::MmWaveFlexTtiMacCschedSapProvider::CschedLcConfigReq().
DoCschedLcReleaseReq()
void ns3::mmwave::MmWaveFlexTtiMacScheduler::DoCschedLcReleaseReq (const struct MmWaveMacCschedSapProvider::CschedLcReleaseReqParameters & params) private
Definition at line 1784 of file mmwave-flex-tti-mac-scheduler.cc.
References ns3::mmwave::MmWaveMacCschedSapProvider::CschedLcReleaseReqParameters::m_logicalChannelIdentity, m_rlcBufferReq, and ns3::mmwave::MmWaveMacCschedSapProvider::CschedLcReleaseReqParameters::m_rnti.
Referenced by BufferSize2BsrId(), and ns3::mmwave::MmWaveFlexTtiMacCschedSapProvider::CschedLcReleaseReq().
DoCschedUeConfigReq()
void ns3::mmwave::MmWaveFlexTtiMacScheduler::DoCschedUeConfigReq (const struct MmWaveMacCschedSapProvider::CschedUeConfigReqParameters & params) private
Definition at line 1739 of file mmwave-flex-tti-mac-scheduler.cc.
References m_dlHarqProcessesDciInfoMap, m_dlHarqProcessesRlcPduMap, m_dlHarqProcessesStatus, m_dlHarqProcessesTimer, ns3::mmwave::MmWaveMacScheduler::m_phyMacConfig, ns3::mmwave::MmWaveMacCschedSapProvider::CschedUeConfigReqParameters::m_rnti, ns3::mmwave::MmWaveMacCschedSapProvider::CschedUeConfigReqParameters::m_transmissionMode, m_ulHarqProcessesDciInfoMap, m_ulHarqProcessesStatus, and m_ulHarqProcessesTimer.
Referenced by BufferSize2BsrId(), and ns3::mmwave::MmWaveFlexTtiMacCschedSapProvider::CschedUeConfigReq().
DoCschedUeReleaseReq()
void ns3::mmwave::MmWaveFlexTtiMacScheduler::DoCschedUeReleaseReq (const struct MmWaveMacCschedSapProvider::CschedUeReleaseReqParameters & params) private
Definition at line 1806 of file mmwave-flex-tti-mac-scheduler.cc.
References m_ceBsrRxed, m_dlHarqProcessesDciInfoMap, m_dlHarqProcessesRlcPduMap, m_dlHarqProcessesStatus, m_dlHarqProcessesTimer, m_nextRntiDl, m_nextRntiUl, m_rlcBufferReq, ns3::mmwave::MmWaveMacCschedSapProvider::CschedUeReleaseReqParameters::m_rnti, m_ulHarqProcessesDciInfoMap, m_ulHarqProcessesStatus, and m_ulHarqProcessesTimer.
Referenced by BufferSize2BsrId(), and ns3::mmwave::MmWaveFlexTtiMacCschedSapProvider::CschedUeReleaseReq().
DoDispose()
void ns3::mmwave::MmWaveFlexTtiMacScheduler::DoDispose (void) override virtual
Reimplemented from ns3::mmwave::MmWaveMacScheduler.
Definition at line 190 of file mmwave-flex-tti-mac-scheduler.cc.
References m_dlHarqInfoList, m_dlHarqProcessesDciInfoMap, m_dlHarqProcessesRlcPduMap, m_dlHarqProcessesTimer, m_macCschedSapProvider, m_macSchedSapProvider, m_ulHarqCurrentProcessId, m_ulHarqProcessesDciInfoMap, m_ulHarqProcessesStatus, m_ulHarqProcessesTimer, and m_wbCqiRxed.
DoSchedDlCqiInfoReq()
void ns3::mmwave::MmWaveFlexTtiMacScheduler::DoSchedDlCqiInfoReq (const MmWaveMacSchedSapProvider::SchedDlCqiInfoReqParameters & params) private
Definition at line 336 of file mmwave-flex-tti-mac-scheduler.cc.
References ns3::mmwave::MmWaveMacSchedSapProvider::SchedDlCqiInfoReqParameters::m_cqiList, m_cqiTimersThreshold, m_wbCqiRxed, m_wbCqiTimers, ns3::mmwave::DlCqiInfo::SB, and ns3::mmwave::DlCqiInfo::WB.
Referenced by BufferSize2BsrId(), and ns3::mmwave::MmWaveFlexTtiMacSchedSapProvider::SchedDlCqiInfoReq().
DoSchedDlRlcBufferReq()
void ns3::mmwave::MmWaveFlexTtiMacScheduler::DoSchedDlRlcBufferReq (const struct MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters & params) private
Definition at line 304 of file mmwave-flex-tti-mac-scheduler.cc.
References m_cqiTimersThreshold, ns3::mmwave::MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters::m_logicalChannelIdentity, m_rlcBufferReq, ns3::mmwave::MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters::m_rlcRetransmissionQueueSize, ns3::mmwave::MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters::m_rlcStatusPduSize, ns3::mmwave::MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters::m_rlcTransmissionQueueSize, ns3::mmwave::MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters::m_rnti, m_wbCqiRxed, and m_wbCqiTimers.
Referenced by BufferSize2BsrId(), and ns3::mmwave::MmWaveFlexTtiMacSchedSapProvider::SchedDlRlcBufferReq().
DoSchedDlTriggerReq()
bool ns3::mmwave::MmWaveFlexTtiMacScheduler::DoSchedDlTriggerReq (const struct MmWaveMacSchedSapProvider::SchedTriggerReqParameters & params, MmWaveMacSchedSapUser::SchedConfigIndParameters & ret, unsigned int frameNum, unsigned int sfNum, unsigned int islot) private
Referenced by BufferSize2BsrId().
DoSchedSetMcs()
void ns3::mmwave::MmWaveFlexTtiMacScheduler::DoSchedSetMcs (int mcs) private
Definition at line 1563 of file mmwave-flex-tti-mac-scheduler.cc.
References m_mcsDefaultDl, and m_mcsDefaultUl.
Referenced by BufferSize2BsrId(), and ns3::mmwave::MmWaveFlexTtiMacSchedSapProvider::SchedSetMcs().
DoSchedTriggerReq()
void ns3::mmwave::MmWaveFlexTtiMacScheduler::DoSchedTriggerReq (const struct MmWaveMacSchedSapProvider::SchedTriggerReqParameters & params) private
Definition at line 657 of file mmwave-flex-tti-mac-scheduler.cc.
References ns3::mmwave::DlHarqInfo::ACK, CalcMinTbSizeNumSym(), ns3::mmwave::TtiAllocInfo::CTRL, ns3::mmwave::TtiAllocInfo::CTRL_DATA, ns3::mmwave::TtiAllocInfo::DL_slotAllocInfo, ns3::mmwave::SfnSf::Encode(), ns3::mmwave::MmWaveSpectrumValueHelper::GetSpectrumModel(), m_amc, m_ceBsrRxed, ns3::mmwave::TtiAllocInfo::m_dci, ns3::mmwave::MmWaveMacSchedSapProvider::SchedTriggerReqParameters::m_dlHarqInfoList, m_dlHarqInfoList, m_dlHarqProcessesDciInfoMap, m_dlHarqProcessesRlcPduMap, m_dlHarqProcessesStatus, m_dlHarqProcessesTimer, ns3::mmwave::MmWaveFlexTtiMacScheduler::UeSchedInfo::m_dlMcs, m_dlOnly, ns3::mmwave::MmWaveFlexTtiMacScheduler::UeSchedInfo::m_dlSymbols, m_fixedMcsDl, m_fixedMcsUl, m_fixedTti, ns3::mmwave::DciInfoElementTdma::m_format, ns3::mmwave::SfnSf::m_frameNum, m_harqOn, ns3::mmwave::DciInfoElementTdma::m_harqProcess, ns3::mmwave::UlHarqInfo::m_harqProcessId, ns3::mmwave::RlcPduInfo::m_lcid, m_macHdrSize, m_macSchedSapUser, ns3::mmwave::DciInfoElementTdma::m_mcs, m_mcsDefaultDl, m_mcsDefaultUl, ns3::mmwave::DciInfoElementTdma::m_ndi, m_nextRnti, ns3::mmwave::DciInfoElementTdma::m_numSym, ns3::mmwave::SlotAllocInfo::m_numSymAlloc, ns3::mmwave::MmWaveMacScheduler::m_phyMacConfig, ns3::mmwave::UlHarqInfo::m_receptionStatus, m_rlcBufferReq, m_rlcHdrSize, ns3::mmwave::MmWaveFlexTtiMacScheduler::UeSchedInfo::m_rlcPduInfo, ns3::mmwave::TtiAllocInfo::m_rlcPduInfo, ns3::mmwave::DciInfoElementTdma::m_rnti, ns3::mmwave::UlHarqInfo::m_rnti, ns3::mmwave::DciInfoElementTdma::m_rv, ns3::mmwave::MmWaveMacSchedSapUser::SchedConfigIndParameters::m_sfnSf, ns3::mmwave::SlotAllocInfo::m_sfnSf, ns3::mmwave::SfnSf::m_sfNum, ns3::mmwave::RlcPduInfo::m_size, ns3::mmwave::MmWaveMacSchedSapUser::SchedConfigIndParameters::m_slotAllocInfo, ns3::mmwave::SfnSf::m_slotNum, ns3::mmwave::MmWaveMacSchedSapProvider::SchedTriggerReqParameters::m_snfSf, m_subHdrSize, m_symPerSlot, ns3::mmwave::SfnSf::m_symStart, ns3::mmwave::DciInfoElementTdma::m_symStart, ns3::mmwave::DciInfoElementTdma::m_tbSize, ns3::mmwave::SlotAllocInfo::m_ttiAllocInfo, ns3::mmwave::TtiAllocInfo::m_ttiIdx, m_ueUlCqi, m_ulAllocationMap, ns3::mmwave::MmWaveMacSchedSapProvider::SchedTriggerReqParameters::m_ulHarqInfoList, m_ulHarqInfoList, m_ulHarqProcessesDciInfoMap, m_ulHarqProcessesStatus, m_ulHarqProcessesTimer, ns3::mmwave::MmWaveFlexTtiMacScheduler::UeSchedInfo::m_ulMcs, m_ulOnly, ns3::mmwave::MmWaveFlexTtiMacScheduler::UeSchedInfo::m_ulSymbols, m_wbCqiRxed, ns3::mmwave::DlHarqInfo::NACK, ns3::mmwave::UlHarqInfo::NotOk, ns3::mmwave::UlHarqInfo::Ok, RefreshDlCqiMaps(), RefreshHarqProcesses(), RefreshUlCqiMaps(), ns3::mmwave::MmWaveMacSchedSapUser::SchedConfigInd(), ns3::mmwave::TtiAllocInfo::UL_slotAllocInfo, UpdateDlHarqProcessId(), UpdateDlRlcBufferInfo(), UpdateUlHarqProcessId(), and UpdateUlRlcBufferInfo().
Referenced by BufferSize2BsrId(), and ns3::mmwave::MmWaveFlexTtiMacSchedSapProvider::SchedTriggerReq().
DoSchedUlCqiInfoReq()
void ns3::mmwave::MmWaveFlexTtiMacScheduler::DoSchedUlCqiInfoReq (const struct MmWaveMacSchedSapProvider::SchedUlCqiInfoReqParameters & params) private
Definition at line 380 of file mmwave-flex-tti-mac-scheduler.cc.
References ns3::mmwave::SfnSf::Encode(), m_cqiTimersThreshold, ns3::mmwave::SfnSf::m_frameNum, ns3::mmwave::MmWaveMacScheduler::m_phyMacConfig, ns3::mmwave::MmWaveMacSchedSapProvider::SchedUlCqiInfoReqParameters::m_sfnSf, ns3::mmwave::SfnSf::m_sfNum, ns3::mmwave::UlCqiInfo::m_sinr, ns3::mmwave::SfnSf::m_slotNum, ns3::mmwave::SfnSf::m_symStart, ns3::mmwave::UlCqiInfo::m_type, m_ueCqiTimers, m_ueUlCqi, m_ulAllocationMap, ns3::mmwave::MmWaveMacSchedSapProvider::SchedUlCqiInfoReqParameters::m_ulCqi, and ns3::mmwave::UlCqiInfo::PUSCH.
Referenced by BufferSize2BsrId(), and ns3::mmwave::MmWaveFlexTtiMacSchedSapProvider::SchedUlCqiInfoReq().
DoSchedUlMacCtrlInfoReq()
void ns3::mmwave::MmWaveFlexTtiMacScheduler::DoSchedUlMacCtrlInfoReq (const struct MmWaveMacSchedSapProvider::SchedUlMacCtrlInfoReqParameters & params) private
Definition at line 1518 of file mmwave-flex-tti-mac-scheduler.cc.
References ns3::mmwave::MacCeElement::BSR, BsrId2BufferSize(), m_ceBsrRxed, and ns3::mmwave::MmWaveMacSchedSapProvider::SchedUlMacCtrlInfoReqParameters::m_macCeList.
Referenced by BufferSize2BsrId(), and ns3::mmwave::MmWaveFlexTtiMacSchedSapProvider::SchedUlMacCtrlInfoReq().
DoSchedUlTriggerReq()
bool ns3::mmwave::MmWaveFlexTtiMacScheduler::DoSchedUlTriggerReq (const struct MmWaveMacSchedSapProvider::SchedTriggerReqParameters & params, MmWaveMacSchedSapUser::SchedConfigIndParameters & ret, unsigned int frameNum, unsigned int sfNum, unsigned int islot) private
Referenced by BufferSize2BsrId().
GetMacCschedSapProvider()
MmWaveMacCschedSapProvider * ns3::mmwave::MmWaveFlexTtiMacScheduler::GetMacCschedSapProvider () override virtual
Implements ns3::mmwave::MmWaveMacScheduler.
Definition at line 287 of file mmwave-flex-tti-mac-scheduler.cc.
References m_macCschedSapProvider.
GetMacSchedSapProvider()
MmWaveMacSchedSapProvider * ns3::mmwave::MmWaveFlexTtiMacScheduler::GetMacSchedSapProvider () override virtual
Implements ns3::mmwave::MmWaveMacScheduler.
Definition at line 281 of file mmwave-flex-tti-mac-scheduler.cc.
References m_macSchedSapProvider.
GetTypeId()
TypeId ns3::mmwave::MmWaveFlexTtiMacScheduler::GetTypeId (void) static
Definition at line 207 of file mmwave-flex-tti-mac-scheduler.cc.
References m_cqiTimersThreshold, m_dlOnly, m_fixedMcsDl, m_fixedMcsUl, m_fixedTti, m_harqOn, m_mcsDefaultDl, m_mcsDefaultUl, m_symPerSlot, and m_ulOnly.
RefreshDlCqiMaps()
void ns3::mmwave::MmWaveFlexTtiMacScheduler::RefreshDlCqiMaps (void)
Definition at line 1580 of file mmwave-flex-tti-mac-scheduler.cc.
References m_cqiTimersThreshold, m_wbCqiRxed, and m_wbCqiTimers.
Referenced by DoSchedTriggerReq().
RefreshHarqProcesses()
void ns3::mmwave::MmWaveFlexTtiMacScheduler::RefreshHarqProcesses () private
Refresh HARQ processes according to the timers.
Definition at line 460 of file mmwave-flex-tti-mac-scheduler.cc.
References m_dlHarqProcessesStatus, m_dlHarqProcessesTimer, ns3::mmwave::MmWaveMacScheduler::m_phyMacConfig, m_ulHarqProcessesStatus, and m_ulHarqProcessesTimer.
Referenced by BufferSize2BsrId(), and DoSchedTriggerReq().
RefreshUlCqiMaps()
void ns3::mmwave::MmWaveFlexTtiMacScheduler::RefreshUlCqiMaps (void)
Definition at line 1611 of file mmwave-flex-tti-mac-scheduler.cc.
References m_cqiTimersThreshold, m_ueCqiTimers, and m_ueUlCqi.
Referenced by DoSchedTriggerReq().
SetMacCschedSapUser()
void ns3::mmwave::MmWaveFlexTtiMacScheduler::SetMacCschedSapUser (MmWaveMacCschedSapUser * s) override virtual
Implements ns3::mmwave::MmWaveMacScheduler.
Definition at line 274 of file mmwave-flex-tti-mac-scheduler.cc.
References m_macCschedSapUser.
SetMacSchedSapUser()
void ns3::mmwave::MmWaveFlexTtiMacScheduler::SetMacSchedSapUser (MmWaveMacSchedSapUser * sap) override virtual
Implements ns3::mmwave::MmWaveMacScheduler.
Definition at line 268 of file mmwave-flex-tti-mac-scheduler.cc.
References m_macSchedSapUser.
SortRlcBufferReq()
bool ns3::mmwave::MmWaveFlexTtiMacScheduler::SortRlcBufferReq (MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters i, MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters j) static
Definition at line 1573 of file mmwave-flex-tti-mac-scheduler.cc.
References ns3::mmwave::MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters::m_rnti.
UpdateDlHarqProcessId()
uint8_t ns3::mmwave::MmWaveFlexTtiMacScheduler::UpdateDlHarqProcessId (uint16_t rnti) private
Definition at line 513 of file mmwave-flex-tti-mac-scheduler.cc.
References m_dlHarqProcessesStatus, m_harqOn, ns3::mmwave::MmWaveMacScheduler::m_phyMacConfig, and m_tbUid.
Referenced by BufferSize2BsrId(), and DoSchedTriggerReq().
UpdateDlRlcBufferInfo()
void ns3::mmwave::MmWaveFlexTtiMacScheduler::UpdateDlRlcBufferInfo (uint16_t rnti, uint8_t lcid, uint16_t size)
Definition at line 1641 of file mmwave-flex-tti-mac-scheduler.cc.
References m_rlcBufferReq.
Referenced by DoSchedTriggerReq().
UpdateUlHarqProcessId()
uint8_t ns3::mmwave::MmWaveFlexTtiMacScheduler::UpdateUlHarqProcessId (uint16_t rnti) private
Definition at line 569 of file mmwave-flex-tti-mac-scheduler.cc.
References m_harqOn, ns3::mmwave::MmWaveMacScheduler::m_phyMacConfig, m_tbUid, and m_ulHarqProcessesStatus.
Referenced by BufferSize2BsrId(), and DoSchedTriggerReq().
UpdateUlRlcBufferInfo()
void ns3::mmwave::MmWaveFlexTtiMacScheduler::UpdateUlRlcBufferInfo (uint16_t rnti, uint16_t size)
Definition at line 1700 of file mmwave-flex-tti-mac-scheduler.cc.
References m_ceBsrRxed.
Referenced by DoSchedTriggerReq().
Friends And Related Function Documentation
MmWaveFlexTtiMacCschedSapProvider
friend class MmWaveFlexTtiMacCschedSapProvider friend
Definition at line 83 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by MmWaveFlexTtiMacScheduler().
MmWaveFlexTtiMacSchedSapProvider
friend class MmWaveFlexTtiMacSchedSapProvider friend
Definition at line 82 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by MmWaveFlexTtiMacScheduler().
Member Data Documentation
m_amc
Ptr<MmWaveAmc> ns3::mmwave::MmWaveFlexTtiMacScheduler::m_amc private
Definition at line 205 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by CalcMinTbSizeNumSym(), ConfigureCommonParameters(), and DoSchedTriggerReq().
m_berDl
const double ns3::mmwave::MmWaveFlexTtiMacScheduler::m_berDl = 0.001 static private
Definition at line 316 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by ns3::mmwave::MmWaveFlexTtiMacSchedSapProvider::SchedSetMcs().
m_ceBsrRxed
std::map<uint16_t,uint32_t> ns3::mmwave::MmWaveFlexTtiMacScheduler::m_ceBsrRxed private
Definition at line 248 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by DoCschedUeReleaseReq(), DoSchedTriggerReq(), DoSchedUlMacCtrlInfoReq(), and UpdateUlRlcBufferInfo().
m_cqiTimersThreshold
uint32_t ns3::mmwave::MmWaveFlexTtiMacScheduler::m_cqiTimersThreshold private
Definition at line 221 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by DoSchedDlCqiInfoReq(), DoSchedDlRlcBufferReq(), DoSchedUlCqiInfoReq(), GetTypeId(), RefreshDlCqiMaps(), and RefreshUlCqiMaps().
m_cschedCellConfig
MmWaveMacCschedSapProvider::CschedCellConfigReqParameters ns3::mmwave::MmWaveFlexTtiMacScheduler::m_cschedCellConfig private
Definition at line 263 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by DoCschedCellConfigReq().
m_dlHarqCurrentProcessId
std::map<uint16_t, uint8_t> ns3::mmwave::MmWaveFlexTtiMacScheduler::m_dlHarqCurrentProcessId private
Definition at line 292 of file mmwave-flex-tti-mac-scheduler.h.
m_dlHarqInfoList
std::vector<DlHarqInfo> ns3::mmwave::MmWaveFlexTtiMacScheduler::m_dlHarqInfoList private
Definition at line 300 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by DoDispose(), and DoSchedTriggerReq().
m_dlHarqProcessesDciInfoMap
std::map<uint16_t, DlHarqProcessesDciInfoList_t> ns3::mmwave::MmWaveFlexTtiMacScheduler::m_dlHarqProcessesDciInfoMap private
Definition at line 298 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by DoCschedUeConfigReq(), DoCschedUeReleaseReq(), DoDispose(), and DoSchedTriggerReq().
m_dlHarqProcessesRlcPduMap
std::map<uint16_t, DlHarqRlcPduList_t> ns3::mmwave::MmWaveFlexTtiMacScheduler::m_dlHarqProcessesRlcPduMap private
Definition at line 299 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by DoCschedUeConfigReq(), DoCschedUeReleaseReq(), DoDispose(), and DoSchedTriggerReq().
m_dlHarqProcessesStatus
std::map<uint16_t, DlHarqProcessesStatus_t> ns3::mmwave::MmWaveFlexTtiMacScheduler::m_dlHarqProcessesStatus private
Definition at line 296 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by DoCschedUeConfigReq(), DoCschedUeReleaseReq(), DoSchedTriggerReq(), RefreshHarqProcesses(), and UpdateDlHarqProcessId().
m_dlHarqProcessesTimer
std::map<uint16_t, DlHarqProcessesTimer_t> ns3::mmwave::MmWaveFlexTtiMacScheduler::m_dlHarqProcessesTimer private
Definition at line 297 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by DoCschedUeConfigReq(), DoCschedUeReleaseReq(), DoDispose(), DoSchedTriggerReq(), and RefreshHarqProcesses().
m_dlOnly
bool ns3::mmwave::MmWaveFlexTtiMacScheduler::m_dlOnly private
Definition at line 322 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by DoSchedTriggerReq(), and GetTypeId().
m_fixedMcsDl
bool ns3::mmwave::MmWaveFlexTtiMacScheduler::m_fixedMcsDl private
Definition at line 317 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by DoSchedTriggerReq(), and GetTypeId().
m_fixedMcsUl
bool ns3::mmwave::MmWaveFlexTtiMacScheduler::m_fixedMcsUl private
Definition at line 318 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by DoSchedTriggerReq(), and GetTypeId().
m_fixedTti
bool ns3::mmwave::MmWaveFlexTtiMacScheduler::m_fixedTti private
Definition at line 325 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by DoSchedTriggerReq(), and GetTypeId().
m_harqOn
bool ns3::mmwave::MmWaveFlexTtiMacScheduler::m_harqOn private
m_harqOn when false inhibit te HARQ mechanisms (by default active)
Definition at line 288 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by DoSchedTriggerReq(), GetTypeId(), UpdateDlHarqProcessId(), and UpdateUlHarqProcessId().
m_harqTimeout
uint8_t ns3::mmwave::MmWaveFlexTtiMacScheduler::m_harqTimeout private
Definition at line 290 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by ConfigureCommonParameters().
m_macCschedSapProvider
MmWaveMacCschedSapProvider* ns3::mmwave::MmWaveFlexTtiMacScheduler::m_macCschedSapProvider private
Definition at line 261 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by DoDispose(), GetMacCschedSapProvider(), and MmWaveFlexTtiMacScheduler().
m_macCschedSapUser
MmWaveMacCschedSapUser* ns3::mmwave::MmWaveFlexTtiMacScheduler::m_macCschedSapUser private
Definition at line 260 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by DoCschedCellConfigReq(), and SetMacCschedSapUser().
m_macHdrSize
const unsigned ns3::mmwave::MmWaveFlexTtiMacScheduler::m_macHdrSize = 0 static private
Definition at line 312 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by DoSchedTriggerReq(), and ns3::mmwave::MmWaveFlexTtiMacSchedSapProvider::SchedSetMcs().
m_macSchedSapProvider
MmWaveMacSchedSapProvider* ns3::mmwave::MmWaveFlexTtiMacScheduler::m_macSchedSapProvider private
Definition at line 258 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by DoDispose(), GetMacSchedSapProvider(), and MmWaveFlexTtiMacScheduler().
m_macSchedSapUser
MmWaveMacSchedSapUser* ns3::mmwave::MmWaveFlexTtiMacScheduler::m_macSchedSapUser private
Definition at line 259 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by DoSchedTriggerReq(), and SetMacSchedSapUser().
m_mcsDefaultDl
uint8_t ns3::mmwave::MmWaveFlexTtiMacScheduler::m_mcsDefaultDl private
Definition at line 319 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by DoSchedSetMcs(), DoSchedTriggerReq(), and GetTypeId().
m_mcsDefaultUl
uint8_t ns3::mmwave::MmWaveFlexTtiMacScheduler::m_mcsDefaultUl private
Definition at line 320 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by DoSchedSetMcs(), DoSchedTriggerReq(), and GetTypeId().
m_nextRnti
uint16_t ns3::mmwave::MmWaveFlexTtiMacScheduler::m_nextRnti private
Definition at line 250 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by DoSchedTriggerReq().
m_nextRntiDl
uint64_t ns3::mmwave::MmWaveFlexTtiMacScheduler::m_nextRntiDl private
Definition at line 251 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by DoCschedUeReleaseReq().
m_nextRntiUl
uint64_t ns3::mmwave::MmWaveFlexTtiMacScheduler::m_nextRntiUl private
Definition at line 252 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by DoCschedUeReleaseReq().
m_numChunks
uint32_t ns3::mmwave::MmWaveFlexTtiMacScheduler::m_numChunks private
Definition at line 255 of file mmwave-flex-tti-mac-scheduler.h.
m_numDataSymbols
uint32_t ns3::mmwave::MmWaveFlexTtiMacScheduler::m_numDataSymbols private
Definition at line 256 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by ConfigureCommonParameters().
m_numHarqProcess
uint8_t ns3::mmwave::MmWaveFlexTtiMacScheduler::m_numHarqProcess private
Definition at line 289 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by ConfigureCommonParameters().
m_rlcBufferReq
std::list<MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters> ns3::mmwave::MmWaveFlexTtiMacScheduler::m_rlcBufferReq private
Definition at line 210 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by DoCschedLcReleaseReq(), DoCschedUeReleaseReq(), DoSchedDlRlcBufferReq(), DoSchedTriggerReq(), and UpdateDlRlcBufferInfo().
m_rlcHdrSize
const unsigned ns3::mmwave::MmWaveFlexTtiMacScheduler::m_rlcHdrSize = 3 static private
Definition at line 314 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by DoSchedTriggerReq(), and ns3::mmwave::MmWaveFlexTtiMacSchedSapProvider::SchedSetMcs().
m_subHdrSize
const unsigned ns3::mmwave::MmWaveFlexTtiMacScheduler::m_subHdrSize = 4 static private
Definition at line 313 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by DoSchedTriggerReq(), and ns3::mmwave::MmWaveFlexTtiMacSchedSapProvider::SchedSetMcs().
m_symPerSlot
uint8_t ns3::mmwave::MmWaveFlexTtiMacScheduler::m_symPerSlot private
Definition at line 326 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by DoSchedTriggerReq(), and GetTypeId().
m_tbUid
uint8_t ns3::mmwave::MmWaveFlexTtiMacScheduler::m_tbUid private
Definition at line 254 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by UpdateDlHarqProcessId(), and UpdateUlHarqProcessId().
m_ueCqiTimers
std::map<uint16_t, uint32_t> ns3::mmwave::MmWaveFlexTtiMacScheduler::m_ueCqiTimers private
Definition at line 243 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by DoSchedUlCqiInfoReq(), and RefreshUlCqiMaps().
m_ueUlCqi
std::map<uint16_t, struct UlCqiMapElem> ns3::mmwave::MmWaveFlexTtiMacScheduler::m_ueUlCqi private
Definition at line 239 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by DoSchedTriggerReq(), DoSchedUlCqiInfoReq(), and RefreshUlCqiMaps().
m_ulAllocationMap
std::map<uint32_t, struct AllocMapElem> ns3::mmwave::MmWaveFlexTtiMacScheduler::m_ulAllocationMap private
Definition at line 282 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by DoSchedTriggerReq(), and DoSchedUlCqiInfoReq().
m_ulHarqCurrentProcessId
std::map<uint16_t, uint8_t> ns3::mmwave::MmWaveFlexTtiMacScheduler::m_ulHarqCurrentProcessId private
Definition at line 303 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by DoDispose().
m_ulHarqInfoList
std::vector<UlHarqInfo> ns3::mmwave::MmWaveFlexTtiMacScheduler::m_ulHarqInfoList private
Definition at line 301 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by DoSchedTriggerReq().
m_ulHarqProcessesDciInfoMap
std::map<uint16_t, UlHarqProcessesDciInfoList_t> ns3::mmwave::MmWaveFlexTtiMacScheduler::m_ulHarqProcessesDciInfoMap private
Definition at line 309 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by DoCschedUeConfigReq(), DoCschedUeReleaseReq(), DoDispose(), and DoSchedTriggerReq().
m_ulHarqProcessesStatus
std::map<uint16_t, UlHarqProcessesStatus_t> ns3::mmwave::MmWaveFlexTtiMacScheduler::m_ulHarqProcessesStatus private
Definition at line 307 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by DoCschedUeConfigReq(), DoCschedUeReleaseReq(), DoDispose(), DoSchedTriggerReq(), RefreshHarqProcesses(), and UpdateUlHarqProcessId().
m_ulHarqProcessesTimer
std::map<uint16_t, UlHarqProcessesTimer_t> ns3::mmwave::MmWaveFlexTtiMacScheduler::m_ulHarqProcessesTimer private
Definition at line 308 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by DoCschedUeConfigReq(), DoCschedUeReleaseReq(), DoDispose(), DoSchedTriggerReq(), and RefreshHarqProcesses().
m_ulOnly
bool ns3::mmwave::MmWaveFlexTtiMacScheduler::m_ulOnly private
Definition at line 323 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by DoSchedTriggerReq(), and GetTypeId().
m_wbCqiRxed
std::map<uint16_t,uint8_t> ns3::mmwave::MmWaveFlexTtiMacScheduler::m_wbCqiRxed private
Definition at line 215 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by DoDispose(), DoSchedDlCqiInfoReq(), DoSchedDlRlcBufferReq(), DoSchedTriggerReq(), and RefreshDlCqiMaps().
m_wbCqiTimers
std::map<uint16_t,uint32_t> ns3::mmwave::MmWaveFlexTtiMacScheduler::m_wbCqiTimers private
Definition at line 219 of file mmwave-flex-tti-mac-scheduler.h.
Referenced by DoSchedDlCqiInfoReq(), DoSchedDlRlcBufferReq(), and RefreshDlCqiMaps().
The documentation for this class was generated from the following files:
src/mmwave/model/mmwave-flex-tti-mac-scheduler.h
src/mmwave/model/mmwave-flex-tti-mac-scheduler.cc