ns3-mmwave: ns3::mmwave::McStatsCalculator Class Reference
ns3::mmwave::McStatsCalculator Class Reference
#include "mc-stats-calculator.h"
Public Member Functions
McStatsCalculator ()
Class constructor.
virtual ~McStatsCalculator ()
Class destructor.
void DoDispose ()
std::string GetCellIdInTimeOutputFilename (void)
std::string GetLteOutputFilename (void)
std::string GetMmWaveOutputFilename (void)
void SetCellIdInTimeOutputFilename (std::string outputFilename)
void SetLteOutputFilename (std::string outputFilename)
void SetMmWaveOutputFilename (std::string outputFilename)
void SwitchToLte (uint64_t imsi, uint16_t cellId, uint16_t rnti)
void SwitchToMmWave (uint64_t imsi, uint16_t cellId, uint16_t rnti)
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
Private Attributes
std::string m_cellInTimeFilename
std::ofstream m_cellInTimeOutFile
std::ofstream m_lteOutFile
std::string m_lteOutputFilename
Name of the file where the downlink PDCP statistics will be saved.
std::ofstream m_mmWaveOutFile
std::string m_mmWaveOutputFilename
Name of the file where the uplink PDCP statistics will be saved.
Detailed Description
Definition at line 37 of file mc-stats-calculator.h.
Constructor & Destructor Documentation
McStatsCalculator()
ns3::mmwave::McStatsCalculator::McStatsCalculator ()
Class constructor.
Definition at line 36 of file mc-stats-calculator.cc.
~McStatsCalculator()
ns3::mmwave::McStatsCalculator::~McStatsCalculator () virtual
Class destructor.
Definition at line 44 of file mc-stats-calculator.cc.
References m_cellInTimeOutFile, m_lteOutFile, and m_mmWaveOutFile.
Member Function Documentation
DoDispose()
void ns3::mmwave::McStatsCalculator::DoDispose ()
Definition at line 89 of file mc-stats-calculator.cc.
GetCellIdInTimeOutputFilename()
std::string ns3::mmwave::McStatsCalculator::GetCellIdInTimeOutputFilename (void)
Definition at line 126 of file mc-stats-calculator.cc.
References m_cellInTimeFilename.
Referenced by SwitchToLte(), and SwitchToMmWave().
GetLteOutputFilename()
std::string ns3::mmwave::McStatsCalculator::GetLteOutputFilename (void)
Definition at line 108 of file mc-stats-calculator.cc.
References m_lteOutputFilename.
Referenced by SwitchToLte().
GetMmWaveOutputFilename()
std::string ns3::mmwave::McStatsCalculator::GetMmWaveOutputFilename (void)
Definition at line 114 of file mc-stats-calculator.cc.
References m_mmWaveOutputFilename.
Referenced by SwitchToMmWave().
GetTypeId()
TypeId ns3::mmwave::McStatsCalculator::GetTypeId (void) static
Register this type.
Returns
The object TypeId.
Definition at line 62 of file mc-stats-calculator.cc.
References SetCellIdInTimeOutputFilename(), SetLteOutputFilename(), and SetMmWaveOutputFilename().
SetCellIdInTimeOutputFilename()
void ns3::mmwave::McStatsCalculator::SetCellIdInTimeOutputFilename (std::string outputFilename)
Definition at line 120 of file mc-stats-calculator.cc.
References m_cellInTimeFilename.
Referenced by GetTypeId().
SetLteOutputFilename()
void ns3::mmwave::McStatsCalculator::SetLteOutputFilename (std::string outputFilename)
Definition at line 95 of file mc-stats-calculator.cc.
References m_lteOutputFilename.
Referenced by GetTypeId().
SetMmWaveOutputFilename()
void ns3::mmwave::McStatsCalculator::SetMmWaveOutputFilename (std::string outputFilename)
Definition at line 102 of file mc-stats-calculator.cc.
References m_mmWaveOutputFilename.
Referenced by GetTypeId().
SwitchToLte()
void ns3::mmwave::McStatsCalculator::SwitchToLte (uint64_t imsi, uint16_t cellId, uint16_t rnti)
Definition at line 132 of file mc-stats-calculator.cc.
References GetCellIdInTimeOutputFilename(), GetLteOutputFilename(), m_cellInTimeOutFile, and m_lteOutFile.
SwitchToMmWave()
void ns3::mmwave::McStatsCalculator::SwitchToMmWave (uint64_t imsi, uint16_t cellId, uint16_t rnti)
Definition at line 151 of file mc-stats-calculator.cc.
References GetCellIdInTimeOutputFilename(), GetMmWaveOutputFilename(), m_cellInTimeOutFile, and m_mmWaveOutFile.
Member Data Documentation
m_cellInTimeFilename
std::string ns3::mmwave::McStatsCalculator::m_cellInTimeFilename private
Definition at line 84 of file mc-stats-calculator.h.
Referenced by GetCellIdInTimeOutputFilename(), and SetCellIdInTimeOutputFilename().
m_cellInTimeOutFile
std::ofstream ns3::mmwave::McStatsCalculator::m_cellInTimeOutFile private
Definition at line 88 of file mc-stats-calculator.h.
Referenced by SwitchToLte(), SwitchToMmWave(), and ~McStatsCalculator().
m_lteOutFile
std::ofstream ns3::mmwave::McStatsCalculator::m_lteOutFile private
Definition at line 86 of file mc-stats-calculator.h.
Referenced by SwitchToLte(), and ~McStatsCalculator().
m_lteOutputFilename
std::string ns3::mmwave::McStatsCalculator::m_lteOutputFilename private
Name of the file where the downlink PDCP statistics will be saved.
Definition at line 77 of file mc-stats-calculator.h.
Referenced by GetLteOutputFilename(), and SetLteOutputFilename().
m_mmWaveOutFile
std::ofstream ns3::mmwave::McStatsCalculator::m_mmWaveOutFile private
Definition at line 87 of file mc-stats-calculator.h.
Referenced by SwitchToMmWave(), and ~McStatsCalculator().
m_mmWaveOutputFilename
std::string ns3::mmwave::McStatsCalculator::m_mmWaveOutputFilename private
Name of the file where the uplink PDCP statistics will be saved.
Definition at line 82 of file mc-stats-calculator.h.
Referenced by GetMmWaveOutputFilename(), and SetMmWaveOutputFilename().
The documentation for this class was generated from the following files:
src/mmwave/helper/mc-stats-calculator.h
src/mmwave/helper/mc-stats-calculator.cc