ns3-mmwave: ns3::mmwave::MmWaveEnbMacMemberEnbCmacSapProvider Class Reference
ns3::mmwave::MmWaveEnbMacMemberEnbCmacSapProvider Class Reference
Public Member Functions
MmWaveEnbMacMemberEnbCmacSapProvider (MmWaveEnbMac *mac)
virtual void AddLc (LcInfo lcinfo, LteMacSapUser *msu)
virtual void AddUe (uint16_t rnti)
virtual AllocateNcRaPreambleReturnValue AllocateNcRaPreamble (uint16_t rnti)
virtual void ConfigureMac (uint8_t ulBandwidth, uint8_t dlBandwidth)
virtual RachConfig GetRachConfig ()
virtual void ReconfigureLc (LcInfo lcinfo)
virtual void ReleaseLc (uint16_t rnti, uint8_t lcid)
virtual void RemoveUe (uint16_t rnti)
virtual void UeUpdateConfigurationReq (UeConfig params)
Private Attributes
MmWaveEnbMac * m_mac
Detailed Description
Definition at line 61 of file mmwave-enb-mac.cc.
Constructor & Destructor Documentation
MmWaveEnbMacMemberEnbCmacSapProvider()
ns3::mmwave::MmWaveEnbMacMemberEnbCmacSapProvider::MmWaveEnbMacMemberEnbCmacSapProvider (MmWaveEnbMac * mac)
Definition at line 83 of file mmwave-enb-mac.cc.
Member Function Documentation
AddLc()
void ns3::mmwave::MmWaveEnbMacMemberEnbCmacSapProvider::AddLc (LcInfo lcinfo, LteMacSapUser * msu) virtual
Definition at line 107 of file mmwave-enb-mac.cc.
References ns3::mmwave::MmWaveEnbMac::DoAddLc(), and m_mac.
AddUe()
void ns3::mmwave::MmWaveEnbMacMemberEnbCmacSapProvider::AddUe (uint16_t rnti) virtual
Definition at line 95 of file mmwave-enb-mac.cc.
References ns3::mmwave::MmWaveEnbMac::DoAddUe(), and m_mac.
AllocateNcRaPreamble()
LteEnbCmacSapProvider::AllocateNcRaPreambleReturnValue ns3::mmwave::MmWaveEnbMacMemberEnbCmacSapProvider::AllocateNcRaPreamble (uint16_t rnti) virtual
Definition at line 137 of file mmwave-enb-mac.cc.
References ns3::mmwave::MmWaveEnbMac::DoAllocateNcRaPreamble(), and m_mac.
ConfigureMac()
void ns3::mmwave::MmWaveEnbMacMemberEnbCmacSapProvider::ConfigureMac (uint8_t ulBandwidth, uint8_t dlBandwidth) virtual
Definition at line 89 of file mmwave-enb-mac.cc.
References ns3::mmwave::MmWaveEnbMac::DoConfigureMac(), and m_mac.
GetRachConfig()
LteEnbCmacSapProvider::RachConfig ns3::mmwave::MmWaveEnbMacMemberEnbCmacSapProvider::GetRachConfig () virtual
Definition at line 131 of file mmwave-enb-mac.cc.
References ns3::mmwave::MmWaveEnbMac::DoGetRachConfig(), and m_mac.
ReconfigureLc()
void ns3::mmwave::MmWaveEnbMacMemberEnbCmacSapProvider::ReconfigureLc (LcInfo lcinfo) virtual
Definition at line 113 of file mmwave-enb-mac.cc.
References ns3::mmwave::MmWaveEnbMac::DoReconfigureLc(), and m_mac.
ReleaseLc()
void ns3::mmwave::MmWaveEnbMacMemberEnbCmacSapProvider::ReleaseLc (uint16_t rnti, uint8_t lcid) virtual
Definition at line 119 of file mmwave-enb-mac.cc.
References ns3::mmwave::MmWaveEnbMac::DoReleaseLc(), and m_mac.
RemoveUe()
void ns3::mmwave::MmWaveEnbMacMemberEnbCmacSapProvider::RemoveUe (uint16_t rnti) virtual
Definition at line 101 of file mmwave-enb-mac.cc.
References ns3::mmwave::MmWaveEnbMac::DoRemoveUe(), and m_mac.
UeUpdateConfigurationReq()
void ns3::mmwave::MmWaveEnbMacMemberEnbCmacSapProvider::UeUpdateConfigurationReq (UeConfig params) virtual
Definition at line 125 of file mmwave-enb-mac.cc.
References m_mac, and ns3::mmwave::MmWaveEnbMac::UeUpdateConfigurationReq().
Member Data Documentation
m_mac
MmWaveEnbMac* ns3::mmwave::MmWaveEnbMacMemberEnbCmacSapProvider::m_mac private
Definition at line 79 of file mmwave-enb-mac.cc.
Referenced by AddLc(), AddUe(), AllocateNcRaPreamble(), ConfigureMac(), GetRachConfig(), ReconfigureLc(), ReleaseLc(), RemoveUe(), and UeUpdateConfigurationReq().
The documentation for this class was generated from the following file:
src/mmwave/model/mmwave-enb-mac.cc