ns3-mmwave: ns3::mmwave::MmWaveIdealHandoverCommandHeader Class Reference
ns3::mmwave::MmWaveIdealHandoverCommandHeader Class Reference
Public Member Functions
virtual uint32_t Deserialize (Buffer::Iterator start)
virtual TypeId GetInstanceTypeId (void) const
uint32_t GetMsgId ()
virtual uint32_t GetSerializedSize (void) const
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
void SetMsgId (uint32_t id)
Static Public Member Functions
static TypeId GetTypeId (void)
Private Attributes
uint32_t m_msgId
Detailed Description
Definition at line 590 of file mmwave-rrc-protocol-ideal.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::mmwave::MmWaveIdealHandoverCommandHeader::Deserialize (Buffer::Iterator start) virtual
Definition at line 650 of file mmwave-rrc-protocol-ideal.cc.
GetInstanceTypeId()
TypeId ns3::mmwave::MmWaveIdealHandoverCommandHeader::GetInstanceTypeId (void) const virtual
Definition at line 630 of file mmwave-rrc-protocol-ideal.cc.
References ns3::mmwave::MmWaveEnbRrcProtocolIdeal::GetTypeId().
GetMsgId()
uint32_t ns3::mmwave::MmWaveIdealHandoverCommandHeader::GetMsgId ()
Definition at line 607 of file mmwave-rrc-protocol-ideal.cc.
Referenced by ns3::mmwave::MmWaveEnbRrcProtocolIdeal::DoDecodeHandoverCommand().
GetSerializedSize()
uint32_t ns3::mmwave::MmWaveIdealHandoverCommandHeader::GetSerializedSize (void) const virtual
Definition at line 640 of file mmwave-rrc-protocol-ideal.cc.
GetTypeId()
TypeId ns3::mmwave::MmWaveIdealHandoverCommandHeader::GetTypeId (void) static
Definition at line 620 of file mmwave-rrc-protocol-ideal.cc.
Print()
void ns3::mmwave::MmWaveIdealHandoverCommandHeader::Print (std::ostream & os) const virtual
Definition at line 635 of file mmwave-rrc-protocol-ideal.cc.
Serialize()
void ns3::mmwave::MmWaveIdealHandoverCommandHeader::Serialize (Buffer::Iterator start) const virtual
Definition at line 645 of file mmwave-rrc-protocol-ideal.cc.
SetMsgId()
void ns3::mmwave::MmWaveIdealHandoverCommandHeader::SetMsgId (uint32_t id)
Definition at line 613 of file mmwave-rrc-protocol-ideal.cc.
Referenced by ns3::mmwave::MmWaveEnbRrcProtocolIdeal::DoEncodeHandoverCommand().
Member Data Documentation
m_msgId
uint32_t ns3::mmwave::MmWaveIdealHandoverCommandHeader::m_msgId private
Definition at line 603 of file mmwave-rrc-protocol-ideal.cc.
The documentation for this class was generated from the following file:
src/mmwave/model/mmwave-rrc-protocol-ideal.cc