ns3-mmwave: ns3::mmwave::MmWaveMacPduHeader Class Reference
ns3::mmwave::MmWaveMacPduHeader Class Reference
#include "mmwave-mac-pdu-header.h"
Public Member Functions
MmWaveMacPduHeader ()
Create an empty Mac header.
MmWaveMacPduHeader (uint16_t frameNo, uint8_t sfNo, uint8_t slotNo)
void AddSubheader (MacSubheader rlcPduInfo)
virtual uint32_t Deserialize (Buffer::Iterator i)
virtual TypeId GetInstanceTypeId (void) const
virtual uint32_t GetSerializedSize () const
std::vector< MacSubheader > GetSubheaders (void)
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator i) const
void SetSubheaders (std::vector< MacSubheader > macSubheaderList)
Static Public Member Functions
static TypeId GetTypeId (void)
Protected Attributes
uint32_t m_headerSize
std::vector< MacSubheader > m_subheaderList
Detailed Description
Definition at line 72 of file mmwave-mac-pdu-header.h.
Constructor & Destructor Documentation
MmWaveMacPduHeader() [1/2]
ns3::mmwave::MmWaveMacPduHeader::MmWaveMacPduHeader ()
Create an empty Mac header.
Definition at line 39 of file mmwave-mac-pdu-header.cc.
MmWaveMacPduHeader() [2/2]
ns3::mmwave::MmWaveMacPduHeader::MmWaveMacPduHeader (uint16_t frameNo, uint8_t sfNo, uint8_t slotNo)
Member Function Documentation
AddSubheader()
void ns3::mmwave::MmWaveMacPduHeader::AddSubheader (MacSubheader rlcPduInfo)
Definition at line 156 of file mmwave-mac-pdu-header.cc.
References m_headerSize, ns3::mmwave::MacSubheader::m_size, and m_subheaderList.
Deserialize()
uint32_t ns3::mmwave::MmWaveMacPduHeader::Deserialize (Buffer::Iterator i) virtual
Definition at line 108 of file mmwave-mac-pdu-header.cc.
References m_headerSize, and m_subheaderList.
GetInstanceTypeId()
TypeId ns3::mmwave::MmWaveMacPduHeader::GetInstanceTypeId (void) const virtual
Definition at line 53 of file mmwave-mac-pdu-header.cc.
References GetTypeId().
GetSerializedSize()
uint32_t ns3::mmwave::MmWaveMacPduHeader::GetSerializedSize (void) const virtual
Definition at line 59 of file mmwave-mac-pdu-header.cc.
References m_headerSize.
GetSubheaders()
std::vector<MacSubheader> ns3::mmwave::MmWaveMacPduHeader::GetSubheaders (void) inline
Definition at line 96 of file mmwave-mac-pdu-header.h.
Referenced by ns3::mmwave::MmWaveUeMac::DoReceivePhyPdu(), ns3::mmwave::MmWaveEnbMac::DoReceivePhyPdu(), and ns3::mmwave::MmWaveUeMac::DoTransmitPdu().
GetTypeId()
TypeId ns3::mmwave::MmWaveMacPduHeader::GetTypeId (void) static
Definition at line 44 of file mmwave-mac-pdu-header.cc.
Referenced by GetInstanceTypeId().
Print()
void ns3::mmwave::MmWaveMacPduHeader::Print (std::ostream & os) const virtual
Definition at line 151 of file mmwave-mac-pdu-header.cc.
Serialize()
void ns3::mmwave::MmWaveMacPduHeader::Serialize (Buffer::Iterator i) const virtual
Definition at line 65 of file mmwave-mac-pdu-header.cc.
References m_subheaderList.
SetSubheaders()
void ns3::mmwave::MmWaveMacPduHeader::SetSubheaders (std::vector< MacSubheader > macSubheaderList) inline
Definition at line 91 of file mmwave-mac-pdu-header.h.
Member Data Documentation
m_headerSize
uint32_t ns3::mmwave::MmWaveMacPduHeader::m_headerSize protected
Definition at line 103 of file mmwave-mac-pdu-header.h.
Referenced by AddSubheader(), Deserialize(), and GetSerializedSize().
m_subheaderList
std::vector<MacSubheader> ns3::mmwave::MmWaveMacPduHeader::m_subheaderList protected
Definition at line 102 of file mmwave-mac-pdu-header.h.
Referenced by AddSubheader(), Deserialize(), and Serialize().
The documentation for this class was generated from the following files:
src/mmwave/model/mmwave-mac-pdu-header.h
src/mmwave/model/mmwave-mac-pdu-header.cc