ns3-mmwave: ns3::mmwave::MmWaveFlexTtiMaxWeightMacSchedSapProvider Class Reference
ns3::mmwave::MmWaveFlexTtiMaxWeightMacSchedSapProvider Class Reference
Public Member Functions
MmWaveFlexTtiMaxWeightMacSchedSapProvider (MmWaveFlexTtiMaxWeightMacScheduler *sched)
virtual void SchedDlCqiInfoReq (const struct MmWaveMacSchedSapProvider::SchedDlCqiInfoReqParameters &params)
virtual void SchedDlRlcBufferReq (const struct MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters &params)
virtual void SchedSetMcs (int mcs)
virtual void SchedTriggerReq (const struct MmWaveMacSchedSapProvider::SchedTriggerReqParameters &params)
virtual void SchedUlCqiInfoReq (const struct MmWaveMacSchedSapProvider::SchedUlCqiInfoReqParameters &params)
virtual void SchedUlMacCtrlInfoReq (const struct MmWaveMacSchedSapProvider::SchedUlMacCtrlInfoReqParameters &params)
Public Member Functions inherited from ns3::mmwave::MmWaveMacSchedSapProvider
virtual ~MmWaveMacSchedSapProvider ()
virtual void SchedDlCqiInfoReq (const SchedDlCqiInfoReqParameters &params)=0
Private Member Functions
MmWaveFlexTtiMaxWeightMacSchedSapProvider ()
Private Attributes
MmWaveFlexTtiMaxWeightMacScheduler * m_scheduler
Detailed Description
Definition at line 86 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
Constructor & Destructor Documentation
MmWaveFlexTtiMaxWeightMacSchedSapProvider() [1/2]
ns3::mmwave::MmWaveFlexTtiMaxWeightMacSchedSapProvider::MmWaveFlexTtiMaxWeightMacSchedSapProvider (MmWaveFlexTtiMaxWeightMacScheduler * sched)
Definition at line 106 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
MmWaveFlexTtiMaxWeightMacSchedSapProvider() [2/2]
ns3::mmwave::MmWaveFlexTtiMaxWeightMacSchedSapProvider::MmWaveFlexTtiMaxWeightMacSchedSapProvider () private
Definition at line 102 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
Member Function Documentation
SchedDlCqiInfoReq()
void ns3::mmwave::MmWaveFlexTtiMaxWeightMacSchedSapProvider::SchedDlCqiInfoReq (const struct MmWaveMacSchedSapProvider::SchedDlCqiInfoReqParameters & params) virtual
Definition at line 124 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::DoSchedDlCqiInfoReq(), and m_scheduler.
SchedDlRlcBufferReq()
void ns3::mmwave::MmWaveFlexTtiMaxWeightMacSchedSapProvider::SchedDlRlcBufferReq (const struct MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters & params) virtual
Implements ns3::mmwave::MmWaveMacSchedSapProvider.
Definition at line 112 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::DoSchedDlRlcBufferReq(), and m_scheduler.
SchedSetMcs()
void ns3::mmwave::MmWaveFlexTtiMaxWeightMacSchedSapProvider::SchedSetMcs (int mcs) virtual
Reimplemented from ns3::mmwave::MmWaveMacSchedSapProvider.
Definition at line 142 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::DoSchedSetMcs(), ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_macHdrSize, ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_rlcHdrSize, m_scheduler, and ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_subHdrSize.
SchedTriggerReq()
void ns3::mmwave::MmWaveFlexTtiMaxWeightMacSchedSapProvider::SchedTriggerReq (const struct MmWaveMacSchedSapProvider::SchedTriggerReqParameters & params) virtual
Implements ns3::mmwave::MmWaveMacSchedSapProvider.
Definition at line 118 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::DoSchedTriggerReq(), and m_scheduler.
SchedUlCqiInfoReq()
void ns3::mmwave::MmWaveFlexTtiMaxWeightMacSchedSapProvider::SchedUlCqiInfoReq (const struct MmWaveMacSchedSapProvider::SchedUlCqiInfoReqParameters & params) virtual
Implements ns3::mmwave::MmWaveMacSchedSapProvider.
Definition at line 130 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::DoSchedUlCqiInfoReq(), and m_scheduler.
SchedUlMacCtrlInfoReq()
void ns3::mmwave::MmWaveFlexTtiMaxWeightMacSchedSapProvider::SchedUlMacCtrlInfoReq (const struct MmWaveMacSchedSapProvider::SchedUlMacCtrlInfoReqParameters & params) virtual
Implements ns3::mmwave::MmWaveMacSchedSapProvider.
Definition at line 136 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::DoSchedUlMacCtrlInfoReq(), and m_scheduler.
Member Data Documentation
m_scheduler
MmWaveFlexTtiMaxWeightMacScheduler* ns3::mmwave::MmWaveFlexTtiMaxWeightMacSchedSapProvider::m_scheduler private
Definition at line 99 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
Referenced by SchedDlCqiInfoReq(), SchedDlRlcBufferReq(), SchedSetMcs(), SchedTriggerReq(), SchedUlCqiInfoReq(), and SchedUlMacCtrlInfoReq().
The documentation for this class was generated from the following file:
src/mmwave/model/mmwave-flex-tti-maxweight-mac-scheduler.cc