ns3-mmwave: ns3::mmwave::MmWaveFlexTtiPfMacSchedSapProvider Class Reference
ns3::mmwave::MmWaveFlexTtiPfMacSchedSapProvider Class Reference
Public Member Functions
MmWaveFlexTtiPfMacSchedSapProvider (MmWaveFlexTtiPfMacScheduler *sched)
virtual void SchedDlCqiInfoReq (const struct MmWaveMacSchedSapProvider::SchedDlCqiInfoReqParameters &params)
virtual void SchedDlRlcBufferReq (const struct MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters &params)
virtual void SchedSetMcs (int mcs)
virtual void SchedTriggerReq (const struct MmWaveMacSchedSapProvider::SchedTriggerReqParameters &params)
virtual void SchedUlCqiInfoReq (const struct MmWaveMacSchedSapProvider::SchedUlCqiInfoReqParameters &params)
virtual void SchedUlMacCtrlInfoReq (const struct MmWaveMacSchedSapProvider::SchedUlMacCtrlInfoReqParameters &params)
Public Member Functions inherited from ns3::mmwave::MmWaveMacSchedSapProvider
virtual ~MmWaveMacSchedSapProvider ()
virtual void SchedDlCqiInfoReq (const SchedDlCqiInfoReqParameters &params)=0
Private Member Functions
MmWaveFlexTtiPfMacSchedSapProvider ()
Private Attributes
MmWaveFlexTtiPfMacScheduler * m_scheduler
Detailed Description
Definition at line 86 of file mmwave-flex-tti-pf-mac-scheduler.cc.
Constructor & Destructor Documentation
MmWaveFlexTtiPfMacSchedSapProvider() [1/2]
ns3::mmwave::MmWaveFlexTtiPfMacSchedSapProvider::MmWaveFlexTtiPfMacSchedSapProvider (MmWaveFlexTtiPfMacScheduler * sched)
Definition at line 106 of file mmwave-flex-tti-pf-mac-scheduler.cc.
MmWaveFlexTtiPfMacSchedSapProvider() [2/2]
ns3::mmwave::MmWaveFlexTtiPfMacSchedSapProvider::MmWaveFlexTtiPfMacSchedSapProvider () private
Definition at line 102 of file mmwave-flex-tti-pf-mac-scheduler.cc.
Member Function Documentation
SchedDlCqiInfoReq()
void ns3::mmwave::MmWaveFlexTtiPfMacSchedSapProvider::SchedDlCqiInfoReq (const struct MmWaveMacSchedSapProvider::SchedDlCqiInfoReqParameters & params) virtual
Definition at line 124 of file mmwave-flex-tti-pf-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiPfMacScheduler::DoSchedDlCqiInfoReq(), and m_scheduler.
SchedDlRlcBufferReq()
void ns3::mmwave::MmWaveFlexTtiPfMacSchedSapProvider::SchedDlRlcBufferReq (const struct MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters & params) virtual
Implements ns3::mmwave::MmWaveMacSchedSapProvider.
Definition at line 112 of file mmwave-flex-tti-pf-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiPfMacScheduler::DoSchedDlRlcBufferReq(), and m_scheduler.
SchedSetMcs()
void ns3::mmwave::MmWaveFlexTtiPfMacSchedSapProvider::SchedSetMcs (int mcs) virtual
Reimplemented from ns3::mmwave::MmWaveMacSchedSapProvider.
Definition at line 142 of file mmwave-flex-tti-pf-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiPfMacScheduler::DoSchedSetMcs(), ns3::mmwave::MmWaveFlexTtiPfMacScheduler::m_macHdrSize, ns3::mmwave::MmWaveFlexTtiPfMacScheduler::m_rlcHdrSize, m_scheduler, and ns3::mmwave::MmWaveFlexTtiPfMacScheduler::m_subHdrSize.
SchedTriggerReq()
void ns3::mmwave::MmWaveFlexTtiPfMacSchedSapProvider::SchedTriggerReq (const struct MmWaveMacSchedSapProvider::SchedTriggerReqParameters & params) virtual
Implements ns3::mmwave::MmWaveMacSchedSapProvider.
Definition at line 118 of file mmwave-flex-tti-pf-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiPfMacScheduler::DoSchedTriggerReq(), and m_scheduler.
SchedUlCqiInfoReq()
void ns3::mmwave::MmWaveFlexTtiPfMacSchedSapProvider::SchedUlCqiInfoReq (const struct MmWaveMacSchedSapProvider::SchedUlCqiInfoReqParameters & params) virtual
Implements ns3::mmwave::MmWaveMacSchedSapProvider.
Definition at line 130 of file mmwave-flex-tti-pf-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiPfMacScheduler::DoSchedUlCqiInfoReq(), and m_scheduler.
SchedUlMacCtrlInfoReq()
void ns3::mmwave::MmWaveFlexTtiPfMacSchedSapProvider::SchedUlMacCtrlInfoReq (const struct MmWaveMacSchedSapProvider::SchedUlMacCtrlInfoReqParameters & params) virtual
Implements ns3::mmwave::MmWaveMacSchedSapProvider.
Definition at line 136 of file mmwave-flex-tti-pf-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiPfMacScheduler::DoSchedUlMacCtrlInfoReq(), and m_scheduler.
Member Data Documentation
m_scheduler
MmWaveFlexTtiPfMacScheduler* ns3::mmwave::MmWaveFlexTtiPfMacSchedSapProvider::m_scheduler private
Definition at line 99 of file mmwave-flex-tti-pf-mac-scheduler.cc.
Referenced by SchedDlCqiInfoReq(), SchedDlRlcBufferReq(), SchedSetMcs(), SchedTriggerReq(), SchedUlCqiInfoReq(), and SchedUlMacCtrlInfoReq().
The documentation for this class was generated from the following file:
src/mmwave/model/mmwave-flex-tti-pf-mac-scheduler.cc