ns3-mmwave: ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler Class Reference
ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler Class Reference
#include "mmwave-flex-tti-maxweight-mac-scheduler.h"
Classes
struct AllocMapElem
struct FlowStats
struct UeSchedInfo
struct UlCqiMapElem
Public Types
typedef std::vector< DciInfoElementTdma > DlHarqProcessesDciInfoList_t
typedef std::vector< uint8_t > DlHarqProcessesStatus_t
typedef std::vector< uint8_t > DlHarqProcessesTimer_t
typedef std::vector< std::vector< struct RlcPduInfo > > DlHarqRlcPduList_t
typedef std::vector< DciInfoElementTdma > UlHarqProcessesDciInfoList_t
typedef std::vector< uint8_t > UlHarqProcessesStatus_t
typedef std::vector< uint8_t > UlHarqProcessesTimer_t
Public Member Functions
MmWaveFlexTtiMaxWeightMacScheduler ()
virtual ~MmWaveFlexTtiMaxWeightMacScheduler ()
virtual void ConfigureCommonParameters (Ptr< MmWavePhyMacCommon > config) override
virtual void DoDispose (void) override
virtual MmWaveMacCschedSapProvider * GetMacCschedSapProvider () override
virtual MmWaveMacSchedSapProvider * GetMacSchedSapProvider () override
void RefreshDlCqiMaps (void)
void RefreshUlCqiMaps (void)
virtual void SetMacCschedSapUser (MmWaveMacCschedSapUser *s) override
virtual void SetMacSchedSapUser (MmWaveMacSchedSapUser *sap) override
void UpdateDlRlcBufferInfo (uint16_t rnti, uint8_t lcid, uint16_t size)
void UpdateUlRlcBufferInfo (uint16_t rnti, uint16_t size)
Public Member Functions inherited from ns3::mmwave::MmWaveMacScheduler
MmWaveMacScheduler ()
virtual ~MmWaveMacScheduler ()
Static Public Member Functions
static TypeId GetTypeId (void)
static bool SortRlcBufferReq (MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters i, MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters j)
Static Public Member Functions inherited from ns3::mmwave::MmWaveMacScheduler
static TypeId GetTypeId (void)
Private Types
enum AlgType { EDF, DELIVERY_DEBT }
Private Member Functions
uint32_t BsrId2BufferSize (uint8_t val)
uint8_t BufferSize2BsrId (uint32_t val)
unsigned CalcMinTbSizeNumSym (unsigned mcs, unsigned bufSize, unsigned &tbSize)
void DoCschedCellConfigReq (const struct MmWaveMacCschedSapProvider::CschedCellConfigReqParameters &params)
void DoCschedLcConfigReq (const struct MmWaveMacCschedSapProvider::CschedLcConfigReqParameters &params)
void DoCschedLcReleaseReq (const struct MmWaveMacCschedSapProvider::CschedLcReleaseReqParameters &params)
void DoCschedUeConfigReq (const struct MmWaveMacCschedSapProvider::CschedUeConfigReqParameters &params)
void DoCschedUeReleaseReq (const struct MmWaveMacCschedSapProvider::CschedUeReleaseReqParameters &params)
void DoSchedDlCqiInfoReq (const MmWaveMacSchedSapProvider::SchedDlCqiInfoReqParameters &params)
void DoSchedDlRlcBufferReq (const struct MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters &params)
bool DoSchedDlTriggerReq (const struct MmWaveMacSchedSapProvider::SchedTriggerReqParameters &params, MmWaveMacSchedSapUser::SchedConfigIndParameters &ret, unsigned int frameNum, unsigned int sfNum, unsigned int islot)
void DoSchedSetMcs (int mcs)
void DoSchedTriggerReq (const struct MmWaveMacSchedSapProvider::SchedTriggerReqParameters &params)
void DoSchedUlCqiInfoReq (const struct MmWaveMacSchedSapProvider::SchedUlCqiInfoReqParameters &params)
void DoSchedUlMacCtrlInfoReq (const struct MmWaveMacSchedSapProvider::SchedUlMacCtrlInfoReqParameters &params)
bool DoSchedUlTriggerReq (const struct MmWaveMacSchedSapProvider::SchedTriggerReqParameters &params, MmWaveMacSchedSapUser::SchedConfigIndParameters &ret, unsigned int frameNum, unsigned int sfNum, unsigned int islot)
void RefreshHarqProcesses ()
Refresh HARQ processes according to the timers.
uint8_t UpdateDlHarqProcessId (uint16_t rnti)
uint8_t UpdateUlHarqProcessId (uint16_t rnti)
Static Private Member Functions
static bool CompareFlowWeightsDeliveryDebt (FlowStats *lflow, FlowStats *rflow)
static bool CompareFlowWeightsEdf (FlowStats *lflow, FlowStats *rflow)
Private Attributes
enum ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::AlgType m_algorithm
Ptr< MmWaveAmc > m_amc
double m_berDl
std::map< uint16_t, uint32_t > m_ceBsrRxed
uint32_t m_cqiTimersThreshold
MmWaveMacCschedSapProvider::CschedCellConfigReqParameters m_cschedCellConfig
std::map< uint16_t, uint8_t > m_dlHarqCurrentProcessId
std::vector< DlHarqInfo > m_dlHarqInfoList
std::map< uint16_t, DlHarqProcessesDciInfoList_t > m_dlHarqProcessesDciInfoMap
std::map< uint16_t, DlHarqRlcPduList_t > m_dlHarqProcessesRlcPduMap
std::map< uint16_t, DlHarqProcessesStatus_t > m_dlHarqProcessesStatus
std::map< uint16_t, DlHarqProcessesTimer_t > m_dlHarqProcessesTimer
bool m_dlOnly
bool m_fixedMcsDl
bool m_fixedMcsUl
bool m_fixedTti
std::vector< FlowStats * > m_flowHeap
uint32_t m_frameNo
bool m_harqOn
m_harqOn when false inhibit te HARQ mechanisms (by default active)
uint8_t m_harqTimeout
MmWaveMacCschedSapProvider * m_macCschedSapProvider
MmWaveMacCschedSapUser * m_macCschedSapUser
MmWaveMacSchedSapProvider * m_macSchedSapProvider
MmWaveMacSchedSapUser * m_macSchedSapUser
uint8_t m_mcsDefaultDl
uint8_t m_mcsDefaultUl
uint16_t m_nextRnti
uint64_t m_nextRntiDl
uint64_t m_nextRntiUl
uint32_t m_numChunks
uint32_t m_numDataSymbols
uint8_t m_numHarqProcess
std::list< MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters > m_rlcBufferReq
uint8_t m_symPerSlot
uint8_t m_tbUid
std::map< uint16_t, uint32_t > m_ueCqiTimers
std::map< uint16_t, UeSchedInfo > m_ueSchedInfoMap
std::map< uint16_t, struct UlCqiMapElem > m_ueUlCqi
std::map< uint32_t, struct AllocMapElem > m_ulAllocationMap
std::map< uint16_t, uint8_t > m_ulHarqCurrentProcessId
std::vector< UlHarqInfo > m_ulHarqInfoList
std::map< uint16_t, UlHarqProcessesDciInfoList_t > m_ulHarqProcessesDciInfoMap
std::map< uint16_t, UlHarqProcessesStatus_t > m_ulHarqProcessesStatus
std::map< uint16_t, UlHarqProcessesTimer_t > m_ulHarqProcessesTimer
bool m_ulOnly
std::list< struct SlotAllocInfo > m_ulSfAllocInfo
std::map< uint16_t, uint8_t > m_wbCqiRxed
std::map< uint16_t, uint32_t > m_wbCqiTimers
Static Private Attributes
static const unsigned m_macHdrSize = 0
static const unsigned m_rlcHdrSize = 3
static const unsigned m_subHdrSize = 4
Friends
class MmWaveFlexTtiMaxWeightMacCschedSapProvider
class MmWaveFlexTtiMaxWeightMacSchedSapProvider
Additional Inherited Members
Protected Attributes inherited from ns3::mmwave::MmWaveMacScheduler
Ptr< MmWavePhyMacCommon > m_phyMacConfig
uint32_t m_rbgSize
Detailed Description
Definition at line 26 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Member Typedef Documentation
DlHarqProcessesDciInfoList_t
typedef std::vector< DciInfoElementTdma > ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::DlHarqProcessesDciInfoList_t
Definition at line 31 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
DlHarqProcessesStatus_t
typedef std::vector< uint8_t > ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::DlHarqProcessesStatus_t
Definition at line 29 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
DlHarqProcessesTimer_t
typedef std::vector< uint8_t > ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::DlHarqProcessesTimer_t
Definition at line 30 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
DlHarqRlcPduList_t
typedef std::vector< std::vector <struct RlcPduInfo> > ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::DlHarqRlcPduList_t
Definition at line 32 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
UlHarqProcessesDciInfoList_t
typedef std::vector< DciInfoElementTdma > ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::UlHarqProcessesDciInfoList_t
Definition at line 36 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
UlHarqProcessesStatus_t
typedef std::vector< uint8_t > ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::UlHarqProcessesStatus_t
Definition at line 37 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
UlHarqProcessesTimer_t
typedef std::vector< uint8_t > ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::UlHarqProcessesTimer_t
Definition at line 35 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Member Enumeration Documentation
AlgType
enum ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::AlgType private
Enumerator
EDF
DELIVERY_DEBT
Definition at line 435 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Constructor & Destructor Documentation
MmWaveFlexTtiMaxWeightMacScheduler()
ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::MmWaveFlexTtiMaxWeightMacScheduler ()
Definition at line 151 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
References m_macCschedSapProvider, m_macSchedSapProvider, MmWaveFlexTtiMaxWeightMacCschedSapProvider, and MmWaveFlexTtiMaxWeightMacSchedSapProvider.
~MmWaveFlexTtiMaxWeightMacScheduler()
ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::~MmWaveFlexTtiMaxWeightMacScheduler () virtual
Definition at line 162 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
Member Function Documentation
BsrId2BufferSize()
uint32_t ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::BsrId2BufferSize (uint8_t val) inline private
Definition at line 231 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
References ns3::mmwave::BufferSizeLevelBsrTable.
Referenced by DoSchedUlMacCtrlInfoReq().
BufferSize2BsrId()
uint8_t ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::BufferSize2BsrId (uint32_t val) inline private
Definition at line 238 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
References ns3::mmwave::BufferSizeLevelBsrTable, DoCschedCellConfigReq(), DoCschedLcConfigReq(), DoCschedLcReleaseReq(), DoCschedUeConfigReq(), DoCschedUeReleaseReq(), DoSchedDlCqiInfoReq(), DoSchedDlRlcBufferReq(), DoSchedDlTriggerReq(), DoSchedSetMcs(), DoSchedTriggerReq(), DoSchedUlCqiInfoReq(), DoSchedUlMacCtrlInfoReq(), DoSchedUlTriggerReq(), RefreshHarqProcesses(), UpdateDlHarqProcessId(), and UpdateUlHarqProcessId().
CalcMinTbSizeNumSym()
unsigned ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::CalcMinTbSizeNumSym (unsigned mcs, unsigned bufSize, unsigned & tbSize) private
Definition at line 700 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
References m_amc, and ns3::mmwave::MmWaveMacScheduler::m_phyMacConfig.
Referenced by CompareFlowWeightsDeliveryDebt().
CompareFlowWeightsDeliveryDebt()
static bool ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::CompareFlowWeightsDeliveryDebt (FlowStats * lflow, FlowStats * rflow) inline static private
Definition at line 221 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
References CalcMinTbSizeNumSym(), ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::FlowStats::m_arrivalRate, ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::FlowStats::m_grantedRate, and ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::FlowStats::m_probErr.
CompareFlowWeightsEdf()
static bool ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::CompareFlowWeightsEdf (FlowStats * lflow, FlowStats * rflow) inline static private
Definition at line 214 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
References ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::FlowStats::m_deadlineUs, and ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::FlowStats::m_txQueueHolDelay.
Referenced by DoSchedTriggerReq().
ConfigureCommonParameters()
void ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::ConfigureCommonParameters (Ptr< MmWavePhyMacCommon > config) override virtual
Implements ns3::mmwave::MmWaveMacScheduler.
Definition at line 277 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
References m_amc, m_harqTimeout, m_numDataSymbols, m_numHarqProcess, and ns3::mmwave::MmWaveMacScheduler::m_phyMacConfig.
DoCschedCellConfigReq()
void ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::DoCschedCellConfigReq (const struct MmWaveMacCschedSapProvider::CschedCellConfigReqParameters & params) private
Definition at line 1631 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
References ns3::mmwave::MmWaveMacCschedSapUser::CschedUeConfigCnf(), m_cschedCellConfig, m_macCschedSapUser, and ns3::mmwave::MmWaveMacCschedSapUser::CschedUeConfigCnfParameters::m_result.
Referenced by BufferSize2BsrId(), and ns3::mmwave::MmWaveFlexTtiMaxWeightMacCschedSapProvider::CschedCellConfigReq().
DoCschedLcConfigReq()
void ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::DoCschedLcConfigReq (const struct MmWaveMacCschedSapProvider::CschedLcConfigReqParameters & params) private
Definition at line 1692 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
References m_flowHeap, ns3::mmwave::MmWaveMacCschedSapProvider::CschedLcConfigReqParameters::m_logicalChannelConfigList, ns3::mmwave::MmWaveMacCschedSapProvider::CschedLcConfigReqParameters::m_rnti, and m_ueSchedInfoMap.
Referenced by BufferSize2BsrId(), and ns3::mmwave::MmWaveFlexTtiMaxWeightMacCschedSapProvider::CschedLcConfigReq().
DoCschedLcReleaseReq()
void ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::DoCschedLcReleaseReq (const struct MmWaveMacCschedSapProvider::CschedLcReleaseReqParameters & params) private
Definition at line 1765 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
References ns3::mmwave::MmWaveMacCschedSapProvider::CschedLcReleaseReqParameters::m_logicalChannelIdentity, m_rlcBufferReq, and ns3::mmwave::MmWaveMacCschedSapProvider::CschedLcReleaseReqParameters::m_rnti.
Referenced by BufferSize2BsrId(), and ns3::mmwave::MmWaveFlexTtiMaxWeightMacCschedSapProvider::CschedLcReleaseReq().
DoCschedUeConfigReq()
void ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::DoCschedUeConfigReq (const struct MmWaveMacCschedSapProvider::CschedUeConfigReqParameters & params) private
Definition at line 1644 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
References m_dlHarqProcessesDciInfoMap, m_dlHarqProcessesRlcPduMap, m_dlHarqProcessesStatus, m_dlHarqProcessesTimer, ns3::mmwave::MmWaveMacScheduler::m_phyMacConfig, ns3::mmwave::MmWaveMacCschedSapProvider::CschedUeConfigReqParameters::m_rnti, ns3::mmwave::MmWaveMacCschedSapProvider::CschedUeConfigReqParameters::m_transmissionMode, m_ueSchedInfoMap, m_ulHarqProcessesDciInfoMap, m_ulHarqProcessesStatus, and m_ulHarqProcessesTimer.
Referenced by BufferSize2BsrId(), and ns3::mmwave::MmWaveFlexTtiMaxWeightMacCschedSapProvider::CschedUeConfigReq().
DoCschedUeReleaseReq()
void ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::DoCschedUeReleaseReq (const struct MmWaveMacCschedSapProvider::CschedUeReleaseReqParameters & params) private
Definition at line 1787 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
References m_ceBsrRxed, m_dlHarqProcessesDciInfoMap, m_dlHarqProcessesRlcPduMap, m_dlHarqProcessesStatus, m_dlHarqProcessesTimer, m_nextRntiDl, m_nextRntiUl, m_rlcBufferReq, ns3::mmwave::MmWaveMacCschedSapProvider::CschedUeReleaseReqParameters::m_rnti, m_ulHarqProcessesDciInfoMap, m_ulHarqProcessesStatus, and m_ulHarqProcessesTimer.
Referenced by BufferSize2BsrId(), and ns3::mmwave::MmWaveFlexTtiMaxWeightMacCschedSapProvider::CschedUeReleaseReq().
DoDispose()
void ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::DoDispose (void) override virtual
Reimplemented from ns3::mmwave::MmWaveMacScheduler.
Definition at line 168 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
References m_dlHarqInfoList, m_dlHarqProcessesDciInfoMap, m_dlHarqProcessesRlcPduMap, m_dlHarqProcessesTimer, m_macCschedSapProvider, m_macSchedSapProvider, m_ulHarqCurrentProcessId, m_ulHarqProcessesDciInfoMap, m_ulHarqProcessesStatus, m_ulHarqProcessesTimer, and m_wbCqiRxed.
DoSchedDlCqiInfoReq()
void ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::DoSchedDlCqiInfoReq (const MmWaveMacSchedSapProvider::SchedDlCqiInfoReqParameters & params) private
Definition at line 406 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
References ns3::mmwave::MmWaveMacSchedSapProvider::SchedDlCqiInfoReqParameters::m_cqiList, m_cqiTimersThreshold, m_wbCqiRxed, m_wbCqiTimers, ns3::mmwave::DlCqiInfo::SB, and ns3::mmwave::DlCqiInfo::WB.
Referenced by BufferSize2BsrId(), and ns3::mmwave::MmWaveFlexTtiMaxWeightMacSchedSapProvider::SchedDlCqiInfoReq().
DoSchedDlRlcBufferReq()
void ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::DoSchedDlRlcBufferReq (const struct MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters & params) private
Definition at line 288 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
References ns3::mmwave::MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters::m_logicalChannelIdentity, ns3::mmwave::MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters::m_rnti, ns3::mmwave::MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters::m_txPacketDelays, ns3::mmwave::MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters::m_txPacketSizes, and m_ueSchedInfoMap.
Referenced by BufferSize2BsrId(), and ns3::mmwave::MmWaveFlexTtiMaxWeightMacSchedSapProvider::SchedDlRlcBufferReq().
DoSchedDlTriggerReq()
bool ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::DoSchedDlTriggerReq (const struct MmWaveMacSchedSapProvider::SchedTriggerReqParameters & params, MmWaveMacSchedSapUser::SchedConfigIndParameters & ret, unsigned int frameNum, unsigned int sfNum, unsigned int islot) private
Referenced by BufferSize2BsrId().
DoSchedSetMcs()
void ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::DoSchedSetMcs (int mcs) private
Definition at line 529 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
References m_mcsDefaultDl, and m_mcsDefaultUl.
Referenced by BufferSize2BsrId(), and ns3::mmwave::MmWaveFlexTtiMaxWeightMacSchedSapProvider::SchedSetMcs().
DoSchedTriggerReq()
void ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::DoSchedTriggerReq (const struct MmWaveMacSchedSapProvider::SchedTriggerReqParameters & params) private
Definition at line 752 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
References ns3::mmwave::DlHarqInfo::ACK, CompareFlowWeightsEdf(), ns3::mmwave::TtiAllocInfo::CTRL, ns3::mmwave::TtiAllocInfo::CTRL_DATA, ns3::mmwave::TtiAllocInfo::DL_slotAllocInfo, EDF, ns3::mmwave::SfnSf::Encode(), ns3::mmwave::MmWaveSpectrumValueHelper::GetSpectrumModel(), m_algorithm, m_amc, ns3::mmwave::TtiAllocInfo::m_dci, ns3::mmwave::MmWaveMacSchedSapProvider::SchedTriggerReqParameters::m_dlHarqInfoList, m_dlHarqInfoList, m_dlHarqProcessesDciInfoMap, m_dlHarqProcessesRlcPduMap, m_dlHarqProcessesStatus, m_dlHarqProcessesTimer, ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::UeSchedInfo::m_dlMcs, ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::UeSchedInfo::m_dlSymbols, ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::UeSchedInfo::m_dlTbSize, m_fixedTti, m_flowHeap, ns3::mmwave::DciInfoElementTdma::m_format, ns3::mmwave::SfnSf::m_frameNum, m_harqOn, ns3::mmwave::DciInfoElementTdma::m_harqProcess, ns3::mmwave::UlHarqInfo::m_harqProcessId, ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::FlowStats::m_isUplink, ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::FlowStats::m_lcid, m_macSchedSapUser, ns3::mmwave::DciInfoElementTdma::m_mcs, ns3::mmwave::DciInfoElementTdma::m_ndi, ns3::mmwave::DciInfoElementTdma::m_numSym, ns3::mmwave::SlotAllocInfo::m_numSymAlloc, ns3::mmwave::MmWaveMacScheduler::m_phyMacConfig, ns3::mmwave::UlHarqInfo::m_receptionStatus, m_rlcHdrSize, ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::UeSchedInfo::m_rlcPduInfo, ns3::mmwave::TtiAllocInfo::m_rlcPduInfo, ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::UeSchedInfo::m_rnti, ns3::mmwave::DciInfoElementTdma::m_rnti, ns3::mmwave::UlHarqInfo::m_rnti, ns3::mmwave::DciInfoElementTdma::m_rv, ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::FlowStats::m_schedPacketSizes, ns3::mmwave::MmWaveMacSchedSapUser::SchedConfigIndParameters::m_sfnSf, ns3::mmwave::SlotAllocInfo::m_sfnSf, ns3::mmwave::SfnSf::m_sfNum, ns3::mmwave::MmWaveMacSchedSapUser::SchedConfigIndParameters::m_slotAllocInfo, ns3::mmwave::SfnSf::m_slotNum, ns3::mmwave::MmWaveMacSchedSapProvider::SchedTriggerReqParameters::m_snfSf, m_subHdrSize, m_symPerSlot, ns3::mmwave::DciInfoElementTdma::m_symStart, ns3::mmwave::DciInfoElementTdma::m_tbSize, ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::FlowStats::m_totalBufSize, ns3::mmwave::SlotAllocInfo::m_ttiAllocInfo, ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::FlowStats::m_txPacketDelays, ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::FlowStats::m_txPacketSizes, ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::FlowStats::m_txQueueHolDelay, ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::FlowStats::m_ueSchedInfo, m_ueSchedInfoMap, m_ueUlCqi, m_ulAllocationMap, ns3::mmwave::MmWaveMacSchedSapProvider::SchedTriggerReqParameters::m_ulHarqInfoList, m_ulHarqInfoList, m_ulHarqProcessesDciInfoMap, m_ulHarqProcessesStatus, m_ulHarqProcessesTimer, ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::UeSchedInfo::m_ulMcs, ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::UeSchedInfo::m_ulSymbols, ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::UeSchedInfo::m_ulTbSize, m_wbCqiRxed, ns3::mmwave::DlHarqInfo::NACK, ns3::mmwave::UlHarqInfo::NotOk, ns3::mmwave::UlHarqInfo::Ok, RefreshDlCqiMaps(), RefreshHarqProcesses(), RefreshUlCqiMaps(), ns3::mmwave::MmWaveMacSchedSapUser::SchedConfigInd(), ns3::mmwave::TtiAllocInfo::UL_slotAllocInfo, UpdateDlHarqProcessId(), and UpdateUlHarqProcessId().
Referenced by BufferSize2BsrId(), and ns3::mmwave::MmWaveFlexTtiMaxWeightMacSchedSapProvider::SchedTriggerReq().
DoSchedUlCqiInfoReq()
void ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::DoSchedUlCqiInfoReq (const struct MmWaveMacSchedSapProvider::SchedUlCqiInfoReqParameters & params) private
Definition at line 450 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
References ns3::mmwave::SfnSf::Encode(), m_cqiTimersThreshold, ns3::mmwave::SfnSf::m_frameNum, ns3::mmwave::MmWaveMacScheduler::m_phyMacConfig, ns3::mmwave::MmWaveMacSchedSapProvider::SchedUlCqiInfoReqParameters::m_sfnSf, ns3::mmwave::SfnSf::m_sfNum, ns3::mmwave::UlCqiInfo::m_sinr, ns3::mmwave::SfnSf::m_slotNum, ns3::mmwave::SfnSf::m_symStart, ns3::mmwave::UlCqiInfo::m_type, m_ueCqiTimers, m_ueUlCqi, m_ulAllocationMap, ns3::mmwave::MmWaveMacSchedSapProvider::SchedUlCqiInfoReqParameters::m_ulCqi, and ns3::mmwave::UlCqiInfo::PUSCH.
Referenced by BufferSize2BsrId(), and ns3::mmwave::MmWaveFlexTtiMaxWeightMacSchedSapProvider::SchedUlCqiInfoReq().
DoSchedUlMacCtrlInfoReq()
void ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::DoSchedUlMacCtrlInfoReq (const struct MmWaveMacSchedSapProvider::SchedUlMacCtrlInfoReqParameters & params) private
Definition at line 349 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
References ns3::mmwave::MacCeElement::BSR, BsrId2BufferSize(), ns3::mmwave::MmWaveMacSchedSapProvider::SchedUlMacCtrlInfoReqParameters::m_macCeList, ns3::mmwave::MmWaveMacScheduler::m_phyMacConfig, and m_ueSchedInfoMap.
Referenced by BufferSize2BsrId(), and ns3::mmwave::MmWaveFlexTtiMaxWeightMacSchedSapProvider::SchedUlMacCtrlInfoReq().
DoSchedUlTriggerReq()
bool ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::DoSchedUlTriggerReq (const struct MmWaveMacSchedSapProvider::SchedTriggerReqParameters & params, MmWaveMacSchedSapUser::SchedConfigIndParameters & ret, unsigned int frameNum, unsigned int sfNum, unsigned int islot) private
Referenced by BufferSize2BsrId().
GetMacCschedSapProvider()
MmWaveMacCschedSapProvider * ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::GetMacCschedSapProvider () override virtual
Implements ns3::mmwave::MmWaveMacScheduler.
Definition at line 271 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
References m_macCschedSapProvider.
GetMacSchedSapProvider()
MmWaveMacSchedSapProvider * ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::GetMacSchedSapProvider () override virtual
Implements ns3::mmwave::MmWaveMacScheduler.
Definition at line 265 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
References m_macSchedSapProvider.
GetTypeId()
TypeId ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::GetTypeId (void) static
Definition at line 185 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
References DELIVERY_DEBT, EDF, m_algorithm, m_cqiTimersThreshold, m_dlOnly, m_fixedMcsDl, m_fixedMcsUl, m_fixedTti, m_harqOn, m_mcsDefaultDl, m_mcsDefaultUl, m_symPerSlot, and m_ulOnly.
RefreshDlCqiMaps()
void ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::RefreshDlCqiMaps (void)
Definition at line 1493 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
References m_cqiTimersThreshold, m_wbCqiRxed, and m_wbCqiTimers.
Referenced by DoSchedTriggerReq().
RefreshHarqProcesses()
void ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::RefreshHarqProcesses () private
Refresh HARQ processes according to the timers.
Definition at line 539 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
References m_dlHarqProcessesStatus, m_dlHarqProcessesTimer, ns3::mmwave::MmWaveMacScheduler::m_phyMacConfig, m_ulHarqProcessesStatus, and m_ulHarqProcessesTimer.
Referenced by BufferSize2BsrId(), and DoSchedTriggerReq().
RefreshUlCqiMaps()
void ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::RefreshUlCqiMaps (void)
Definition at line 1524 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
References m_cqiTimersThreshold, m_ueCqiTimers, and m_ueUlCqi.
Referenced by DoSchedTriggerReq().
SetMacCschedSapUser()
void ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::SetMacCschedSapUser (MmWaveMacCschedSapUser * s) override virtual
Implements ns3::mmwave::MmWaveMacScheduler.
Definition at line 258 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
References m_macCschedSapUser.
SetMacSchedSapUser()
void ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::SetMacSchedSapUser (MmWaveMacSchedSapUser * sap) override virtual
Implements ns3::mmwave::MmWaveMacScheduler.
Definition at line 252 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
References m_macSchedSapUser.
SortRlcBufferReq()
bool ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::SortRlcBufferReq (MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters i, MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters j) static
Definition at line 1486 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
References ns3::mmwave::MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters::m_rnti.
UpdateDlHarqProcessId()
uint8_t ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::UpdateDlHarqProcessId (uint16_t rnti) private
Definition at line 592 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
References m_dlHarqProcessesStatus, m_harqOn, ns3::mmwave::MmWaveMacScheduler::m_phyMacConfig, and m_tbUid.
Referenced by BufferSize2BsrId(), and DoSchedTriggerReq().
UpdateDlRlcBufferInfo()
void ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::UpdateDlRlcBufferInfo (uint16_t rnti, uint8_t lcid, uint16_t size)
Definition at line 1554 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
References m_rlcBufferReq.
UpdateUlHarqProcessId()
uint8_t ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::UpdateUlHarqProcessId (uint16_t rnti) private
Definition at line 648 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
References m_harqOn, ns3::mmwave::MmWaveMacScheduler::m_phyMacConfig, m_tbUid, and m_ulHarqProcessesStatus.
Referenced by BufferSize2BsrId(), and DoSchedTriggerReq().
UpdateUlRlcBufferInfo()
void ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::UpdateUlRlcBufferInfo (uint16_t rnti, uint16_t size)
Definition at line 1605 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
References m_ceBsrRxed.
Friends And Related Function Documentation
MmWaveFlexTtiMaxWeightMacCschedSapProvider
friend class MmWaveFlexTtiMaxWeightMacCschedSapProvider friend
Definition at line 63 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by MmWaveFlexTtiMaxWeightMacScheduler().
MmWaveFlexTtiMaxWeightMacSchedSapProvider
friend class MmWaveFlexTtiMaxWeightMacSchedSapProvider friend
Definition at line 62 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by MmWaveFlexTtiMaxWeightMacScheduler().
Member Data Documentation
m_algorithm
enum ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::AlgType ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_algorithm private
Referenced by DoSchedTriggerReq(), and GetTypeId().
m_amc
Ptr<MmWaveAmc> ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_amc private
Definition at line 309 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by CalcMinTbSizeNumSym(), ConfigureCommonParameters(), and DoSchedTriggerReq().
m_berDl
double ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_berDl private
Definition at line 423 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
m_ceBsrRxed
std::map<uint16_t,uint32_t> ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_ceBsrRxed private
Definition at line 352 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by DoCschedUeReleaseReq(), and UpdateUlRlcBufferInfo().
m_cqiTimersThreshold
uint32_t ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_cqiTimersThreshold private
Definition at line 325 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by DoSchedDlCqiInfoReq(), DoSchedUlCqiInfoReq(), GetTypeId(), RefreshDlCqiMaps(), and RefreshUlCqiMaps().
m_cschedCellConfig
MmWaveMacCschedSapProvider::CschedCellConfigReqParameters ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_cschedCellConfig private
Definition at line 368 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by DoCschedCellConfigReq().
m_dlHarqCurrentProcessId
std::map<uint16_t, uint8_t> ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_dlHarqCurrentProcessId private
Definition at line 397 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
m_dlHarqInfoList
std::vector<DlHarqInfo> ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_dlHarqInfoList private
Definition at line 405 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by DoDispose(), and DoSchedTriggerReq().
m_dlHarqProcessesDciInfoMap
std::map<uint16_t, DlHarqProcessesDciInfoList_t> ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_dlHarqProcessesDciInfoMap private
Definition at line 403 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by DoCschedUeConfigReq(), DoCschedUeReleaseReq(), DoDispose(), and DoSchedTriggerReq().
m_dlHarqProcessesRlcPduMap
std::map<uint16_t, DlHarqRlcPduList_t> ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_dlHarqProcessesRlcPduMap private
Definition at line 404 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by DoCschedUeConfigReq(), DoCschedUeReleaseReq(), DoDispose(), and DoSchedTriggerReq().
m_dlHarqProcessesStatus
std::map<uint16_t, DlHarqProcessesStatus_t> ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_dlHarqProcessesStatus private
Definition at line 401 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by DoCschedUeConfigReq(), DoCschedUeReleaseReq(), DoSchedTriggerReq(), RefreshHarqProcesses(), and UpdateDlHarqProcessId().
m_dlHarqProcessesTimer
std::map<uint16_t, DlHarqProcessesTimer_t> ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_dlHarqProcessesTimer private
Definition at line 402 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by DoCschedUeConfigReq(), DoCschedUeReleaseReq(), DoDispose(), DoSchedTriggerReq(), and RefreshHarqProcesses().
m_dlOnly
bool ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_dlOnly private
Definition at line 430 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by GetTypeId().
m_fixedMcsDl
bool ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_fixedMcsDl private
Definition at line 426 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by GetTypeId().
m_fixedMcsUl
bool ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_fixedMcsUl private
Definition at line 427 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by GetTypeId().
m_fixedTti
bool ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_fixedTti private
Definition at line 444 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by DoSchedTriggerReq(), and GetTypeId().
m_flowHeap
std::vector<FlowStats*> ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_flowHeap private
Definition at line 442 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by DoCschedLcConfigReq(), and DoSchedTriggerReq().
m_frameNo
uint32_t ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_frameNo private
Definition at line 358 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
m_harqOn
bool ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_harqOn private
m_harqOn when false inhibit te HARQ mechanisms (by default active)
Definition at line 393 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by DoSchedTriggerReq(), GetTypeId(), UpdateDlHarqProcessId(), and UpdateUlHarqProcessId().
m_harqTimeout
uint8_t ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_harqTimeout private
Definition at line 395 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by ConfigureCommonParameters().
m_macCschedSapProvider
MmWaveMacCschedSapProvider* ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_macCschedSapProvider private
Definition at line 366 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by DoDispose(), GetMacCschedSapProvider(), and MmWaveFlexTtiMaxWeightMacScheduler().
m_macCschedSapUser
MmWaveMacCschedSapUser* ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_macCschedSapUser private
Definition at line 365 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by DoCschedCellConfigReq(), and SetMacCschedSapUser().
m_macHdrSize
const unsigned ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_macHdrSize = 0 static private
Definition at line 419 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by ns3::mmwave::MmWaveFlexTtiMaxWeightMacSchedSapProvider::SchedSetMcs().
m_macSchedSapProvider
MmWaveMacSchedSapProvider* ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_macSchedSapProvider private
Definition at line 363 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by DoDispose(), GetMacSchedSapProvider(), and MmWaveFlexTtiMaxWeightMacScheduler().
m_macSchedSapUser
MmWaveMacSchedSapUser* ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_macSchedSapUser private
Definition at line 364 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by DoSchedTriggerReq(), and SetMacSchedSapUser().
m_mcsDefaultDl
uint8_t ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_mcsDefaultDl private
Definition at line 428 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by DoSchedSetMcs(), and GetTypeId().
m_mcsDefaultUl
uint8_t ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_mcsDefaultUl private
Definition at line 429 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by DoSchedSetMcs(), and GetTypeId().
m_nextRnti
uint16_t ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_nextRnti private
Definition at line 354 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
m_nextRntiDl
uint64_t ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_nextRntiDl private
Definition at line 355 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by DoCschedUeReleaseReq().
m_nextRntiUl
uint64_t ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_nextRntiUl private
Definition at line 356 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by DoCschedUeReleaseReq().
m_numChunks
uint32_t ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_numChunks private
Definition at line 360 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
m_numDataSymbols
uint32_t ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_numDataSymbols private
Definition at line 361 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by ConfigureCommonParameters().
m_numHarqProcess
uint8_t ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_numHarqProcess private
Definition at line 394 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by ConfigureCommonParameters().
m_rlcBufferReq
std::list<MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters> ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_rlcBufferReq private
Definition at line 314 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by DoCschedLcReleaseReq(), DoCschedUeReleaseReq(), and UpdateDlRlcBufferInfo().
m_rlcHdrSize
const unsigned ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_rlcHdrSize = 3 static private
Definition at line 421 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by DoSchedTriggerReq(), and ns3::mmwave::MmWaveFlexTtiMaxWeightMacSchedSapProvider::SchedSetMcs().
m_subHdrSize
const unsigned ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_subHdrSize = 4 static private
Definition at line 420 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by DoSchedTriggerReq(), and ns3::mmwave::MmWaveFlexTtiMaxWeightMacSchedSapProvider::SchedSetMcs().
m_symPerSlot
uint8_t ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_symPerSlot private
Definition at line 445 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by DoSchedTriggerReq(), and GetTypeId().
m_tbUid
uint8_t ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_tbUid private
Definition at line 359 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by UpdateDlHarqProcessId(), and UpdateUlHarqProcessId().
m_ueCqiTimers
std::map<uint16_t, uint32_t> ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_ueCqiTimers private
Definition at line 347 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by DoSchedUlCqiInfoReq(), and RefreshUlCqiMaps().
m_ueSchedInfoMap
std::map<uint16_t, UeSchedInfo> ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_ueSchedInfoMap private
Definition at line 433 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by DoCschedLcConfigReq(), DoCschedUeConfigReq(), DoSchedDlRlcBufferReq(), DoSchedTriggerReq(), and DoSchedUlMacCtrlInfoReq().
m_ueUlCqi
std::map<uint16_t, struct UlCqiMapElem> ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_ueUlCqi private
Definition at line 343 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by DoSchedTriggerReq(), DoSchedUlCqiInfoReq(), and RefreshUlCqiMaps().
m_ulAllocationMap
std::map<uint32_t, struct AllocMapElem> ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_ulAllocationMap private
Definition at line 387 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by DoSchedTriggerReq(), and DoSchedUlCqiInfoReq().
m_ulHarqCurrentProcessId
std::map<uint16_t, uint8_t> ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_ulHarqCurrentProcessId private
Definition at line 408 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by DoDispose().
m_ulHarqInfoList
std::vector<UlHarqInfo> ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_ulHarqInfoList private
Definition at line 406 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by DoSchedTriggerReq().
m_ulHarqProcessesDciInfoMap
std::map<uint16_t, UlHarqProcessesDciInfoList_t> ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_ulHarqProcessesDciInfoMap private
Definition at line 414 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by DoCschedUeConfigReq(), DoCschedUeReleaseReq(), DoDispose(), and DoSchedTriggerReq().
m_ulHarqProcessesStatus
std::map<uint16_t, UlHarqProcessesStatus_t> ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_ulHarqProcessesStatus private
Definition at line 412 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by DoCschedUeConfigReq(), DoCschedUeReleaseReq(), DoDispose(), DoSchedTriggerReq(), RefreshHarqProcesses(), and UpdateUlHarqProcessId().
m_ulHarqProcessesTimer
std::map<uint16_t, UlHarqProcessesTimer_t> ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_ulHarqProcessesTimer private
Definition at line 413 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by DoCschedUeConfigReq(), DoCschedUeReleaseReq(), DoDispose(), DoSchedTriggerReq(), and RefreshHarqProcesses().
m_ulOnly
bool ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_ulOnly private
Definition at line 431 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by GetTypeId().
m_ulSfAllocInfo
std::list<struct SlotAllocInfo> ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_ulSfAllocInfo private
Definition at line 417 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
m_wbCqiRxed
std::map<uint16_t,uint8_t> ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_wbCqiRxed private
Definition at line 319 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by DoDispose(), DoSchedDlCqiInfoReq(), DoSchedTriggerReq(), and RefreshDlCqiMaps().
m_wbCqiTimers
std::map<uint16_t,uint32_t> ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::m_wbCqiTimers private
Definition at line 323 of file mmwave-flex-tti-maxweight-mac-scheduler.h.
Referenced by DoSchedDlCqiInfoReq(), and RefreshDlCqiMaps().
The documentation for this class was generated from the following files:
src/mmwave/model/mmwave-flex-tti-maxweight-mac-scheduler.h
src/mmwave/model/mmwave-flex-tti-maxweight-mac-scheduler.cc