ns3-mmwave: ns3::mmwave::MacUeMemberPhySapUser Class Reference
ns3::mmwave::MacUeMemberPhySapUser Class Reference
Public Member Functions
MacUeMemberPhySapUser (MmWaveUeMac *mac)
virtual void ReceiveControlMessage (Ptr< MmWaveControlMessage > msg)
Receive SendLteControlMessage (PDCCH map, CQI feedbacks) using the ideal control channel.
virtual void ReceivePhyPdu (Ptr< Packet > p)
Called by the Phy to notify the MAC of the reception of a new PHY-PDU.
virtual void SetConfigurationParameters (Ptr< MmWavePhyMacCommon > params)
When PHY connects to a new eNB, update the configuration parameters.
virtual void SlotIndication (SfnSf sfn)
Send from the PHY layer the current frame, subframe, slot numbers and the current starting OFDM symbol within the slot.
Public Member Functions inherited from ns3::mmwave::MmWaveUePhySapUser
virtual ~MmWaveUePhySapUser ()
Private Attributes
MmWaveUeMac * m_mac
Detailed Description
Definition at line 159 of file mmwave-ue-mac.cc.
Constructor & Destructor Documentation
MacUeMemberPhySapUser()
ns3::mmwave::MacUeMemberPhySapUser::MacUeMemberPhySapUser (MmWaveUeMac * mac)
Definition at line 180 of file mmwave-ue-mac.cc.
Member Function Documentation
ReceiveControlMessage()
void ns3::mmwave::MacUeMemberPhySapUser::ReceiveControlMessage (Ptr< MmWaveControlMessage > msg) virtual
Receive SendLteControlMessage (PDCCH map, CQI feedbacks) using the ideal control channel.
Parameters
msg the Ideal Control Message to receive
Implements ns3::mmwave::MmWaveUePhySapUser.
Definition at line 192 of file mmwave-ue-mac.cc.
References ns3::mmwave::MmWaveUeMac::DoReceiveControlMessage(), and m_mac.
ReceivePhyPdu()
void ns3::mmwave::MacUeMemberPhySapUser::ReceivePhyPdu (Ptr< Packet > p) virtual
Called by the Phy to notify the MAC of the reception of a new PHY-PDU.
Parameters
p
Implements ns3::mmwave::MmWaveUePhySapUser.
Definition at line 186 of file mmwave-ue-mac.cc.
References ns3::mmwave::MmWaveUeMac::DoReceivePhyPdu(), and m_mac.
SetConfigurationParameters()
void ns3::mmwave::MacUeMemberPhySapUser::SetConfigurationParameters (Ptr< MmWavePhyMacCommon > params) virtual
When PHY connects to a new eNB, update the configuration parameters.
Implements ns3::mmwave::MmWaveUePhySapUser.
Definition at line 204 of file mmwave-ue-mac.cc.
References m_mac, and ns3::mmwave::MmWaveUeMac::SetConfigurationParameters().
SlotIndication()
void ns3::mmwave::MacUeMemberPhySapUser::SlotIndication (SfnSf snf) virtual
Send from the PHY layer the current frame, subframe, slot numbers and the current starting OFDM symbol within the slot.
Parameters
snf The current frame, subframe, slot and starting OFDM symbol counters
Implements ns3::mmwave::MmWaveUePhySapUser.
Definition at line 198 of file mmwave-ue-mac.cc.
References ns3::mmwave::MmWaveUeMac::DoSlotIndication(), and m_mac.
Member Data Documentation
m_mac
MmWaveUeMac* ns3::mmwave::MacUeMemberPhySapUser::m_mac private
Definition at line 177 of file mmwave-ue-mac.cc.
Referenced by ReceiveControlMessage(), ReceivePhyPdu(), SetConfigurationParameters(), and SlotIndication().
The documentation for this class was generated from the following file:
src/mmwave/model/mmwave-ue-mac.cc