ns3-mmwave: ns3::mmwave::MmWaveMacSchedSapProvider Class Reference
ns3::mmwave::MmWaveMacSchedSapProvider Class Reference abstract
#include "mmwave-mac-sched-sap.h"
Classes
struct SchedDlCqiInfoReqParameters
struct SchedDlRlcBufferReqParameters
struct SchedTriggerReqParameters
struct SchedUlCqiInfoReqParameters
struct SchedUlMacCtrlInfoReqParameters
Public Member Functions
virtual ~MmWaveMacSchedSapProvider ()
virtual void SchedDlCqiInfoReq (const SchedDlCqiInfoReqParameters &params)=0
virtual void SchedDlRlcBufferReq (const struct SchedDlRlcBufferReqParameters &params)=0
virtual void SchedSetMcs (int mcs)
virtual void SchedTriggerReq (const struct SchedTriggerReqParameters &params)=0
virtual void SchedUlCqiInfoReq (const struct SchedUlCqiInfoReqParameters &params)=0
virtual void SchedUlMacCtrlInfoReq (const struct SchedUlMacCtrlInfoReqParameters &params)=0
Detailed Description
Definition at line 40 of file mmwave-mac-sched-sap.h.
Constructor & Destructor Documentation
~MmWaveMacSchedSapProvider()
ns3::mmwave::MmWaveMacSchedSapProvider::~MmWaveMacSchedSapProvider () virtual
Definition at line 36 of file mmwave-mac-sched-sap.cc.
Member Function Documentation
SchedDlCqiInfoReq()
virtual void ns3::mmwave::MmWaveMacSchedSapProvider::SchedDlCqiInfoReq (const SchedDlCqiInfoReqParameters & params) pure virtual
Referenced by ns3::mmwave::MmWaveEnbMac::DoSlotIndication().
SchedDlRlcBufferReq()
virtual void ns3::mmwave::MmWaveMacSchedSapProvider::SchedDlRlcBufferReq (const struct SchedDlRlcBufferReqParameters & params) pure virtual
Implemented in ns3::mmwave::MmWaveFlexTtiMacSchedSapProvider, ns3::mmwave::MmWaveFlexTtiMaxRateMacSchedSapProvider, ns3::mmwave::MmWaveFlexTtiMaxWeightMacSchedSapProvider, and ns3::mmwave::MmWaveFlexTtiPfMacSchedSapProvider.
Referenced by ns3::mmwave::MmWaveEnbMac::DoReportBufferStatus().
SchedSetMcs()
virtual void ns3::mmwave::MmWaveMacSchedSapProvider::SchedSetMcs (int mcs) inline virtual
Reimplemented in ns3::mmwave::MmWaveFlexTtiMacSchedSapProvider, ns3::mmwave::MmWaveFlexTtiMaxRateMacSchedSapProvider, ns3::mmwave::MmWaveFlexTtiMaxWeightMacSchedSapProvider, and ns3::mmwave::MmWaveFlexTtiPfMacSchedSapProvider.
Definition at line 98 of file mmwave-mac-sched-sap.h.
Referenced by ns3::mmwave::MmWaveEnbMac::SetMcs().
SchedTriggerReq()
virtual void ns3::mmwave::MmWaveMacSchedSapProvider::SchedTriggerReq (const struct SchedTriggerReqParameters & params) pure virtual
Implemented in ns3::mmwave::MmWaveFlexTtiMacSchedSapProvider, ns3::mmwave::MmWaveFlexTtiMaxRateMacSchedSapProvider, ns3::mmwave::MmWaveFlexTtiMaxWeightMacSchedSapProvider, and ns3::mmwave::MmWaveFlexTtiPfMacSchedSapProvider.
Referenced by ns3::mmwave::MmWaveEnbMac::DoSlotIndication().
SchedUlCqiInfoReq()
virtual void ns3::mmwave::MmWaveMacSchedSapProvider::SchedUlCqiInfoReq (const struct SchedUlCqiInfoReqParameters & params) pure virtual
Implemented in ns3::mmwave::MmWaveFlexTtiMacSchedSapProvider, ns3::mmwave::MmWaveFlexTtiMaxRateMacSchedSapProvider, ns3::mmwave::MmWaveFlexTtiMaxWeightMacSchedSapProvider, and ns3::mmwave::MmWaveFlexTtiPfMacSchedSapProvider.
Referenced by ns3::mmwave::MmWaveEnbMac::DoSlotIndication().
SchedUlMacCtrlInfoReq()
virtual void ns3::mmwave::MmWaveMacSchedSapProvider::SchedUlMacCtrlInfoReq (const struct SchedUlMacCtrlInfoReqParameters & params) pure virtual
Implemented in ns3::mmwave::MmWaveFlexTtiMacSchedSapProvider, ns3::mmwave::MmWaveFlexTtiMaxRateMacSchedSapProvider, ns3::mmwave::MmWaveFlexTtiMaxWeightMacSchedSapProvider, and ns3::mmwave::MmWaveFlexTtiPfMacSchedSapProvider.
Referenced by ns3::mmwave::MmWaveEnbMac::DoSlotIndication().
The documentation for this class was generated from the following files:
src/mmwave/model/mmwave-mac-sched-sap.h
src/mmwave/model/mmwave-mac-sched-sap.cc