ns3-mmwave: ns3::mmwave::MmWaveIdealHandoverPreparationInfoHeader Class Reference
ns3::mmwave::MmWaveIdealHandoverPreparationInfoHeader Class Reference
Public Member Functions
virtual uint32_t Deserialize (Buffer::Iterator start)
virtual TypeId GetInstanceTypeId (void) const
uint32_t GetMsgId ()
virtual uint32_t GetSerializedSize (void) const
virtual void Print (std::ostream &os) const
virtual void Serialize (Buffer::Iterator start) const
void SetMsgId (uint32_t id)
Static Public Member Functions
static TypeId GetTypeId (void)
Private Attributes
uint32_t m_msgId
Detailed Description
Definition at line 484 of file mmwave-rrc-protocol-ideal.cc.
Member Function Documentation
Deserialize()
uint32_t ns3::mmwave::MmWaveIdealHandoverPreparationInfoHeader::Deserialize (Buffer::Iterator start) virtual
Definition at line 544 of file mmwave-rrc-protocol-ideal.cc.
GetInstanceTypeId()
TypeId ns3::mmwave::MmWaveIdealHandoverPreparationInfoHeader::GetInstanceTypeId (void) const virtual
Definition at line 524 of file mmwave-rrc-protocol-ideal.cc.
References ns3::mmwave::MmWaveEnbRrcProtocolIdeal::GetTypeId().
GetMsgId()
uint32_t ns3::mmwave::MmWaveIdealHandoverPreparationInfoHeader::GetMsgId ()
Definition at line 501 of file mmwave-rrc-protocol-ideal.cc.
Referenced by ns3::mmwave::MmWaveEnbRrcProtocolIdeal::DoDecodeHandoverPreparationInformation().
GetSerializedSize()
uint32_t ns3::mmwave::MmWaveIdealHandoverPreparationInfoHeader::GetSerializedSize (void) const virtual
Definition at line 534 of file mmwave-rrc-protocol-ideal.cc.
GetTypeId()
TypeId ns3::mmwave::MmWaveIdealHandoverPreparationInfoHeader::GetTypeId (void) static
Definition at line 514 of file mmwave-rrc-protocol-ideal.cc.
Print()
void ns3::mmwave::MmWaveIdealHandoverPreparationInfoHeader::Print (std::ostream & os) const virtual
Definition at line 529 of file mmwave-rrc-protocol-ideal.cc.
Serialize()
void ns3::mmwave::MmWaveIdealHandoverPreparationInfoHeader::Serialize (Buffer::Iterator start) const virtual
Definition at line 539 of file mmwave-rrc-protocol-ideal.cc.
SetMsgId()
void ns3::mmwave::MmWaveIdealHandoverPreparationInfoHeader::SetMsgId (uint32_t id)
Definition at line 507 of file mmwave-rrc-protocol-ideal.cc.
Referenced by ns3::mmwave::MmWaveEnbRrcProtocolIdeal::DoEncodeHandoverPreparationInformation().
Member Data Documentation
m_msgId
uint32_t ns3::mmwave::MmWaveIdealHandoverPreparationInfoHeader::m_msgId private
Definition at line 497 of file mmwave-rrc-protocol-ideal.cc.
The documentation for this class was generated from the following file:
src/mmwave/model/mmwave-rrc-protocol-ideal.cc