ns3-mmwave: ns3::mmwave::MmWaveEnbNetDevice Class Reference
ns3::mmwave::MmWaveEnbNetDevice Class Reference
#include "mmwave-enb-net-device.h"
Public Member Functions
MmWaveEnbNetDevice ()
virtual ~MmWaveEnbNetDevice (void)
virtual void DoDispose (void) override
virtual bool DoSend (Ptr< Packet > packet, const Address &dest, uint16_t protocolNumber) override
uint8_t GetBandwidth () const
uint16_t GetCellId () const
Ptr< MmWaveEnbMac > GetMac (void)
Ptr< MmWaveEnbMac > GetMac (uint8_t index)
Ptr< MmWaveEnbPhy > GetPhy (void) const
Ptr< MmWaveEnbPhy > GetPhy (uint8_t index)
Ptr< LteEnbRrc > GetRrc (void)
bool HasCellId (uint16_t cellId) const
void SetBandwidth (uint8_t bw)
void SetCcMap (std::map< uint8_t, Ptr< MmWaveComponentCarrier > > ccm) override
void SetRrc (Ptr< LteEnbRrc > rrc)
Public Member Functions inherited from ns3::mmwave::MmWaveNetDevice
MmWaveNetDevice (void)
virtual ~MmWaveNetDevice (void)
virtual void AddLinkChangeCallback (Callback< void > callback) override
virtual Address GetAddress (void) const override
Ptr< ThreeGppAntennaArrayModel > GetAntenna (uint8_t ccId) const
Get the antenna for the component carrier.
virtual uint16_t GetAntennaNum () const
virtual Address GetBroadcast (void) const override
virtual std::map< uint8_t, Ptr< MmWaveComponentCarrier > > GetCcMap () const
virtual Ptr< Channel > GetChannel (void) const override
virtual uint16_t GetEarfcn () const
virtual uint32_t GetIfIndex (void) const override
virtual uint16_t GetMtu (void) const override
virtual Address GetMulticast (Ipv4Address multicastGroup) const override
virtual Address GetMulticast (Ipv6Address addr) const override
virtual Ptr< Node > GetNode (void) const override
Ipv4Address GetPacketDestination (Ptr< Packet > packet)
virtual bool IsBridge (void) const override
virtual bool IsBroadcast (void) const override
virtual bool IsLinkUp (void) const override
virtual bool IsMulticast (void) const override
virtual bool IsPointToPoint (void) const override
virtual bool NeedsArp (void) const override
void Receive (Ptr< Packet > p)
virtual bool Send (Ptr< Packet > packet, const Address &dest, uint16_t protocolNumber) override
virtual bool SendFrom (Ptr< Packet > packet, const Address &source, const Address &dest, uint16_t protocolNumber) override
virtual void SetAddress (Address address) override
virtual void SetAntennaNum (uint16_t antennaNum)
virtual void SetEarfcn (uint16_t earfcn)
virtual void SetIfIndex (const uint32_t index) override
virtual bool SetMtu (const uint16_t mtu) override
virtual void SetNode (Ptr< Node > node) override
virtual void SetPromiscReceiveCallback (PromiscReceiveCallback cb) override
virtual void SetReceiveCallback (ReceiveCallback cb) override
virtual bool SupportsSendFrom (void) const override
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::mmwave::MmWaveNetDevice
static TypeId GetTypeId (void)
Protected Member Functions
virtual void DoInitialize (void) override
void UpdateConfig ()
Private Attributes
uint8_t m_Bandwidth
uint16_t m_cellId
Ptr< LteEnbComponentCarrierManager > m_componentCarrierManager
the component carrier manager of this eNb
bool m_isConfigured
Ptr< LteEnbRrc > m_rrc
Ptr< MmWaveMacScheduler > m_scheduler
Additional Inherited Members
Protected Attributes inherited from ns3::mmwave::MmWaveNetDevice
uint16_t m_antennaNum
Number of antenna elements for the device.
std::map< uint8_t, Ptr< MmWaveComponentCarrier > > m_ccMap
ComponentCarrier map.
uint16_t m_earfcn
Carrier frequency.
bool m_isConstructed
indicates if the object has been initialized
NetDevice::ReceiveCallback m_rxCallback
Detailed Description
Definition at line 63 of file mmwave-enb-net-device.h.
Constructor & Destructor Documentation
MmWaveEnbNetDevice()
ns3::mmwave::MmWaveEnbNetDevice::MmWaveEnbNetDevice ()
Definition at line 89 of file mmwave-enb-net-device.cc.
~MmWaveEnbNetDevice()
ns3::mmwave::MmWaveEnbNetDevice::~MmWaveEnbNetDevice (void) virtual
Definition at line 99 of file mmwave-enb-net-device.cc.
Member Function Documentation
DoDispose()
void ns3::mmwave::MmWaveEnbNetDevice::DoDispose (void) override virtual
Reimplemented from ns3::mmwave::MmWaveNetDevice.
Definition at line 119 of file mmwave-enb-net-device.cc.
References ns3::mmwave::MmWaveNetDevice::DoDispose(), ns3::mmwave::MmWaveNetDevice::m_ccMap, m_componentCarrierManager, and m_rrc.
DoInitialize()
void ns3::mmwave::MmWaveEnbNetDevice::DoInitialize (void) override protected virtual
Definition at line 105 of file mmwave-enb-net-device.cc.
References ns3::mmwave::MmWaveNetDevice::m_ccMap, m_componentCarrierManager, ns3::mmwave::MmWaveNetDevice::m_isConstructed, m_rrc, and UpdateConfig().
DoSend()
bool ns3::mmwave::MmWaveEnbNetDevice::DoSend (Ptr< Packet > packet, const Address & dest, uint16_t protocolNumber) override virtual
Implements ns3::mmwave::MmWaveNetDevice.
Definition at line 213 of file mmwave-enb-net-device.cc.
References m_rrc.
GetBandwidth()
uint8_t ns3::mmwave::MmWaveEnbNetDevice::GetBandwidth () const
Definition at line 175 of file mmwave-enb-net-device.cc.
References m_Bandwidth.
GetCellId()
uint16_t ns3::mmwave::MmWaveEnbNetDevice::GetCellId () const
Definition at line 154 of file mmwave-enb-net-device.cc.
References m_cellId.
Referenced by ns3::mmwave::MmWavePointToPointEpcHelper::AddX2Interface(), ns3::mmwave::MmWaveHelper::AttachIrToClosestEnb(), and ns3::mmwave::MmWaveHelper::AttachToEnbWithIndex().
GetMac() [1/2]
Ptr< MmWaveEnbMac > ns3::mmwave::MmWaveEnbNetDevice::GetMac (void)
Definition at line 189 of file mmwave-enb-net-device.cc.
References ns3::mmwave::MmWaveNetDevice::m_ccMap.
Referenced by GetMac().
GetMac() [2/2]
Ptr< MmWaveEnbMac > ns3::mmwave::MmWaveEnbNetDevice::GetMac (uint8_t index)
Definition at line 195 of file mmwave-enb-net-device.cc.
References GetMac(), and ns3::mmwave::MmWaveNetDevice::m_ccMap.
GetPhy() [1/2]
Ptr< MmWaveEnbPhy > ns3::mmwave::MmWaveEnbNetDevice::GetPhy (void) const
Definition at line 140 of file mmwave-enb-net-device.cc.
References ns3::mmwave::MmWaveNetDevice::m_ccMap.
Referenced by GetPhy().
GetPhy() [2/2]
Ptr< MmWaveEnbPhy > ns3::mmwave::MmWaveEnbNetDevice::GetPhy (uint8_t index)
Definition at line 147 of file mmwave-enb-net-device.cc.
References GetPhy(), and ns3::mmwave::MmWaveNetDevice::m_ccMap.
GetRrc()
Ptr< LteEnbRrc > ns3::mmwave::MmWaveEnbNetDevice::GetRrc (void)
Definition at line 207 of file mmwave-enb-net-device.cc.
References m_rrc.
GetTypeId()
TypeId ns3::mmwave::MmWaveEnbNetDevice::GetTypeId (void) static
Definition at line 63 of file mmwave-enb-net-device.cc.
References m_cellId, m_componentCarrierManager, and m_rrc.
Referenced by ns3::mmwave::MmWaveHelper::MmWaveHelper().
HasCellId()
bool ns3::mmwave::MmWaveEnbNetDevice::HasCellId (uint16_t cellId) const
Definition at line 161 of file mmwave-enb-net-device.cc.
References ns3::mmwave::MmWaveNetDevice::m_ccMap.
SetBandwidth()
void ns3::mmwave::MmWaveEnbNetDevice::SetBandwidth (uint8_t bw)
Definition at line 182 of file mmwave-enb-net-device.cc.
References m_Bandwidth.
SetCcMap()
void ns3::mmwave::MmWaveEnbNetDevice::SetCcMap (std::map< uint8_t, Ptr< MmWaveComponentCarrier > > ccm) override virtual
Reimplemented from ns3::mmwave::MmWaveNetDevice.
Definition at line 265 of file mmwave-enb-net-device.cc.
References ns3::mmwave::MmWaveNetDevice::m_ccMap, and m_isConfigured.
SetRrc()
void ns3::mmwave::MmWaveEnbNetDevice::SetRrc (Ptr< LteEnbRrc > rrc)
Definition at line 201 of file mmwave-enb-net-device.cc.
References m_rrc.
UpdateConfig()
void ns3::mmwave::MmWaveEnbNetDevice::UpdateConfig (void) protected
Definition at line 223 of file mmwave-enb-net-device.cc.
References ns3::mmwave::MmWaveNetDevice::m_ccMap, m_cellId, m_isConfigured, ns3::mmwave::MmWaveNetDevice::m_isConstructed, and m_rrc.
Referenced by DoInitialize().
Member Data Documentation
m_Bandwidth
uint8_t ns3::mmwave::MmWaveEnbNetDevice::m_Bandwidth private
Definition at line 108 of file mmwave-enb-net-device.h.
Referenced by GetBandwidth(), and SetBandwidth().
m_cellId
uint16_t ns3::mmwave::MmWaveEnbNetDevice::m_cellId private
Definition at line 106 of file mmwave-enb-net-device.h.
Referenced by GetCellId(), GetTypeId(), and UpdateConfig().
m_componentCarrierManager
Ptr<LteEnbComponentCarrierManager> ns3::mmwave::MmWaveEnbNetDevice::m_componentCarrierManager private
the component carrier manager of this eNb
Definition at line 110 of file mmwave-enb-net-device.h.
Referenced by DoDispose(), DoInitialize(), and GetTypeId().
m_isConfigured
bool ns3::mmwave::MmWaveEnbNetDevice::m_isConfigured private
Definition at line 112 of file mmwave-enb-net-device.h.
Referenced by SetCcMap(), and UpdateConfig().
m_rrc
Ptr<LteEnbRrc> ns3::mmwave::MmWaveEnbNetDevice::m_rrc private
Definition at line 104 of file mmwave-enb-net-device.h.
Referenced by DoDispose(), DoInitialize(), DoSend(), GetRrc(), GetTypeId(), SetRrc(), and UpdateConfig().
m_scheduler
Ptr<MmWaveMacScheduler> ns3::mmwave::MmWaveEnbNetDevice::m_scheduler private
Definition at line 102 of file mmwave-enb-net-device.h.
The documentation for this class was generated from the following files:
src/mmwave/model/mmwave-enb-net-device.h
src/mmwave/model/mmwave-enb-net-device.cc