ns3-mmwave: ns3::mmwave::MmWaveSpectrumValueHelper Class Reference
ns3::mmwave::MmWaveSpectrumValueHelper Class Reference
This class defines all functions to create spectrum model for mmwave.
#include "mmwave-spectrum-value-helper.h"
Static Public Member Functions
static Ptr< SpectrumValue > CreateNoisePowerSpectralDensity (Ptr< MmWavePhyMacCommon > ptrConfig, double noiseFigure)
static Ptr< SpectrumValue > CreateNoisePowerSpectralDensity (double noiseFigure, Ptr< SpectrumModel > spectrumModel)
static Ptr< SpectrumValue > CreateTxPowerSpectralDensity (Ptr< MmWavePhyMacCommon > ptrConfig, double powerTx, std::vector< int > activeRbs)
static Ptr< SpectrumValue > CreateTxPowerSpectralDensity (Ptr< MmWavePhyMacCommon > ptrConfig, double powerTx, std::map< int, double > powerTxMap, std::vector< int > activeRbs)
static Ptr< SpectrumModel > GetSpectrumModel (Ptr< MmWavePhyMacCommon > ptrConfig)
Static Private Attributes
static std::map< uint8_t, Ptr< SpectrumModel > > m_model
Detailed Description
This class defines all functions to create spectrum model for mmwave.
Definition at line 51 of file mmwave-spectrum-value-helper.h.
Member Function Documentation
CreateNoisePowerSpectralDensity() [1/2]
Ptr< SpectrumValue > ns3::mmwave::MmWaveSpectrumValueHelper::CreateNoisePowerSpectralDensity (Ptr< MmWavePhyMacCommon > ptrConfig, double noiseFigure) static
Definition at line 125 of file mmwave-spectrum-value-helper.cc.
References GetSpectrumModel().
Referenced by ns3::mmwave::MmWaveEnbPhy::DoInitialize(), ns3::mmwave::MmWaveUePhy::RegisterToEnb(), and ns3::mmwave::MmWaveEnbPhy::UpdateUeSinrEstimate().
CreateNoisePowerSpectralDensity() [2/2]
Ptr< SpectrumValue > ns3::mmwave::MmWaveSpectrumValueHelper::CreateNoisePowerSpectralDensity (double noiseFigure, Ptr< SpectrumModel > spectrumModel) static
Definition at line 133 of file mmwave-spectrum-value-helper.cc.
CreateTxPowerSpectralDensity() [1/2]
Ptr< SpectrumValue > ns3::mmwave::MmWaveSpectrumValueHelper::CreateTxPowerSpectralDensity (Ptr< MmWavePhyMacCommon > ptrConfig, double powerTx, std::vector< int > activeRbs) static
Definition at line 94 of file mmwave-spectrum-value-helper.cc.
References GetSpectrumModel().
Referenced by ns3::mmwave::MmWaveEnbPhy::CreateTxPowerSpectralDensity(), ns3::mmwave::MmWaveUePhy::CreateTxPowerSpectralDensity(), and ns3::mmwave::MmWaveEnbPhy::UpdateUeSinrEstimate().
CreateTxPowerSpectralDensity() [2/2]
Ptr< SpectrumValue > ns3::mmwave::MmWaveSpectrumValueHelper::CreateTxPowerSpectralDensity (Ptr< MmWavePhyMacCommon > ptrConfig, double powerTx, std::map< int, double > powerTxMap, std::vector< int > activeRbs) static
Definition at line 116 of file mmwave-spectrum-value-helper.cc.
GetSpectrumModel()
Ptr< SpectrumModel > ns3::mmwave::MmWaveSpectrumValueHelper::GetSpectrumModel (Ptr< MmWavePhyMacCommon > ptrConfig) static
Definition at line 56 of file mmwave-spectrum-value-helper.cc.
References m_model.
Referenced by CreateNoisePowerSpectralDensity(), CreateTxPowerSpectralDensity(), ns3::mmwave::MmWaveFlexTtiMacScheduler::DoSchedTriggerReq(), ns3::mmwave::MmWaveFlexTtiPfMacScheduler::DoSchedTriggerReq(), ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::DoSchedTriggerReq(), and ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::DoSchedTriggerReq().
Member Data Documentation
m_model
std::map< uint8_t, Ptr< SpectrumModel > > ns3::mmwave::MmWaveSpectrumValueHelper::m_model static private
Definition at line 73 of file mmwave-spectrum-value-helper.h.
Referenced by GetSpectrumModel().
The documentation for this class was generated from the following files:
src/mmwave/model/mmwave-spectrum-value-helper.h
src/mmwave/model/mmwave-spectrum-value-helper.cc