ns3-mmwave: ns3::mmwave::MmWaveEnbRrcProtocolIdeal Class Reference
ns3::mmwave::MmWaveEnbRrcProtocolIdeal Class Reference
Models the transmission of RRC messages from the UE to the eNB in an ideal fashion, without errors and without consuming any radio resources.
#include "mmwave-rrc-protocol-ideal.h"
Public Member Functions
MmWaveEnbRrcProtocolIdeal ()
virtual ~MmWaveEnbRrcProtocolIdeal ()
virtual void DoDispose (void) override
LteEnbRrcSapUser * GetLteEnbRrcSapUser ()
LteUeRrcSapProvider * GetUeRrcSapProvider (uint16_t rnti)
void SetCellId (uint16_t cellId)
void SetLteEnbRrcSapProvider (LteEnbRrcSapProvider *p)
void SetUeRrcSapProvider (uint16_t rnti, LteUeRrcSapProvider *p)
Static Public Member Functions
static TypeId GetTypeId (void)
Private Member Functions
LteRrcSap::RrcConnectionReconfiguration DoDecodeHandoverCommand (Ptr< Packet > p)
LteRrcSap::HandoverPreparationInfo DoDecodeHandoverPreparationInformation (Ptr< Packet > p)
Ptr< Packet > DoEncodeHandoverCommand (LteRrcSap::RrcConnectionReconfiguration msg)
Ptr< Packet > DoEncodeHandoverPreparationInformation (LteRrcSap::HandoverPreparationInfo msg)
void DoRemoveUe (uint16_t rnti)
void DoSendRrcConnectionReconfiguration (uint16_t rnti, LteRrcSap::RrcConnectionReconfiguration msg)
void DoSendRrcConnectionReestablishment (uint16_t rnti, LteRrcSap::RrcConnectionReestablishment msg)
void DoSendRrcConnectionReestablishmentReject (uint16_t rnti, LteRrcSap::RrcConnectionReestablishmentReject msg)
void DoSendRrcConnectionReject (uint16_t rnti, LteRrcSap::RrcConnectionReject msg)
void DoSendRrcConnectionRelease (uint16_t rnti, LteRrcSap::RrcConnectionRelease msg)
void DoSendRrcConnectionSetup (uint16_t rnti, LteRrcSap::RrcConnectionSetup msg)
void DoSendRrcConnectionSwitch (uint16_t rnti, LteRrcSap::RrcConnectionSwitch msg)
void DoSendRrcConnectToMmWave (uint16_t rnti, uint16_t mmWaveCellId)
void DoSendSystemInformation (uint16_t cellId, LteRrcSap::SystemInformation msg)
void DoSetupUe (uint16_t rnti, LteEnbRrcSapUser::SetupUeParameters params)
void SendSystemInformation (uint16_t cellId, LteRrcSap::SystemInformation msg)
Private Attributes
uint16_t m_cellId
LteEnbRrcSapProvider * m_enbRrcSapProvider
std::map< uint16_t, LteUeRrcSapProvider * > m_enbRrcSapProviderMap
LteEnbRrcSapUser * m_enbRrcSapUser
uint16_t m_rnti
Friends
class MemberLteEnbRrcSapUser< MmWaveEnbRrcProtocolIdeal >
Detailed Description
Models the transmission of RRC messages from the UE to the eNB in an ideal fashion, without errors and without consuming any radio resources.
Definition at line 105 of file mmwave-rrc-protocol-ideal.h.
Constructor & Destructor Documentation
MmWaveEnbRrcProtocolIdeal()
ns3::mmwave::MmWaveEnbRrcProtocolIdeal::MmWaveEnbRrcProtocolIdeal ()
Definition at line 241 of file mmwave-rrc-protocol-ideal.cc.
References m_enbRrcSapUser, and MemberLteEnbRrcSapUser< MmWaveEnbRrcProtocolIdeal >.
~MmWaveEnbRrcProtocolIdeal()
ns3::mmwave::MmWaveEnbRrcProtocolIdeal::~MmWaveEnbRrcProtocolIdeal () virtual
Definition at line 248 of file mmwave-rrc-protocol-ideal.cc.
Member Function Documentation
DoDecodeHandoverCommand()
LteRrcSap::RrcConnectionReconfiguration ns3::mmwave::MmWaveEnbRrcProtocolIdeal::DoDecodeHandoverCommand (Ptr< Packet > p) private
Definition at line 673 of file mmwave-rrc-protocol-ideal.cc.
References ns3::mmwave::MmWaveIdealHandoverCommandHeader::GetMsgId().
DoDecodeHandoverPreparationInformation()
LteRrcSap::HandoverPreparationInfo ns3::mmwave::MmWaveEnbRrcProtocolIdeal::DoDecodeHandoverPreparationInformation (Ptr< Packet > p) private
Definition at line 567 of file mmwave-rrc-protocol-ideal.cc.
References ns3::mmwave::MmWaveIdealHandoverPreparationInfoHeader::GetMsgId().
DoDispose()
void ns3::mmwave::MmWaveEnbRrcProtocolIdeal::DoDispose (void) override virtual
Definition at line 254 of file mmwave-rrc-protocol-ideal.cc.
References m_enbRrcSapUser.
DoEncodeHandoverCommand()
Ptr< Packet > ns3::mmwave::MmWaveEnbRrcProtocolIdeal::DoEncodeHandoverCommand (LteRrcSap::RrcConnectionReconfiguration msg) private
Definition at line 659 of file mmwave-rrc-protocol-ideal.cc.
References ns3::mmwave::g_handoverCommandMsgIdCounter, and ns3::mmwave::MmWaveIdealHandoverCommandHeader::SetMsgId().
DoEncodeHandoverPreparationInformation()
Ptr< Packet > ns3::mmwave::MmWaveEnbRrcProtocolIdeal::DoEncodeHandoverPreparationInformation (LteRrcSap::HandoverPreparationInfo msg) private
Definition at line 553 of file mmwave-rrc-protocol-ideal.cc.
References ns3::mmwave::g_handoverPreparationInfoMsgIdCounter, and ns3::mmwave::MmWaveIdealHandoverPreparationInfoHeader::SetMsgId().
DoRemoveUe()
void ns3::mmwave::MmWaveEnbRrcProtocolIdeal::DoRemoveUe (uint16_t rnti) private
Definition at line 315 of file mmwave-rrc-protocol-ideal.cc.
References m_enbRrcSapProviderMap.
DoSendRrcConnectionReconfiguration()
void ns3::mmwave::MmWaveEnbRrcProtocolIdeal::DoSendRrcConnectionReconfiguration (uint16_t rnti, LteRrcSap::RrcConnectionReconfiguration msg) private
Definition at line 404 of file mmwave-rrc-protocol-ideal.cc.
References GetUeRrcSapProvider().
DoSendRrcConnectionReestablishment()
void ns3::mmwave::MmWaveEnbRrcProtocolIdeal::DoSendRrcConnectionReestablishment (uint16_t rnti, LteRrcSap::RrcConnectionReestablishment msg) private
Definition at line 413 of file mmwave-rrc-protocol-ideal.cc.
References GetUeRrcSapProvider().
DoSendRrcConnectionReestablishmentReject()
void ns3::mmwave::MmWaveEnbRrcProtocolIdeal::DoSendRrcConnectionReestablishmentReject (uint16_t rnti, LteRrcSap::RrcConnectionReestablishmentReject msg) private
Definition at line 422 of file mmwave-rrc-protocol-ideal.cc.
References GetUeRrcSapProvider().
DoSendRrcConnectionReject()
void ns3::mmwave::MmWaveEnbRrcProtocolIdeal::DoSendRrcConnectionReject (uint16_t rnti, LteRrcSap::RrcConnectionReject msg) private
Definition at line 440 of file mmwave-rrc-protocol-ideal.cc.
References GetUeRrcSapProvider().
DoSendRrcConnectionRelease()
void ns3::mmwave::MmWaveEnbRrcProtocolIdeal::DoSendRrcConnectionRelease (uint16_t rnti, LteRrcSap::RrcConnectionRelease msg) private
Definition at line 431 of file mmwave-rrc-protocol-ideal.cc.
References GetUeRrcSapProvider().
DoSendRrcConnectionSetup()
void ns3::mmwave::MmWaveEnbRrcProtocolIdeal::DoSendRrcConnectionSetup (uint16_t rnti, LteRrcSap::RrcConnectionSetup msg) private
Definition at line 395 of file mmwave-rrc-protocol-ideal.cc.
References GetUeRrcSapProvider().
DoSendRrcConnectionSwitch()
void ns3::mmwave::MmWaveEnbRrcProtocolIdeal::DoSendRrcConnectionSwitch (uint16_t rnti, LteRrcSap::RrcConnectionSwitch msg) private
Definition at line 450 of file mmwave-rrc-protocol-ideal.cc.
DoSendRrcConnectToMmWave()
void ns3::mmwave::MmWaveEnbRrcProtocolIdeal::DoSendRrcConnectToMmWave (uint16_t rnti, uint16_t mmWaveCellId) private
Definition at line 456 of file mmwave-rrc-protocol-ideal.cc.
References GetUeRrcSapProvider().
DoSendSystemInformation()
void ns3::mmwave::MmWaveEnbRrcProtocolIdeal::DoSendSystemInformation (uint16_t cellId, LteRrcSap::SystemInformation msg) private
Definition at line 322 of file mmwave-rrc-protocol-ideal.cc.
References ns3::mmwave::MmWaveUeNetDevice::GetRrc(), and m_cellId.
DoSetupUe()
void ns3::mmwave::MmWaveEnbRrcProtocolIdeal::DoSetupUe (uint16_t rnti, LteEnbRrcSapUser::SetupUeParameters params) private
Definition at line 307 of file mmwave-rrc-protocol-ideal.cc.
References m_enbRrcSapProviderMap.
GetLteEnbRrcSapUser()
LteEnbRrcSapUser * ns3::mmwave::MmWaveEnbRrcProtocolIdeal::GetLteEnbRrcSapUser ()
Definition at line 277 of file mmwave-rrc-protocol-ideal.cc.
References m_enbRrcSapUser.
GetTypeId()
TypeId ns3::mmwave::MmWaveEnbRrcProtocolIdeal::GetTypeId (void) static
Definition at line 261 of file mmwave-rrc-protocol-ideal.cc.
Referenced by ns3::mmwave::MmWaveIdealHandoverPreparationInfoHeader::GetInstanceTypeId(), and ns3::mmwave::MmWaveIdealHandoverCommandHeader::GetInstanceTypeId().
GetUeRrcSapProvider()
LteUeRrcSapProvider * ns3::mmwave::MmWaveEnbRrcProtocolIdeal::GetUeRrcSapProvider (uint16_t rnti)
Definition at line 289 of file mmwave-rrc-protocol-ideal.cc.
References m_enbRrcSapProviderMap.
Referenced by DoSendRrcConnectionReconfiguration(), DoSendRrcConnectionReestablishment(), DoSendRrcConnectionReestablishmentReject(), DoSendRrcConnectionReject(), DoSendRrcConnectionRelease(), DoSendRrcConnectionSetup(), and DoSendRrcConnectToMmWave().
SendSystemInformation()
void ns3::mmwave::MmWaveEnbRrcProtocolIdeal::SendSystemInformation (uint16_t cellId, LteRrcSap::SystemInformation msg) private
SetCellId()
void ns3::mmwave::MmWaveEnbRrcProtocolIdeal::SetCellId (uint16_t cellId)
Definition at line 283 of file mmwave-rrc-protocol-ideal.cc.
References m_cellId.
SetLteEnbRrcSapProvider()
void ns3::mmwave::MmWaveEnbRrcProtocolIdeal::SetLteEnbRrcSapProvider (LteEnbRrcSapProvider * p)
Definition at line 271 of file mmwave-rrc-protocol-ideal.cc.
References m_enbRrcSapProvider.
SetUeRrcSapProvider()
void ns3::mmwave::MmWaveEnbRrcProtocolIdeal::SetUeRrcSapProvider (uint16_t rnti, LteUeRrcSapProvider * p)
Definition at line 298 of file mmwave-rrc-protocol-ideal.cc.
References m_enbRrcSapProviderMap.
Referenced by ns3::mmwave::MmWaveUeRrcProtocolIdeal::SetEnbRrcSapProvider().
Friends And Related Function Documentation
MemberLteEnbRrcSapUser< MmWaveEnbRrcProtocolIdeal >
friend class MemberLteEnbRrcSapUser< MmWaveEnbRrcProtocolIdeal > friend
Definition at line 107 of file mmwave-rrc-protocol-ideal.h.
Referenced by MmWaveEnbRrcProtocolIdeal().
Member Data Documentation
m_cellId
uint16_t ns3::mmwave::MmWaveEnbRrcProtocolIdeal::m_cellId private
Definition at line 146 of file mmwave-rrc-protocol-ideal.h.
Referenced by DoSendSystemInformation(), and SetCellId().
m_enbRrcSapProvider
LteEnbRrcSapProvider* ns3::mmwave::MmWaveEnbRrcProtocolIdeal::m_enbRrcSapProvider private
Definition at line 147 of file mmwave-rrc-protocol-ideal.h.
Referenced by SetLteEnbRrcSapProvider().
m_enbRrcSapProviderMap
std::map<uint16_t, LteUeRrcSapProvider*> ns3::mmwave::MmWaveEnbRrcProtocolIdeal::m_enbRrcSapProviderMap private
Definition at line 149 of file mmwave-rrc-protocol-ideal.h.
Referenced by DoRemoveUe(), DoSetupUe(), GetUeRrcSapProvider(), and SetUeRrcSapProvider().
m_enbRrcSapUser
LteEnbRrcSapUser* ns3::mmwave::MmWaveEnbRrcProtocolIdeal::m_enbRrcSapUser private
Definition at line 148 of file mmwave-rrc-protocol-ideal.h.
Referenced by DoDispose(), GetLteEnbRrcSapUser(), and MmWaveEnbRrcProtocolIdeal().
m_rnti
uint16_t ns3::mmwave::MmWaveEnbRrcProtocolIdeal::m_rnti private
Definition at line 145 of file mmwave-rrc-protocol-ideal.h.
The documentation for this class was generated from the following files:
src/mmwave/model/mmwave-rrc-protocol-ideal.h
src/mmwave/model/mmwave-rrc-protocol-ideal.cc