ns3-mmwave: ns3::mmwave::MmWaveFlexTtiMaxRateMacCschedSapProvider Class Reference
ns3::mmwave::MmWaveFlexTtiMaxRateMacCschedSapProvider Class Reference
Public Member Functions
MmWaveFlexTtiMaxRateMacCschedSapProvider (MmWaveFlexTtiMaxRateMacScheduler *scheduler)
virtual void CschedCellConfigReq (const struct MmWaveMacCschedSapProvider::CschedCellConfigReqParameters &params)
CSCHED_CELL_CONFIG_REQ.
virtual void CschedLcConfigReq (const struct MmWaveMacCschedSapProvider::CschedLcConfigReqParameters &params)
virtual void CschedLcReleaseReq (const struct MmWaveMacCschedSapProvider::CschedLcReleaseReqParameters &params)
virtual void CschedUeConfigReq (const struct MmWaveMacCschedSapProvider::CschedUeConfigReqParameters &params)
virtual void CschedUeReleaseReq (const struct MmWaveMacCschedSapProvider::CschedUeReleaseReqParameters &params)
Public Member Functions inherited from ns3::mmwave::MmWaveMacCschedSapProvider
virtual ~MmWaveMacCschedSapProvider ()
Private Member Functions
MmWaveFlexTtiMaxRateMacCschedSapProvider ()
Private Attributes
MmWaveFlexTtiMaxRateMacScheduler * m_scheduler
Detailed Description
Definition at line 29 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
Constructor & Destructor Documentation
MmWaveFlexTtiMaxRateMacCschedSapProvider() [1/2]
ns3::mmwave::MmWaveFlexTtiMaxRateMacCschedSapProvider::MmWaveFlexTtiMaxRateMacCschedSapProvider (MmWaveFlexTtiMaxRateMacScheduler * scheduler)
Definition at line 50 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
MmWaveFlexTtiMaxRateMacCschedSapProvider() [2/2]
ns3::mmwave::MmWaveFlexTtiMaxRateMacCschedSapProvider::MmWaveFlexTtiMaxRateMacCschedSapProvider () private
Definition at line 46 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
Member Function Documentation
CschedCellConfigReq()
void ns3::mmwave::MmWaveFlexTtiMaxRateMacCschedSapProvider::CschedCellConfigReq (const struct MmWaveMacCschedSapProvider::CschedCellConfigReqParameters & params) virtual
CSCHED_CELL_CONFIG_REQ.
Implements ns3::mmwave::MmWaveMacCschedSapProvider.
Definition at line 56 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::DoCschedCellConfigReq(), and m_scheduler.
CschedLcConfigReq()
void ns3::mmwave::MmWaveFlexTtiMaxRateMacCschedSapProvider::CschedLcConfigReq (const struct MmWaveMacCschedSapProvider::CschedLcConfigReqParameters & params) virtual
Implements ns3::mmwave::MmWaveMacCschedSapProvider.
Definition at line 69 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::DoCschedLcConfigReq(), and m_scheduler.
CschedLcReleaseReq()
void ns3::mmwave::MmWaveFlexTtiMaxRateMacCschedSapProvider::CschedLcReleaseReq (const struct MmWaveMacCschedSapProvider::CschedLcReleaseReqParameters & params) virtual
Implements ns3::mmwave::MmWaveMacCschedSapProvider.
Definition at line 75 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::DoCschedLcReleaseReq(), and m_scheduler.
CschedUeConfigReq()
void ns3::mmwave::MmWaveFlexTtiMaxRateMacCschedSapProvider::CschedUeConfigReq (const struct MmWaveMacCschedSapProvider::CschedUeConfigReqParameters & params) virtual
Implements ns3::mmwave::MmWaveMacCschedSapProvider.
Definition at line 62 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::DoCschedUeConfigReq(), and m_scheduler.
CschedUeReleaseReq()
void ns3::mmwave::MmWaveFlexTtiMaxRateMacCschedSapProvider::CschedUeReleaseReq (const struct MmWaveMacCschedSapProvider::CschedUeReleaseReqParameters & params) virtual
Implements ns3::mmwave::MmWaveMacCschedSapProvider.
Definition at line 81 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiMaxRateMacScheduler::DoCschedUeReleaseReq(), and m_scheduler.
Member Data Documentation
m_scheduler
MmWaveFlexTtiMaxRateMacScheduler* ns3::mmwave::MmWaveFlexTtiMaxRateMacCschedSapProvider::m_scheduler private
Definition at line 43 of file mmwave-flex-tti-maxrate-mac-scheduler.cc.
Referenced by CschedCellConfigReq(), CschedLcConfigReq(), CschedLcReleaseReq(), CschedUeConfigReq(), and CschedUeReleaseReq().
The documentation for this class was generated from the following file:
src/mmwave/model/mmwave-flex-tti-maxrate-mac-scheduler.cc