ns3-mmwave: ns3::mmwave::MmWaveFlexTtiMacSchedSapProvider Class Reference
ns3::mmwave::MmWaveFlexTtiMacSchedSapProvider Class Reference
Public Member Functions
MmWaveFlexTtiMacSchedSapProvider (MmWaveFlexTtiMacScheduler *sched)
virtual void SchedDlCqiInfoReq (const struct MmWaveMacSchedSapProvider::SchedDlCqiInfoReqParameters &params)
virtual void SchedDlRlcBufferReq (const struct MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters &params)
virtual void SchedSetMcs (int mcs)
virtual void SchedTriggerReq (const struct MmWaveMacSchedSapProvider::SchedTriggerReqParameters &params)
virtual void SchedUlCqiInfoReq (const struct MmWaveMacSchedSapProvider::SchedUlCqiInfoReqParameters &params)
virtual void SchedUlMacCtrlInfoReq (const struct MmWaveMacSchedSapProvider::SchedUlMacCtrlInfoReqParameters &params)
Public Member Functions inherited from ns3::mmwave::MmWaveMacSchedSapProvider
virtual ~MmWaveMacSchedSapProvider ()
virtual void SchedDlCqiInfoReq (const SchedDlCqiInfoReqParameters &params)=0
Private Member Functions
MmWaveFlexTtiMacSchedSapProvider ()
Private Attributes
MmWaveFlexTtiMacScheduler * m_scheduler
Detailed Description
Definition at line 106 of file mmwave-flex-tti-mac-scheduler.cc.
Constructor & Destructor Documentation
MmWaveFlexTtiMacSchedSapProvider() [1/2]
ns3::mmwave::MmWaveFlexTtiMacSchedSapProvider::MmWaveFlexTtiMacSchedSapProvider (MmWaveFlexTtiMacScheduler * sched)
Definition at line 126 of file mmwave-flex-tti-mac-scheduler.cc.
MmWaveFlexTtiMacSchedSapProvider() [2/2]
ns3::mmwave::MmWaveFlexTtiMacSchedSapProvider::MmWaveFlexTtiMacSchedSapProvider () private
Definition at line 122 of file mmwave-flex-tti-mac-scheduler.cc.
Member Function Documentation
SchedDlCqiInfoReq()
void ns3::mmwave::MmWaveFlexTtiMacSchedSapProvider::SchedDlCqiInfoReq (const struct MmWaveMacSchedSapProvider::SchedDlCqiInfoReqParameters & params) virtual
Definition at line 144 of file mmwave-flex-tti-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiMacScheduler::DoSchedDlCqiInfoReq(), and m_scheduler.
SchedDlRlcBufferReq()
void ns3::mmwave::MmWaveFlexTtiMacSchedSapProvider::SchedDlRlcBufferReq (const struct MmWaveMacSchedSapProvider::SchedDlRlcBufferReqParameters & params) virtual
Implements ns3::mmwave::MmWaveMacSchedSapProvider.
Definition at line 132 of file mmwave-flex-tti-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiMacScheduler::DoSchedDlRlcBufferReq(), and m_scheduler.
SchedSetMcs()
void ns3::mmwave::MmWaveFlexTtiMacSchedSapProvider::SchedSetMcs (int mcs) virtual
Reimplemented from ns3::mmwave::MmWaveMacSchedSapProvider.
Definition at line 162 of file mmwave-flex-tti-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiMacScheduler::DoSchedSetMcs(), ns3::mmwave::MmWaveFlexTtiMacScheduler::m_berDl, ns3::mmwave::MmWaveFlexTtiMacScheduler::m_macHdrSize, ns3::mmwave::MmWaveFlexTtiMacScheduler::m_rlcHdrSize, m_scheduler, and ns3::mmwave::MmWaveFlexTtiMacScheduler::m_subHdrSize.
SchedTriggerReq()
void ns3::mmwave::MmWaveFlexTtiMacSchedSapProvider::SchedTriggerReq (const struct MmWaveMacSchedSapProvider::SchedTriggerReqParameters & params) virtual
Implements ns3::mmwave::MmWaveMacSchedSapProvider.
Definition at line 138 of file mmwave-flex-tti-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiMacScheduler::DoSchedTriggerReq(), and m_scheduler.
SchedUlCqiInfoReq()
void ns3::mmwave::MmWaveFlexTtiMacSchedSapProvider::SchedUlCqiInfoReq (const struct MmWaveMacSchedSapProvider::SchedUlCqiInfoReqParameters & params) virtual
Implements ns3::mmwave::MmWaveMacSchedSapProvider.
Definition at line 150 of file mmwave-flex-tti-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiMacScheduler::DoSchedUlCqiInfoReq(), and m_scheduler.
SchedUlMacCtrlInfoReq()
void ns3::mmwave::MmWaveFlexTtiMacSchedSapProvider::SchedUlMacCtrlInfoReq (const struct MmWaveMacSchedSapProvider::SchedUlMacCtrlInfoReqParameters & params) virtual
Implements ns3::mmwave::MmWaveMacSchedSapProvider.
Definition at line 156 of file mmwave-flex-tti-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiMacScheduler::DoSchedUlMacCtrlInfoReq(), and m_scheduler.
Member Data Documentation
m_scheduler
MmWaveFlexTtiMacScheduler* ns3::mmwave::MmWaveFlexTtiMacSchedSapProvider::m_scheduler private
Definition at line 119 of file mmwave-flex-tti-mac-scheduler.cc.
Referenced by SchedDlCqiInfoReq(), SchedDlRlcBufferReq(), SchedSetMcs(), SchedTriggerReq(), SchedUlCqiInfoReq(), and SchedUlMacCtrlInfoReq().
The documentation for this class was generated from the following file:
src/mmwave/model/mmwave-flex-tti-mac-scheduler.cc