ns3-mmwave: ns3::mmwave::MmWaveMemberPhySapProvider Class Reference
ns3::mmwave::MmWaveMemberPhySapProvider Class Reference
Public Member Functions
MmWaveMemberPhySapProvider (MmWavePhy *phy)
virtual void SendControlMessage (Ptr< MmWaveControlMessage > msg)
virtual void SendMacPdu (Ptr< Packet > p)
virtual void SendRachPreamble (uint8_t PreambleId, uint8_t Rnti)
virtual void SetSlotAllocInfo (SlotAllocInfo slotAllocInfo)
Updates the current NR slot with the allocation info provided by the scheduler.
Public Member Functions inherited from ns3::mmwave::MmWavePhySapProvider
virtual ~MmWavePhySapProvider ()
Private Attributes
MmWavePhy * m_phy
Detailed Description
Definition at line 57 of file mmwave-phy.cc.
Constructor & Destructor Documentation
MmWaveMemberPhySapProvider()
ns3::mmwave::MmWaveMemberPhySapProvider::MmWaveMemberPhySapProvider (MmWavePhy * phy)
Definition at line 74 of file mmwave-phy.cc.
Member Function Documentation
SendControlMessage()
void ns3::mmwave::MmWaveMemberPhySapProvider::SendControlMessage (Ptr< MmWaveControlMessage > msg) virtual
Implements ns3::mmwave::MmWavePhySapProvider.
Definition at line 87 of file mmwave-phy.cc.
References m_phy, and ns3::mmwave::MmWavePhy::SetControlMessage().
SendMacPdu()
void ns3::mmwave::MmWaveMemberPhySapProvider::SendMacPdu (Ptr< Packet > p) virtual
Implements ns3::mmwave::MmWavePhySapProvider.
Definition at line 81 of file mmwave-phy.cc.
References m_phy, and ns3::mmwave::MmWavePhy::SetMacPdu().
SendRachPreamble()
void ns3::mmwave::MmWaveMemberPhySapProvider::SendRachPreamble (uint8_t PreambleId, uint8_t Rnti) virtual
Implements ns3::mmwave::MmWavePhySapProvider.
Definition at line 93 of file mmwave-phy.cc.
References m_phy, and ns3::mmwave::MmWavePhy::SendRachPreamble().
SetSlotAllocInfo()
void ns3::mmwave::MmWaveMemberPhySapProvider::SetSlotAllocInfo (SlotAllocInfo slotAllocInfo) virtual
Updates the current NR slot with the allocation info provided by the scheduler.
Parameters
slotAllocInfo the slot allocation info created by the scheduler.
Implements ns3::mmwave::MmWavePhySapProvider.
Definition at line 99 of file mmwave-phy.cc.
References ns3::mmwave::MmWavePhy::DoSetSlotAllocInfo(), and m_phy.
Member Data Documentation
m_phy
MmWavePhy* ns3::mmwave::MmWaveMemberPhySapProvider::m_phy private
Definition at line 71 of file mmwave-phy.cc.
Referenced by SendControlMessage(), SendMacPdu(), SendRachPreamble(), and SetSlotAllocInfo().
The documentation for this class was generated from the following file:
src/mmwave/model/mmwave-phy.cc