ns3-mmwave: ns3::mmwave::MmWaveUePhy Class Reference
ns3::mmwave::MmWaveUePhy Class Reference
#include "mmwave-ue-phy.h"
Public Member Functions
MmWaveUePhy ()
MmWaveUePhy (Ptr< MmWaveSpectrumPhy > ulPhy, Ptr< MmWaveSpectrumPhy > dlPhy)
virtual ~MmWaveUePhy ()
Ptr< MmWaveDlCqiMessage > CreateDlCqiFeedbackMessage (const SpectrumValue &sinr)
Ptr< SpectrumValue > CreateTxPowerSpectralDensity () override
Compute the TX Power Spectral Density.
void DelayPhyDataPacketReceived (Ptr< Packet > p)
virtual void DoDispose (void) override
virtual void DoInitialize (void) override
void DoSendControlMessage (Ptr< MmWaveControlMessage > msg)
void DoSetSubChannels ()
void EndTti ()
Marks the end of a Transmission Time Interval (TTI).
void GenerateDlCqiReport (const SpectrumValue &sinr)
uint32_t GetAbsoluteSubframeNo ()
Ptr< MmWaveSpectrumPhy > GetDlSpectrumPhy () const
uint64_t GetImsi () const
double GetNoiseFigure () const
uint16_t GetRnti ()
std::vector< int > GetSubChannelsForReception (void)
std::vector< int > GetSubChannelsForTransmission (void)
uint32_t GetSubframeNumber (void)
double GetTxPower () const
LteUeCphySapProvider * GetUeCphySapProvider ()
Ptr< MmWaveSpectrumPhy > GetUlSpectrumPhy () const
void InitializeSlotAllocation (uint16_t frameNum, uint8_t sfNum, uint8_t slotNum)
Initializes the slots allocation info for the given frame, subframe and slot.
bool IsReceptionEnabled ()
void PhyDataPacketReceived (Ptr< Packet > p)
void ReceiveControlMessageList (std::list< Ptr< MmWaveControlMessage > > msgList)
void ReceiveLteDlHarqFeedback (DlHarqInfo m)
void RegisterOtherEnb (uint16_t cellId, Ptr< MmWavePhyMacCommon > config, Ptr< MmWaveEnbNetDevice > enb)
void RegisterToEnb (uint16_t cellId, Ptr< MmWavePhyMacCommon > config)
void ResetReception ()
void SendCtrlChannels (std::list< Ptr< MmWaveControlMessage > > ctrlMsg, Time prd)
void SendDataChannels (Ptr< PacketBurst > pb, std::list< Ptr< MmWaveControlMessage > > ctrlMsg, Time duration, uint8_t slotInd)
bool SendPacket (Ptr< Packet > packet)
void SetHarqPhyModule (Ptr< MmWaveHarqPhy > harq)
void SetImsi (uint64_t imsi)
void SetNoiseFigure (double pf)
void SetPhySapUser (MmWaveUePhySapUser *ptr)
void SetSubChannelsForReception (std::vector< int > mask)
void SetSubChannelsForTransmission (std::vector< int > mask)
void SetTxPower (double pow)
void SetUeCphySapUser (LteUeCphySapUser *s)
void SlotIndication (uint16_t frameNum, uint8_t subframeNum, uint8_t slotNum)
Marks the beginning of a new NR slot.
void StartTti ()
Marks the beginning of a new Transmission Time Interval (TTI).
void UpdateSinrEstimate (uint16_t cellId, double sinr)
Public Member Functions inherited from ns3::mmwave::MmWavePhy
MmWavePhy ()
MmWavePhy (Ptr< MmWaveSpectrumPhy > dlChannelPhy, Ptr< MmWaveSpectrumPhy > ulChannelPhy)
virtual ~MmWavePhy ()
void AddPropagationLossModel (Ptr< PropagationLossModel > model)
void AddSpectrumPropagationLossModel (Ptr< SpectrumPropagationLossModel > model)
void DoSetCellId (uint16_t cellId)
void DoSetSlotAllocInfo (SlotAllocInfo sfAllocInfo)
uint8_t GetComponentCarrierId ()
Get the component carrier ID.
Ptr< MmWavePhyMacCommon > GetConfigurationParameters (void) const
std::list< Ptr< MmWaveControlMessage > > GetControlMessages (void)
Ptr< NetDevice > GetDevice ()
Time GetNextSlotDelay ()
The purpose of this function is to sync the slot duration to the correct value.
double GetNoiseFigure (void) const
virtual Ptr< PacketBurst > GetPacketBurst (SfnSf)
MmWavePhySapProvider * GetPhySapProvider ()
SlotAllocInfo GetSfAllocInfo (uint8_t subframeNum)
virtual void SendRachPreamble (uint32_t PreambleId, uint32_t Rnti)
void SetChannel (Ptr< SpectrumChannel > c)
void SetComponentCarrierId (uint8_t index)
Set the component carrier ID.
void SetConfigurationParameters (Ptr< MmWavePhyMacCommon > ptrConfig)
void SetControlMessage (Ptr< MmWaveControlMessage > m)
void SetDevice (Ptr< NetDevice > d)
virtual void SetMacPdu (Ptr< Packet > pb)
void SetNoiseFigure (double nf)
void SetSlotCtrlStructure (uint8_t slotIndex)
Sets the control data allocation within a NR slot.
void UpdateCurrentAllocationAndSchedule (uint32_t frame, uint32_t sf)
Static Public Member Functions
static TypeId GetTypeId (void)
Static Public Member Functions inherited from ns3::mmwave::MmWavePhy
static TypeId GetTypeId (void)
Private Member Functions
void DoConfigureReferenceSignalPower (int8_t referenceSignalPower)
void DoConfigureUplink (uint16_t ulEarfcn, uint8_t ulBandwidth)
void DoReset ()
void DoSetDlBandwidth (uint8_t ulBandwidth)
void DoSetPa (double pa)
void DoSetRnti (uint16_t rnti)
void DoSetRsrpFilterCoefficient (uint8_t rsrpFilterCoefficient)
void DoSetSrsConfigurationIndex (uint16_t srcCi)
void DoSetTransmissionMode (uint8_t txMode)
void DoStartCellSearch (uint16_t dlEarfcn)
void DoSynchronizeWithEnb (uint16_t cellId)
void DoSynchronizeWithEnb (uint16_t cellId, uint16_t dlEarfcn)
void ReceiveDataPeriod (uint32_t slotNum)
void TraceUlPhyTransmission (DciInfoElementTdma dciInfo, uint8_t tddType)
Triggers the callback for the ReportUlPhyTransmission Trace Source.
Private Attributes
Ptr< MmWaveAmc > m_amc
std::map< uint16_t, double > m_cellSinrMap
std::vector< int > m_channelChunks
uint8_t m_consecutiveSinrBelowThreshold
SlotAllocInfo m_currSlotAllocInfo
Holds the allocation info for the current NR slot.
TtiAllocInfo m_currTti
Holds the allocation info for the current Tti.
Time m_dataPeriod
Data period time duration.
bool m_dlConfigured
Ptr< MmWaveHarqPhy > m_harqPhyModule
uint64_t m_imsi
uint8_t m_n310
long double m_outageThreshold
bool m_phyReset
MmWaveUePhySapUser * m_phySapUser
uint8_t m_prevSlot
TtiAllocInfo::TddMode m_prevTtiDir
Time Division Duplexing (TDD) mode of the previous Tti.
bool m_receptionEnabled
std::map< uint16_t, std::pair< Ptr< MmWavePhyMacCommon >, Ptr< MmWaveEnbNetDevice > > > m_registeredEnb
TracedCallback< uint64_t, SpectrumValue &, SpectrumValue &> m_reportCurrentCellRsrpSinrTrace
TracedCallback< uint64_t, uint64_t > m_reportDlTbSize
TracedCallback< uint64_t, uint64_t > m_reportUlTbSize
uint16_t m_rnti
EventId m_sendDataChannelEvent
EventId m_sendDlHarqFeedbackEvent
bool m_sfAllocInfoUpdated
std::vector< int > m_subChannelsforRx
std::vector< int > m_subChannelsForTx
LteUeCphySapProvider * m_ueCphySapProvider
LteUeCphySapUser * m_ueCphySapUser
bool m_ulConfigured
bool m_ulGrant
TracedCallback< PhyTransmissionTraceParams > m_ulPhyTrace
Traces the current TTI allocation info, from the UE side.
Time m_wbCqiLast
Time m_wbCqiPeriod
Wideband Periodic CQI: 2, 5, 10, 16, 20, 32, 40, 64, 80 or 160 ms.
Friends
class MemberLteUeCphySapProvider< MmWaveUePhy >
class UeMemberLteUePhySapProvider
Additional Inherited Members
Protected Attributes inherited from ns3::mmwave::MmWavePhy
uint16_t m_cellId
uint8_t m_componentCarrierId
component carrier Id used to address sap
std::vector< std::list< Ptr< MmWaveControlMessage > > > m_controlMessageQueue
Time m_ctrlPeriod
Time m_dataPeriod
Ptr< MmWaveSpectrumPhy > m_downlinkSpectrumPhy
uint16_t m_frameNum
Time m_lastSlotStart
Time at which the current slot started.
Ptr< NetDevice > m_netDevice
double m_noiseFigure
std::map< uint64_t, Ptr< PacketBurst > > m_packetBurstMap
Ptr< MmWavePhyMacCommon > m_phyMacConfig
MmWavePhySapProvider * m_phySapProvider
Ptr< PropagationLossModel > m_propagationLoss
uint32_t m_raPreambleId
bool m_sfAllocInfoUpdated
uint8_t m_sfNum
std::vector< SlotAllocInfo > m_slotAllocInfo
Maps slot number to its allocation info.
std::map< uint32_t, SlotAllocInfo > m_slotAllocInfoMap
uint8_t m_slotNum
Time m_slotPeriod
Slot period time duration.
Ptr< MmWaveSpectrumPhy > m_spectrumPhy
Ptr< SpectrumPropagationLossModel > m_spectrumPropagationLossModel
uint8_t m_ttiIndex
Keeps track of the TTIs within the single NR slot.
double m_txPower
Ptr< MmWaveSpectrumPhy > m_uplinkSpectrumPhy
Detailed Description
Definition at line 57 of file mmwave-ue-phy.h.
Constructor & Destructor Documentation
MmWaveUePhy() [1/2]
ns3::mmwave::MmWaveUePhy::MmWaveUePhy ()
Definition at line 57 of file mmwave-ue-phy.cc.
MmWaveUePhy() [2/2]
ns3::mmwave::MmWaveUePhy::MmWaveUePhy (Ptr< MmWaveSpectrumPhy > ulPhy, Ptr< MmWaveSpectrumPhy > dlPhy)
Definition at line 63 of file mmwave-ue-phy.cc.
References m_cellSinrMap, m_ueCphySapProvider, m_wbCqiLast, MemberLteUeCphySapProvider< MmWaveUePhy >, and SlotIndication().
~MmWaveUePhy()
ns3::mmwave::MmWaveUePhy::~MmWaveUePhy () virtual
Definition at line 75 of file mmwave-ue-phy.cc.
Member Function Documentation
CreateDlCqiFeedbackMessage()
Ptr< MmWaveDlCqiMessage > ns3::mmwave::MmWaveUePhy::CreateDlCqiFeedbackMessage (const SpectrumValue & sinr)
Definition at line 740 of file mmwave-ue-phy.cc.
References m_amc, m_currTti, ns3::mmwave::TtiAllocInfo::m_dci, ns3::mmwave::DciInfoElementTdma::m_format, ns3::mmwave::DciInfoElementTdma::m_numSym, ns3::mmwave::MmWavePhy::m_phyMacConfig, m_rnti, ns3::mmwave::DlCqiInfo::m_rnti, ns3::mmwave::DciInfoElementTdma::m_tbSize, and ns3::mmwave::DlCqiInfo::WB.
Referenced by GenerateDlCqiReport().
CreateTxPowerSpectralDensity()
Ptr< SpectrumValue > ns3::mmwave::MmWaveUePhy::CreateTxPowerSpectralDensity () override virtual
Compute the TX Power Spectral Density.
Returns
a pointer to a newly allocated SpectrumValue representing the TX Power Spectral Density in W/Hz for each Resource Block
Implements ns3::mmwave::MmWavePhy.
Definition at line 225 of file mmwave-ue-phy.cc.
References ns3::mmwave::MmWaveSpectrumValueHelper::CreateTxPowerSpectralDensity(), ns3::mmwave::MmWavePhy::m_phyMacConfig, m_subChannelsForTx, and ns3::mmwave::MmWavePhy::m_txPower.
Referenced by SetSubChannelsForTransmission().
DelayPhyDataPacketReceived()
void ns3::mmwave::MmWaveUePhy::DelayPhyDataPacketReceived (Ptr< Packet > p)
Definition at line 697 of file mmwave-ue-phy.cc.
References m_phySapUser, and ns3::mmwave::MmWaveUePhySapUser::ReceivePhyPdu().
Referenced by PhyDataPacketReceived().
DoConfigureReferenceSignalPower()
void ns3::mmwave::MmWaveUePhy::DoConfigureReferenceSignalPower (int8_t referenceSignalPower) private
Definition at line 935 of file mmwave-ue-phy.cc.
DoConfigureUplink()
void ns3::mmwave::MmWaveUePhy::DoConfigureUplink (uint16_t ulEarfcn, uint8_t ulBandwidth) private
Definition at line 928 of file mmwave-ue-phy.cc.
References m_ulConfigured.
DoDispose()
void ns3::mmwave::MmWaveUePhy::DoDispose (void) override virtual
Reimplemented from ns3::mmwave::MmWavePhy.
Definition at line 170 of file mmwave-ue-phy.cc.
References m_registeredEnb.
DoInitialize()
void ns3::mmwave::MmWaveUePhy::DoInitialize (void) override virtual
Reimplemented from ns3::mmwave::MmWavePhy.
Definition at line 148 of file mmwave-ue-phy.cc.
References ns3::mmwave::MmWavePhy::DoInitialize(), m_channelChunks, ns3::mmwave::MmWavePhy::m_phyMacConfig, m_phyReset, ns3::mmwave::MmWavePhy::m_slotAllocInfo, ns3::mmwave::MmWavePhy::m_slotPeriod, and ns3::mmwave::MmWavePhy::SetSlotCtrlStructure().
DoReset()
void ns3::mmwave::MmWaveUePhy::DoReset () private
Definition at line 843 of file mmwave-ue-phy.cc.
References ns3::mmwave::MmWavePhy::m_cellId, ns3::mmwave::MmWavePhy::m_controlMessageQueue, ns3::mmwave::MmWavePhy::m_downlinkSpectrumPhy, ns3::mmwave::MmWavePhy::m_packetBurstMap, m_phyReset, ns3::mmwave::MmWavePhy::m_raPreambleId, m_rnti, m_sendDataChannelEvent, m_sendDlHarqFeedbackEvent, and m_subChannelsForTx.
DoSendControlMessage()
void ns3::mmwave::MmWaveUePhy::DoSendControlMessage (Ptr< MmWaveControlMessage > msg)
Definition at line 303 of file mmwave-ue-phy.cc.
References ns3::mmwave::MmWavePhy::SetControlMessage().
Referenced by GenerateDlCqiReport(), and ReceiveLteDlHarqFeedback().
DoSetDlBandwidth()
void ns3::mmwave::MmWaveUePhy::DoSetDlBandwidth (uint8_t ulBandwidth) private
Definition at line 921 of file mmwave-ue-phy.cc.
DoSetPa()
void ns3::mmwave::MmWaveUePhy::DoSetPa (double pa) private
Definition at line 888 of file mmwave-ue-phy.cc.
DoSetRnti()
void ns3::mmwave::MmWaveUePhy::DoSetRnti (uint16_t rnti) private
Definition at line 941 of file mmwave-ue-phy.cc.
References m_rnti.
DoSetRsrpFilterCoefficient()
void ns3::mmwave::MmWaveUePhy::DoSetRsrpFilterCoefficient (uint8_t rsrpFilterCoefficient) private
Definition at line 894 of file mmwave-ue-phy.cc.
DoSetSrsConfigurationIndex()
void ns3::mmwave::MmWaveUePhy::DoSetSrsConfigurationIndex (uint16_t srcCi) private
Definition at line 954 of file mmwave-ue-phy.cc.
DoSetSubChannels()
void ns3::mmwave::MmWaveUePhy::DoSetSubChannels ()
Definition at line 233 of file mmwave-ue-phy.cc.
DoSetTransmissionMode()
void ns3::mmwave::MmWaveUePhy::DoSetTransmissionMode (uint8_t txMode) private
Definition at line 948 of file mmwave-ue-phy.cc.
DoStartCellSearch()
void ns3::mmwave::MmWaveUePhy::DoStartCellSearch (uint16_t dlEarfcn) private
Definition at line 875 of file mmwave-ue-phy.cc.
DoSynchronizeWithEnb() [1/2]
void ns3::mmwave::MmWaveUePhy::DoSynchronizeWithEnb (uint16_t cellId) private
Definition at line 900 of file mmwave-ue-phy.cc.
References m_registeredEnb, and RegisterToEnb().
Referenced by DoSynchronizeWithEnb().
DoSynchronizeWithEnb() [2/2]
void ns3::mmwave::MmWaveUePhy::DoSynchronizeWithEnb (uint16_t cellId, uint16_t dlEarfcn) private
Definition at line 881 of file mmwave-ue-phy.cc.
References DoSynchronizeWithEnb().
EndTti()
void ns3::mmwave::MmWaveUePhy::EndTti (void)
Marks the end of a Transmission Time Interval (TTI).
Periodically, it alternates with StartTti in order to scan through the TTIs scheduled within a slot. Using the duration of the current TTI, the various frame/subframe and slot counters get updated; whenever the end of the current slot is reached, SlotIndication is called.
Definition at line 631 of file mmwave-ue-phy.cc.
References ns3::mmwave::MmWavePhy::GetNextSlotDelay(), m_currSlotAllocInfo, ns3::mmwave::MmWavePhy::m_frameNum, ns3::mmwave::MmWavePhy::m_lastSlotStart, ns3::mmwave::MmWavePhy::m_phyMacConfig, m_receptionEnabled, m_rnti, ns3::mmwave::MmWavePhy::m_sfNum, ns3::mmwave::MmWavePhy::m_slotNum, ns3::mmwave::SlotAllocInfo::m_ttiAllocInfo, ns3::mmwave::MmWavePhy::m_ttiIndex, SlotIndication(), and StartTti().
Referenced by StartTti().
GenerateDlCqiReport()
void ns3::mmwave::MmWaveUePhy::GenerateDlCqiReport (const SpectrumValue & sinr)
Definition at line 791 of file mmwave-ue-phy.cc.
References CreateDlCqiFeedbackMessage(), DoSendControlMessage(), m_imsi, m_receptionEnabled, m_reportCurrentCellRsrpSinrTrace, m_rnti, m_ulConfigured, m_wbCqiLast, and m_wbCqiPeriod.
Referenced by ns3::mmwave::MmWaveHelper::InstallSingleMcUeDevice(), and ns3::mmwave::MmWaveHelper::InstallSingleUeDevice().
GetAbsoluteSubframeNo()
uint32_t ns3::mmwave::MmWaveUePhy::GetAbsoluteSubframeNo ()
Definition at line 734 of file mmwave-ue-phy.cc.
References ns3::mmwave::MmWavePhy::m_frameNum, and ns3::mmwave::MmWavePhy::m_slotNum.
GetDlSpectrumPhy()
Ptr< MmWaveSpectrumPhy > ns3::mmwave::MmWaveUePhy::GetDlSpectrumPhy () const
Definition at line 359 of file mmwave-ue-phy.cc.
References ns3::mmwave::MmWavePhy::m_downlinkSpectrumPhy.
Referenced by GetTypeId().
GetImsi()
uint64_t ns3::mmwave::MmWaveUePhy::GetImsi (void) const
Definition at line 196 of file mmwave-ue-phy.cc.
References m_imsi.
GetNoiseFigure()
double ns3::mmwave::MmWaveUePhy::GetNoiseFigure (void) const
Definition at line 219 of file mmwave-ue-phy.cc.
References ns3::mmwave::MmWavePhy::m_noiseFigure.
GetRnti()
uint16_t ns3::mmwave::MmWaveUePhy::GetRnti (void)
Definition at line 836 of file mmwave-ue-phy.cc.
References m_rnti.
GetSubChannelsForReception()
std::vector< int > ns3::mmwave::MmWaveUePhy::GetSubChannelsForReception (void)
Definition at line 278 of file mmwave-ue-phy.cc.
GetSubChannelsForTransmission()
std::vector< int > ns3::mmwave::MmWaveUePhy::GetSubChannelsForTransmission (void)
Definition at line 295 of file mmwave-ue-phy.cc.
GetSubframeNumber()
uint32_t ns3::mmwave::MmWaveUePhy::GetSubframeNumber (void)
GetTxPower()
double ns3::mmwave::MmWaveUePhy::GetTxPower () const
Definition at line 207 of file mmwave-ue-phy.cc.
References ns3::mmwave::MmWavePhy::m_txPower.
Referenced by GetTypeId().
GetTypeId()
TypeId ns3::mmwave::MmWaveUePhy::GetTypeId (void) static
Definition at line 81 of file mmwave-ue-phy.cc.
References GetDlSpectrumPhy(), ns3::mmwave::MmWavePhy::GetNoiseFigure(), GetTxPower(), GetUlSpectrumPhy(), m_n310, m_outageThreshold, m_reportCurrentCellRsrpSinrTrace, m_reportDlTbSize, m_reportUlTbSize, m_ulPhyTrace, ns3::mmwave::MmWavePhy::SetNoiseFigure(), and SetTxPower().
GetUeCphySapProvider()
LteUeCphySapProvider * ns3::mmwave::MmWaveUePhy::GetUeCphySapProvider ()
Definition at line 183 of file mmwave-ue-phy.cc.
References m_ueCphySapProvider.
GetUlSpectrumPhy()
Ptr< MmWaveSpectrumPhy > ns3::mmwave::MmWaveUePhy::GetUlSpectrumPhy () const
Definition at line 365 of file mmwave-ue-phy.cc.
References ns3::mmwave::MmWavePhy::m_uplinkSpectrumPhy.
Referenced by GetTypeId().
InitializeSlotAllocation()
void ns3::mmwave::MmWaveUePhy::InitializeSlotAllocation (uint16_t frameNum, uint8_t sfNum, uint8_t slotNum)
Initializes the slots allocation info for the given frame, subframe and slot.
This function is periodically called by SlotIndication in order to initialize the slot allocation structure for the same slot and next subframe (and, eventually, frame). N.S. The timing of such process can not be changed, as future slots might contain UL DCIs that have been previously scheduled in advance.
Parameters
frameNum the intended frame number.
sfNum the intended subframe number.
slotNum the intended slot number.
Definition at line 488 of file mmwave-ue-phy.cc.
References ns3::mmwave::MmWavePhy::m_phyMacConfig, ns3::mmwave::MmWavePhy::m_slotAllocInfo, and ns3::mmwave::MmWavePhy::SetSlotCtrlStructure().
Referenced by SlotIndication().
IsReceptionEnabled()
bool ns3::mmwave::MmWaveUePhy::IsReceptionEnabled ()
Definition at line 824 of file mmwave-ue-phy.cc.
References m_receptionEnabled.
PhyDataPacketReceived()
void ns3::mmwave::MmWaveUePhy::PhyDataPacketReceived (Ptr< Packet > p)
Definition at line 683 of file mmwave-ue-phy.cc.
References DelayPhyDataPacketReceived(), ns3::mmwave::MmWavePhy::m_phyMacConfig, and m_phyReset.
Referenced by ns3::mmwave::MmWaveHelper::InstallSingleMcUeDevice(), and ns3::mmwave::MmWaveHelper::InstallSingleUeDevice().
ReceiveControlMessageList()
void ns3::mmwave::MmWaveUePhy::ReceiveControlMessageList (std::list< Ptr< MmWaveControlMessage > > msgList)
Definition at line 371 of file mmwave-ue-phy.cc.
References ns3::mmwave::MmWaveControlMessage::DCI_TDMA, ns3::mmwave::DciInfoElementTdma::DL_dci, ns3::mmwave::TtiAllocInfo::DL_slotAllocInfo, ns3::mmwave::MmWavePhy::m_cellId, m_currSlotAllocInfo, ns3::mmwave::TtiAllocInfo::m_dci, ns3::mmwave::SfnSf::m_frameNum, ns3::mmwave::MmWavePhy::m_frameNum, ns3::mmwave::MmWavePhy::m_phyMacConfig, m_phySapUser, ns3::mmwave::MmWavePhy::m_raPreambleId, m_rnti, ns3::mmwave::SfnSf::m_sfNum, ns3::mmwave::MmWavePhy::m_sfNum, ns3::mmwave::MmWavePhy::m_slotAllocInfo, ns3::mmwave::MmWavePhy::m_slotNum, ns3::mmwave::TtiAllocInfo::m_tddMode, ns3::mmwave::SlotAllocInfo::m_ttiAllocInfo, ns3::mmwave::TtiAllocInfo::m_ttiIdx, ns3::mmwave::MmWavePhy::m_ttiIndex, m_ueCphySapUser, ns3::mmwave::MmWaveControlMessage::MIB, ns3::mmwave::MmWaveControlMessage::RAR, ns3::mmwave::MmWaveUePhySapUser::ReceiveControlMessage(), ns3::mmwave::MmWaveControlMessage::SIB1, ns3::mmwave::DciInfoElementTdma::UL_dci, and ns3::mmwave::TtiAllocInfo::UL_slotAllocInfo.
Referenced by ns3::mmwave::MmWaveHelper::InstallSingleMcUeDevice(), and ns3::mmwave::MmWaveHelper::InstallSingleUeDevice().
ReceiveDataPeriod()
void ns3::mmwave::MmWaveUePhy::ReceiveDataPeriod (uint32_t slotNum) private
ReceiveLteDlHarqFeedback()
void ns3::mmwave::MmWaveUePhy::ReceiveLteDlHarqFeedback (DlHarqInfo m)
Definition at line 810 of file mmwave-ue-phy.cc.
References DoSendControlMessage(), ns3::mmwave::MmWavePhy::m_phyMacConfig, and m_sendDlHarqFeedbackEvent.
Referenced by ns3::mmwave::MmWaveHelper::InstallSingleMcUeDevice(), and ns3::mmwave::MmWaveHelper::InstallSingleUeDevice().
RegisterOtherEnb()
void ns3::mmwave::MmWaveUePhy::RegisterOtherEnb (uint16_t cellId, Ptr< MmWavePhyMacCommon > config, Ptr< MmWaveEnbNetDevice > enb)
Definition at line 351 of file mmwave-ue-phy.cc.
References m_registeredEnb.
RegisterToEnb()
void ns3::mmwave::MmWaveUePhy::RegisterToEnb (uint16_t cellId, Ptr< MmWavePhyMacCommon > config)
Definition at line 311 of file mmwave-ue-phy.cc.
References ns3::mmwave::MmWaveSpectrumValueHelper::CreateNoisePowerSpectralDensity(), ns3::mmwave::MmWavePhy::m_cellId, ns3::mmwave::MmWavePhy::m_downlinkSpectrumPhy, ns3::mmwave::MmWavePhy::m_netDevice, ns3::mmwave::MmWavePhy::m_noiseFigure, ns3::mmwave::MmWavePhy::m_phyMacConfig, m_phyReset, m_phySapUser, m_registeredEnb, ns3::mmwave::MmWavePhy::m_slotAllocInfo, ns3::mmwave::MmWaveUePhySapUser::SetConfigurationParameters(), and ns3::mmwave::MmWavePhy::SetSlotCtrlStructure().
Referenced by DoSynchronizeWithEnb().
ResetReception()
void ns3::mmwave::MmWaveUePhy::ResetReception ()
Definition at line 830 of file mmwave-ue-phy.cc.
References m_receptionEnabled.
SendCtrlChannels()
void ns3::mmwave::MmWaveUePhy::SendCtrlChannels (std::list< Ptr< MmWaveControlMessage > > ctrlMsg, Time prd)
Definition at line 727 of file mmwave-ue-phy.cc.
References ns3::mmwave::MmWavePhy::m_downlinkSpectrumPhy.
Referenced by StartTti().
SendDataChannels()
void ns3::mmwave::MmWaveUePhy::SendDataChannels (Ptr< PacketBurst > pb, std::list< Ptr< MmWaveControlMessage > > ctrlMsg, Time duration, uint8_t slotInd)
Definition at line 703 of file mmwave-ue-phy.cc.
References ns3::mmwave::MmWavePhy::m_downlinkSpectrumPhy.
Referenced by StartTti().
SendPacket()
bool ns3::mmwave::MmWaveUePhy::SendPacket (Ptr< Packet > packet)
SetHarqPhyModule()
void ns3::mmwave::MmWaveUePhy::SetHarqPhyModule (Ptr< MmWaveHarqPhy > harq)
Definition at line 983 of file mmwave-ue-phy.cc.
References m_harqPhyModule.
SetImsi()
void ns3::mmwave::MmWaveUePhy::SetImsi (uint64_t imsi)
Definition at line 190 of file mmwave-ue-phy.cc.
References m_imsi.
SetNoiseFigure()
void ns3::mmwave::MmWaveUePhy::SetNoiseFigure (double pf)
Definition at line 213 of file mmwave-ue-phy.cc.
References ns3::mmwave::MmWavePhy::m_noiseFigure.
SetPhySapUser()
void ns3::mmwave::MmWaveUePhy::SetPhySapUser (MmWaveUePhySapUser * ptr)
Definition at line 977 of file mmwave-ue-phy.cc.
References m_phySapUser.
SetSubChannelsForReception()
void ns3::mmwave::MmWaveUePhy::SetSubChannelsForReception (std::vector< int > mask)
Definition at line 239 of file mmwave-ue-phy.cc.
SetSubChannelsForTransmission()
void ns3::mmwave::MmWaveUePhy::SetSubChannelsForTransmission (std::vector< int > mask)
Definition at line 286 of file mmwave-ue-phy.cc.
References CreateTxPowerSpectralDensity(), ns3::mmwave::MmWavePhy::m_downlinkSpectrumPhy, and m_subChannelsForTx.
Referenced by StartTti().
SetTxPower()
void ns3::mmwave::MmWaveUePhy::SetTxPower (double pow)
Definition at line 202 of file mmwave-ue-phy.cc.
References ns3::mmwave::MmWavePhy::m_txPower.
Referenced by GetTypeId().
SetUeCphySapUser()
void ns3::mmwave::MmWaveUePhy::SetUeCphySapUser (LteUeCphySapUser * s)
Definition at line 176 of file mmwave-ue-phy.cc.
References m_ueCphySapUser.
SlotIndication()
void ns3::mmwave::MmWaveUePhy::SlotIndication (uint16_t frameNum, uint8_t subframeNum, uint8_t slotNum)
Marks the beginning of a new NR slot.
Parameters
frameNum the current frame
subframeNum the current subframe
slotNum the current slot
Definition at line 500 of file mmwave-ue-phy.cc.
References InitializeSlotAllocation(), m_currSlotAllocInfo, ns3::mmwave::SfnSf::m_frameNum, ns3::mmwave::MmWavePhy::m_frameNum, ns3::mmwave::MmWavePhy::m_lastSlotStart, ns3::mmwave::SlotAllocInfo::m_sfnSf, ns3::mmwave::SfnSf::m_sfNum, ns3::mmwave::MmWavePhy::m_sfNum, ns3::mmwave::MmWavePhy::m_slotAllocInfo, ns3::mmwave::SfnSf::m_slotNum, ns3::mmwave::MmWavePhy::m_slotNum, ns3::mmwave::MmWavePhy::m_ttiIndex, and StartTti().
Referenced by EndTti(), and MmWaveUePhy().
StartTti()
void ns3::mmwave::MmWaveUePhy::StartTti (void)
Marks the beginning of a new Transmission Time Interval (TTI).
Periodically, it alternates with EndTti in order to scan through the TTIs scheduled within a slot.
Definition at line 523 of file mmwave-ue-phy.cc.
References ns3::mmwave::PhyTransmissionTraceParams::CTRL, ns3::mmwave::PhyTransmissionTraceParams::DATA, ns3::mmwave::DciInfoElementTdma::DL_dci, EndTti(), ns3::mmwave::MmWavePhy::GetControlMessages(), ns3::mmwave::MmWavePhy::GetPacketBurst(), ns3::mmwave::MmWaveMacPduTag::GetSfn(), ns3::mmwave::MmWavePhy::m_cellId, m_channelChunks, m_currSlotAllocInfo, m_currTti, ns3::mmwave::TtiAllocInfo::m_dci, ns3::mmwave::MmWavePhy::m_downlinkSpectrumPhy, ns3::mmwave::DciInfoElementTdma::m_format, ns3::mmwave::SfnSf::m_frameNum, ns3::mmwave::MmWavePhy::m_frameNum, ns3::mmwave::DciInfoElementTdma::m_harqProcess, m_imsi, ns3::mmwave::DciInfoElementTdma::m_mcs, ns3::mmwave::DciInfoElementTdma::m_ndi, ns3::mmwave::DciInfoElementTdma::m_numSym, ns3::mmwave::MmWavePhy::m_phyMacConfig, m_phySapUser, m_prevTtiDir, m_receptionEnabled, m_registeredEnb, m_reportDlTbSize, m_reportUlTbSize, ns3::mmwave::DciInfoElementTdma::m_rnti, m_rnti, ns3::mmwave::DciInfoElementTdma::m_rv, m_sendDataChannelEvent, ns3::mmwave::SfnSf::m_sfNum, ns3::mmwave::MmWavePhy::m_sfNum, ns3::mmwave::SfnSf::m_slotNum, ns3::mmwave::MmWavePhy::m_slotNum, ns3::mmwave::SfnSf::m_symStart, ns3::mmwave::DciInfoElementTdma::m_symStart, ns3::mmwave::DciInfoElementTdma::m_tbSize, ns3::mmwave::TtiAllocInfo::m_tddMode, ns3::mmwave::SlotAllocInfo::m_ttiAllocInfo, ns3::mmwave::MmWavePhy::m_ttiIndex, SendCtrlChannels(), SendDataChannels(), SetSubChannelsForTransmission(), ns3::mmwave::MmWaveUePhySapUser::SlotIndication(), TraceUlPhyTransmission(), and ns3::mmwave::DciInfoElementTdma::UL_dci.
Referenced by EndTti(), and SlotIndication().
TraceUlPhyTransmission()
void ns3::mmwave::MmWaveUePhy::TraceUlPhyTransmission (DciInfoElementTdma dciInfo, uint8_t tddType) private
Triggers the callback for the ReportUlPhyTransmission Trace Source.
Sets up the necessary info for the ReportUlPhyTransmission source and triggers the related callback
Parameters
dciInfo the actual DCI info for the current UL transmission
tddType the TDD TTI type. Either DATA or CTRL
< Holds the current UL transmission info
Definition at line 960 of file mmwave-ue-phy.cc.
References ns3::mmwave::PhyTransmissionTraceParams::m_ccId, ns3::mmwave::MmWavePhy::m_componentCarrierId, ns3::mmwave::PhyTransmissionTraceParams::m_frameNum, ns3::mmwave::MmWavePhy::m_frameNum, ns3::mmwave::PhyTransmissionTraceParams::m_numSym, ns3::mmwave::DciInfoElementTdma::m_numSym, ns3::mmwave::PhyTransmissionTraceParams::m_rnti, ns3::mmwave::DciInfoElementTdma::m_rnti, ns3::mmwave::PhyTransmissionTraceParams::m_rv, ns3::mmwave::DciInfoElementTdma::m_rv, ns3::mmwave::PhyTransmissionTraceParams::m_sfNum, ns3::mmwave::MmWavePhy::m_sfNum, ns3::mmwave::PhyTransmissionTraceParams::m_slotNum, ns3::mmwave::MmWavePhy::m_slotNum, ns3::mmwave::PhyTransmissionTraceParams::m_symStart, ns3::mmwave::DciInfoElementTdma::m_symStart, ns3::mmwave::PhyTransmissionTraceParams::m_tddMode, ns3::mmwave::PhyTransmissionTraceParams::m_ttiType, m_ulPhyTrace, and ns3::mmwave::PhyTransmissionTraceParams::UL.
Referenced by StartTti().
UpdateSinrEstimate()
void ns3::mmwave::MmWaveUePhy::UpdateSinrEstimate (uint16_t cellId, double sinr)
Definition at line 245 of file mmwave-ue-phy.cc.
References ns3::mmwave::MmWavePhy::m_cellId, m_cellSinrMap, m_consecutiveSinrBelowThreshold, m_n310, and m_outageThreshold.
Friends And Related Function Documentation
MemberLteUeCphySapProvider< MmWaveUePhy >
friend class MemberLteUeCphySapProvider< MmWaveUePhy > friend
Definition at line 60 of file mmwave-ue-phy.h.
Referenced by MmWaveUePhy().
UeMemberLteUePhySapProvider
friend class UeMemberLteUePhySapProvider friend
Definition at line 59 of file mmwave-ue-phy.h.
Member Data Documentation
m_amc
Ptr<MmWaveAmc> ns3::mmwave::MmWaveUePhy::m_amc private
Definition at line 209 of file mmwave-ue-phy.h.
Referenced by CreateDlCqiFeedbackMessage().
m_cellSinrMap
std::map<uint16_t, double> ns3::mmwave::MmWaveUePhy::m_cellSinrMap private
Definition at line 252 of file mmwave-ue-phy.h.
Referenced by MmWaveUePhy(), and UpdateSinrEstimate().
m_channelChunks
std::vector<int> ns3::mmwave::MmWaveUePhy::m_channelChunks private
Definition at line 242 of file mmwave-ue-phy.h.
Referenced by DoInitialize(), and StartTti().
m_consecutiveSinrBelowThreshold
uint8_t ns3::mmwave::MmWaveUePhy::m_consecutiveSinrBelowThreshold private
Definition at line 254 of file mmwave-ue-phy.h.
Referenced by UpdateSinrEstimate().
m_currSlotAllocInfo
SlotAllocInfo ns3::mmwave::MmWaveUePhy::m_currSlotAllocInfo private
Holds the allocation info for the current NR slot.
Definition at line 218 of file mmwave-ue-phy.h.
Referenced by EndTti(), ReceiveControlMessageList(), SlotIndication(), and StartTti().
m_currTti
TtiAllocInfo ns3::mmwave::MmWaveUePhy::m_currTti private
Holds the allocation info for the current Tti.
Definition at line 244 of file mmwave-ue-phy.h.
Referenced by CreateDlCqiFeedbackMessage(), and StartTti().
m_dataPeriod
Time ns3::mmwave::MmWaveUePhy::m_dataPeriod private
Data period time duration.
Definition at line 222 of file mmwave-ue-phy.h.
m_dlConfigured
bool ns3::mmwave::MmWaveUePhy::m_dlConfigured private
Definition at line 224 of file mmwave-ue-phy.h.
m_harqPhyModule
Ptr<MmWaveHarqPhy> ns3::mmwave::MmWaveUePhy::m_harqPhyModule private
Definition at line 240 of file mmwave-ue-phy.h.
Referenced by SetHarqPhyModule().
m_imsi
uint64_t ns3::mmwave::MmWaveUePhy::m_imsi private
Definition at line 238 of file mmwave-ue-phy.h.
Referenced by GenerateDlCqiReport(), GetImsi(), SetImsi(), and StartTti().
m_n310
uint8_t ns3::mmwave::MmWaveUePhy::m_n310 private
Definition at line 256 of file mmwave-ue-phy.h.
Referenced by GetTypeId(), and UpdateSinrEstimate().
m_outageThreshold
long double ns3::mmwave::MmWaveUePhy::m_outageThreshold private
Definition at line 255 of file mmwave-ue-phy.h.
Referenced by GetTypeId(), and UpdateSinrEstimate().
m_phyReset
bool ns3::mmwave::MmWaveUePhy::m_phyReset private
Definition at line 250 of file mmwave-ue-phy.h.
Referenced by DoInitialize(), DoReset(), PhyDataPacketReceived(), and RegisterToEnb().
m_phySapUser
MmWaveUePhySapUser* ns3::mmwave::MmWaveUePhy::m_phySapUser private
Definition at line 204 of file mmwave-ue-phy.h.
Referenced by DelayPhyDataPacketReceived(), ReceiveControlMessageList(), RegisterToEnb(), SetPhySapUser(), and StartTti().
m_prevSlot
uint8_t ns3::mmwave::MmWaveUePhy::m_prevSlot private
Definition at line 234 of file mmwave-ue-phy.h.
m_prevTtiDir
TtiAllocInfo::TddMode ns3::mmwave::MmWaveUePhy::m_prevTtiDir private
Time Division Duplexing (TDD) mode of the previous Tti.
Definition at line 216 of file mmwave-ue-phy.h.
Referenced by StartTti().
m_receptionEnabled
bool ns3::mmwave::MmWaveUePhy::m_receptionEnabled private
Definition at line 236 of file mmwave-ue-phy.h.
Referenced by EndTti(), GenerateDlCqiReport(), IsReceptionEnabled(), ResetReception(), and StartTti().
m_registeredEnb
std::map<uint16_t, std::pair<Ptr<MmWavePhyMacCommon>, Ptr<MmWaveEnbNetDevice> > > ns3::mmwave::MmWaveUePhy::m_registeredEnb private
Definition at line 246 of file mmwave-ue-phy.h.
Referenced by DoDispose(), DoSynchronizeWithEnb(), RegisterOtherEnb(), RegisterToEnb(), and StartTti().
m_reportCurrentCellRsrpSinrTrace
TracedCallback< uint64_t, SpectrumValue&, SpectrumValue& > ns3::mmwave::MmWaveUePhy::m_reportCurrentCellRsrpSinrTrace private
Definition at line 227 of file mmwave-ue-phy.h.
Referenced by GenerateDlCqiReport(), and GetTypeId().
m_reportDlTbSize
TracedCallback<uint64_t, uint64_t> ns3::mmwave::MmWaveUePhy::m_reportDlTbSize private
Definition at line 230 of file mmwave-ue-phy.h.
Referenced by GetTypeId(), and StartTti().
m_reportUlTbSize
TracedCallback<uint64_t, uint64_t> ns3::mmwave::MmWaveUePhy::m_reportUlTbSize private
Definition at line 229 of file mmwave-ue-phy.h.
Referenced by GetTypeId(), and StartTti().
m_rnti
uint16_t ns3::mmwave::MmWaveUePhy::m_rnti private
Definition at line 237 of file mmwave-ue-phy.h.
Referenced by CreateDlCqiFeedbackMessage(), DoReset(), DoSetRnti(), EndTti(), GenerateDlCqiReport(), GetRnti(), ReceiveControlMessageList(), and StartTti().
m_sendDataChannelEvent
EventId ns3::mmwave::MmWaveUePhy::m_sendDataChannelEvent private
Definition at line 248 of file mmwave-ue-phy.h.
Referenced by DoReset(), and StartTti().
m_sendDlHarqFeedbackEvent
EventId ns3::mmwave::MmWaveUePhy::m_sendDlHarqFeedbackEvent private
Definition at line 249 of file mmwave-ue-phy.h.
Referenced by DoReset(), and ReceiveLteDlHarqFeedback().
m_sfAllocInfoUpdated
bool ns3::mmwave::MmWaveUePhy::m_sfAllocInfoUpdated private
Definition at line 220 of file mmwave-ue-phy.h.
m_subChannelsforRx
std::vector<int> ns3::mmwave::MmWaveUePhy::m_subChannelsforRx private
Definition at line 211 of file mmwave-ue-phy.h.
m_subChannelsForTx
std::vector<int> ns3::mmwave::MmWaveUePhy::m_subChannelsForTx private
Definition at line 210 of file mmwave-ue-phy.h.
Referenced by CreateTxPowerSpectralDensity(), DoReset(), and SetSubChannelsForTransmission().
m_ueCphySapProvider
LteUeCphySapProvider* ns3::mmwave::MmWaveUePhy::m_ueCphySapProvider private
Definition at line 206 of file mmwave-ue-phy.h.
Referenced by GetUeCphySapProvider(), and MmWaveUePhy().
m_ueCphySapUser
LteUeCphySapUser* ns3::mmwave::MmWaveUePhy::m_ueCphySapUser private
Definition at line 207 of file mmwave-ue-phy.h.
Referenced by ReceiveControlMessageList(), and SetUeCphySapUser().
m_ulConfigured
bool ns3::mmwave::MmWaveUePhy::m_ulConfigured private
Definition at line 225 of file mmwave-ue-phy.h.
Referenced by DoConfigureUplink(), and GenerateDlCqiReport().
m_ulGrant
bool ns3::mmwave::MmWaveUePhy::m_ulGrant private
Definition at line 219 of file mmwave-ue-phy.h.
m_ulPhyTrace
TracedCallback<PhyTransmissionTraceParams> ns3::mmwave::MmWaveUePhy::m_ulPhyTrace private
Traces the current TTI allocation info, from the UE side.
Definition at line 232 of file mmwave-ue-phy.h.
Referenced by GetTypeId(), and TraceUlPhyTransmission().
m_wbCqiLast
Time ns3::mmwave::MmWaveUePhy::m_wbCqiLast private
Definition at line 214 of file mmwave-ue-phy.h.
Referenced by GenerateDlCqiReport(), and MmWaveUePhy().
m_wbCqiPeriod
Time ns3::mmwave::MmWaveUePhy::m_wbCqiPeriod private
Wideband Periodic CQI: 2, 5, 10, 16, 20, 32, 40, 64, 80 or 160 ms.
Definition at line 213 of file mmwave-ue-phy.h.
Referenced by GenerateDlCqiReport().
The documentation for this class was generated from the following files:
src/mmwave/model/mmwave-ue-phy.h
src/mmwave/model/mmwave-ue-phy.cc