ns3-mmwave: ns3::mmwave::MmWaveBearerStatsConnector Class Reference
ns3::mmwave::MmWaveBearerStatsConnector Class Reference
This class is very useful when user needs to collect statistics from PDCD and RLC.
#include "mmwave-bearer-stats-connector.h"
Classes
struct CellIdRnti
Struct used as key in m_ueManagerPathByCellIdRnti map.
Public Member Functions
MmWaveBearerStatsConnector ()
Constructor.
virtual ~MmWaveBearerStatsConnector ()
Class destructor.
void DoDispose ()
void EnableMcStats (Ptr< McStatsCalculator > mcStats)
void EnablePdcpStats (Ptr< MmWaveBearerStatsCalculator > pdcpStats)
Enables trace sinks for PDCP layer.
void EnableRlcStats (Ptr< MmWaveBearerStatsCalculator > rlcStats)
Enables trace sinks for RLC layer.
void EnsureConnected ()
Connects trace sinks to appropriate trace sources.
std::string GetCellIdStatsOutputFilename (void)
std::string GetEnbHandoverEndOutputFilename (void)
std::string GetEnbHandoverStartOutputFilename (void)
std::string GetLteSinrOutputFilename (void)
std::string GetMmWaveSinrOutputFilename (void)
std::string GetUeHandoverEndOutputFilename (void)
std::string GetUeHandoverStartOutputFilename (void)
void PrintLteSinr (uint16_t rnti, uint16_t cellId, double sinr)
void PrintMmWaveSinr (uint64_t imsi, uint16_t cellId, long double sinr)
void SetCellIdStatsOutputFilename (std::string outputFilename)
void SetEnbHandoverEndOutputFilename (std::string outputFilename)
void SetEnbHandoverStartOutputFilename (std::string outputFilename)
void SetLteSinrOutputFilename (std::string outputFilename)
void SetMmWaveSinrOutputFilename (std::string outputFilename)
void SetUeHandoverEndOutputFilename (std::string outputFilename)
void SetUeHandoverStartOutputFilename (std::string outputFilename)
Static Public Member Functions
static TypeId GetTypeId (void)
Register this type.
static void NotifyConnectionReconfigurationEnb (MmWaveBearerStatsConnector *c, std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti)
Function hooked to ConnectionReconfiguration trace source at eNB RRC, which is fired upon RRC connection reconfiguration.
static void NotifyConnectionReconfigurationUe (MmWaveBearerStatsConnector *c, std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti)
Function hooked to ConnectionReconfiguration trace source at UE RRC, which is fired upon RRC connection reconfiguration.
static void NotifyConnectionSetupUe (MmWaveBearerStatsConnector *c, std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti)
Sink connected source of UE Connection Setup trace.
static void NotifyHandoverEndOkEnb (MmWaveBearerStatsConnector *c, std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti)
Function hooked to HandoverEndOk trace source at eNB RRC, which is fired upon successful termination of a handover procedure.
static void NotifyHandoverEndOkUe (MmWaveBearerStatsConnector *c, std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti)
Function hooked to HandoverStart trace source at UE RRC, which is fired upon successful termination of a handover procedure.
static void NotifyHandoverStartEnb (MmWaveBearerStatsConnector *c, std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti, uint16_t targetCellId)
Function hooked to HandoverStart trace source at eNB RRC, which is fired upon start of a handover procedure.
static void NotifyHandoverStartUe (MmWaveBearerStatsConnector *c, std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti, uint16_t targetCellId)
Function hooked to HandoverStart trace source at UE RRC, which is fired upon start of a handover procedure.
static void NotifyLteSinr (MmWaveBearerStatsConnector *c, std::string context, uint16_t cellId, uint16_t rnti, double rsrp, double sinr, uint8_t cc)
static void NotifyMmWaveSinr (MmWaveBearerStatsConnector *c, std::string context, uint64_t imsi, uint16_t cellId, long double sinr)
static void NotifyNewUeContextEnb (MmWaveBearerStatsConnector *c, std::string context, uint16_t cellid, uint16_t rnti)
Function hooked to NewUeContext trace source at eNB RRC, which is fired upon creation of a new UE context.
static void NotifyRandomAccessSuccessfulUe (MmWaveBearerStatsConnector *c, std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti)
Function hooked to RandomAccessSuccessful trace source at UE RRC, which is fired upon successful completion of the random access procedure.
static void NotifySecondaryMmWaveEnbAvailable (MmWaveBearerStatsConnector *c, std::string context, uint64_t imsi, uint16_t cellId, uint16_t rnti)
static void NotifySwitchToMmWaveUe (MmWaveBearerStatsConnector *c, std::string context, uint64_t imsi, uint16_t cellId, uint16_t rnti)
Private Member Functions
void ConnectDrbTracesEnb (std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti)
Connects DRBs trace sources at eNB to RLC and PDCP calculators.
void ConnectDrbTracesUe (std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti)
Connects DRBs trace sources at UE to RLC and PDCP calculators.
void ConnectSecondaryTracesEnb (std::string context, uint64_t imsi, uint16_t cellId, uint16_t rnti)
void ConnectSecondaryTracesUe (std::string context, uint64_t imsi, uint16_t cellId, uint16_t rnti)
void ConnectSrb0Traces (std::string ueRrcPath, uint64_t imsi, uint16_t cellId, uint16_t rnti)
Connects Srb0 trace sources at UE and eNB to RLC and PDCP calculators, and Srb1 trace sources at eNB to RLC and PDCP calculators,.
void ConnectSrb1TracesEnb (std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti)
Connects SRB1 trace sources at eNB to RLC and PDCP calculators.
void ConnectSrb1TracesUe (std::string ueRrcPath, uint64_t imsi, uint16_t cellId, uint16_t rnti)
Connects SRB1 trace sources at UE to RLC and PDCP calculators.
void ConnectTracesEnbIfFirstTime (std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti)
Connects all trace sources at eNB to RLC and PDCP calculators.
void ConnectTracesUeIfFirstTime (std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti)
Connects all trace sources at UE to RLC and PDCP calculators.
void DisconnectDrbTracesUe (std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti)
Disconnects DRB trace sources at UE to RLC and PDCP calculators.
void DisconnectTracesEnb (std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti)
Disconnects all trace sources at eNB to RLC and PDCP calculators.
void DisconnectTracesUe (std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti)
Disconnects all trace sources at UE to RLC and PDCP calculators.
void PrintEnbEndHandover (uint64_t imsi, uint16_t targetCellId, uint16_t rnti)
void PrintEnbStartHandover (uint64_t imsi, uint16_t sourceCellid, uint16_t targetCellId, uint16_t rnti)
void PrintUeEndHandover (uint64_t imsi, uint16_t targetCellId, uint16_t rnti)
void PrintUeStartHandover (uint64_t imsi, uint16_t sourceCellid, uint16_t targetCellId, uint16_t rnti)
void StoreUeManagerPath (std::string ueManagerPath, uint16_t cellId, uint16_t rnti)
Creates UE Manager path and stores it in m_ueManagerPathByCellIdRnti.
Private Attributes
std::string m_cellIdInTimeHandoverFilename
std::ofstream m_cellIdInTimeHandoverOutFile
bool m_connected
true if traces are connected to sinks, initially set to false
std::string m_enbHandoverEndFilename
std::ofstream m_enbHandoverEndOutFile
std::string m_enbHandoverStartFilename
std::ofstream m_enbHandoverStartOutFile
std::set< uint64_t > m_imsiSeenEnbDrb
stores all eNBs for which RLC and PDCP traces for DRBs were connected
std::map< uint64_t, uint16_t > m_imsiSeenUeDrb
stores all UEs for which RLC and PDCP traces for DRBs were connected
std::set< uint64_t > m_imsiSeenUeSrb
stores all UEs for which RLC and PDCP for SRB1 traces were connected
std::ofstream m_lteSinrOutFile
std::string m_lteSinrOutputFilename
Ptr< McStatsCalculator > m_mcStats
Calculator for multi-connectivity Statistics.
std::ofstream m_mmWaveSinrOutFile
std::string m_mmWaveSinrOutputFilename
std::map< uint64_t, CallbackBase > m_pdcpDrbDlRxCb
Sinks for the received DL PDCP data packets.
std::map< uint64_t, CallbackBase > m_pdcpDrbUlTxCb
Sinks for the sent UL PDCP data packets.
Ptr< MmWaveBearerStatsCalculator > m_pdcpStats
Calculator for PDCP Statistics.
std::map< uint64_t, CallbackBase > m_rlcDrbDlRxCb
Sinks for the received DL RLC data packets.
std::map< uint64_t, CallbackBase > m_rlcDrbUlTxCb
Sinks for the sent UL RLC data packets.
Ptr< MmWaveBearerStatsCalculator > m_rlcStats
Calculator for RLC Statistics.
std::string m_ueHandoverEndFilename
std::ofstream m_ueHandoverEndOutFile
std::string m_ueHandoverStartFilename
std::ofstream m_ueHandoverStartOutFile
std::map< CellIdRnti, std::string > m_ueManagerPathByCellIdRnti
List UE Manager Paths by CellIdRnti.
Friends
bool operator< (const CellIdRnti &a, const CellIdRnti &b)
Less than operator for CellIdRnti, because it is used as key in map.
Detailed Description
This class is very useful when user needs to collect statistics from PDCD and RLC.
It automatically connects MmWaveBearerStatsCalculator to appropriate trace sinks. Usually user do not use this class. All he/she needs to to do is to call: LteHelper::EnablePdcpTraces() and/or LteHelper::EnableRlcTraces().
Definition at line 70 of file mmwave-bearer-stats-connector.h.
Constructor & Destructor Documentation
MmWaveBearerStatsConnector()
ns3::mmwave::MmWaveBearerStatsConnector::MmWaveBearerStatsConnector ()
Constructor.
Definition at line 172 of file mmwave-bearer-stats-connector.cc.
~MmWaveBearerStatsConnector()
ns3::mmwave::MmWaveBearerStatsConnector::~MmWaveBearerStatsConnector () virtual
Class destructor.
Definition at line 183 of file mmwave-bearer-stats-connector.cc.
References m_cellIdInTimeHandoverOutFile, m_enbHandoverEndOutFile, m_enbHandoverStartOutFile, m_lteSinrOutFile, m_mmWaveSinrOutFile, m_ueHandoverEndOutFile, and m_ueHandoverStartOutFile.
Member Function Documentation
ConnectDrbTracesEnb()
void ns3::mmwave::MmWaveBearerStatsConnector::ConnectDrbTracesEnb (std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti) private
Connects DRBs trace sources at eNB to RLC and PDCP calculators.
Parameters
context
imsi
cellid
rnti
Definition at line 833 of file mmwave-bearer-stats-connector.cc.
References ns3::mmwave::DlTxPduCallback(), m_pdcpStats, m_rlcStats, and ns3::mmwave::UlRxPduCallback().
Referenced by ConnectTracesEnbIfFirstTime(), and NotifyHandoverEndOkEnb().
ConnectDrbTracesUe()
void ns3::mmwave::MmWaveBearerStatsConnector::ConnectDrbTracesUe (std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti) private
Connects DRBs trace sources at UE to RLC and PDCP calculators.
Parameters
context
imsi
cellid
rnti
Definition at line 718 of file mmwave-bearer-stats-connector.cc.
References ns3::mmwave::DlRxPduCallback(), m_pdcpDrbDlRxCb, m_pdcpDrbUlTxCb, m_pdcpStats, m_rlcDrbDlRxCb, m_rlcDrbUlTxCb, m_rlcStats, and ns3::mmwave::UlTxPduCallback().
Referenced by ConnectTracesUeIfFirstTime(), and NotifyHandoverEndOkUe().
ConnectSecondaryTracesEnb()
void ns3::mmwave::MmWaveBearerStatsConnector::ConnectSecondaryTracesEnb (std::string context, uint64_t imsi, uint16_t cellId, uint16_t rnti) private
Definition at line 942 of file mmwave-bearer-stats-connector.cc.
References ns3::mmwave::DlTxPduCallback(), m_rlcStats, and ns3::mmwave::UlRxPduCallback().
Referenced by NotifySecondaryMmWaveEnbAvailable().
ConnectSecondaryTracesUe()
void ns3::mmwave::MmWaveBearerStatsConnector::ConnectSecondaryTracesUe (std::string context, uint64_t imsi, uint16_t cellId, uint16_t rnti) private
Definition at line 919 of file mmwave-bearer-stats-connector.cc.
References ns3::mmwave::DlRxPduCallback(), m_rlcStats, and ns3::mmwave::UlTxPduCallback().
Referenced by NotifySwitchToMmWaveUe().
ConnectSrb0Traces()
void ns3::mmwave::MmWaveBearerStatsConnector::ConnectSrb0Traces (std::string ueRrcPath, uint64_t imsi, uint16_t cellId, uint16_t rnti) private
Connects Srb0 trace sources at UE and eNB to RLC and PDCP calculators, and Srb1 trace sources at eNB to RLC and PDCP calculators,.
Parameters
ueRrcPath
imsi
cellId
rnti
Definition at line 589 of file mmwave-bearer-stats-connector.cc.
References ns3::mmwave::MmWaveBearerStatsConnector::CellIdRnti::cellId, ns3::mmwave::DlRxPduCallback(), ns3::mmwave::DlTxPduCallback(), m_pdcpStats, m_rlcStats, m_ueManagerPathByCellIdRnti, ns3::mmwave::MmWaveBearerStatsConnector::CellIdRnti::rnti, ns3::mmwave::UlRxPduCallback(), and ns3::mmwave::UlTxPduCallback().
Referenced by NotifyRandomAccessSuccessfulUe().
ConnectSrb1TracesEnb()
void ns3::mmwave::MmWaveBearerStatsConnector::ConnectSrb1TracesEnb (std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti) private
Connects SRB1 trace sources at eNB to RLC and PDCP calculators.
Parameters
context
imsi
cellid
rnti
Definition at line 798 of file mmwave-bearer-stats-connector.cc.
References ns3::mmwave::DlTxPduCallback(), m_pdcpStats, m_rlcStats, and ns3::mmwave::UlRxPduCallback().
Referenced by NotifyHandoverEndOkEnb().
ConnectSrb1TracesUe()
void ns3::mmwave::MmWaveBearerStatsConnector::ConnectSrb1TracesUe (std::string ueRrcPath, uint64_t imsi, uint16_t cellId, uint16_t rnti) private
Connects SRB1 trace sources at UE to RLC and PDCP calculators.
Parameters
ueRrcPath
imsi
cellId
rnti
Definition at line 757 of file mmwave-bearer-stats-connector.cc.
References ns3::mmwave::DlRxPduCallback(), m_mcStats, m_pdcpStats, m_rlcStats, ns3::mmwave::SwitchToLteCallback(), ns3::mmwave::SwitchToMmWaveCallback(), and ns3::mmwave::UlTxPduCallback().
Referenced by ConnectTracesUeIfFirstTime(), NotifyConnectionSetupUe(), and NotifyHandoverEndOkUe().
ConnectTracesEnbIfFirstTime()
void ns3::mmwave::MmWaveBearerStatsConnector::ConnectTracesEnbIfFirstTime (std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti) private
Connects all trace sources at eNB to RLC and PDCP calculators.
This function can connect traces only once for eNB.
Parameters
context
imsi
cellid
rnti
Definition at line 696 of file mmwave-bearer-stats-connector.cc.
References ConnectDrbTracesEnb(), and m_imsiSeenEnbDrb.
Referenced by NotifyConnectionReconfigurationEnb().
ConnectTracesUeIfFirstTime()
void ns3::mmwave::MmWaveBearerStatsConnector::ConnectTracesUeIfFirstTime (std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti) private
Connects all trace sources at UE to RLC and PDCP calculators.
This function can connect traces only once for UE.
Parameters
context
imsi
cellid
rnti
Definition at line 652 of file mmwave-bearer-stats-connector.cc.
References ConnectDrbTracesUe(), ConnectSrb1TracesUe(), DisconnectDrbTracesUe(), m_imsiSeenUeDrb, and m_imsiSeenUeSrb.
Referenced by NotifyConnectionReconfigurationUe().
DisconnectDrbTracesUe()
void ns3::mmwave::MmWaveBearerStatsConnector::DisconnectDrbTracesUe (std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti) private
Disconnects DRB trace sources at UE to RLC and PDCP calculators.
Function is not implemented.
Parameters
context
imsi
cellid
rnti
Definition at line 884 of file mmwave-bearer-stats-connector.cc.
References m_pdcpDrbDlRxCb, m_pdcpDrbUlTxCb, m_pdcpStats, m_rlcDrbDlRxCb, m_rlcDrbUlTxCb, and m_rlcStats.
Referenced by ConnectTracesUeIfFirstTime().
DisconnectTracesEnb()
void ns3::mmwave::MmWaveBearerStatsConnector::DisconnectTracesEnb (std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti) private
Disconnects all trace sources at eNB to RLC and PDCP calculators.
Function is not implemented.
Parameters
context
imsi
cellid
rnti
Definition at line 912 of file mmwave-bearer-stats-connector.cc.
Referenced by NotifyHandoverStartEnb().
DisconnectTracesUe()
void ns3::mmwave::MmWaveBearerStatsConnector::DisconnectTracesUe (std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti) private
Disconnects all trace sources at UE to RLC and PDCP calculators.
Function is not implemented.
Parameters
context
imsi
cellid
rnti
Definition at line 864 of file mmwave-bearer-stats-connector.cc.
References m_mcStats, ns3::mmwave::SwitchToLteCallback(), and ns3::mmwave::SwitchToMmWaveCallback().
Referenced by NotifyHandoverStartUe().
DoDispose()
void ns3::mmwave::MmWaveBearerStatsConnector::DoDispose ()
Definition at line 265 of file mmwave-bearer-stats-connector.cc.
EnableMcStats()
void ns3::mmwave::MmWaveBearerStatsConnector::EnableMcStats (Ptr< McStatsCalculator > mcStats)
Definition at line 285 of file mmwave-bearer-stats-connector.cc.
References EnsureConnected(), and m_mcStats.
EnablePdcpStats()
void ns3::mmwave::MmWaveBearerStatsConnector::EnablePdcpStats (Ptr< MmWaveBearerStatsCalculator > pdcpStats)
Enables trace sinks for PDCP layer.
Usually, this function is called by LteHelper::EnablePdcpTraces().
Parameters
pdcpStats statistics calculator for PDCP layer
Definition at line 278 of file mmwave-bearer-stats-connector.cc.
References EnsureConnected(), and m_pdcpStats.
EnableRlcStats()
void ns3::mmwave::MmWaveBearerStatsConnector::EnableRlcStats (Ptr< MmWaveBearerStatsCalculator > rlcStats)
Enables trace sinks for RLC layer.
Usually, this function is called by LteHelper::EnableRlcTraces().
Parameters
rlcStats statistics calculator for RLC layer
Definition at line 271 of file mmwave-bearer-stats-connector.cc.
References EnsureConnected(), and m_rlcStats.
EnsureConnected()
void ns3::mmwave::MmWaveBearerStatsConnector::EnsureConnected ()
Connects trace sinks to appropriate trace sources.
Definition at line 292 of file mmwave-bearer-stats-connector.cc.
References m_connected, NotifyConnectionReconfigurationEnb(), NotifyConnectionReconfigurationUe(), NotifyHandoverEndOkEnb(), NotifyHandoverEndOkUe(), NotifyHandoverStartEnb(), NotifyHandoverStartUe(), NotifyLteSinr(), NotifyMmWaveSinr(), NotifyNewUeContextEnb(), NotifyRandomAccessSuccessfulUe(), and NotifySwitchToMmWaveUe().
Referenced by EnableMcStats(), EnablePdcpStats(), and EnableRlcStats().
GetCellIdStatsOutputFilename()
std::string ns3::mmwave::MmWaveBearerStatsConnector::GetCellIdStatsOutputFilename (void)
Definition at line 475 of file mmwave-bearer-stats-connector.cc.
References m_cellIdInTimeHandoverFilename.
Referenced by PrintUeEndHandover().
GetEnbHandoverEndOutputFilename()
std::string ns3::mmwave::MmWaveBearerStatsConnector::GetEnbHandoverEndOutputFilename (void)
Definition at line 445 of file mmwave-bearer-stats-connector.cc.
References m_enbHandoverEndFilename.
Referenced by PrintEnbEndHandover().
GetEnbHandoverStartOutputFilename()
std::string ns3::mmwave::MmWaveBearerStatsConnector::GetEnbHandoverStartOutputFilename (void)
Definition at line 439 of file mmwave-bearer-stats-connector.cc.
References m_enbHandoverStartFilename.
Referenced by PrintEnbStartHandover().
GetLteSinrOutputFilename()
std::string ns3::mmwave::MmWaveBearerStatsConnector::GetLteSinrOutputFilename (void)
Definition at line 457 of file mmwave-bearer-stats-connector.cc.
References m_lteSinrOutputFilename.
Referenced by PrintLteSinr().
GetMmWaveSinrOutputFilename()
std::string ns3::mmwave::MmWaveBearerStatsConnector::GetMmWaveSinrOutputFilename (void)
Definition at line 451 of file mmwave-bearer-stats-connector.cc.
References m_mmWaveSinrOutputFilename.
Referenced by PrintMmWaveSinr().
GetTypeId()
TypeId ns3::mmwave::MmWaveBearerStatsConnector::GetTypeId (void) static
Register this type.
Returns
The object TypeId.
Definition at line 218 of file mmwave-bearer-stats-connector.cc.
References SetCellIdStatsOutputFilename(), SetEnbHandoverEndOutputFilename(), SetEnbHandoverStartOutputFilename(), SetLteSinrOutputFilename(), SetMmWaveSinrOutputFilename(), SetUeHandoverEndOutputFilename(), and SetUeHandoverStartOutputFilename().
GetUeHandoverEndOutputFilename()
std::string ns3::mmwave::MmWaveBearerStatsConnector::GetUeHandoverEndOutputFilename (void)
Definition at line 469 of file mmwave-bearer-stats-connector.cc.
References m_ueHandoverEndFilename.
Referenced by PrintUeEndHandover().
GetUeHandoverStartOutputFilename()
std::string ns3::mmwave::MmWaveBearerStatsConnector::GetUeHandoverStartOutputFilename (void)
Definition at line 463 of file mmwave-bearer-stats-connector.cc.
References m_ueHandoverStartFilename.
Referenced by PrintUeStartHandover().
NotifyConnectionReconfigurationEnb()
void ns3::mmwave::MmWaveBearerStatsConnector::NotifyConnectionReconfigurationEnb (MmWaveBearerStatsConnector * c, std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti) static
Function hooked to ConnectionReconfiguration trace source at eNB RRC, which is fired upon RRC connection reconfiguration.
Parameters
c
context
imsi
cellid
rnti
Definition at line 372 of file mmwave-bearer-stats-connector.cc.
References ConnectTracesEnbIfFirstTime().
Referenced by EnsureConnected().
NotifyConnectionReconfigurationUe()
void ns3::mmwave::MmWaveBearerStatsConnector::NotifyConnectionReconfigurationUe (MmWaveBearerStatsConnector * c, std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti) static
Function hooked to ConnectionReconfiguration trace source at UE RRC, which is fired upon RRC connection reconfiguration.
Parameters
c
context
imsi
cellid
rnti
Definition at line 345 of file mmwave-bearer-stats-connector.cc.
References ConnectTracesUeIfFirstTime().
Referenced by EnsureConnected().
NotifyConnectionSetupUe()
void ns3::mmwave::MmWaveBearerStatsConnector::NotifyConnectionSetupUe (MmWaveBearerStatsConnector * c, std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti) static
Sink connected source of UE Connection Setup trace.
Not used.
Parameters
c
context
imsi
cellid
rnti
Definition at line 339 of file mmwave-bearer-stats-connector.cc.
References ConnectSrb1TracesUe().
NotifyHandoverEndOkEnb()
void ns3::mmwave::MmWaveBearerStatsConnector::NotifyHandoverEndOkEnb (MmWaveBearerStatsConnector * c, std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti) static
Function hooked to HandoverEndOk trace source at eNB RRC, which is fired upon successful termination of a handover procedure.
Parameters
c
context
imsi
cellid
rnti
Definition at line 385 of file mmwave-bearer-stats-connector.cc.
References ConnectDrbTracesEnb(), ConnectSrb1TracesEnb(), and PrintEnbEndHandover().
Referenced by EnsureConnected().
NotifyHandoverEndOkUe()
void ns3::mmwave::MmWaveBearerStatsConnector::NotifyHandoverEndOkUe (MmWaveBearerStatsConnector * c, std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti) static
Function hooked to HandoverStart trace source at UE RRC, which is fired upon successful termination of a handover procedure.
Parameters
c
context
imsi
cellid
rnti
Definition at line 358 of file mmwave-bearer-stats-connector.cc.
References ConnectDrbTracesUe(), ConnectSrb1TracesUe(), and PrintUeEndHandover().
Referenced by EnsureConnected().
NotifyHandoverStartEnb()
void ns3::mmwave::MmWaveBearerStatsConnector::NotifyHandoverStartEnb (MmWaveBearerStatsConnector * c, std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti, uint16_t targetCellId) static
Function hooked to HandoverStart trace source at eNB RRC, which is fired upon start of a handover procedure.
Parameters
c
context
imsi
cellid
rnti
targetCellId
Definition at line 378 of file mmwave-bearer-stats-connector.cc.
References DisconnectTracesEnb(), and PrintEnbStartHandover().
Referenced by EnsureConnected().
NotifyHandoverStartUe()
void ns3::mmwave::MmWaveBearerStatsConnector::NotifyHandoverStartUe (MmWaveBearerStatsConnector * c, std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti, uint16_t targetCellId) static
Function hooked to HandoverStart trace source at UE RRC, which is fired upon start of a handover procedure.
Parameters
c
context
imsi
cellid
rnti
targetCellId
Definition at line 351 of file mmwave-bearer-stats-connector.cc.
References DisconnectTracesUe(), and PrintUeStartHandover().
Referenced by EnsureConnected().
NotifyLteSinr()
void ns3::mmwave::MmWaveBearerStatsConnector::NotifyLteSinr (MmWaveBearerStatsConnector * c, std::string context, uint16_t cellId, uint16_t rnti, double rsrp, double sinr, uint8_t cc) static
Definition at line 422 of file mmwave-bearer-stats-connector.cc.
References PrintLteSinr().
Referenced by EnsureConnected().
NotifyMmWaveSinr()
void ns3::mmwave::MmWaveBearerStatsConnector::NotifyMmWaveSinr (MmWaveBearerStatsConnector * c, std::string context, uint64_t imsi, uint16_t cellId, long double sinr) static
Definition at line 405 of file mmwave-bearer-stats-connector.cc.
References PrintMmWaveSinr().
Referenced by EnsureConnected().
NotifyNewUeContextEnb()
void ns3::mmwave::MmWaveBearerStatsConnector::NotifyNewUeContextEnb (MmWaveBearerStatsConnector * c, std::string context, uint16_t cellid, uint16_t rnti) static
Function hooked to NewUeContext trace source at eNB RRC, which is fired upon creation of a new UE context.
Parameters
c
context
cellid
rnti
Definition at line 366 of file mmwave-bearer-stats-connector.cc.
References StoreUeManagerPath().
Referenced by EnsureConnected().
NotifyRandomAccessSuccessfulUe()
void ns3::mmwave::MmWaveBearerStatsConnector::NotifyRandomAccessSuccessfulUe (MmWaveBearerStatsConnector * c, std::string context, uint64_t imsi, uint16_t cellid, uint16_t rnti) static
Function hooked to RandomAccessSuccessful trace source at UE RRC, which is fired upon successful completion of the random access procedure.
Parameters
c
context
imsi
cellid
rnti
Definition at line 333 of file mmwave-bearer-stats-connector.cc.
References ConnectSrb0Traces().
Referenced by EnsureConnected().
NotifySecondaryMmWaveEnbAvailable()
void ns3::mmwave::MmWaveBearerStatsConnector::NotifySecondaryMmWaveEnbAvailable (MmWaveBearerStatsConnector * c, std::string context, uint64_t imsi, uint16_t cellId, uint16_t rnti) static
Definition at line 399 of file mmwave-bearer-stats-connector.cc.
References ConnectSecondaryTracesEnb().
Referenced by StoreUeManagerPath().
NotifySwitchToMmWaveUe()
void ns3::mmwave::MmWaveBearerStatsConnector::NotifySwitchToMmWaveUe (MmWaveBearerStatsConnector * c, std::string context, uint64_t imsi, uint16_t cellId, uint16_t rnti) static
Definition at line 393 of file mmwave-bearer-stats-connector.cc.
References ConnectSecondaryTracesUe().
Referenced by EnsureConnected().
PrintEnbEndHandover()
void ns3::mmwave::MmWaveBearerStatsConnector::PrintEnbEndHandover (uint64_t imsi, uint16_t targetCellId, uint16_t rnti) private
Definition at line 532 of file mmwave-bearer-stats-connector.cc.
References GetEnbHandoverEndOutputFilename(), and m_enbHandoverEndOutFile.
Referenced by NotifyHandoverEndOkEnb().
PrintEnbStartHandover()
void ns3::mmwave::MmWaveBearerStatsConnector::PrintEnbStartHandover (uint64_t imsi, uint16_t sourceCellid, uint16_t targetCellId, uint16_t rnti) private
Definition at line 521 of file mmwave-bearer-stats-connector.cc.
References GetEnbHandoverStartOutputFilename(), and m_enbHandoverStartOutFile.
Referenced by NotifyHandoverStartEnb().
PrintLteSinr()
void ns3::mmwave::MmWaveBearerStatsConnector::PrintLteSinr (uint16_t rnti, uint16_t cellId, double sinr)
Definition at line 428 of file mmwave-bearer-stats-connector.cc.
References GetLteSinrOutputFilename(), and m_lteSinrOutFile.
Referenced by NotifyLteSinr().
PrintMmWaveSinr()
void ns3::mmwave::MmWaveBearerStatsConnector::PrintMmWaveSinr (uint64_t imsi, uint16_t cellId, long double sinr)
Definition at line 411 of file mmwave-bearer-stats-connector.cc.
References GetMmWaveSinrOutputFilename(), and m_mmWaveSinrOutFile.
Referenced by NotifyMmWaveSinr().
PrintUeEndHandover()
void ns3::mmwave::MmWaveBearerStatsConnector::PrintUeEndHandover (uint64_t imsi, uint16_t targetCellId, uint16_t rnti) private
Definition at line 554 of file mmwave-bearer-stats-connector.cc.
References GetCellIdStatsOutputFilename(), GetUeHandoverEndOutputFilename(), m_cellIdInTimeHandoverOutFile, and m_ueHandoverEndOutFile.
Referenced by NotifyHandoverEndOkUe().
PrintUeStartHandover()
void ns3::mmwave::MmWaveBearerStatsConnector::PrintUeStartHandover (uint64_t imsi, uint16_t sourceCellid, uint16_t targetCellId, uint16_t rnti) private
Definition at line 543 of file mmwave-bearer-stats-connector.cc.
References GetUeHandoverStartOutputFilename(), and m_ueHandoverStartOutFile.
Referenced by NotifyHandoverStartUe().
SetCellIdStatsOutputFilename()
void ns3::mmwave::MmWaveBearerStatsConnector::SetCellIdStatsOutputFilename (std::string outputFilename)
Definition at line 503 of file mmwave-bearer-stats-connector.cc.
References m_cellIdInTimeHandoverFilename.
Referenced by GetTypeId().
SetEnbHandoverEndOutputFilename()
void ns3::mmwave::MmWaveBearerStatsConnector::SetEnbHandoverEndOutputFilename (std::string outputFilename)
Definition at line 480 of file mmwave-bearer-stats-connector.cc.
References m_enbHandoverEndFilename.
Referenced by GetTypeId().
SetEnbHandoverStartOutputFilename()
void ns3::mmwave::MmWaveBearerStatsConnector::SetEnbHandoverStartOutputFilename (std::string outputFilename)
Definition at line 485 of file mmwave-bearer-stats-connector.cc.
References m_enbHandoverStartFilename.
Referenced by GetTypeId().
SetLteSinrOutputFilename()
void ns3::mmwave::MmWaveBearerStatsConnector::SetLteSinrOutputFilename (std::string outputFilename)
Definition at line 515 of file mmwave-bearer-stats-connector.cc.
References m_lteSinrOutputFilename.
Referenced by GetTypeId().
SetMmWaveSinrOutputFilename()
void ns3::mmwave::MmWaveBearerStatsConnector::SetMmWaveSinrOutputFilename (std::string outputFilename)
Definition at line 509 of file mmwave-bearer-stats-connector.cc.
References m_mmWaveSinrOutputFilename.
Referenced by GetTypeId().
SetUeHandoverEndOutputFilename()
void ns3::mmwave::MmWaveBearerStatsConnector::SetUeHandoverEndOutputFilename (std::string outputFilename)
Definition at line 497 of file mmwave-bearer-stats-connector.cc.
References m_ueHandoverEndFilename.
Referenced by GetTypeId().
SetUeHandoverStartOutputFilename()
void ns3::mmwave::MmWaveBearerStatsConnector::SetUeHandoverStartOutputFilename (std::string outputFilename)
Definition at line 491 of file mmwave-bearer-stats-connector.cc.
References m_ueHandoverStartFilename.
Referenced by GetTypeId().
StoreUeManagerPath()
void ns3::mmwave::MmWaveBearerStatsConnector::StoreUeManagerPath (std::string ueManagerPath, uint16_t cellId, uint16_t rnti) private
Creates UE Manager path and stores it in m_ueManagerPathByCellIdRnti.
Parameters
ueManagerPath
cellId
rnti
Definition at line 571 of file mmwave-bearer-stats-connector.cc.
References ns3::mmwave::MmWaveBearerStatsConnector::CellIdRnti::cellId, m_rlcStats, m_ueManagerPathByCellIdRnti, NotifySecondaryMmWaveEnbAvailable(), and ns3::mmwave::MmWaveBearerStatsConnector::CellIdRnti::rnti.
Referenced by NotifyNewUeContextEnb().
Friends And Related Function Documentation
operator<
bool operator< (const CellIdRnti & a, const CellIdRnti & b) friend
Less than operator for CellIdRnti, because it is used as key in map.
Definition at line 62 of file mmwave-bearer-stats-connector.cc.
Member Data Documentation
m_cellIdInTimeHandoverFilename
std::string ns3::mmwave::MmWaveBearerStatsConnector::m_cellIdInTimeHandoverFilename private
Definition at line 390 of file mmwave-bearer-stats-connector.h.
Referenced by GetCellIdStatsOutputFilename(), and SetCellIdStatsOutputFilename().
m_cellIdInTimeHandoverOutFile
std::ofstream ns3::mmwave::MmWaveBearerStatsConnector::m_cellIdInTimeHandoverOutFile private
Definition at line 398 of file mmwave-bearer-stats-connector.h.
Referenced by PrintUeEndHandover(), and ~MmWaveBearerStatsConnector().
m_connected
bool ns3::mmwave::MmWaveBearerStatsConnector::m_connected private
true if traces are connected to sinks, initially set to false
Definition at line 362 of file mmwave-bearer-stats-connector.h.
Referenced by EnsureConnected().
m_enbHandoverEndFilename
std::string ns3::mmwave::MmWaveBearerStatsConnector::m_enbHandoverEndFilename private
Definition at line 387 of file mmwave-bearer-stats-connector.h.
Referenced by GetEnbHandoverEndOutputFilename(), and SetEnbHandoverEndOutputFilename().
m_enbHandoverEndOutFile
std::ofstream ns3::mmwave::MmWaveBearerStatsConnector::m_enbHandoverEndOutFile private
Definition at line 396 of file mmwave-bearer-stats-connector.h.
Referenced by PrintEnbEndHandover(), and ~MmWaveBearerStatsConnector().
m_enbHandoverStartFilename
std::string ns3::mmwave::MmWaveBearerStatsConnector::m_enbHandoverStartFilename private
Definition at line 386 of file mmwave-bearer-stats-connector.h.
Referenced by GetEnbHandoverStartOutputFilename(), and SetEnbHandoverStartOutputFilename().
m_enbHandoverStartOutFile
std::ofstream ns3::mmwave::MmWaveBearerStatsConnector::m_enbHandoverStartOutFile private
Definition at line 394 of file mmwave-bearer-stats-connector.h.
Referenced by PrintEnbStartHandover(), and ~MmWaveBearerStatsConnector().
m_imsiSeenEnbDrb
std::set<uint64_t> ns3::mmwave::MmWaveBearerStatsConnector::m_imsiSeenEnbDrb private
stores all eNBs for which RLC and PDCP traces for DRBs were connected
Definition at line 365 of file mmwave-bearer-stats-connector.h.
Referenced by ConnectTracesEnbIfFirstTime().
m_imsiSeenUeDrb
std::map<uint64_t,uint16_t> ns3::mmwave::MmWaveBearerStatsConnector::m_imsiSeenUeDrb private
stores all UEs for which RLC and PDCP traces for DRBs were connected
Definition at line 364 of file mmwave-bearer-stats-connector.h.
Referenced by ConnectTracesUeIfFirstTime().
m_imsiSeenUeSrb
std::set<uint64_t> ns3::mmwave::MmWaveBearerStatsConnector::m_imsiSeenUeSrb private
stores all UEs for which RLC and PDCP for SRB1 traces were connected
Definition at line 363 of file mmwave-bearer-stats-connector.h.
Referenced by ConnectTracesUeIfFirstTime().
m_lteSinrOutFile
std::ofstream ns3::mmwave::MmWaveBearerStatsConnector::m_lteSinrOutFile private
Definition at line 400 of file mmwave-bearer-stats-connector.h.
Referenced by PrintLteSinr(), and ~MmWaveBearerStatsConnector().
m_lteSinrOutputFilename
std::string ns3::mmwave::MmWaveBearerStatsConnector::m_lteSinrOutputFilename private
Definition at line 392 of file mmwave-bearer-stats-connector.h.
Referenced by GetLteSinrOutputFilename(), and SetLteSinrOutputFilename().
m_mcStats
Ptr<McStatsCalculator> ns3::mmwave::MmWaveBearerStatsConnector::m_mcStats private
Calculator for multi-connectivity Statistics.
Definition at line 354 of file mmwave-bearer-stats-connector.h.
Referenced by ConnectSrb1TracesUe(), DisconnectTracesUe(), and EnableMcStats().
m_mmWaveSinrOutFile
std::ofstream ns3::mmwave::MmWaveBearerStatsConnector::m_mmWaveSinrOutFile private
Definition at line 399 of file mmwave-bearer-stats-connector.h.
Referenced by PrintMmWaveSinr(), and ~MmWaveBearerStatsConnector().
m_mmWaveSinrOutputFilename
std::string ns3::mmwave::MmWaveBearerStatsConnector::m_mmWaveSinrOutputFilename private
Definition at line 391 of file mmwave-bearer-stats-connector.h.
Referenced by GetMmWaveSinrOutputFilename(), and SetMmWaveSinrOutputFilename().
m_pdcpDrbDlRxCb
std::map<uint64_t, CallbackBase> ns3::mmwave::MmWaveBearerStatsConnector::m_pdcpDrbDlRxCb private
Sinks for the received DL PDCP data packets.
Definition at line 359 of file mmwave-bearer-stats-connector.h.
Referenced by ConnectDrbTracesUe(), and DisconnectDrbTracesUe().
m_pdcpDrbUlTxCb
std::map<uint64_t, CallbackBase> ns3::mmwave::MmWaveBearerStatsConnector::m_pdcpDrbUlTxCb private
Sinks for the sent UL PDCP data packets.
Definition at line 360 of file mmwave-bearer-stats-connector.h.
Referenced by ConnectDrbTracesUe(), and DisconnectDrbTracesUe().
m_pdcpStats
Ptr<MmWaveBearerStatsCalculator> ns3::mmwave::MmWaveBearerStatsConnector::m_pdcpStats private
Calculator for PDCP Statistics.
Definition at line 353 of file mmwave-bearer-stats-connector.h.
Referenced by ConnectDrbTracesEnb(), ConnectDrbTracesUe(), ConnectSrb0Traces(), ConnectSrb1TracesEnb(), ConnectSrb1TracesUe(), DisconnectDrbTracesUe(), and EnablePdcpStats().
m_rlcDrbDlRxCb
std::map<uint64_t, CallbackBase> ns3::mmwave::MmWaveBearerStatsConnector::m_rlcDrbDlRxCb private
Sinks for the received DL RLC data packets.
Definition at line 356 of file mmwave-bearer-stats-connector.h.
Referenced by ConnectDrbTracesUe(), and DisconnectDrbTracesUe().
m_rlcDrbUlTxCb
std::map<uint64_t, CallbackBase> ns3::mmwave::MmWaveBearerStatsConnector::m_rlcDrbUlTxCb private
Sinks for the sent UL RLC data packets.
Definition at line 357 of file mmwave-bearer-stats-connector.h.
Referenced by ConnectDrbTracesUe(), and DisconnectDrbTracesUe().
m_rlcStats
Ptr<MmWaveBearerStatsCalculator> ns3::mmwave::MmWaveBearerStatsConnector::m_rlcStats private
Calculator for RLC Statistics.
Definition at line 352 of file mmwave-bearer-stats-connector.h.
Referenced by ConnectDrbTracesEnb(), ConnectDrbTracesUe(), ConnectSecondaryTracesEnb(), ConnectSecondaryTracesUe(), ConnectSrb0Traces(), ConnectSrb1TracesEnb(), ConnectSrb1TracesUe(), DisconnectDrbTracesUe(), EnableRlcStats(), and StoreUeManagerPath().
m_ueHandoverEndFilename
std::string ns3::mmwave::MmWaveBearerStatsConnector::m_ueHandoverEndFilename private
Definition at line 389 of file mmwave-bearer-stats-connector.h.
Referenced by GetUeHandoverEndOutputFilename(), and SetUeHandoverEndOutputFilename().
m_ueHandoverEndOutFile
std::ofstream ns3::mmwave::MmWaveBearerStatsConnector::m_ueHandoverEndOutFile private
Definition at line 397 of file mmwave-bearer-stats-connector.h.
Referenced by PrintUeEndHandover(), and ~MmWaveBearerStatsConnector().
m_ueHandoverStartFilename
std::string ns3::mmwave::MmWaveBearerStatsConnector::m_ueHandoverStartFilename private
Definition at line 388 of file mmwave-bearer-stats-connector.h.
Referenced by GetUeHandoverStartOutputFilename(), and SetUeHandoverStartOutputFilename().
m_ueHandoverStartOutFile
std::ofstream ns3::mmwave::MmWaveBearerStatsConnector::m_ueHandoverStartOutFile private
Definition at line 395 of file mmwave-bearer-stats-connector.h.
Referenced by PrintUeStartHandover(), and ~MmWaveBearerStatsConnector().
m_ueManagerPathByCellIdRnti
std::map<CellIdRnti, std::string> ns3::mmwave::MmWaveBearerStatsConnector::m_ueManagerPathByCellIdRnti private
List UE Manager Paths by CellIdRnti.
Definition at line 384 of file mmwave-bearer-stats-connector.h.
Referenced by ConnectSrb0Traces(), and StoreUeManagerPath().
The documentation for this class was generated from the following files:
src/mmwave/helper/mmwave-bearer-stats-connector.h
src/mmwave/helper/mmwave-bearer-stats-connector.cc