ns3-mmwave: ns3::mmwave::MmWaveFlexTtiMaxWeightMacCschedSapProvider Class Reference
ns3::mmwave::MmWaveFlexTtiMaxWeightMacCschedSapProvider Class Reference
Public Member Functions
MmWaveFlexTtiMaxWeightMacCschedSapProvider (MmWaveFlexTtiMaxWeightMacScheduler *scheduler)
virtual void CschedCellConfigReq (const struct MmWaveMacCschedSapProvider::CschedCellConfigReqParameters &params)
CSCHED_CELL_CONFIG_REQ.
virtual void CschedLcConfigReq (const struct MmWaveMacCschedSapProvider::CschedLcConfigReqParameters &params)
virtual void CschedLcReleaseReq (const struct MmWaveMacCschedSapProvider::CschedLcReleaseReqParameters &params)
virtual void CschedUeConfigReq (const struct MmWaveMacCschedSapProvider::CschedUeConfigReqParameters &params)
virtual void CschedUeReleaseReq (const struct MmWaveMacCschedSapProvider::CschedUeReleaseReqParameters &params)
Public Member Functions inherited from ns3::mmwave::MmWaveMacCschedSapProvider
virtual ~MmWaveMacCschedSapProvider ()
Private Member Functions
MmWaveFlexTtiMaxWeightMacCschedSapProvider ()
Private Attributes
MmWaveFlexTtiMaxWeightMacScheduler * m_scheduler
Detailed Description
Definition at line 29 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
Constructor & Destructor Documentation
MmWaveFlexTtiMaxWeightMacCschedSapProvider() [1/2]
ns3::mmwave::MmWaveFlexTtiMaxWeightMacCschedSapProvider::MmWaveFlexTtiMaxWeightMacCschedSapProvider (MmWaveFlexTtiMaxWeightMacScheduler * scheduler)
Definition at line 50 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
MmWaveFlexTtiMaxWeightMacCschedSapProvider() [2/2]
ns3::mmwave::MmWaveFlexTtiMaxWeightMacCschedSapProvider::MmWaveFlexTtiMaxWeightMacCschedSapProvider () private
Definition at line 46 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
Member Function Documentation
CschedCellConfigReq()
void ns3::mmwave::MmWaveFlexTtiMaxWeightMacCschedSapProvider::CschedCellConfigReq (const struct MmWaveMacCschedSapProvider::CschedCellConfigReqParameters & params) virtual
CSCHED_CELL_CONFIG_REQ.
Implements ns3::mmwave::MmWaveMacCschedSapProvider.
Definition at line 56 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::DoCschedCellConfigReq(), and m_scheduler.
CschedLcConfigReq()
void ns3::mmwave::MmWaveFlexTtiMaxWeightMacCschedSapProvider::CschedLcConfigReq (const struct MmWaveMacCschedSapProvider::CschedLcConfigReqParameters & params) virtual
Implements ns3::mmwave::MmWaveMacCschedSapProvider.
Definition at line 69 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::DoCschedLcConfigReq(), and m_scheduler.
CschedLcReleaseReq()
void ns3::mmwave::MmWaveFlexTtiMaxWeightMacCschedSapProvider::CschedLcReleaseReq (const struct MmWaveMacCschedSapProvider::CschedLcReleaseReqParameters & params) virtual
Implements ns3::mmwave::MmWaveMacCschedSapProvider.
Definition at line 75 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::DoCschedLcReleaseReq(), and m_scheduler.
CschedUeConfigReq()
void ns3::mmwave::MmWaveFlexTtiMaxWeightMacCschedSapProvider::CschedUeConfigReq (const struct MmWaveMacCschedSapProvider::CschedUeConfigReqParameters & params) virtual
Implements ns3::mmwave::MmWaveMacCschedSapProvider.
Definition at line 62 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::DoCschedUeConfigReq(), and m_scheduler.
CschedUeReleaseReq()
void ns3::mmwave::MmWaveFlexTtiMaxWeightMacCschedSapProvider::CschedUeReleaseReq (const struct MmWaveMacCschedSapProvider::CschedUeReleaseReqParameters & params) virtual
Implements ns3::mmwave::MmWaveMacCschedSapProvider.
Definition at line 81 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiMaxWeightMacScheduler::DoCschedUeReleaseReq(), and m_scheduler.
Member Data Documentation
m_scheduler
MmWaveFlexTtiMaxWeightMacScheduler* ns3::mmwave::MmWaveFlexTtiMaxWeightMacCschedSapProvider::m_scheduler private
Definition at line 43 of file mmwave-flex-tti-maxweight-mac-scheduler.cc.
Referenced by CschedCellConfigReq(), CschedLcConfigReq(), CschedLcReleaseReq(), CschedUeConfigReq(), and CschedUeReleaseReq().
The documentation for this class was generated from the following file:
src/mmwave/model/mmwave-flex-tti-maxweight-mac-scheduler.cc