ns3-mmwave: ns3::mmwave::MmWaveFlexTtiMacCschedSapProvider Class Reference
ns3::mmwave::MmWaveFlexTtiMacCschedSapProvider Class Reference
Public Member Functions
MmWaveFlexTtiMacCschedSapProvider (MmWaveFlexTtiMacScheduler *scheduler)
virtual void CschedCellConfigReq (const struct MmWaveMacCschedSapProvider::CschedCellConfigReqParameters &params)
CSCHED_CELL_CONFIG_REQ.
virtual void CschedLcConfigReq (const struct MmWaveMacCschedSapProvider::CschedLcConfigReqParameters &params)
virtual void CschedLcReleaseReq (const struct MmWaveMacCschedSapProvider::CschedLcReleaseReqParameters &params)
virtual void CschedUeConfigReq (const struct MmWaveMacCschedSapProvider::CschedUeConfigReqParameters &params)
virtual void CschedUeReleaseReq (const struct MmWaveMacCschedSapProvider::CschedUeReleaseReqParameters &params)
Public Member Functions inherited from ns3::mmwave::MmWaveMacCschedSapProvider
virtual ~MmWaveMacCschedSapProvider ()
Private Member Functions
MmWaveFlexTtiMacCschedSapProvider ()
Private Attributes
MmWaveFlexTtiMacScheduler * m_scheduler
Detailed Description
Definition at line 49 of file mmwave-flex-tti-mac-scheduler.cc.
Constructor & Destructor Documentation
MmWaveFlexTtiMacCschedSapProvider() [1/2]
ns3::mmwave::MmWaveFlexTtiMacCschedSapProvider::MmWaveFlexTtiMacCschedSapProvider (MmWaveFlexTtiMacScheduler * scheduler)
Definition at line 70 of file mmwave-flex-tti-mac-scheduler.cc.
MmWaveFlexTtiMacCschedSapProvider() [2/2]
ns3::mmwave::MmWaveFlexTtiMacCschedSapProvider::MmWaveFlexTtiMacCschedSapProvider () private
Definition at line 66 of file mmwave-flex-tti-mac-scheduler.cc.
Member Function Documentation
CschedCellConfigReq()
void ns3::mmwave::MmWaveFlexTtiMacCschedSapProvider::CschedCellConfigReq (const struct MmWaveMacCschedSapProvider::CschedCellConfigReqParameters & params) virtual
CSCHED_CELL_CONFIG_REQ.
Implements ns3::mmwave::MmWaveMacCschedSapProvider.
Definition at line 76 of file mmwave-flex-tti-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiMacScheduler::DoCschedCellConfigReq(), and m_scheduler.
CschedLcConfigReq()
void ns3::mmwave::MmWaveFlexTtiMacCschedSapProvider::CschedLcConfigReq (const struct MmWaveMacCschedSapProvider::CschedLcConfigReqParameters & params) virtual
Implements ns3::mmwave::MmWaveMacCschedSapProvider.
Definition at line 89 of file mmwave-flex-tti-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiMacScheduler::DoCschedLcConfigReq(), and m_scheduler.
CschedLcReleaseReq()
void ns3::mmwave::MmWaveFlexTtiMacCschedSapProvider::CschedLcReleaseReq (const struct MmWaveMacCschedSapProvider::CschedLcReleaseReqParameters & params) virtual
Implements ns3::mmwave::MmWaveMacCschedSapProvider.
Definition at line 95 of file mmwave-flex-tti-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiMacScheduler::DoCschedLcReleaseReq(), and m_scheduler.
CschedUeConfigReq()
void ns3::mmwave::MmWaveFlexTtiMacCschedSapProvider::CschedUeConfigReq (const struct MmWaveMacCschedSapProvider::CschedUeConfigReqParameters & params) virtual
Implements ns3::mmwave::MmWaveMacCschedSapProvider.
Definition at line 82 of file mmwave-flex-tti-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiMacScheduler::DoCschedUeConfigReq(), and m_scheduler.
CschedUeReleaseReq()
void ns3::mmwave::MmWaveFlexTtiMacCschedSapProvider::CschedUeReleaseReq (const struct MmWaveMacCschedSapProvider::CschedUeReleaseReqParameters & params) virtual
Implements ns3::mmwave::MmWaveMacCschedSapProvider.
Definition at line 101 of file mmwave-flex-tti-mac-scheduler.cc.
References ns3::mmwave::MmWaveFlexTtiMacScheduler::DoCschedUeReleaseReq(), and m_scheduler.
Member Data Documentation
m_scheduler
MmWaveFlexTtiMacScheduler* ns3::mmwave::MmWaveFlexTtiMacCschedSapProvider::m_scheduler private
Definition at line 63 of file mmwave-flex-tti-mac-scheduler.cc.
Referenced by CschedCellConfigReq(), CschedLcConfigReq(), CschedLcReleaseReq(), CschedUeConfigReq(), and CschedUeReleaseReq().
The documentation for this class was generated from the following file:
src/mmwave/model/mmwave-flex-tti-mac-scheduler.cc