ns3-mmwave: ns3::mmwave::MmWaveHelper Class Reference
ns3::mmwave::MmWaveHelper Class Reference
#include "mmwave-helper.h"
Public Member Functions
MmWaveHelper (void)
virtual ~MmWaveHelper (void)
void ActivateDataRadioBearer (NetDeviceContainer ueDevices, EpsBearer bearer)
void ActivateDataRadioBearer (Ptr< NetDevice > ueDevice, EpsBearer bearer)
void AddX2Interface (NodeContainer enbNodes)
void AddX2Interface (NodeContainer lteEnbNodes, NodeContainer mmWaveEnbNodes)
void AddX2Interface (Ptr< Node > enbNode1, Ptr< Node > enbNode2)
void AttachIrToClosestEnb (NetDeviceContainer ueDevices, NetDeviceContainer mmWaveEnbDevices, NetDeviceContainer lteEnbDevices)
Attach MC ueDevices to the closest MmWave eNB device, register all MmWave eNBs to the MmWaveUePhy, store all cellId in each LteUeRrc layer.
void AttachToClosestEnb (NetDeviceContainer ueDevices, NetDeviceContainer enbDevices)
Attach mmWave-only ueDevices to the closest enbDevice.
void AttachToClosestEnb (NetDeviceContainer ueDevices, NetDeviceContainer mmWaveEnbDevices, NetDeviceContainer lteEnbDevices)
Attach MC ueDevices to the closest LTE enbDevice, register all MmWave eNBs to the MmWaveUePhy.
void AttachToEnbWithIndex (Ptr< NetDevice > ueDevice, NetDeviceContainer enbDevices, uint32_t index)
Attach to an eNB selecting which one with an index.
virtual void DoDispose (void)
void EnableDlPhyTrace ()
void EnableEnbSchedTrace ()
void EnableMcTraces (void)
void EnablePdcpTraces (void)
void EnableRlcTraces (void)
void EnableTraces ()
void EnableUlPhyTrace ()
std::map< uint8_t, MmWaveComponentCarrier > GetCcPhyParams ()
This method is used to get the MmWaveComponentCarrier map.
std::string GetEnbComponentCarrierManagerType () const
bool GetHarqEnabled ()
std::string GetLteEnbComponentCarrierManagerType () const
std::string GetLteFfrAlgorithmType () const
std::string GetLteHandoverAlgorithmType () const
std::string GetLteSchedulerType () const
Ptr< PropagationLossModel > GetPathLossModel (uint8_t index)
std::string GetSchedulerType () const
bool GetSnrTest ()
std::string GetUeComponentCarrierManagerType () const
NetDeviceContainer InstallEnbDevice (NodeContainer c)
NetDeviceContainer InstallInterRatHoCapableUeDevice (NodeContainer c)
NetDeviceContainer InstallLteEnbDevice (NodeContainer c)
NetDeviceContainer InstallMcUeDevice (NodeContainer c)
NetDeviceContainer InstallUeDevice (NodeContainer c)
void SetBeamformingModelAttribute (std::string name, const AttributeValue &value)
Set an attribute to the MmWaveBeamformingModel.
void SetBeamformingModelType (std::string type)
Set the type of beamforming model to be used.
void SetBlockageMap (std::map< uint8_t, bool > blockageMap)
Set the blockage attribute of each channel if MmWave3gppChannel is used.
void SetCcPhyParams (std::map< uint8_t, MmWaveComponentCarrier > ccMapParams)
This method is used to set the MmWaveComponentCarrier map.
void SetChannelConditionModelType (std::string type)
void SetChannelModelAttribute (std::string name, const AttributeValue &value)
Set an attribute to the SpectrumPropagationLossModels.
void SetChannelModelType (std::string type)
void SetEnbComponentCarrierManagerType (std::string type)
Set the type of carrier component algorithm to be used by gNodeB devices.
void SetEpcHelper (Ptr< EpcHelper > epcHelper)
void SetHarqEnabled (bool harqEnabled)
void SetLteCcPhyParams (std::map< uint8_t, ComponentCarrier > ccMapParams)
This method is used to set the ComponentCarrier map.
void SetLteEnbComponentCarrierManagerType (std::string type)
Set the type of carrier component algorithm to be used by eNodeB devices.
void SetLteFfrAlgorithmType (std::string type)
Set the type of FFR algorithm to be used by LTE eNodeB devices.
void SetLteHandoverAlgorithmType (std::string type)
Set the type of handover algorithm to be used by LTE eNodeB devices.
void SetLtePathlossModelType (std::string type)
void SetLteSchedulerType (std::string type)
void SetMcUeNetDeviceAttribute (std::string name, const AttributeValue &value)
Set an attribute to the McUeNetDevice.
void SetMmWaveEnbNetDeviceAttribute (std::string name, const AttributeValue &value)
Set an attribute to the MmWaveEnbNetDevice.
void SetMmWaveUeNetDeviceAttribute (std::string name, const AttributeValue &value)
Set an attribute to the MmWaveUeNetDevice.
void SetPathlossModelType (std::string type)
void SetSchedulerType (std::string type)
void SetSnrTest (bool snrTest)
void SetUeComponentCarrierManagerType (std::string type)
Set the type of Component Carrier Manager to be used by Ue devices.
Static Public Member Functions
static TypeId GetTypeId (void)
Protected Member Functions
virtual void DoInitialize ()
Private Member Functions
void AttachIrToClosestEnb (Ptr< NetDevice > ueDevice, NetDeviceContainer mmWaveEnbDevices, NetDeviceContainer lteEnbDevices)
void AttachMcToClosestEnb (Ptr< NetDevice > ueDevice, NetDeviceContainer mmWaveEnbDevices, NetDeviceContainer lteEnbDevices)
void AttachToClosestEnb (Ptr< NetDevice > ueDevice, NetDeviceContainer enbDevices)
void EnableEnbPacketCountTrace ()
void EnableTransportBlockTrace ()
void EnableUePacketCountTrace ()
Ptr< McStatsCalculator > GetMcStats (void)
Ptr< MmWaveBearerStatsCalculator > GetPdcpStats (void)
Ptr< MmWaveBearerStatsCalculator > GetRlcStats (void)
Ptr< NetDevice > InstallSingleEnbDevice (Ptr< Node > n)
Ptr< NetDevice > InstallSingleInterRatHoCapableUeDevice (Ptr< Node > n)
Ptr< NetDevice > InstallSingleLteEnbDevice (Ptr< Node > n)
Ptr< NetDevice > InstallSingleMcUeDevice (Ptr< Node > n)
Ptr< NetDevice > InstallSingleUeDevice (Ptr< Node > n)
void LteChannelModelInitialization ()
void MmWaveChannelModelInitialization ()
Private Attributes
ObjectFactory m_bfModelFactory
Factory of antenna objects for Lte eNB.
uint16_t m_cellIdCounter
std::map< uint8_t, Ptr< SpectrumChannel > > m_channel
ObjectFactory m_channelConditionModelFactory
the factory for the ChannelConditionModel objects
std::string m_channelConditionModelType
The uplink LTE channel used in the simulation.
ObjectFactory m_channelFactory
Ptr< CoreNetworkStatsCalculator > m_cnStats
std::map< uint8_t, MmWaveComponentCarrier > m_componentCarrierPhyParams
This contains all the informations about each mmWave component carrier.
ObjectFactory m_dlPathlossModelFactory
Factory of both the downlink and uplink LTE channels.
Ptr< SpectrumChannel > m_downlinkChannel
Ptr< Object > m_downlinkPathlossModel
ObjectFactory m_enbComponentCarrierManagerFactory
Factory of path loss model object for the uplink channel.
ObjectFactory m_enbNetDeviceFactory
Ptr< MmWaveMacTrace > m_enbStats
Ptr< EpcHelper > m_epcHelper
ObjectFactory m_ffrAlgorithmFactory
bool m_harqEnabled
uint64_t m_imsiCounter
Factory of enb component carrier manager object.
bool m_isAnrEnabled
ObjectFactory m_lteChannelFactory
std::map< uint8_t, ComponentCarrier > m_lteComponentCarrierPhyParams
This contains all the informations about each LTE component carrier.
ObjectFactory m_lteEnbAntennaModelFactory
Factory of antenna object for Lte UE.
ObjectFactory m_lteEnbComponentCarrierManagerFactory
Factory of ue component carrier manager object.
ObjectFactory m_lteEnbNetDeviceFactory
ObjectFactory m_lteFfrAlgorithmFactory
ObjectFactory m_lteHandoverAlgorithmFactory
ObjectFactory m_lteSchedulerFactory
ObjectFactory m_lteUeAntennaModelFactory
bool m_lteUseCa
The LteUseCa attribute.
Ptr< McStatsCalculator > m_mcStats
ObjectFactory m_mcUeNetDeviceFactory
uint16_t m_noOfCcs
Number of component carriers that will be installed by default at gNodeB and UE devices.
uint16_t m_noOfLteCcs
Number of LTE component carriers that will be installed by default at LTE eNodeB and MC-UE devices.
std::map< uint8_t, Ptr< Object > > m_pathlossModel
ObjectFactory m_pathlossModelFactory
std::string m_pathlossModelType
Ptr< MmWaveBearerStatsCalculator > m_pdcpStats
Ptr< MmWavePhyTrace > m_phyStats
Ptr< MmWaveBearerStatsConnector > m_radioBearerStatsConnector
bool m_rlcAmEnabled
Ptr< MmWaveBearerStatsCalculator > m_rlcStats
ObjectFactory m_schedulerFactory
bool m_snrTest
ObjectFactory m_spectrumPropagationLossModelFactory
the factory for the SpectrumPropagationLossModel objects
std::string m_spectrumPropagationLossModelType
The path loss model used in the LTE uplink channel.
ObjectFactory m_ueComponentCarrierManagerFactory
Factory of enb component carrier manager object.
ObjectFactory m_ueNetDeviceFactory
ObjectFactory m_ulPathlossModelFactory
Factory of path loss model object for the downlink channel.
Ptr< SpectrumChannel > m_uplinkChannel
The downlink LTE channel used in the simulation.
Ptr< Object > m_uplinkPathlossModel
The path loss model used in the LTE downlink channel.
bool m_useCa
The UseCa attribute.
bool m_useIdealRrc
bool m_usePdschForCqiGeneration
From lte-helper.h The UsePdschForCqiGeneration attribute.
Detailed Description
Definition at line 97 of file mmwave-helper.h.
Constructor & Destructor Documentation
MmWaveHelper()
ns3::mmwave::MmWaveHelper::MmWaveHelper (void)
Definition at line 78 of file mmwave-helper.cc.
References ns3::mmwave::MmWaveUeNetDevice::GetTypeId(), ns3::mmwave::MmWaveEnbNetDevice::GetTypeId(), ns3::mmwave::McUeNetDevice::GetTypeId(), ns3::mmwave::MmWaveSvdBeamforming::GetTypeId(), m_bfModelFactory, m_channelFactory, m_enbNetDeviceFactory, m_lteChannelFactory, m_lteEnbAntennaModelFactory, m_lteEnbNetDeviceFactory, m_lteUeAntennaModelFactory, m_mcUeNetDeviceFactory, and m_ueNetDeviceFactory.
~MmWaveHelper()
ns3::mmwave::MmWaveHelper::~MmWaveHelper (void) virtual
Definition at line 101 of file mmwave-helper.cc.
Member Function Documentation
ActivateDataRadioBearer() [1/2]
void ns3::mmwave::MmWaveHelper::ActivateDataRadioBearer (NetDeviceContainer ueDevices, EpsBearer bearer)
Definition at line 2613 of file mmwave-helper.cc.
ActivateDataRadioBearer() [2/2]
void ns3::mmwave::MmWaveHelper::ActivateDataRadioBearer (Ptr< NetDevice > ueDevice, EpsBearer bearer)
Definition at line 2622 of file mmwave-helper.cc.
References ns3::mmwave::MmWaveDrbActivator::ActivateCallback().
AddX2Interface() [1/3]
void ns3::mmwave::MmWaveHelper::AddX2Interface (NodeContainer enbNodes)
Definition at line 2450 of file mmwave-helper.cc.
References ns3::mmwave::CoreNetworkStatsCalculator::LogX2Packet(), m_cnStats, and m_epcHelper.
Referenced by AddX2Interface().
AddX2Interface() [2/3]
void ns3::mmwave::MmWaveHelper::AddX2Interface (NodeContainer lteEnbNodes, NodeContainer mmWaveEnbNodes)
Definition at line 2482 of file mmwave-helper.cc.
References AddX2Interface(), ns3::mmwave::CoreNetworkStatsCalculator::LogX2Packet(), m_cnStats, and m_epcHelper.
AddX2Interface() [3/3]
void ns3::mmwave::MmWaveHelper::AddX2Interface (Ptr< Node > enbNode1, Ptr< Node > enbNode2)
Definition at line 2473 of file mmwave-helper.cc.
References m_epcHelper.
AttachIrToClosestEnb() [1/2]
void ns3::mmwave::MmWaveHelper::AttachIrToClosestEnb (NetDeviceContainer ueDevices, NetDeviceContainer mmWaveEnbDevices, NetDeviceContainer lteEnbDevices)
Attach MC ueDevices to the closest MmWave eNB device, register all MmWave eNBs to the MmWaveUePhy, store all cellId in each LteUeRrc layer.
This must be used when attaching InterRatHandover capable devices
Parameters
ueDevices the ueNetDevice
mmWaveEnbDevices all the mmwave eNBs
lteEnbDevices all the lte eNBs
Definition at line 2180 of file mmwave-helper.cc.
AttachIrToClosestEnb() [2/2]
void ns3::mmwave::MmWaveHelper::AttachIrToClosestEnb (Ptr< NetDevice > ueDevice, NetDeviceContainer mmWaveEnbDevices, NetDeviceContainer lteEnbDevices) private
Definition at line 2301 of file mmwave-helper.cc.
References ns3::mmwave::MmWaveEnbNetDevice::GetCellId(), ns3::mmwave::McUeNetDevice::GetLteRrc(), and m_epcHelper.
AttachMcToClosestEnb()
void ns3::mmwave::MmWaveHelper::AttachMcToClosestEnb (Ptr< NetDevice > ueDevice, NetDeviceContainer mmWaveEnbDevices, NetDeviceContainer lteEnbDevices) private
Definition at line 2237 of file mmwave-helper.cc.
References ns3::mmwave::MmWaveNetDevice::GetCcMap(), ns3::mmwave::McUeNetDevice::GetNode(), and m_epcHelper.
Referenced by AttachToClosestEnb().
AttachToClosestEnb() [1/3]
void ns3::mmwave::MmWaveHelper::AttachToClosestEnb (NetDeviceContainer ueDevices, NetDeviceContainer enbDevices)
Attach mmWave-only ueDevices to the closest enbDevice.
Definition at line 2156 of file mmwave-helper.cc.
AttachToClosestEnb() [2/3]
void ns3::mmwave::MmWaveHelper::AttachToClosestEnb (NetDeviceContainer ueDevices, NetDeviceContainer mmWaveEnbDevices, NetDeviceContainer lteEnbDevices)
Attach MC ueDevices to the closest LTE enbDevice, register all MmWave eNBs to the MmWaveUePhy.
Definition at line 2168 of file mmwave-helper.cc.
References AttachMcToClosestEnb().
AttachToClosestEnb() [3/3]
void ns3::mmwave::MmWaveHelper::AttachToClosestEnb (Ptr< NetDevice > ueDevice, NetDeviceContainer enbDevices) private
Definition at line 2211 of file mmwave-helper.cc.
References AttachToEnbWithIndex().
AttachToEnbWithIndex()
void ns3::mmwave::MmWaveHelper::AttachToEnbWithIndex (Ptr< NetDevice > ueDevice, NetDeviceContainer enbDevices, uint32_t index)
Attach to an eNB selecting which one with an index.
Parameters
ueDevice the ueNetDevice
enbDevices all the eNBs
index an index to select the eNB (cellId - 1)
Definition at line 2379 of file mmwave-helper.cc.
References ns3::mmwave::MmWaveNetDevice::GetCcMap(), ns3::mmwave::MmWaveEnbNetDevice::GetCellId(), ns3::mmwave::MmWaveUeNetDevice::GetImsi(), and m_epcHelper.
Referenced by AttachToClosestEnb().
DoDispose()
void ns3::mmwave::MmWaveHelper::DoDispose (void) virtual
Definition at line 262 of file mmwave-helper.cc.
References m_channel, m_componentCarrierPhyParams, and m_lteComponentCarrierPhyParams.
DoInitialize()
void ns3::mmwave::MmWaveHelper::DoInitialize () protected virtual
Definition at line 272 of file mmwave-helper.cc.
References LteChannelModelInitialization(), m_cnStats, m_componentCarrierPhyParams, m_enbStats, m_lteComponentCarrierPhyParams, m_lteUseCa, m_phyStats, m_radioBearerStatsConnector, m_useCa, MmWaveChannelModelInitialization(), SetCcPhyParams(), and SetLteCcPhyParams().
EnableDlPhyTrace()
void ns3::mmwave::MmWaveHelper::EnableDlPhyTrace (void)
Definition at line 2667 of file mmwave-helper.cc.
References ns3::mmwave::MmWavePhyTrace::ReportDlPhyTransmissionCallback(), and ns3::mmwave::MmWavePhyTrace::RxPacketTraceUeCallback().
EnableEnbPacketCountTrace()
void ns3::mmwave::MmWaveHelper::EnableEnbPacketCountTrace () private
EnableEnbSchedTrace()
void ns3::mmwave::MmWaveHelper::EnableEnbSchedTrace ()
Definition at line 2658 of file mmwave-helper.cc.
References ns3::mmwave::MmWaveMacTrace::ReportEnbSchedulingInfo().
EnableMcTraces()
void ns3::mmwave::MmWaveHelper::EnableMcTraces (void)
Definition at line 2735 of file mmwave-helper.cc.
EnablePdcpTraces()
void ns3::mmwave::MmWaveHelper::EnablePdcpTraces (void)
Definition at line 2721 of file mmwave-helper.cc.
EnableRlcTraces()
void ns3::mmwave::MmWaveHelper::EnableRlcTraces (void)
Definition at line 2707 of file mmwave-helper.cc.
EnableTraces()
void ns3::mmwave::MmWaveHelper::EnableTraces (void)
Definition at line 2645 of file mmwave-helper.cc.
EnableTransportBlockTrace()
void ns3::mmwave::MmWaveHelper::EnableTransportBlockTrace () private
Definition at line 2698 of file mmwave-helper.cc.
References ns3::mmwave::MmWavePhyTrace::ReportDownLinkTBSize().
EnableUePacketCountTrace()
void ns3::mmwave::MmWaveHelper::EnableUePacketCountTrace () private
EnableUlPhyTrace()
void ns3::mmwave::MmWaveHelper::EnableUlPhyTrace (void)
Definition at line 2686 of file mmwave-helper.cc.
References ns3::mmwave::MmWavePhyTrace::ReportUlPhyTransmissionCallback(), and ns3::mmwave::MmWavePhyTrace::RxPacketTraceEnbCallback().
GetCcPhyParams()
std::map< uint8_t, MmWaveComponentCarrier > ns3::mmwave::MmWaveHelper::GetCcPhyParams ()
This method is used to get the MmWaveComponentCarrier map.
Returns
ccmap the component carrier map
Definition at line 642 of file mmwave-helper.cc.
References m_componentCarrierPhyParams.
GetEnbComponentCarrierManagerType()
std::string ns3::mmwave::MmWaveHelper::GetEnbComponentCarrierManagerType () const
Returns
the carrier gnb component carrier manager type
Definition at line 2749 of file mmwave-helper.cc.
Referenced by GetTypeId().
GetHarqEnabled()
bool ns3::mmwave::MmWaveHelper::GetHarqEnabled ()
Definition at line 617 of file mmwave-helper.cc.
References m_harqEnabled.
GetLteEnbComponentCarrierManagerType()
std::string ns3::mmwave::MmWaveHelper::GetLteEnbComponentCarrierManagerType () const
Returns
the carrier enb component carrier manager type
Definition at line 2763 of file mmwave-helper.cc.
Referenced by GetTypeId().
GetLteFfrAlgorithmType()
std::string ns3::mmwave::MmWaveHelper::GetLteFfrAlgorithmType () const
Returns
the LTE FFR algorithm type
Definition at line 581 of file mmwave-helper.cc.
References m_lteFfrAlgorithmFactory.
Referenced by GetTypeId().
GetLteHandoverAlgorithmType()
std::string ns3::mmwave::MmWaveHelper::GetLteHandoverAlgorithmType () const
Returns
the LTE handover algorithm type
Definition at line 597 of file mmwave-helper.cc.
References m_lteHandoverAlgorithmFactory.
Referenced by GetTypeId().
GetLteSchedulerType()
std::string ns3::mmwave::MmWaveHelper::GetLteSchedulerType () const
Definition at line 574 of file mmwave-helper.cc.
References m_lteSchedulerFactory.
Referenced by GetTypeId().
GetMcStats()
Ptr< McStatsCalculator > ns3::mmwave::MmWaveHelper::GetMcStats (void) private
Definition at line 2743 of file mmwave-helper.cc.
GetPathLossModel()
Ptr< PropagationLossModel > ns3::mmwave::MmWaveHelper::GetPathLossModel (uint8_t index)
Definition at line 498 of file mmwave-helper.cc.
References m_pathlossModel.
GetPdcpStats()
Ptr< MmWaveBearerStatsCalculator > ns3::mmwave::MmWaveHelper::GetPdcpStats (void) private
Definition at line 2729 of file mmwave-helper.cc.
GetRlcStats()
Ptr< MmWaveBearerStatsCalculator > ns3::mmwave::MmWaveHelper::GetRlcStats (void) private
Definition at line 2715 of file mmwave-helper.cc.
GetSchedulerType()
std::string ns3::mmwave::MmWaveHelper::GetSchedulerType () const
Definition at line 560 of file mmwave-helper.cc.
References m_schedulerFactory.
Referenced by GetTypeId().
GetSnrTest()
bool ns3::mmwave::MmWaveHelper::GetSnrTest ()
Definition at line 629 of file mmwave-helper.cc.
References m_snrTest.
GetTypeId()
TypeId ns3::mmwave::MmWaveHelper::GetTypeId (void) static
Definition at line 107 of file mmwave-helper.cc.
References GetEnbComponentCarrierManagerType(), GetLteEnbComponentCarrierManagerType(), GetLteFfrAlgorithmType(), GetLteHandoverAlgorithmType(), GetLteSchedulerType(), GetSchedulerType(), GetUeComponentCarrierManagerType(), m_cellIdCounter, m_harqEnabled, m_imsiCounter, m_isAnrEnabled, m_lteUseCa, m_noOfCcs, m_noOfLteCcs, m_rlcAmEnabled, m_useCa, m_useIdealRrc, m_usePdschForCqiGeneration, SetBeamformingModelType(), SetChannelModelType(), SetEnbComponentCarrierManagerType(), SetLteEnbComponentCarrierManagerType(), SetLteFfrAlgorithmType(), SetLteHandoverAlgorithmType(), SetLtePathlossModelType(), SetLteSchedulerType(), SetPathlossModelType(), SetSchedulerType(), and SetUeComponentCarrierManagerType().
GetUeComponentCarrierManagerType()
std::string ns3::mmwave::MmWaveHelper::GetUeComponentCarrierManagerType () const
Returns
the carrier ue component carrier manager type
Definition at line 2777 of file mmwave-helper.cc.
Referenced by GetTypeId().
InstallEnbDevice()
NetDeviceContainer ns3::mmwave::MmWaveHelper::InstallEnbDevice (NodeContainer c)
Definition at line 705 of file mmwave-helper.cc.
References InstallSingleEnbDevice().
InstallInterRatHoCapableUeDevice()
NetDeviceContainer ns3::mmwave::MmWaveHelper::InstallInterRatHoCapableUeDevice (NodeContainer c)
Definition at line 689 of file mmwave-helper.cc.
References InstallSingleInterRatHoCapableUeDevice().
InstallLteEnbDevice()
NetDeviceContainer ns3::mmwave::MmWaveHelper::InstallLteEnbDevice (NodeContainer c)
Definition at line 721 of file mmwave-helper.cc.
References InstallSingleLteEnbDevice().
InstallMcUeDevice()
NetDeviceContainer ns3::mmwave::MmWaveHelper::InstallMcUeDevice (NodeContainer c)
Definition at line 673 of file mmwave-helper.cc.
References InstallSingleMcUeDevice().
InstallSingleEnbDevice()
Ptr< NetDevice > ns3::mmwave::MmWaveHelper::InstallSingleEnbDevice (Ptr< Node > n) private
Definition at line 1563 of file mmwave-helper.cc.
References ns3::mmwave::MmWaveMacScheduler::ConfigureCommonParameters(), ns3::mmwave::MmWaveEnbPhy::GenerateDataCqiReport(), m_bfModelFactory, m_cellIdCounter, m_channel, m_componentCarrierPhyParams, m_enbComponentCarrierManagerFactory, m_enbNetDeviceFactory, m_epcHelper, m_noOfCcs, m_pathlossModel, m_pathlossModelType, m_rlcAmEnabled, m_schedulerFactory, m_snrTest, m_useCa, m_useIdealRrc, ns3::mmwave::MmWaveEnbPhy::PhyCtrlMessagesReceived(), ns3::mmwave::MmWaveEnbPhy::PhyDataPacketReceived(), ns3::mmwave::MmWaveNetDevice::Receive(), ns3::mmwave::MmWaveEnbPhy::ReceiveUlHarqFeedback(), ns3::mmwave::MmWaveNetDevice::SetNode(), and ns3::mmwave::MmWaveSpectrumPhy::UpdateSinrPerceived().
Referenced by InstallEnbDevice().
InstallSingleInterRatHoCapableUeDevice()
Ptr< NetDevice > ns3::mmwave::MmWaveHelper::InstallSingleInterRatHoCapableUeDevice (Ptr< Node > n) private
Definition at line 1119 of file mmwave-helper.cc.
References m_imsiCounter, and m_mcUeNetDeviceFactory.
Referenced by InstallInterRatHoCapableUeDevice().
InstallSingleLteEnbDevice()
Ptr< NetDevice > ns3::mmwave::MmWaveHelper::InstallSingleLteEnbDevice (Ptr< Node > n) private
Definition at line 1897 of file mmwave-helper.cc.
References m_cellIdCounter, m_downlinkChannel, m_downlinkPathlossModel, m_epcHelper, m_isAnrEnabled, m_lteComponentCarrierPhyParams, m_lteEnbAntennaModelFactory, m_lteEnbComponentCarrierManagerFactory, m_lteEnbNetDeviceFactory, m_lteFfrAlgorithmFactory, m_lteHandoverAlgorithmFactory, m_lteSchedulerFactory, m_lteUseCa, m_noOfLteCcs, m_rlcAmEnabled, m_uplinkChannel, m_uplinkPathlossModel, and m_useIdealRrc.
Referenced by InstallLteEnbDevice().
InstallSingleMcUeDevice()
Ptr< NetDevice > ns3::mmwave::MmWaveHelper::InstallSingleMcUeDevice (Ptr< Node > n) private
Definition at line 737 of file mmwave-helper.cc.
References ns3::mmwave::MmWaveUePhy::GenerateDlCqiReport(), m_bfModelFactory, m_channel, m_componentCarrierPhyParams, m_downlinkChannel, m_epcHelper, m_harqEnabled, m_imsiCounter, m_lteComponentCarrierPhyParams, m_lteUeAntennaModelFactory, m_lteUseCa, m_mcUeNetDeviceFactory, m_noOfCcs, m_noOfLteCcs, m_ueComponentCarrierManagerFactory, m_uplinkChannel, m_useCa, m_useIdealRrc, m_usePdschForCqiGeneration, ns3::mmwave::MmWaveUePhy::PhyDataPacketReceived(), ns3::mmwave::McUeNetDevice::Receive(), ns3::mmwave::MmWaveUePhy::ReceiveControlMessageList(), ns3::mmwave::MmWaveUePhy::ReceiveLteDlHarqFeedback(), ns3::mmwave::MmWaveBeamformingModel::SetAntenna(), ns3::mmwave::McUeNetDevice::SetNode(), and ns3::mmwave::MmWaveSpectrumPhy::UpdateSinrPerceived().
Referenced by InstallMcUeDevice().
InstallSingleUeDevice()
Ptr< NetDevice > ns3::mmwave::MmWaveHelper::InstallSingleUeDevice (Ptr< Node > n) private
Definition at line 1347 of file mmwave-helper.cc.
References ns3::mmwave::MmWaveUePhy::GenerateDlCqiReport(), m_bfModelFactory, m_channel, m_componentCarrierPhyParams, m_epcHelper, m_harqEnabled, m_imsiCounter, m_noOfCcs, m_ueComponentCarrierManagerFactory, m_ueNetDeviceFactory, m_useIdealRrc, ns3::mmwave::MmWaveUePhy::PhyDataPacketReceived(), ns3::mmwave::MmWaveNetDevice::Receive(), ns3::mmwave::MmWaveUePhy::ReceiveControlMessageList(), ns3::mmwave::MmWaveUePhy::ReceiveLteDlHarqFeedback(), ns3::mmwave::MmWaveNetDevice::SetNode(), and ns3::mmwave::MmWaveSpectrumPhy::UpdateSinrPerceived().
Referenced by InstallUeDevice().
InstallUeDevice()
NetDeviceContainer ns3::mmwave::MmWaveHelper::InstallUeDevice (NodeContainer c)
Definition at line 656 of file mmwave-helper.cc.
References InstallSingleUeDevice().
LteChannelModelInitialization()
void ns3::mmwave::MmWaveHelper::LteChannelModelInitialization (void) private
Definition at line 417 of file mmwave-helper.cc.
References m_dlPathlossModelFactory, m_downlinkChannel, m_downlinkPathlossModel, m_lteChannelFactory, m_ulPathlossModelFactory, m_uplinkChannel, and m_uplinkPathlossModel.
Referenced by DoInitialize().
MmWaveChannelModelInitialization()
void ns3::mmwave::MmWaveHelper::MmWaveChannelModelInitialization (void) private
Definition at line 325 of file mmwave-helper.cc.
References m_channel, m_channelConditionModelFactory, m_channelConditionModelType, m_channelFactory, m_componentCarrierPhyParams, m_pathlossModel, m_pathlossModelFactory, m_pathlossModelType, m_spectrumPropagationLossModelFactory, and m_spectrumPropagationLossModelType.
Referenced by DoInitialize().
SetBeamformingModelAttribute()
void ns3::mmwave::MmWaveHelper::SetBeamformingModelAttribute (std::string name, const AttributeValue & value)
Set an attribute to the MmWaveBeamformingModel.
Parameters
name name of the attribute to set
value value to set
Definition at line 546 of file mmwave-helper.cc.
References m_bfModelFactory.
SetBeamformingModelType()
void ns3::mmwave::MmWaveHelper::SetBeamformingModelType (std::string type)
Set the type of beamforming model to be used.
Parameters
type beamforming model type
Definition at line 467 of file mmwave-helper.cc.
References m_bfModelFactory.
Referenced by GetTypeId().
SetBlockageMap()
void ns3::mmwave::MmWaveHelper::SetBlockageMap (std::map< uint8_t, bool > blockageMap)
Set the blockage attribute of each channel if MmWave3gppChannel is used.
Parameters
blockageMap (CC ID, blockage attribute value)
SetCcPhyParams()
void ns3::mmwave::MmWaveHelper::SetCcPhyParams (std::map< uint8_t, MmWaveComponentCarrier > ccMapParams)
This method is used to set the MmWaveComponentCarrier map.
The structure will be used within InstallSingleEnbDevice, InstallSingleUeNetDevice and InstallSingleMcUeDevice.
Parameters
ccMapParams the component carrier map
Definition at line 635 of file mmwave-helper.cc.
References m_componentCarrierPhyParams.
Referenced by DoInitialize().
SetChannelConditionModelType()
void ns3::mmwave::MmWaveHelper::SetChannelConditionModelType (std::string type)
Definition at line 474 of file mmwave-helper.cc.
References m_channelConditionModelFactory, and m_channelConditionModelType.
SetChannelModelAttribute()
void ns3::mmwave::MmWaveHelper::SetChannelModelAttribute (std::string name, const AttributeValue & value)
Set an attribute to the SpectrumPropagationLossModels.
Parameters
name name of the attribute to set
value value to set
Definition at line 518 of file mmwave-helper.cc.
References m_spectrumPropagationLossModelFactory.
SetChannelModelType()
void ns3::mmwave::MmWaveHelper::SetChannelModelType (std::string type)
Definition at line 506 of file mmwave-helper.cc.
References m_spectrumPropagationLossModelFactory, and m_spectrumPropagationLossModelType.
Referenced by GetTypeId().
SetEnbComponentCarrierManagerType()
void ns3::mmwave::MmWaveHelper::SetEnbComponentCarrierManagerType (std::string type)
Set the type of carrier component algorithm to be used by gNodeB devices.
Parameters
type type of carrier component manager
Definition at line 2755 of file mmwave-helper.cc.
Referenced by GetTypeId().
SetEpcHelper()
void ns3::mmwave::MmWaveHelper::SetEpcHelper (Ptr< EpcHelper > epcHelper)
Definition at line 2546 of file mmwave-helper.cc.
References m_epcHelper.
SetHarqEnabled()
void ns3::mmwave::MmWaveHelper::SetHarqEnabled (bool harqEnabled)
Definition at line 611 of file mmwave-helper.cc.
References m_harqEnabled.
SetLteCcPhyParams()
void ns3::mmwave::MmWaveHelper::SetLteCcPhyParams (std::map< uint8_t, ComponentCarrier > ccMapParams)
This method is used to set the ComponentCarrier map.
The structure will be used within InstallSingleLteEnbDevice, and InstallSingleMcUeDevice.
Parameters
ccMapParams the component carrier map
Definition at line 649 of file mmwave-helper.cc.
References m_lteComponentCarrierPhyParams.
Referenced by DoInitialize().
SetLteEnbComponentCarrierManagerType()
void ns3::mmwave::MmWaveHelper::SetLteEnbComponentCarrierManagerType (std::string type)
Set the type of carrier component algorithm to be used by eNodeB devices.
Parameters
type type of carrier component manager
Definition at line 2769 of file mmwave-helper.cc.
Referenced by GetTypeId().
SetLteFfrAlgorithmType()
void ns3::mmwave::MmWaveHelper::SetLteFfrAlgorithmType (std::string type)
Set the type of FFR algorithm to be used by LTE eNodeB devices.
Parameters
type type of FFR algorithm, must be a type name of any class inheriting from ns3::LteFfrAlgorithm, for example: "ns3::LteFrNoOpAlgorithm"
Equivalent with setting the FfrAlgorithm attribute.
Definition at line 587 of file mmwave-helper.cc.
References m_lteFfrAlgorithmFactory.
Referenced by GetTypeId().
SetLteHandoverAlgorithmType()
void ns3::mmwave::MmWaveHelper::SetLteHandoverAlgorithmType (std::string type)
Set the type of handover algorithm to be used by LTE eNodeB devices.
Parameters
type type of handover algorithm, must be a type name of any class inheriting from ns3::LteHandoverAlgorithm, for example: "ns3::NoOpHandoverAlgorithm"
Equivalent with setting the HandoverAlgorithm attribute.
Definition at line 603 of file mmwave-helper.cc.
References m_lteHandoverAlgorithmFactory.
Referenced by GetTypeId().
SetLtePathlossModelType()
void ns3::mmwave::MmWaveHelper::SetLtePathlossModelType (std::string type)
Definition at line 457 of file mmwave-helper.cc.
References m_dlPathlossModelFactory, and m_ulPathlossModelFactory.
Referenced by GetTypeId().
SetLteSchedulerType()
void ns3::mmwave::MmWaveHelper::SetLteSchedulerType (std::string type)
Definition at line 566 of file mmwave-helper.cc.
References m_lteSchedulerFactory.
Referenced by GetTypeId().
SetMcUeNetDeviceAttribute()
void ns3::mmwave::MmWaveHelper::SetMcUeNetDeviceAttribute (std::string name, const AttributeValue & value)
Set an attribute to the McUeNetDevice.
Parameters
name name of the attribute to set
value value to set
Definition at line 539 of file mmwave-helper.cc.
References m_mcUeNetDeviceFactory.
SetMmWaveEnbNetDeviceAttribute()
void ns3::mmwave::MmWaveHelper::SetMmWaveEnbNetDeviceAttribute (std::string name, const AttributeValue & value)
Set an attribute to the MmWaveEnbNetDevice.
Parameters
name name of the attribute to set
value value to set
Definition at line 525 of file mmwave-helper.cc.
References m_enbNetDeviceFactory.
SetMmWaveUeNetDeviceAttribute()
void ns3::mmwave::MmWaveHelper::SetMmWaveUeNetDeviceAttribute (std::string name, const AttributeValue & value)
Set an attribute to the MmWaveUeNetDevice.
Parameters
name name of the attribute to set
value value to set
Definition at line 532 of file mmwave-helper.cc.
References m_ueNetDeviceFactory.
SetPathlossModelType()
void ns3::mmwave::MmWaveHelper::SetPathlossModelType (std::string type)
Definition at line 486 of file mmwave-helper.cc.
References m_pathlossModelFactory, and m_pathlossModelType.
Referenced by GetTypeId().
SetSchedulerType()
void ns3::mmwave::MmWaveHelper::SetSchedulerType (std::string type)
Definition at line 553 of file mmwave-helper.cc.
References m_schedulerFactory.
Referenced by GetTypeId().
SetSnrTest()
void ns3::mmwave::MmWaveHelper::SetSnrTest (bool snrTest)
Definition at line 623 of file mmwave-helper.cc.
References m_snrTest.
SetUeComponentCarrierManagerType()
void ns3::mmwave::MmWaveHelper::SetUeComponentCarrierManagerType (std::string type)
Set the type of Component Carrier Manager to be used by Ue devices.
Parameters
type type of UE Component Carrier Manager
Definition at line 2783 of file mmwave-helper.cc.
Referenced by GetTypeId().
Member Data Documentation
m_bfModelFactory
ObjectFactory ns3::mmwave::MmWaveHelper::m_bfModelFactory private
Factory of antenna objects for Lte eNB.
Factory for the beamforming model
Definition at line 400 of file mmwave-helper.h.
Referenced by InstallSingleEnbDevice(), InstallSingleMcUeDevice(), InstallSingleUeDevice(), MmWaveHelper(), SetBeamformingModelAttribute(), and SetBeamformingModelType().
m_cellIdCounter
uint16_t ns3::mmwave::MmWaveHelper::m_cellIdCounter private
Definition at line 392 of file mmwave-helper.h.
Referenced by GetTypeId(), InstallSingleEnbDevice(), and InstallSingleLteEnbDevice().
m_channel
std::map< uint8_t, Ptr<SpectrumChannel> > ns3::mmwave::MmWaveHelper::m_channel private
Definition at line 354 of file mmwave-helper.h.
Referenced by DoDispose(), InstallSingleEnbDevice(), InstallSingleMcUeDevice(), InstallSingleUeDevice(), and MmWaveChannelModelInitialization().
m_channelConditionModelFactory
ObjectFactory ns3::mmwave::MmWaveHelper::m_channelConditionModelFactory private
the factory for the ChannelConditionModel objects
Definition at line 373 of file mmwave-helper.h.
Referenced by MmWaveChannelModelInitialization(), and SetChannelConditionModelType().
m_channelConditionModelType
std::string ns3::mmwave::MmWaveHelper::m_channelConditionModelType private
The uplink LTE channel used in the simulation.
the type of the channel condition model to be used (empty string means no channel condition model)
Definition at line 358 of file mmwave-helper.h.
Referenced by MmWaveChannelModelInitialization(), and SetChannelConditionModelType().
m_channelFactory
ObjectFactory ns3::mmwave::MmWaveHelper::m_channelFactory private
Definition at line 372 of file mmwave-helper.h.
Referenced by MmWaveChannelModelInitialization(), and MmWaveHelper().
m_cnStats
Ptr<CoreNetworkStatsCalculator> ns3::mmwave::MmWaveHelper::m_cnStats private
Definition at line 421 of file mmwave-helper.h.
Referenced by AddX2Interface(), and DoInitialize().
m_componentCarrierPhyParams
std::map< uint8_t, MmWaveComponentCarrier > ns3::mmwave::MmWaveHelper::m_componentCarrierPhyParams private
This contains all the informations about each mmWave component carrier.
Definition at line 443 of file mmwave-helper.h.
Referenced by DoDispose(), DoInitialize(), GetCcPhyParams(), InstallSingleEnbDevice(), InstallSingleMcUeDevice(), InstallSingleUeDevice(), MmWaveChannelModelInitialization(), and SetCcPhyParams().
m_dlPathlossModelFactory
ObjectFactory ns3::mmwave::MmWaveHelper::m_dlPathlossModelFactory private
Factory of both the downlink and uplink LTE channels.
Definition at line 383 of file mmwave-helper.h.
Referenced by LteChannelModelInitialization(), and SetLtePathlossModelType().
m_downlinkChannel
Ptr<SpectrumChannel> ns3::mmwave::MmWaveHelper::m_downlinkChannel private
Definition at line 355 of file mmwave-helper.h.
Referenced by InstallSingleLteEnbDevice(), InstallSingleMcUeDevice(), and LteChannelModelInitialization().
m_downlinkPathlossModel
Ptr<Object> ns3::mmwave::MmWaveHelper::m_downlinkPathlossModel private
Definition at line 362 of file mmwave-helper.h.
Referenced by InstallSingleLteEnbDevice(), and LteChannelModelInitialization().
m_enbComponentCarrierManagerFactory
ObjectFactory ns3::mmwave::MmWaveHelper::m_enbComponentCarrierManagerFactory private
Factory of path loss model object for the uplink channel.
Definition at line 386 of file mmwave-helper.h.
Referenced by InstallSingleEnbDevice().
m_enbNetDeviceFactory
ObjectFactory ns3::mmwave::MmWaveHelper::m_enbNetDeviceFactory private
Definition at line 368 of file mmwave-helper.h.
Referenced by InstallSingleEnbDevice(), MmWaveHelper(), and SetMmWaveEnbNetDeviceAttribute().
m_enbStats
Ptr<MmWaveMacTrace> ns3::mmwave::MmWaveHelper::m_enbStats private
Definition at line 395 of file mmwave-helper.h.
Referenced by DoInitialize().
m_epcHelper
Ptr<EpcHelper> ns3::mmwave::MmWaveHelper::m_epcHelper private
Definition at line 410 of file mmwave-helper.h.
Referenced by AddX2Interface(), AttachIrToClosestEnb(), AttachMcToClosestEnb(), AttachToEnbWithIndex(), InstallSingleEnbDevice(), InstallSingleLteEnbDevice(), InstallSingleMcUeDevice(), InstallSingleUeDevice(), and SetEpcHelper().
m_ffrAlgorithmFactory
ObjectFactory ns3::mmwave::MmWaveHelper::m_ffrAlgorithmFactory private
Definition at line 378 of file mmwave-helper.h.
m_harqEnabled
bool ns3::mmwave::MmWaveHelper::m_harqEnabled private
Definition at line 412 of file mmwave-helper.h.
Referenced by GetHarqEnabled(), GetTypeId(), InstallSingleMcUeDevice(), InstallSingleUeDevice(), and SetHarqEnabled().
m_imsiCounter
uint64_t ns3::mmwave::MmWaveHelper::m_imsiCounter private
Factory of enb component carrier manager object.
Definition at line 391 of file mmwave-helper.h.
Referenced by GetTypeId(), InstallSingleInterRatHoCapableUeDevice(), InstallSingleMcUeDevice(), and InstallSingleUeDevice().
m_isAnrEnabled
bool ns3::mmwave::MmWaveHelper::m_isAnrEnabled private
Definition at line 408 of file mmwave-helper.h.
Referenced by GetTypeId(), and InstallSingleLteEnbDevice().
m_lteChannelFactory
ObjectFactory ns3::mmwave::MmWaveHelper::m_lteChannelFactory private
Definition at line 382 of file mmwave-helper.h.
Referenced by LteChannelModelInitialization(), and MmWaveHelper().
m_lteComponentCarrierPhyParams
std::map< uint8_t, ComponentCarrier > ns3::mmwave::MmWaveHelper::m_lteComponentCarrierPhyParams private
This contains all the informations about each LTE component carrier.
Definition at line 438 of file mmwave-helper.h.
Referenced by DoDispose(), DoInitialize(), InstallSingleLteEnbDevice(), InstallSingleMcUeDevice(), and SetLteCcPhyParams().
m_lteEnbAntennaModelFactory
ObjectFactory ns3::mmwave::MmWaveHelper::m_lteEnbAntennaModelFactory private
Factory of antenna object for Lte UE.
Definition at line 398 of file mmwave-helper.h.
Referenced by InstallSingleLteEnbDevice(), and MmWaveHelper().
m_lteEnbComponentCarrierManagerFactory
ObjectFactory ns3::mmwave::MmWaveHelper::m_lteEnbComponentCarrierManagerFactory private
Factory of ue component carrier manager object.
Definition at line 389 of file mmwave-helper.h.
Referenced by InstallSingleLteEnbDevice().
m_lteEnbNetDeviceFactory
ObjectFactory ns3::mmwave::MmWaveHelper::m_lteEnbNetDeviceFactory private
Definition at line 369 of file mmwave-helper.h.
Referenced by InstallSingleLteEnbDevice(), and MmWaveHelper().
m_lteFfrAlgorithmFactory
ObjectFactory ns3::mmwave::MmWaveHelper::m_lteFfrAlgorithmFactory private
Definition at line 379 of file mmwave-helper.h.
Referenced by GetLteFfrAlgorithmType(), InstallSingleLteEnbDevice(), and SetLteFfrAlgorithmType().
m_lteHandoverAlgorithmFactory
ObjectFactory ns3::mmwave::MmWaveHelper::m_lteHandoverAlgorithmFactory private
Definition at line 380 of file mmwave-helper.h.
Referenced by GetLteHandoverAlgorithmType(), InstallSingleLteEnbDevice(), and SetLteHandoverAlgorithmType().
m_lteSchedulerFactory
ObjectFactory ns3::mmwave::MmWaveHelper::m_lteSchedulerFactory private
Definition at line 377 of file mmwave-helper.h.
Referenced by GetLteSchedulerType(), InstallSingleLteEnbDevice(), and SetLteSchedulerType().
m_lteUeAntennaModelFactory
ObjectFactory ns3::mmwave::MmWaveHelper::m_lteUeAntennaModelFactory private
Definition at line 397 of file mmwave-helper.h.
Referenced by InstallSingleMcUeDevice(), and MmWaveHelper().
m_lteUseCa
bool ns3::mmwave::MmWaveHelper::m_lteUseCa private
The LteUseCa attribute.
If true, Carrier Aggregation is enabled in the LTE stack.
Definition at line 427 of file mmwave-helper.h.
Referenced by DoInitialize(), GetTypeId(), InstallSingleLteEnbDevice(), and InstallSingleMcUeDevice().
m_mcStats
Ptr<McStatsCalculator> ns3::mmwave::MmWaveHelper::m_mcStats private
Definition at line 419 of file mmwave-helper.h.
m_mcUeNetDeviceFactory
ObjectFactory ns3::mmwave::MmWaveHelper::m_mcUeNetDeviceFactory private
Definition at line 371 of file mmwave-helper.h.
Referenced by InstallSingleInterRatHoCapableUeDevice(), InstallSingleMcUeDevice(), MmWaveHelper(), and SetMcUeNetDeviceAttribute().
m_noOfCcs
uint16_t ns3::mmwave::MmWaveHelper::m_noOfCcs private
Number of component carriers that will be installed by default at gNodeB and UE devices.
Definition at line 455 of file mmwave-helper.h.
Referenced by GetTypeId(), InstallSingleEnbDevice(), InstallSingleMcUeDevice(), and InstallSingleUeDevice().
m_noOfLteCcs
uint16_t ns3::mmwave::MmWaveHelper::m_noOfLteCcs private
Number of LTE component carriers that will be installed by default at LTE eNodeB and MC-UE devices.
Definition at line 449 of file mmwave-helper.h.
Referenced by GetTypeId(), InstallSingleLteEnbDevice(), and InstallSingleMcUeDevice().
m_pathlossModel
std::map< uint8_t, Ptr<Object> > ns3::mmwave::MmWaveHelper::m_pathlossModel private
Definition at line 360 of file mmwave-helper.h.
Referenced by GetPathLossModel(), InstallSingleEnbDevice(), and MmWaveChannelModelInitialization().
m_pathlossModelFactory
ObjectFactory ns3::mmwave::MmWaveHelper::m_pathlossModelFactory private
Definition at line 374 of file mmwave-helper.h.
Referenced by MmWaveChannelModelInitialization(), and SetPathlossModelType().
m_pathlossModelType
std::string ns3::mmwave::MmWaveHelper::m_pathlossModelType private
Definition at line 361 of file mmwave-helper.h.
Referenced by InstallSingleEnbDevice(), MmWaveChannelModelInitialization(), and SetPathlossModelType().
m_pdcpStats
Ptr<MmWaveBearerStatsCalculator> ns3::mmwave::MmWaveHelper::m_pdcpStats private
Definition at line 418 of file mmwave-helper.h.
m_phyStats
Ptr<MmWavePhyTrace> ns3::mmwave::MmWaveHelper::m_phyStats private
Definition at line 394 of file mmwave-helper.h.
Referenced by DoInitialize().
m_radioBearerStatsConnector
Ptr<MmWaveBearerStatsConnector> ns3::mmwave::MmWaveHelper::m_radioBearerStatsConnector private
Definition at line 420 of file mmwave-helper.h.
Referenced by DoInitialize().
m_rlcAmEnabled
bool ns3::mmwave::MmWaveHelper::m_rlcAmEnabled private
Definition at line 413 of file mmwave-helper.h.
Referenced by GetTypeId(), InstallSingleEnbDevice(), and InstallSingleLteEnbDevice().
m_rlcStats
Ptr<MmWaveBearerStatsCalculator> ns3::mmwave::MmWaveHelper::m_rlcStats private
Definition at line 417 of file mmwave-helper.h.
m_schedulerFactory
ObjectFactory ns3::mmwave::MmWaveHelper::m_schedulerFactory private
Definition at line 376 of file mmwave-helper.h.
Referenced by GetSchedulerType(), InstallSingleEnbDevice(), and SetSchedulerType().
m_snrTest
bool ns3::mmwave::MmWaveHelper::m_snrTest private
Definition at line 414 of file mmwave-helper.h.
Referenced by GetSnrTest(), InstallSingleEnbDevice(), and SetSnrTest().
m_spectrumPropagationLossModelFactory
ObjectFactory ns3::mmwave::MmWaveHelper::m_spectrumPropagationLossModelFactory private
the factory for the SpectrumPropagationLossModel objects
Definition at line 375 of file mmwave-helper.h.
Referenced by MmWaveChannelModelInitialization(), SetChannelModelAttribute(), and SetChannelModelType().
m_spectrumPropagationLossModelType
std::string ns3::mmwave::MmWaveHelper::m_spectrumPropagationLossModelType private
The path loss model used in the LTE uplink channel.
the type of the SpectrumPropagationLossModel to use (if needed)
Definition at line 366 of file mmwave-helper.h.
Referenced by MmWaveChannelModelInitialization(), and SetChannelModelType().
m_ueComponentCarrierManagerFactory
ObjectFactory ns3::mmwave::MmWaveHelper::m_ueComponentCarrierManagerFactory private
Factory of enb component carrier manager object.
Definition at line 387 of file mmwave-helper.h.
Referenced by InstallSingleMcUeDevice(), and InstallSingleUeDevice().
m_ueNetDeviceFactory
ObjectFactory ns3::mmwave::MmWaveHelper::m_ueNetDeviceFactory private
Definition at line 370 of file mmwave-helper.h.
Referenced by InstallSingleUeDevice(), MmWaveHelper(), and SetMmWaveUeNetDeviceAttribute().
m_ulPathlossModelFactory
ObjectFactory ns3::mmwave::MmWaveHelper::m_ulPathlossModelFactory private
Factory of path loss model object for the downlink channel.
Definition at line 384 of file mmwave-helper.h.
Referenced by LteChannelModelInitialization(), and SetLtePathlossModelType().
m_uplinkChannel
Ptr<SpectrumChannel> ns3::mmwave::MmWaveHelper::m_uplinkChannel private
The downlink LTE channel used in the simulation.
Definition at line 356 of file mmwave-helper.h.
Referenced by InstallSingleLteEnbDevice(), InstallSingleMcUeDevice(), and LteChannelModelInitialization().
m_uplinkPathlossModel
Ptr<Object> ns3::mmwave::MmWaveHelper::m_uplinkPathlossModel private
The path loss model used in the LTE downlink channel.
Definition at line 363 of file mmwave-helper.h.
Referenced by InstallSingleLteEnbDevice(), and LteChannelModelInitialization().
m_useCa
bool ns3::mmwave::MmWaveHelper::m_useCa private
The UseCa attribute.
If true, Carrier Aggregation is enabled in the MmWave stack.
Definition at line 433 of file mmwave-helper.h.
Referenced by DoInitialize(), GetTypeId(), InstallSingleEnbDevice(), and InstallSingleMcUeDevice().
m_useIdealRrc
bool ns3::mmwave::MmWaveHelper::m_useIdealRrc private
Definition at line 415 of file mmwave-helper.h.
Referenced by GetTypeId(), InstallSingleEnbDevice(), InstallSingleLteEnbDevice(), InstallSingleMcUeDevice(), and InstallSingleUeDevice().
m_usePdschForCqiGeneration
bool ns3::mmwave::MmWaveHelper::m_usePdschForCqiGeneration private
From lte-helper.h The UsePdschForCqiGeneration attribute.
If true, DL-CQI will be calculated from PDCCH as signal and PDSCH as interference. If false, DL-CQI will be calculated from PDCCH as signal and PDCCH as interference.
Definition at line 407 of file mmwave-helper.h.
Referenced by GetTypeId(), and InstallSingleMcUeDevice().
The documentation for this class was generated from the following files:
src/mmwave/helper/mmwave-helper.h
src/mmwave/helper/mmwave-helper.cc