ns3-mmwave: src/mmwave/examples/dce-example-mptcp-mmwave.cc File Reference
dce-example-mptcp-mmwave.cc File Reference
#include "ns3/network-module.h"
#include "ns3/core-module.h"
#include "ns3/internet-module.h"
#include "ns3/dce-module.h"
#include "ns3/point-to-point-module.h"
#include "ns3/wifi-module.h"
#include "ns3/lte-module.h"
#include "ns3/buildings-module.h"
#include "ns3/mmwave-module.h"
#include "ns3/mobility-module.h"
#include "ns3/applications-module.h"
#include "ns3/netanim-module.h"
#include "ns3/constant-position-mobility-model.h"
#include "ns3/config-store-module.h"
#include <iostream>
#include <ctime>
#include <stdlib.h>
#include <sstream>
Macros
#define SSTR(x)
Functions
void changePos (Ptr< Node > node, int x, int y, int z)
void ChangeSpeed (Ptr< Node > n, Vector speed)
static ns3::GlobalValue g_congestionControl ("congestionControl", "CC algorithm", ns3::StringValue("cubic"), ns3::MakeStringChecker())
static ns3::GlobalValue g_dist ("dist", "Distance from eNB", ns3::UintegerValue(190), ns3::MakeUintegerChecker< uint32_t >())
static ns3::GlobalValue g_harqEnabled ("harqEnabled", "If true, enable harq", ns3::BooleanValue(true), ns3::MakeBooleanChecker())
static ns3::GlobalValue g_outPath ("outPath", "The path of output log files", ns3::StringValue("./"), ns3::MakeStringChecker())
static ns3::GlobalValue g_rlcAmEnabled ("rlcAmEnabled", "If true, use RLC AM, else use RLC UM", ns3::BooleanValue(true), ns3::MakeBooleanChecker())
void PrintPid (ApplicationContainer apps, DceApplicationHelper dce)
void PrintTcpFlags (std::string key, std::string value)
void randomPos (Ptr< Node > n, int R_max, int z)
void setPos (Ptr< Node > n, int x, int y, int z)
Macro Definition Documentation
SSTR
#define SSTR (x)
Value:
static_cast< std::ostringstream & > (\
    ( std::ostringstream () << std::dec << x ) ).str ()
Definition at line 49 of file dce-example-mptcp-mmwave.cc.
Function Documentation
changePos()
void changePos (Ptr< Node > node, int x, int y, int z)
Definition at line 80 of file dce-example-mptcp-mmwave.cc.
ChangeSpeed()
void ChangeSpeed (Ptr< Node > n, Vector speed)
Definition at line 90 of file dce-example-mptcp-mmwave.cc.
g_congestionControl()
static ns3::GlobalValue g_congestionControl ("congestionControl" , "CC algorithm" , ns3::StringValue("cubic") , ns3::MakeStringChecker()) static
Referenced by PrintPid().
g_dist()
static ns3::GlobalValue g_dist ("dist" , "Distance from eNB" , ns3::UintegerValue(190) , ns3::MakeUintegerChecker< uint32_t > ()) static
Referenced by PrintPid().
g_harqEnabled()
static ns3::GlobalValue g_harqEnabled ("harqEnabled" , "If true, enable harq" , ns3::BooleanValue(true) , ns3::MakeBooleanChecker()) static
Referenced by PrintPid().
g_outPath()
static ns3::GlobalValue g_outPath ("outPath" , "The path of output log files" , ns3::StringValue("./") , ns3::MakeStringChecker()) static
Referenced by PrintPid().
g_rlcAmEnabled()
static ns3::GlobalValue g_rlcAmEnabled ("rlcAmEnabled" , "If true, use RLC AM, else use RLC UM" , ns3::BooleanValue(true) , ns3::MakeBooleanChecker()) static
Referenced by PrintPid().
PrintPid()
void PrintPid (ApplicationContainer apps, DceApplicationHelper dce)
Definition at line 103 of file dce-example-mptcp-mmwave.cc.
References g_congestionControl(), g_dist(), g_harqEnabled(), g_outPath(), and g_rlcAmEnabled().
PrintTcpFlags()
void PrintTcpFlags (std::string key, std::string value)
Definition at line 97 of file dce-example-mptcp-mmwave.cc.
randomPos()
void randomPos (Ptr< Node > n, int R_max, int z)
Definition at line 65 of file dce-example-mptcp-mmwave.cc.
setPos()
void setPos (Ptr< Node > n, int x, int y, int z)
Definition at line 55 of file dce-example-mptcp-mmwave.cc.