ns3-mmwave: src/mmwave/examples/mc-twoenbs-ipv6.cc File Reference
mc-twoenbs-ipv6.cc File Reference
#include "ns3/mmwave-helper.h"
#include "ns3/epc-helper.h"
#include "ns3/core-module.h"
#include "ns3/network-module.h"
#include "ns3/ipv4-global-routing-helper.h"
#include "ns3/internet-module.h"
#include "ns3/mobility-module.h"
#include "ns3/applications-module.h"
#include "ns3/point-to-point-helper.h"
#include "ns3/config-store.h"
#include "ns3/mmwave-point-to-point-epc-helper.h"
#include <ns3/buildings-helper.h>
#include <ns3/buildings-module.h>
#include <ns3/random-variable-stream.h>
#include <ns3/lte-ue-net-device.h>
#include <iostream>
#include <ctime>
#include <stdlib.h>
#include <list>
Functions
bool AreOverlapping (Box a, Box b)
void ChangePosition (Ptr< Node > node, Vector vector)
void ChangeSpeed (Ptr< Node > n, Vector speed)
static ns3::GlobalValue g_bufferSize ("bufferSize", "RLC tx buffer size (MB)", ns3::UintegerValue(20), ns3::MakeUintegerChecker< uint32_t >())
static ns3::GlobalValue g_handoverMode ("handoverMode", "Handover mode", ns3::UintegerValue(3), ns3::MakeUintegerChecker< uint8_t >())
static ns3::GlobalValue g_interPckInterval ("interPckInterval", "Interarrival time of UDP packets (us)", ns3::UintegerValue(20), ns3::MakeUintegerChecker< uint32_t >())
static ns3::GlobalValue g_lteUplink ("lteUplink", "If true, always use LTE for uplink signalling", ns3::BooleanValue(false), ns3::MakeBooleanChecker())
static ns3::GlobalValue g_maxXAxis ("maxXAxis", "The maximum X coordinate for the area in which to deploy the buildings", ns3::DoubleValue(150), ns3::MakeDoubleChecker< double >())
static ns3::GlobalValue g_maxYAxis ("maxYAxis", "The maximum Y coordinate for the area in which to deploy the buildings", ns3::DoubleValue(40), ns3::MakeDoubleChecker< double >())
static ns3::GlobalValue g_mmeLatency ("mmeLatency", "Latency on MME interface (us)", ns3::DoubleValue(10000), ns3::MakeDoubleChecker< double >())
static ns3::GlobalValue g_mmw1DistFromMainStreet ("mmw1Dist", "Distance from the main street of the first MmWaveEnb", ns3::UintegerValue(50), ns3::MakeUintegerChecker< uint32_t >())
static ns3::GlobalValue g_mmw2DistFromMainStreet ("mmw2Dist", "Distance from the main street of the second MmWaveEnb", ns3::UintegerValue(50), ns3::MakeUintegerChecker< uint32_t >())
static ns3::GlobalValue g_mmw3DistFromMainStreet ("mmw3Dist", "Distance from the main street of the third MmWaveEnb", ns3::UintegerValue(110), ns3::MakeUintegerChecker< uint32_t >())
static ns3::GlobalValue g_mmWaveDistance ("mmWaveDist", "Distance between MmWave eNB 1 and 2", ns3::UintegerValue(200), ns3::MakeUintegerChecker< uint32_t >())
static ns3::GlobalValue g_mobileUeSpeed ("mobileSpeed", "The speed of the UE (m/s)", ns3::DoubleValue(2), ns3::MakeDoubleChecker< double >())
static ns3::GlobalValue g_noiseAndFilter ("noiseAndFilter", "If true, use noisy SINR samples, filtered. If false, just use the SINR measure", ns3::BooleanValue(false), ns3::MakeBooleanChecker())
static ns3::GlobalValue g_numBuildingsBetweenMmWaveEnb ("numBlocks", "Number of buildings between MmWave eNB 1 and 2", ns3::UintegerValue(8), ns3::MakeUintegerChecker< uint32_t >())
static ns3::GlobalValue g_outageThreshold ("outageTh", "Outage threshold", ns3::DoubleValue(-5), ns3::MakeDoubleChecker< double >())
static ns3::GlobalValue g_outPath ("outPath", "The path of output log files", ns3::StringValue("./"), ns3::MakeStringChecker())
static ns3::GlobalValue g_reportTablePeriodicity ("reportTablePeriodicity", "Periodicity of RTs", ns3::UintegerValue(1600), ns3::MakeUintegerChecker< uint32_t >())
static ns3::GlobalValue g_rlcAmEnabled ("rlcAmEnabled", "If true, use RLC AM, else use RLC UM", ns3::BooleanValue(true), ns3::MakeBooleanChecker())
static ns3::GlobalValue g_x2Latency ("x2Latency", "Latency on X2 interface (us)", ns3::DoubleValue(500), ns3::MakeDoubleChecker< double >())
std::pair< Box, std::list< Box > > GenerateBuildingBounds (double xArea, double yArea, double maxBuildSize, std::list< Box > m_previousBlocks)
bool OverlapWithAnyPrevious (Box box, std::list< Box > m_previousBlocks)
void PrintGnuplottableBuildingListToFile (std::string filename)
Sample simulation script for MC device.
void PrintGnuplottableEnbListToFile (std::string filename)
void PrintGnuplottableUeListToFile (std::string filename)
void PrintLostUdpPackets (Ptr< UdpServer > app, std::string fileName)
void PrintPosition (Ptr< Node > node)
Function Documentation
AreOverlapping()
bool AreOverlapping (Box a, Box b)
Definition at line 191 of file mc-twoenbs-ipv6.cc.
Referenced by OverlapWithAnyPrevious().
ChangePosition()
void ChangePosition (Ptr< Node > node, Vector vector)
Definition at line 159 of file mc-twoenbs-ipv6.cc.
ChangeSpeed()
void ChangeSpeed (Ptr< Node > n, Vector speed)
Definition at line 167 of file mc-twoenbs-ipv6.cc.
g_bufferSize()
static ns3::GlobalValue g_bufferSize ("bufferSize" , "RLC tx buffer size (MB)" , ns3::UintegerValue(20) , ns3::MakeUintegerChecker< uint32_t > ()) static
Referenced by GenerateBuildingBounds().
g_handoverMode()
static ns3::GlobalValue g_handoverMode ("handoverMode" , "Handover mode" , ns3::UintegerValue(3) , ns3::MakeUintegerChecker< uint8_t > ()) static
Referenced by GenerateBuildingBounds().
g_interPckInterval()
static ns3::GlobalValue g_interPckInterval ("interPckInterval" , "Interarrival time of UDP packets (us)" , ns3::UintegerValue(20) , ns3::MakeUintegerChecker< uint32_t > ()) static
Referenced by GenerateBuildingBounds().
g_lteUplink()
static ns3::GlobalValue g_lteUplink ("lteUplink" , "If true, always use LTE for uplink signalling" , ns3::BooleanValue(false) , ns3::MakeBooleanChecker()) static
Referenced by GenerateBuildingBounds().
g_maxXAxis()
static ns3::GlobalValue g_maxXAxis ("maxXAxis" , "The maximum X coordinate for the area in which to deploy the buildings" , ns3::DoubleValue(150) , ns3::MakeDoubleChecker< double > ()) static
Referenced by GenerateBuildingBounds().
g_maxYAxis()
static ns3::GlobalValue g_maxYAxis ("maxYAxis" , "The maximum Y coordinate for the area in which to deploy the buildings" , ns3::DoubleValue(40) , ns3::MakeDoubleChecker< double > ()) static
Referenced by GenerateBuildingBounds().
g_mmeLatency()
static ns3::GlobalValue g_mmeLatency ("mmeLatency" , "Latency on MME interface (us)" , ns3::DoubleValue(10000) , ns3::MakeDoubleChecker< double > ()) static
Referenced by GenerateBuildingBounds().
g_mmw1DistFromMainStreet()
static ns3::GlobalValue g_mmw1DistFromMainStreet ("mmw1Dist" , "Distance from the main street of the first MmWaveEnb" , ns3::UintegerValue(50) , ns3::MakeUintegerChecker< uint32_t > ()) static
Referenced by GenerateBuildingBounds().
g_mmw2DistFromMainStreet()
static ns3::GlobalValue g_mmw2DistFromMainStreet ("mmw2Dist" , "Distance from the main street of the second MmWaveEnb" , ns3::UintegerValue(50) , ns3::MakeUintegerChecker< uint32_t > ()) static
Referenced by GenerateBuildingBounds().
g_mmw3DistFromMainStreet()
static ns3::GlobalValue g_mmw3DistFromMainStreet ("mmw3Dist" , "Distance from the main street of the third MmWaveEnb" , ns3::UintegerValue(110) , ns3::MakeUintegerChecker< uint32_t > ()) static
Referenced by GenerateBuildingBounds().
g_mmWaveDistance()
static ns3::GlobalValue g_mmWaveDistance ("mmWaveDist" , "Distance between MmWave eNB 1 and 2" , ns3::UintegerValue(200) , ns3::MakeUintegerChecker< uint32_t > ()) static
Referenced by GenerateBuildingBounds().
g_mobileUeSpeed()
static ns3::GlobalValue g_mobileUeSpeed ("mobileSpeed" , "The speed of the UE (m/s)" , ns3::DoubleValue(2) , ns3::MakeDoubleChecker< double > ()) static
Referenced by GenerateBuildingBounds().
g_noiseAndFilter()
static ns3::GlobalValue g_noiseAndFilter ("noiseAndFilter" , "If true, use noisy SINR samples, filtered. If false, just use the SINR measure" , ns3::BooleanValue(false) , ns3::MakeBooleanChecker()) static
Referenced by GenerateBuildingBounds().
g_numBuildingsBetweenMmWaveEnb()
static ns3::GlobalValue g_numBuildingsBetweenMmWaveEnb ("numBlocks" , "Number of buildings between MmWave eNB 1 and 2" , ns3::UintegerValue(8) , ns3::MakeUintegerChecker< uint32_t > ()) static
Referenced by GenerateBuildingBounds().
g_outageThreshold()
static ns3::GlobalValue g_outageThreshold ("outageTh" , "Outage threshold" , ns3::DoubleValue(-5) , ns3::MakeDoubleChecker< double > ()) static
Referenced by GenerateBuildingBounds().
g_outPath()
static ns3::GlobalValue g_outPath ("outPath" , "The path of output log files" , ns3::StringValue("./") , ns3::MakeStringChecker()) static
Referenced by GenerateBuildingBounds().
g_reportTablePeriodicity()
static ns3::GlobalValue g_reportTablePeriodicity ("reportTablePeriodicity" , "Periodicity of RTs" , ns3::UintegerValue(1600) , ns3::MakeUintegerChecker< uint32_t > ()) static
Referenced by GenerateBuildingBounds().
g_rlcAmEnabled()
static ns3::GlobalValue g_rlcAmEnabled ("rlcAmEnabled" , "If true, use RLC AM, else use RLC UM" , ns3::BooleanValue(true) , ns3::MakeBooleanChecker()) static
Referenced by GenerateBuildingBounds().
g_x2Latency()
static ns3::GlobalValue g_x2Latency ("x2Latency" , "Latency on X2 interface (us)" , ns3::DoubleValue(500) , ns3::MakeDoubleChecker< double > ()) static
Referenced by GenerateBuildingBounds().
GenerateBuildingBounds()
std::pair<Box, std::list<Box> > GenerateBuildingBounds (double xArea, double yArea, double maxBuildSize, std::list< Box > m_previousBlocks)
Definition at line 212 of file mc-twoenbs-ipv6.cc.
References g_bufferSize(), g_handoverMode(), g_interPckInterval(), g_lteUplink(), g_maxXAxis(), g_maxYAxis(), g_mmeLatency(), g_mmw1DistFromMainStreet(), g_mmw2DistFromMainStreet(), g_mmw3DistFromMainStreet(), g_mmWaveDistance(), g_mobileUeSpeed(), g_noiseAndFilter(), g_numBuildingsBetweenMmWaveEnb(), g_outageThreshold(), g_outPath(), g_reportTablePeriodicity(), g_rlcAmEnabled(), g_x2Latency(), and OverlapWithAnyPrevious().
OverlapWithAnyPrevious()
bool OverlapWithAnyPrevious (Box box, std::list< Box > m_previousBlocks)
Definition at line 198 of file mc-twoenbs-ipv6.cc.
References AreOverlapping().
Referenced by GenerateBuildingBounds().
PrintGnuplottableBuildingListToFile()
void PrintGnuplottableBuildingListToFile (std::string filename)
Sample simulation script for MC device.
It instantiates a LTE and two MmWave eNodeB, attaches one MC UE to both and starts a flow for the UE to and from a remote host.
Definition at line 53 of file mc-twoenbs-ipv6.cc.
PrintGnuplottableEnbListToFile()
void PrintGnuplottableEnbListToFile (std::string filename)
Definition at line 120 of file mc-twoenbs-ipv6.cc.
PrintGnuplottableUeListToFile()
void PrintGnuplottableUeListToFile (std::string filename)
Definition at line 76 of file mc-twoenbs-ipv6.cc.
PrintLostUdpPackets()
void PrintLostUdpPackets (Ptr< UdpServer > app, std::string fileName)
Definition at line 181 of file mc-twoenbs-ipv6.cc.
PrintPosition()
void PrintPosition (Ptr< Node > node)
Definition at line 174 of file mc-twoenbs-ipv6.cc.